"""Tier 1 Scenarios: Ages 6-8 (10 episodes x 7 turns = 70 turns)."""
from scenarios_common import make_ep, make_turn

t1 = [
    make_ep("t1_e1", "tier1", "모래성 감탄", "📍 Episode 1/10: Sandcastle Masterpiece", "sandcastle", [
        make_turn(1, "Penny", "🐧", "Look at my giant sandcastle! It's so cool!", "내 거대한 모래성 좀 봐! 멋지지!",
                  '"저것 좀 봐!"라고 자연스럽게 감탄해보세요!', "Look at that!",
                  "Right? It took all morning to build!", "그치? 아침 내내 만들었어!",
                  '신기한 것을 볼 때 미국 아이들은 "Look at that!"을 가장 먼저 외칩니다.',
                  "저것 좀 봐! (가장 자연스러운 감탄)", "I observe a castle.", "딱딱한 문장이에요.", "Good evening, sir.", "상황에 안 맞아요."),
        make_turn(2, "Penny", "🐧", "Wanna find seashells for the roof together?", "지붕에 올릴 조개껍데기 같이 찾으러 갈래?",
                  '"완전 좋지!"라고 기쁘게 수락해보세요!', "I'd love to!",
                  "Awesome! Let's search by the big rock!", "신난다! 큰 바위 쪽에서 찾아보자!",
                  '친구의 다정한 제안에 "I\'d love to!"는 가장 따뜻하고 적극적인 수락입니다.',
                  "완전 좋지! (적극적인 찬성)", "I decline searching.", "너무 쌀쌀맞아요.", "Pass me salt.", "식탁에서 쓰는 말이에요."),
        make_turn(3, "Penny", "🐧", "We put all the shiny shells on top! Look at our castle now!", "지붕에 반짝이는 조개 다 올렸어! 이제 우리 성 좀 봐!",
                  '"다 완성했다!"라고 환호해보세요!', "All done!",
                  "Our sandcastle is the king of the whole beach! High five!", "우리 모래성이 온 해변에서 제일 멋져! 하이파이브!",
                  '장난감 조립이나 만들기를 마쳤을 때 아이들이 가장 신나게 외치는 표현입니다.',
                  "다 완성했다! (기쁨의 완료)", "Work is terminated.", "너무 기계적인 표현이에요.", "I want to sleep.", "상황에 어색해요."),
        make_turn(4, "Penny", "🐧", "The sun is going down and the tide is coming in! Where do our shovels go?", "해가 지고 파도가 밀려오고 있어! 우리 모래삽은 어디다 두지?",
                  '"장난감 치우자!"라고 구동사 clean up을 써서 말해보세요!', "Let's clean up!",
                  "Good idea! Let's put all the buckets in my beach bag! Done!", "좋은 생각이야! 양동이들 내 비치백에 다 넣자! 끝!",
                  '구동사 "clean up"은 놀이나 식사 후에 주변을 깨끗하게 정리할 때 아이들이 매일 쓰는 필수 표현입니다.',
                  "깨끗이 치우자! (정리정돈 필수 구동사)", "Break the castle.", "모래성 부수자는 엉뚱한 말이에요.", "Eat sand.", "모래 먹자는 이상한 말이에요."),
        make_turn(5, "Penny", "🐧", "The sand is burning hot like a cookie oven! Don't step on it barefoot!", "모래가 쿠키 오븐처럼 엄청 뜨거워! 맨발로 밟지 마!",
                  '"샌들 신어!"라고 구동사 put on을 써서 외쳐보세요!', "Put on your sandals!",
                  "Strap on tight! Now my toes are safe from the scorching sand!", "스트랩 꽉 잠갔다! 이제 발가락 안 데이고 안전해!",
                  '구동사 "put on"은 신발, 모자, 안경, 겉옷 등을 "착용하다/신다"라는 뜻으로 유초등 아이들이 매일 쓰는 초특급 필수 구동사입니다.',
                  "샌들 신어! (의류 및 신발 착용 필수 구동사)", "Eat your sandals.", "샌들 먹으라는 엉뚱한 말이에요.", "Throw sandals away.", "샌들 버리라는 나쁜 말이에요."),
        make_turn(6, "Penny", "🐧", "The cool ocean breeze is blowing and the beach guard is blowing the whistle! Time to pack up!", "시원한 저녁 바람 불고 해변 안전요원 아저씨 호루라기 부셔! 이제 짐 챙길 시간이야!",
                  '"우리 이제 가자!"라고 구동사 get going을 써서 씩씩하게 말해보세요!', "Let's get going!",
                  "On our way! What a super fun beach day with our giant sandcastle!", "출발! 거대한 모래성 만들고 진짜 역대급으로 신나는 해변 하루였어!",
                  '구동사 "get going"은 "이제 출발하다/가다"라는 뜻으로 자리에서 일어날 때 미국 가족과 아이들이 매일 쓰는 최고빈도 표현입니다.',
                  "우리 이제 가자! (출발 필수 구동사)", "Sleep on sand forever.", "모래에서 자자는 오답이에요.", "Destroy the ocean.", "바다를 파괴하자는 오답이에요."),
        make_turn(7, "Penny", "🐧", "Look, the ice cream truck is jingling by the parking lot before we leave! Can we get a strawberry popsicle?", "봐봐, 떠나기 전에 주차장 옆에서 아이스크림 트럭 종 울린다! 딸기맛 하드 하나 먹을래?",
                  "\"하나 사 먹자!\"라고 기본동사 get을 써서 신나게 외쳐보세요!", "Let's get one!",
                  "Strawberry popsicle with rainbow sprinkles! Sweetest ending to our sandcastle beach adventure!", "레인보우 스프링클 뿌린 딸기맛 하드! 모래성 해변 모험의 가장 달콤한 엔딩이야!",
                  "기본동사 \"get\"은 물건이나 음식을 \"사다/먹다/얻다\"라는 뜻으로 아이들이 일상에서 무언가를 구매하거나 먹자고 할 때 매일 쓰는 표현입니다.",
                  "하나 사 먹자! (구매 및 취식 필수 기본동사)", "Smash the truck.", "트럭 부수라는 악담이에요.", "Never eat treats.", "간식 먹지 말라는 오답이에요.")
    ]),

    make_ep("t1_e2", "tier1", "놀이터 술래잡기", "📍 Episode 2/10: Playground Tag", "tag", [
        make_turn(1, "Leo", "🦁", "We are playing tag right now! Wanna join?", "우리 지금 술래잡기 할 건데! 같이 할래?",
                  '"나도 같이 놀아도 돼?"라고 물어보세요!', "Can I play?",
                  "Of course! Run fast, Sammy is it!", "당연하지! 빨리 뛰어, 새미가 술래야!",
                  '"Can I play?"는 놀이터에서 친구 무리에 들어갈 때 마법처럼 통하는 표현입니다.',
                  "나도 같이 놀아도 돼? (놀이터 필수 표현)", "I refuse your game.", "거절하는 말이에요.", "Yes, I am human.", "엉뚱한 답변이에요."),
        make_turn(2, "Leo", "🦁", "Watch out! The monster is coming right behind you!", "조심해! 술래가 바로 뒤까지 쫓아왔어!",
                  '"도망쳐!"라고 다급하게 외쳐보세요!', "Run away!",
                  "Phew! Made it to the safe tree base!", "휴! 안전지대 나무까지 살아서 도착했다!",
                  '술래잡기나 위험 상황에서 아이들이 가장 비명을 지르며 외치는 단어입니다.',
                  "도망쳐! (박진감 넘치는 외침)", "Please walk slowly.", "술래에게 잡혀요!", "Good morning.", "상황에 맞지 않아요."),
        make_turn(3, "Leo", "🦁", "Sammy tried to tag my shoes, but I touched the oak tree!", "새미가 내 신발 터치하려 했는데, 내가 참나무 만졌지롱!",
                  '"안전지대 세이프!"라고 당당하게 외쳐보세요!', "Safe base!",
                  "Haha, Sammy couldn't catch us! We're untouchable!", "하하 새미가 우리 못 잡았지! 우리 완전 세이프야!",
                  '놀이터 술래잡기에서 안전지대(Safe zone/base)에 도착했을 때 외치는 아동 필수 규칙 표현입니다.',
                  "세이프! (안전지대 도달)", "You lose completely.", "친구를 놀리는 나쁜 말이에요.", "It is midnight.", "자정이라는 엉뚱한 말이에요."),
        make_turn(4, "Leo", "🦁", "Sammy is zooming right around the big oak tree! Look out for that tree root!", "새미가 참나무 주변을 쌩쌩 달리고 있어! 저기 나무뿌리 걸리지 않게 조심해!",
                  '"발밑 조심해!"라고 구동사 watch out을 써서 외쳐보세요!', "Watch out!",
                  "Phew, you warned him just in time! He hopped right over it!", "휴, 네가 딱 맞춰 경고해줬어! 폴짝 뛰어넘었다!",
                  '구동사 "Watch out!"은 장애물이나 위험이 닥쳤을 때 "조심해!"라고 즉시 외치는 가장 기본적이고 긴박한 표현입니다.',
                  "조심해! (위험 경고 필수 구동사)", "Fall down hard.", "세게 넘어지라는 악담이에요.", "Sleep on grass.", "잔디에서 자라는 엉뚱한 말이에요."),
        make_turn(5, "Leo", "🦁", "Sammy is turning around the monkey bars and zooming straight at us! Don't stop!", "새미가 구름사다리 돌아서 우리 쪽으로 직진해 온다! 멈추지 마!",
                  '"계속 뛰어!"라고 기본동사 keep을 써서 응원해보세요!', "Keep running!",
                  "I'm running as fast as a cheetah! Sammy can't catch us now!", "나 치타처럼 빠르게 달리는 중! 새미 이제 우리 절대 못 잡아!",
                  '기본동사 "keep" 뒤에 ~ing를 붙인 "Keep running!"(계속 뛰어!), "Keep going!"(계속 가!)는 멈추지 않고 지속할 때 입버릇처럼 쓰는 대표적 표현입니다.',
                  "계속 뛰어! (지속과 격려의 기본동사)", "Stop and sleep.", "자라는 엉뚱한 말이에요.", "Fall on grass.", "넘어지라는 악담이에요."),
        make_turn(6, "Leo", "🦁", "Phew! We ran around the playground three whole laps! My legs feel like wobbly jelly!", "휴! 우리 운동장 세 바퀴나 전력 질주했어! 다리가 젤리처럼 후들거려!",
                  '"잠깐 쉬자!"라고 기본동사 take를 써서 숨을 돌려보세요!', "Let's take a break!",
                  "Sitting under the cool tree shade! Ahh, my breath is catching up!", "시원한 나무 그늘 아래 앉았다! 아아 숨 좀 이제 골라지네!",
                  '기본동사 "take"를 활용한 "Take a break"(잠깐 쉬다/휴식하다)는 공부나 놀이 중 지쳤을 때 누구나 외치는 필수 생활 표현입니다.',
                  "잠깐 쉬자! (휴식 필수 기본동사)", "Run twenty more miles.", "20마일 더 뛰라는 오답이에요.", "Eat soccer ball.", "축구공 먹으라는 오답이에요."),
        make_turn(7, "Leo", "🦁", "My water bottle is right here on the picnic table! Our throats are totally dry from running three laps!", "피크닉 테이블 위에 내 물병 딱 있어! 세 바퀴나 전력 질주해서 목 진짜 타들어간다!",
                  "\"물 좀 마시자!\"라고 기본동사 have를 써서 숨을 돌려보세요!", "Let's have some water!",
                  "Gulp gulp! Ice cold water tastes like heaven after playing tag! Ready for round two whenever you are!", "벌컥벌컥! 술래잡기하고 마시는 얼음물 진짜 꿀맛이다! 너만 준비되면 언제든 2라운드 출발!",
                  "기본동사 \"have\"는 음식이나 음료를 \"먹다/마시다\"라는 뜻으로 \"Let's have some water!\"처럼 가장 자연스럽게 쓰입니다.",
                  "물 좀 마시자! (음료 섭취 필수 기본동사)", "Spill water on dirt.", "흙에 물 쏟으라는 오답이에요.", "Run ten more laps thirsty.", "목마른 채로 열 바퀴 더 뛰자는 오답이에요.")
    ]),

    make_ep("t1_e3", "tier1", "간식 나눠먹기", "📍 Episode 3/10: Snack Sharing", "cafeteria", [
        make_turn(1, "Sammy", "🦊", "My mom packed yummy strawberry gummy bears!", "우리 엄마가 맛있는 딸기 젤리 싸주셨어!",
                  '"나도 좀 줄래?"라고 예쁘게 부탁해보세요!', "Can I have some?",
                  "Sure! Here is a red bear for you!", "그럼! 여기 빨간 딸기 곰 젤리 너 하나 줄게!",
                  '친구의 간식을 얻어먹을 때 가장 귀엽고 공손한 아동 구어체입니다.',
                  "나도 좀 줄래? (자연스러운 요청)", "Surrender food now.", "강도 같은 거친 말이에요!", "Thank you for lunch.", "아직 안 받았어요!"),
        make_turn(2, "Sammy", "🦊", "How does it taste? Super sweet, right?", "맛이 어때? 엄청 달콤하지?",
                  '"진짜 맛있다!"라고 감탄해보세요!', "It's so good!",
                  "Yay! I will bring grape gummies tomorrow!", "야호! 내일은 포도 맛 젤리 가져올게!",
                  '음식이 맛있을 때 미국 아이들이 직관적으로 가장 많이 쓰는 감탄사입니다.',
                  "진짜 맛있다! (달콤한 감탄)", "It contains sugar.", "성분표 같아요.", "I am sleeping.", "자고 있다는 뜻이에요."),
        make_turn(3, "Sammy", "🦊", "I saved the biggest green apple gummy just for you too!", "제일 큰 사과맛 곰 젤리도 너 주려고 아껴뒀어!",
                  '"정말 고마워!"라고 환하게 감사 인사를 해보세요!', "Thank you so much!",
                  "Anytime, buddy! Sharing snacks makes everything better!", "언제든 말해 친구야! 나눠 먹는 게 최고지!",
                  '친구의 따뜻한 호의에 활짝 웃으며 건네는 가장 예쁜 아동 감사 표현입니다.',
                  "정말 고마워! (진심 어린 감사)", "Give me money instead.", "무례한 오답이에요.", "I hate apples.", "음식 투정이에요."),
        make_turn(4, "Sammy", "🦊", "I have grape and strawberry left in the pouch! Which one do you want?", "봉지에 포도맛이랑 딸기맛 남았어! 너 어떤 거 먹을래?",
                  '"하나 집어봐!"라고 기본동사 take를 써서 골라보세요!', "Take one!",
                  "I'll take the purple grape bear! Om nom nom, so juicy!", "난 보라색 포도 곰 젤리 먹을래! 냠냠 완전 즙 터진다!",
                  '기본동사 "take"는 손으로 물건을 집거나 선택할 때 "Take one(하나 골라봐/집어봐)"처럼 매일 쓰이는 핵심 동사입니다.',
                  "하나 골라봐! (선택을 권하는 기본동사)", "Throw it away.", "버리라는 나쁜 말이에요.", "Hide the food.", "음식 숨기라는 엉뚱한 말이에요."),
        make_turn(5, "Sammy", "🦊", "Wait, the snack bell is ringing! Zipper your pocket so your gummy bear doesn't tumble out!", "잠깐, 간식 시간 끝나는 종 쳐! 곰 젤리 안 떨어지게 주머니에 얼른 넣어!",
                  '"가방에 잘 챙겨 넣어둘게!"라고 구동사 put away를 써서 말해보세요!', "I'll put it away!",
                  "Safe inside your pocket zipper! Snack mission complete!", "주머니 지퍼 안에 쏙 안전하게 보관 완료! 간식 미션 성공!",
                  '구동사 "put away"는 물건, 간식, 장난감을 가방이나 원래 자리에 "정리하여 넣어두다"라는 뜻의 일상 필수 구동사입니다.',
                  "가방에 잘 넣어둘게! (정리 및 보관 필수 구동사)", "Drop it in mud.", "진흙에 떨어뜨리라는 오답이에요.", "Throw at teacher.", "선생님께 던지라는 오답이에요."),
        make_turn(6, "Sammy", "🦊", "Look at your sticky fingers from the grape gummy! The classroom door is opening!", "포도 젤리 먹어서 손가락 끈적끈적해진 것 좀 봐! 교실 문 열린다!",
                  '"손 깨끗이 닦자!"라고 구동사 wipe off를 써서 챙겨주세요!', "Wipe your hands!",
                  "Clean and dry with the wet wipe! Ready for story time with clean paws!", "물티슈로 뽀송뽀송하게 다 닦았어! 깨끗한 손으로 동화 시간 준비 완료!",
                  '구동사 "wipe off"(닦아내다) 또는 wipe는 음식이나 물기를 닦을 때 부모님과 선생님이 아이들에게 매일 쓰는 대표 구동사입니다.',
                  "손 깨끗이 닦자! (청결 필수 구동사)", "Rub dirt on pants.", "바지에 흙 문지르라는 오답이에요.", "Lick the table.", "식탁 핥으라는 오답이에요."),
        make_turn(7, "Sammy", "🦊", "Look, the teacher is opening the big picture storybook on the carpet! Everyone is sitting down cross-legged!", "봐봐, 선생님이 카펫 위에서 커다란 그림책 펼치셨어! 애들 다 아빠 다리로 앉고 있어!",
                  "\"얼른 가서 앉자!\"라고 구동사 sit down을 써서 말해보세요!", "Let's sit down!",
                  "Right in the front row! The dinosaur picture book looks super exciting with pop-up wings!", "맨 앞줄에 쏙 앉았다! 팝업 날개 달린 공룡 그림책 진짜 완전 흥미진진해 보여!",
                  "구동사 \"sit down\"은 바닥이나 의자에 \"자리를 잡고 앉다\"라는 뜻으로 교실과 가정에서 매일 사용하는 초특급 기본 구동사입니다.",
                  "얼른 가서 앉자! (착석 필수 구동사)", "Stand on desk.", "책상 위에 서 있으라는 엉뚱한 말이에요.", "Run out the window.", "창문으로 뛰어나가자는 오답이에요.")
    ]),

    make_ep("t1_e4", "tier1", "레고 블록 꼭대기", "📍 Episode 4/10: LEGO Tower Top", "toybox", [
        make_turn(1, "Leo", "🦁", "Who gets to put the golden dragon on top?", "탑 꼭대기에 황금 용 올릴 사람 누구?",
                  '"이번엔 내 차례야!"라고 씩씩하게 말해보세요!', "My turn!",
                  "Alright, your turn! Place it gently!", "좋아, 네 차례야! 조심해서 올려봐!",
                  '"My turn!"은 게임이나 놀이에서 자기 순서임을 당당하게 알리는 만능 단어입니다.',
                  "내 차례야! (명쾌한 순서 표현)", "I have priority.", "너무 기계적이에요.", "Good night.", "자러 가는 인사예요."),
        make_turn(2, "Leo", "🦁", "Whoa, it balanced! We built the tallest tower!", "우와, 중심 잡혔다! 우리가 제일 높은 탑을 만들었어!",
                  '"우리 해냈어!"라고 환호해보세요!', "We did it!",
                  "High five! Best building team ever!", "하이파이브! 우리 최고의 조립 팀이다!",
                  '협동 놀이나 게임을 완수했을 때 다 함께 외치는 최고의 성취 표현입니다.',
                  "우리 해냈어! (기쁨의 환호)", "Mission executed.", "군대 보고 같아요.", "I am absent.", "결석했다는 뜻이에요."),
        make_turn(3, "Leo", "🦁", "Put your hand up high! Don't leave me hanging!", "손 높이 들어봐! 하이파이브 받아줘야지!",
                  '"하이파이브!"라고 손바닥을 부딪치며 외쳐보세요!', "High five!",
                  "Slap! That was a loud one! We rock!", "짝! 소리 진짜 시원하다! 우리 완전 짱이야!",
                  '성공이나 승리의 순간 미국 아이들이 손바닥을 맞부딪치며 외치는 필수 제스처 구호입니다.',
                  "하이파이브! (팀워크의 상징)", "Do not touch hands.", "거절하는 차가운 말이에요.", "Take an aspirin.", "두통약 먹으라는 엉뚱한 말이에요."),
        make_turn(4, "Leo", "🦁", "Whoa, the golden dragon is tilting! Don't let the bricks tumble!", "우와, 황금 용이 기울어지고 있어! 블록 안 와르르 무너지게 조심해!",
                  '"잠깐 기다려봐!"라고 구동사 hold on을 써서 진정시켜보세요!', "Hold on!",
                  "Phew, I steady it with both hands! The tower is standing strong!", "휴, 두 손으로 중심 잡았어! 탑이 튼튼하게 서 있다!",
                  '구동사 "Hold on!"은 "잠깐만!", "기다려 봐!"라는 뜻으로 급하거나 위험한 순간 멈추라고 할 때 입버릇처럼 쓰입니다.',
                  "잠깐만 기다려! (순간을 멈추는 필수 구동사)", "Smash it down.", "부숴버리라는 심술궂은 말이에요.", "I am crying.", "울고 있다는 딴소리예요."),
        make_turn(5, "Leo", "🦁", "The warning whistle blew! We have fifty extra yellow bricks scattered on the blue carpet!", "정리 호루라기 불렸다! 파란 카펫에 노란 블록 50개 흩어져 있어!",
                  '"원래 상자에 다시 넣어두자!"라고 구동사 put back을 써서 제안해보세요!', "Let's put them back!",
                  "Scooping them into the red tub! The carpet is squeaky clean!", "빨간 통에 다 쓸어 담았어! 카펫 완전 반짝반짝 깨끗하다!",
                  '구동사 "put back"은 썼던 물건이나 장난감을 "원래 자리에 되돌려놓다"라는 뜻으로 학교와 가정에서 매일 쓰는 최고빈도 표현입니다.',
                  "원래 자리에 되돌려놓자! (제자리 정리 필수 구동사)", "Smash the box.", "상자 부수라는 오답이에요.", "Hide them forever.", "영원히 숨기라는 오답이에요."),
        make_turn(6, "Leo", "🦁", "All fifty yellow bricks are inside the red tub! Now snap the yellow lid on top!", "노란 블록 50개 빨간 상자에 다 들어갔어! 이제 노란 뚜껑을 위에 딱 닫자!",
                  '"뚜껑 덮어!"라고 기본동사 put을 써서 뚜껑을 닫아보세요!', "Put the lid on!",
                  "Snap! It clicked tight! Our playroom floor is officially ten out of ten!", "딱! 꽉 닫혔다! 우리 놀이방 바닥 이제 공식적으로 10점 만점에 10점이야!",
                  '기본동사 "put"과 on이 만난 "Put ~ on"(뚜껑을 덮다, 옷을 입다)은 일상에서 가장 흔하게 쓰이는 초특급 기본 표현입니다.',
                  "뚜껑 덮어! (뚜껑 닫기 필수 기본동사)", "Kick the toy bin.", "상자 발로 차라는 오답이에요.", "Chew plastic bricks.", "플라스틱 씹으라는 오답이에요."),
        make_turn(7, "Leo", "🦁", "The playroom carpet is completely cleared and the toy bin is stacked! High five for being the best cleanup team!", "놀이방 카펫 싹 치워졌고 장난감 상자도 딱 쌓였어! 최고의 정리 팀 하이파이브!",
                  "\"수고했어, 잘했어!\"라고 칭찬 표현 Good job을 건네보세요!", "Good job!",
                  "Teamwork makes the dream work! Tomorrow let's build a giant pirate ship with the blue bricks!", "팀워크가 최고야! 내일은 파란 블록으로 거대한 해적선 만들자!",
                  "\"Good job!\"은 친구가 노력했거나 놀이와 정리를 멋지게 마쳤을 때 서로를 격려하고 칭찬하는 가장 따뜻한 필수 표현입니다.",
                  "잘했어, 최고야! (노력과 완료 칭찬 필수 표현)", "You failed completely.", "완전 실패했다는 악담이에요.", "I will mess it up.", "어지르겠다는 심술이에요.")
    ]),

    make_ep("t1_e5", "tier1", "크레파스 실수", "📍 Episode 5/10: Crayon Drop Oopsie", "tag", [
        make_turn(1, "Penny", "🐧", "Oops! I accidentally knocked down your crayon!", "앗! 내가 실수로 네 크레파스를 떨어뜨렸어!",
                  '"별거 아니야, 괜찮아!"라고 친구를 안심시켜주세요!', "No biggie!",
                  "Phew, thank you! I picked it right back up!", "휴 다행이다, 고마워! 내가 얼른 주웠어!",
                  '"No biggie!"는 "No big deal"의 아주 귀여운 키즈 구어체 표현입니다.',
                  "별거 아니야! (귀여운 위로)", "Pay for crayon.", "매정하게 화내는 말이에요.", "I am fine, and you?", "교과서 답변이에요."),
        make_turn(2, "Penny", "🐧", "Do you want the glitter marker to finish your drawing?", "그림 완성하게 반짝이 매직 펜 빌려줄까?",
                  '"응, 제발 줘!"라고 공손하게 부탁해보세요!', "Yes, please!",
                  "Here you go! Your unicorn looks amazing!", "여기 있어! 네 유니콘 그림 진짜 환상적이다!",
                  '친절한 제안을 수락할 때 "Yes, please!"는 아이들의 필수 예절 표현입니다.',
                  "응, 제발 부탁해! (필수 예의 표현)", "Give it now.", "명령조라 어색해요.", "No never.", "절대 싫다는 거절이에요."),
        make_turn(3, "Penny", "🐧", "Look, the glitter dried and it sparkles like starlight!", "봐봐, 반짝이 마르니까 별빛처럼 반짝거려!",
                  '"진짜 멋지다!"라고 친구와 함께 감탄해보세요!', "Looks great!",
                  "Our drawing is definitely going up on the class wall!", "우리 그림 무조건 교실 벽에 전시될 거야!",
                  '결과물이나 작품을 보고 짧고 따뜻하게 칭찬할 때 가장 자주 쓰는 아동 표현입니다.',
                  "진짜 멋지다! (따뜻한 칭찬)", "It looks dirty.", "친구 기분을 망쳐요.", "I am not here.", "부재중이라는 오답이에요."),
        make_turn(4, "Penny", "🐧", "Oh, look! The yellow sun crayon rolled all the way under the chair!", "어 저기 봐! 노란 해님 크레파스가 의자 밑으로 데굴데굴 굴러갔어!",
                  '"내가 주워올릴게!"라고 구동사 pick up을 써서 말해보세요!', "I'll pick it up!",
                  "You got it! Thank you for picking it up so fast!", "네가 해냈네! 얼른 주워줘서 진짜 고마워!",
                  '구동사 "pick up"은 바닥에 떨어진 물건을 손으로 "집어 올리다"라는 뜻으로 일상생활에서 매일 사용합니다.',
                  "내가 주워올릴게! (물건 줍기 필수 구동사)", "Kick it far.", "멀리 차라는 나쁜 말이에요.", "Leave it dirty.", "더럽게 두라는 오답이에요."),
        make_turn(5, "Penny", "🐧", "I drew the sun and the rainbow arch! Can you draw the little smiling cloud with your blue marker?", "내가 해님이랑 무지개 아치 그렸어! 네가 파란색 매직으로 웃는 구름 그려볼래?",
                  '"한번 해볼게!"라고 기본동사 give를 써서 씩씩하게 말해보세요!', "I'll give it a try!",
                  "Whoa, that cloud has the cutest smile ever! Our drawing is a masterpiece!", "우와, 저 구름 미소 진짜 세상에서 제일 귀엽다! 우리 그림 완전 명작이야!",
                  '기본동사 "give"를 활용한 "Give it a try!"(한번 해보다/시도하다)는 자신 있게 도전하거나 권할 때 원어민들이 가장 많이 쓰는 표현입니다.',
                  "한번 해볼게! (도전과 시도의 기본동사)", "I destroy drawing.", "그림 찢는다는 오답이에요.", "Color is illegal.", "색칠은 불법이라는 오답이에요."),
        make_turn(6, "Penny", "🐧", "Our smiling rainbow cloud drawing is completely dry! The teacher gave us two gold stars!", "우리 무지개 구름 그림 잉크 싹 말랐어! 선생님이 황금 별 스티커 두 개나 붙여주셨어!",
                  '"벽에 걸어두자!"라고 구동사 hang up을 써서 전시해보세요!', "Let's hang it up!",
                  "Pinning it to the bulletin board! Everyone walking down the hall will admire our art!", "게시판에 압정으로 콕 꽂았다! 복도 지나가는 모든 친구들이 우리 작품 보고 감탄할 거야!",
                  '구동사 "hang up"은 옷걸이에 옷을 걸거나 벽/게시판에 그림을 "걸어두다"라는 뜻으로 교실과 가정의 필수 구동사입니다.',
                  "벽에 걸어두자! (전시 및 걸기 필수 구동사)", "Rip it into pieces.", "조각조각 찢으라는 악담이에요.", "Hide it under trash.", "쓰레기 밑에 숨기라는 오답이에요."),
        make_turn(7, "Penny", "🐧", "Everyone walking into the classroom is stopping to admire our smiling rainbow! Look at their happy faces!", "교실 들어오는 친구들마다 우리 무지개 그림 보고 멈춰서 감탄해! 애들 활짝 웃는 것 좀 봐!",
                  "\"정말 뿌듯하다!\"라고 감정을 솔직하게 표현해보세요!", "I'm so proud!",
                  "Me too! That rainbow cloud is the happiest artwork in our entire elementary school hall!", "나도! 저 무지개 구름 우리 초등학교 복도 통틀어서 제일 행복한 그림이야!",
                  "자신이나 친구의 멋진 성과에 자부심과 뿌듯함을 느낄 때 미국 아이들이 \"I'm so proud!(정말 자랑스러워/뿌듯해!)\"를 외칩니다.",
                  "정말 뿌듯해! (자긍심과 기쁨의 감정 표현)", "I hate this art.", "그림 싫다는 심술이에요.", "Erase the rainbow.", "무지개 지우라는 오답이에요.")
    ]),

    make_ep("t1_e6", "tier1", "미끄럼틀 양보", "📍 Episode 6/10: Slide Line Etiquette", "swing", [
        make_turn(1, "Sammy", "🦊", "The spiral slide has a long line! Who goes first?", "뱅글뱅글 미끄럼틀 줄 길다! 누가 먼저 탈래?",
                  '"너 먼저 타!"라고 양보해보세요!', "After you!",
                  "Really? Thank you! I'll slide down super fast!", "정말? 고마워! 나 슝 하고 엄청 빠르게 내려갈게!",
                  '"After you!"는 줄을 서거나 문을 지날 때 상대방을 먼저 배려하는 멋진 표현입니다.',
                  "너 먼저 해! (배려 넘치는 양보)", "I will push you.", "밀겠다는 위험한 말이에요.", "Bye bye.", "작별 인사예요."),
        make_turn(2, "Sammy", "🦊", "Wheee! That was so fast! Did you see me zoom?", "우와아! 진짜 빨랐다! 나 슝 내려오는 거 봤어?",
                  '"완전 대박이었어!"라고 맞장구쳐보세요!', "That was awesome!",
                  "Now it's your turn, go for it!", "이제 네 차례야, 출발해봐!",
                  '친구가 멋진 일을 했을 때 "That was awesome!"은 최고의 찬사입니다.',
                  "완전 대박이었어! (신나는 찬사)", "It was boring.", "기분을 상하게 해요.", "I am hungry.", "갑자기 배고프다는 말이에요."),
        make_turn(3, "Sammy", "🦊", "Ready at the top? I'll catch you at the bottom!", "위에서 준비됐어? 내가 밑에서 받아줄게!",
                  '"나 출발한다!"라고 씩씩하게 외쳐보세요!', "Here I go!",
                  "Wheeee! Look at you zoom! You were even faster than me!", "와아아! 너 진짜 날아왔다! 나보다 훨씬 빨랐어!",
                  '놀이기구를 타거나 다이빙, 달리기를 시작하며 몸을 던질 때 외치는 만능 구호입니다.',
                  "나 출발한다! (씩씩한 출발)", "I am retreating.", "후퇴한다는 군대 용어예요.", "Stop the slide.", "미끄럼틀 멈추라는 말이에요."),
        make_turn(4, "Sammy", "🦊", "That was the fastest slide ever! The stairs are empty right now!", "역대급으로 빠른 미끄럼틀이었어! 지금 계단 텅 비어있어!",
                  '"빨리 와!"라고 재촉하며 구동사 come on을 써서 외쳐보세요!', "Come on!",
                  "Running to the ladder right now! Let's slide down together again!", "지금 사다리로 뛰어가는 중! 우리 같이 한 번 더 슝 내려가자!",
                  '구동사 "Come on!"은 "빨리 와!", "어서!", "힘내!"처럼 친구를 부르거나 재촉할 때 전 세계에서 가장 많이 쓰는 구동사입니다.',
                  "빨리 와, 어서! (재촉과 활기의 구동사)", "Go away.", "저리 가라는 차가운 말이에요.", "Stop playing.", "놀지 말라는 김빠지는 소리예요."),
        make_turn(5, "Sammy", "🦊", "We're standing side by side at the very top of the slide tunnel! The slide is clear!", "우리 미끄럼틀 터널 꼭대기에 나란히 섰어! 아래 미끄럼틀 비었다!",
                  '"너 먼저 타!"라고 구동사 go ahead를 써서 양보해보세요!', "Go ahead!",
                  "Wheee! Zooming down like a rocket ship! Now your turn to zoom!", "우와아! 로켓처럼 슝 내려간다! 이제 네가 슝 내려올 차례야!",
                  '구동사 "Go ahead!"는 "먼저 해!", "어서 가!"라는 뜻으로 줄서기나 놀이에서 양보하고 배려할 때 미국에서 1위로 쓰이는 구동사입니다.',
                  "너 먼저 타! 어서 가! (배려와 양보의 필수 구동사)", "Push me down hard.", "세게 밀라는 위험한 오답이에요.", "Sit here all day.", "하루 종일 앉아있자는 오답이에요."),
        make_turn(6, "Sammy", "🦊", "You zoomed down like lightning! Look, nobody is climbing the playground wooden ladder now!", "너 번개처럼 슝 미끄러져 내려왔다! 봐봐, 지금 놀이터 나무 사다리 아무도 안 올라가!",
                  '"같이 올라가자!"라고 구동사 go up을 써서 권해보세요!', "Let's go up!",
                  "Climbing step by step to the wooden castle! Double slide race next!", "나무 성으로 한 계단씩 올라가는 중! 다음엔 2인 연속 슬라이드 레이스다!",
                  '구동사 "go up"은 계단이나 사다리, 언덕을 "올라가다"라는 뜻으로 놀이터에서 친구와 뛰어놀 때 가장 많이 쓰는 구동사입니다.',
                  "같이 올라가자! (상승과 이동 필수 구동사)", "Jump off the top.", "꼭대기에서 뛰어내리라는 위험한 말이에요.", "Sleep under the slide.", "미끄럼틀 밑에서 자라는 오답이에요."),
        make_turn(7, "Sammy", "🦊", "We're standing side by side at the slide starting gate! Three, two, one, ready for the double rocket slide?", "우리 슬라이드 출발선에 나란히 섰어! 셋, 둘, 하나, 2인 연속 로켓 슬라이드 준비됐어?",
                  "\"손잡이 꽉 잡아!\"라고 구동사 hold on을 써서 안전하게 당부해보세요!", "Hold on tight!",
                  "Wheeeee! Flying down side by side like twin jet planes! Landed straight onto our sneakers!", "우와아아! 쌍둥이 제트기처럼 나란히 슝 내려왔다! 운동화로 완벽 착지!",
                  "구동사 \"hold on\"은 손잡이나 난간을 \"꽉 붙잡다\"라는 뜻으로 놀이기구를 타거나 속도가 빠를 때 꼭 필요한 안전 표현입니다.",
                  "손잡이 꽉 잡아! (안전 파지 필수 구동사)", "Let go of hands.", "손 놓으라는 위험한 말이에요.", "Close eyes and cry.", "눈 감고 울라는 오답이에요.")
    ]),

    make_ep("t1_e7", "tier1", "잃어버린 스티커", "📍 Episode 7/10: Lost Dinosaur Sticker", "toybox", [
        make_turn(1, "Penny", "🐧", "Oh no, my gold dinosaur sticker is gone from my box!", "어떡해, 내 필통에 있던 황금 공룡 스티커가 없어졌어!",
                  '"내가 도와줄게!"라고 다정하게 말해보세요!', "I can help!",
                  "Thank you! Can you check under the rug?", "고마워! 저기 카펫 밑에 있는지 봐줄래?",
                  '친구가 곤란할 때 아이들이 손을 번쩍 들며 외치는 따뜻한 한마디입니다.',
                  "내가 도와줄게! (적극적인 배려)", "Stickers are bad.", "이상한 소리예요.", "Happy New Year.", "상황에 안 맞아요."),
        make_turn(2, "Penny", "🐧", "Wait, is that shiny paper peeking out by your shoe?", "잠깐, 네 신발 옆에서 반짝거리는 저 종이 맞아?",
                  '"찾았다!"라고 기쁘게 외쳐보세요!', "I found it!",
                  "Hooray! You found my favorite sticker! You're the best!", "만세! 내 최애 스티커를 찾아줬어! 너 최고야!",
                  '물건을 찾았을 때 만국 공통으로 가장 기쁘게 외치는 표현입니다.',
                  "내가 찾았어! (기쁜 발견)", "I lost it.", "잃어버렸다는 반대말이에요.", "It is midnight.", "자정이라는 엉뚱한 말이에요."),
        make_turn(3, "Penny", "🐧", "I was about to cry! How can I ever thank you?", "나 진짜 울 뻔했잖아! 어떻게 고마움을 전하지?",
                  '"천만에, 별말을!"이라고 쿨하게 화답해보세요!', "You got it!",
                  "You're the sweetest friend in our whole school!", "너 우리 학교에서 제일 다정한 친구야!",
                  '친구가 큰 감사를 표할 때 미국 아이들이 "천만에, 언제든 말해!"라는 뜻으로 자주 쓰는 관용구입니다.',
                  "천만에, 별말을! (다정한 화답)", "You owe me money.", "돈 내놓으라는 무례한 말이에요.", "I will hide it.", "숨기겠다는 나쁜 말이에요."),
        make_turn(4, "Penny", "🐧", "I finally got my favorite T-rex sticker back! Where should I put it?", "최애 티라노 스티커 되찾았다! 이거 어디에 둘까?",
                  '"소중히 잘 보관해!"라고 기본동사 keep을 써서 조언해보세요!', "Keep it safe!",
                  "Putting it inside my secret pocket zipper! It's safe now!", "내 비밀 주머니 지퍼 안에 쏙 넣었어! 이제 절대 안 잃어버려!",
                  '기본동사 "keep"은 어떤 상태를 그대로 유지하거나 소중한 물건을 지킬 때 "Keep it safe(안전하게 잘 둬)"로 쓰입니다.',
                  "안전하게 잘 보관해! (상태 유지 기본동사)", "Throw it out.", "버리라는 이상한 말이에요.", "Lose it again.", "다시 잃어버리라는 악담이에요."),
        make_turn(5, "Penny", "🐧", "I have a shiny silver astronaut sticker sheet in my desk drawer! Wanna see?", "내 책상 서랍에 반짝이는 은색 우주비행사 스티커 시트도 있어! 볼래?",
                  '"한번 봐보자!"라고 기본동사 take를 써서 말해보세요!', "Let's take a look!",
                  "Look at the glowing helmet stickers! Pick your favorite one to keep!", "빛나는 헬멧 스티커 봐봐! 마음에 드는 거 하나 골라서 가져!",
                  '기본동사 "take"와 look이 합쳐진 "Take a look!"(한번 봐봐!)은 무언가를 살펴보고 구경할 때 매일 쓰는 필수 관용 표현입니다.',
                  "한번 봐보자! (탐색과 확인의 기본동사)", "Close your eyes tight.", "눈 꼭 감으라는 오답이에요.", "Tear the sticker book.", "스티커북 찢으라는 오답이에요."),
        make_turn(6, "Penny", "🐧", "The shiny gold T-rex sticker is safely inside your pencil case! Don't let it slip out!", "반짝이는 황금 티라노 스티커 필통에 쏙 넣었어! 또 미끄러져 떨어지지 않게 해!",
                  '"꼭 쥐고 있어!"라고 구동사 hold on to를 써서 당부해보세요!', "Hold on to it!",
                  "Holding it tight in both paws! It's my good luck charm for the spelling quiz!", "두 손으로 꼭 쥐었어! 오늘 단어 퀴즈 행운의 부적으로 삼을 거야!",
                  '구동사 "hold on to"는 물건이나 손을 "놓치지 않고 꽉 쥐다/간직하다"라는 뜻으로 아이들이 물건을 지킬 때 매일 쓰는 표현입니다.',
                  "꼭 쥐고 있어! (파지 및 간직 필수 구동사)", "Throw it in the toilet.", "변기에 버리라는 오답이에요.", "Cut it with scissors.", "가위로 자르라는 오답이에요."),
        make_turn(7, "Penny", "🐧", "The teacher is handing out the spelling quiz papers! My shiny gold T-rex sticker is shining on my desk!", "선생님이 단어 시험지 나눠주신다! 내 반짝이는 황금 티라노 스티커가 책상 위에서 빛나고 있어!",
                  "\"시험 잘 봐, 행운을 빌어!\"라고 Good luck을 전해보세요!", "Good luck!",
                  "Thank you! With your good luck wish and my lucky dinosaur, I'm scoring a hundred percent!", "고마워! 네 응원이랑 행운의 공룡 덕분에 오늘 백 점 맞을 것 같아!",
                  "\"Good luck!\"은 시험, 경기, 도전 직전 친구에게 행운과 성공을 빌어줄 때 전 세계에서 가장 많이 쓰는 마법의 응원 문구입니다.",
                  "행운을 빌어, 잘 봐! (시험 및 도전 응원 필수 표현)", "Fail the test.", "시험 망치라는 나쁜 말이에요.", "Tear the paper.", "시험지 찢으라는 오답이에요.")
    ]),

    make_ep("t1_e8", "tier1", "왕 비눗방울 불기", "📍 Episode 8/10: Giant Bubble Blast", "tag", [
        make_turn(1, "Leo", "🦁", "Look, my bubble wand made three bubbles at once!", "봐봐, 내 비눗방울 막대로 세 개를 한 번에 불었어!",
                  '"나 좀 봐봐!"라고 자신 있게 말해보세요!', "Watch me!",
                  "Whoa, yours is as big as a soccer ball!", "우와, 네 거 축구공만큼 커졌다!",
                  '자신의 멋진 솜씨나 묘기를 보여줄 때 "Watch me!"를 씁니다.',
                  "나 좀 봐! (자신감 넘치는 한마디)", "Close eyes.", "눈을 감으라는 오답이에요.", "I am sleeping.", "상황에 안 맞아요."),
        make_turn(2, "Leo", "🦁", "It's floating up to the tree branch! Pop it quick!", "나무 나뭇가지 쪽으로 날아가고 있어! 얼른 터뜨려!",
                  '"잡았다!"라고 신나게 외쳐보세요!', "Gotcha!",
                  "Pop! Drops splashed right on my nose haha!", "펑! 비눗방울 방울이 내 코에 튀었어 ㅋㅋㅋ!",
                  '무언가를 터뜨리거나 잡았을 때 속 시원하게 외치는 단어입니다.',
                  "잡았다! (신나는 포획)", "I missed.", "놓쳤다는 뜻이에요.", "Good evening.", "저녁 인사예요."),
        make_turn(3, "Leo", "🦁", "Look, a whole cloud of mini bubbles is flying your way!", "저기 봐, 미니 비눗방울 구름 떼가 너한테 날아간다!",
                  '"다 터뜨려!"라고 신나게 점프하며 외쳐보세요!', "Pop it!",
                  "Pop pop pop! We cleared the whole playground sky!", "톡톡톡! 우리가 운동장 하늘을 비눗방울로 싹 정복했어!",
                  '풍선이나 비눗방울을 터뜨릴 때 아이들이 방방 뛰며 소리치는 직관적인 단어입니다.',
                  "터뜨려! (신나는 점프 외침)", "Do not touch air.", "공기 만지지 말라는 엉뚱한 말이에요.", "I am bored.", "지루하다는 찬물 끼얹기예요."),
        make_turn(4, "Leo", "🦁", "Look! A giant rainbow bubble is floating toward the swings! Quick!", "봐봐! 무지개 왕 비눗방울이 그네 쪽으로 둥실둥실 날아간다! 얼른!",
                  '"얼른 가서 잡아!"라고 기본동사 go와 get을 써서 외쳐보세요!', "Go get it!",
                  "I'm running after it! POP! Bubble splash right on my nose!", "내가 뒤쫓아 뛰어간다! 톡! 내 코끝에서 퐁 터졌어!",
                  '기본동사 "go"와 "get"이 결합한 "Go get it!"은 목표를 향해 "얼른 가서 잡아라/가져와라!"라고 신나게 뛸 때 쓰는 표현입니다.',
                  "얼른 가서 잡아! (행동 촉구 기본동사 콤보)", "Look away.", "딴 데 보라는 오답이에요.", "Sit down.", "주저앉으라는 김빠지는 말이에요."),
        make_turn(5, "Leo", "🦁", "Look at that monster bubble! It's drifting slowly towards the sandbox! Can you catch it?", "저 괴물 비눗방울 좀 봐! 모래사장 쪽으로 살살 떠가고 있어! 잡을 수 있어?",
                  '"이것 좀 봐봐!"라고 구동사 check out을 써서 가리켜보세요!', "Check that out!",
                  "Whoa, it reflects the whole playground! POP! Splash of soap water!", "우와, 비눗방울에 운동장 전체가 비쳐! 퐁! 비눗물이 톡 튀었어!",
                  '구동사 "check out"은 눈앞의 신기한 것이나 물건을 "확인해보다/봐봐!"라고 주의를 끌 때 원어민들이 매일 쓰는 구동사입니다.',
                  "이것 좀 봐봐! (주목과 확인의 필수 구동사)", "Don't look at it.", "보지 말라는 오답이에요.", "Blow black smoke.", "검은 연기 불라는 오답이에요."),
        make_turn(6, "Leo", "🦁", "My bubble wand blew ten giant bubbles, but now the plastic cup is totally empty!", "내 비눗방울 막대로 왕 비눗방울 열 개 불었더니, 플라스틱 컵이 완전 바닥났어!",
                  '"비눗물 다시 채우자!"라고 구동사 fill it up을 써서 외쳐보세요!', "Fill it up!",
                  "Pouring the bubbly soap mixture to the brim! Round two of bubble rain begins!", "비눗물 찰랑찰랑하게 채웠다! 비눗방울 비 2라운드 시작!",
                  '구동사 "fill up"은 컵이나 물통, 그릇을 "가득 채우다"라는 뜻으로 음료나 놀이에서 매일 쓰는 최고빈도 구동사입니다.',
                  "비눗물 다시 채우자! (채우기 필수 구동사)", "Drink all soap.", "비눗물 다 마시라는 위험한 오답이에요.", "Dump it on Leo's head.", "친구 머리에 쏟으라는 오답이에요."),
        make_turn(7, "Leo", "🦁", "The plastic cup is brim-full with bubbly soap water and a gentle breeze is blowing! Ready for the bubble cannon?", "플라스틱 컵에 비눗물 가득 찼고 살랑살랑 바람 분다! 왕 비눗방울 대포 쏠 준비 됐어?",
                  "\"힘껏 세게 불어!\"라고 기본동사 blow를 써서 응원해보세요!", "Blow hard!",
                  "WHOA! A giant balloon-sized bubble floating right into the sunshine! That was magnificent!", "우와아! 풍선만 한 왕 비눗방울이 햇살 속으로 둥둥 떠간다! 완전 장관이다!",
                  "기본동사 \"blow\"는 입으로 바람을 \"불다\"라는 뜻으로 비눗방울, 촛불, 풍선을 불 때 매일 쓰는 대표 기본동사입니다.",
                  "힘껏 세게 불어! (호흡 및 발사 필수 기본동사)", "Inhale the soap.", "비눗물 들이마시라는 위험한 오답이에요.", "Break the wand.", "막대 부러뜨리라는 오답이에요.")
    ]),

    make_ep("t1_e9", "tier1", "종이비행기 날리기", "📍 Episode 9/10: Airplane Launch", "tag", [
        make_turn(1, "Sammy", "🦊", "I folded a super supersonic jet! Ready to throw?", "초음속 제트기 접었어! 던질 준비 됐어?",
                  '"준비, 땅!"이라고 씩씩하게 외쳐보세요!', "Ready, set, go!",
                  "Three, two, one, blast off into the wind!", "셋, 둘, 하나, 바람 타고 날아간다!",
                  '경주나 던지기 놀이를 시작할 때 외치는 미국의 공식 출발 구호입니다.',
                  "준비, 땅! (출발 신호)", "Stop everything.", "멈추라는 말이에요.", "I am full.", "배부르다는 말이에요."),
        make_turn(2, "Sammy", "🦊", "Look how far your plane flew! Almost over the wall!", "네 비행기 날아간 것 좀 봐! 담장을 거의 넘었어!",
                  '"진짜 빠르다!"라고 환호해보세요!', "So fast!",
                  "You definitely won the distance trophy today!", "오늘 멀리 날리기 1등 트로피는 네 거야!",
                  '속도가 빠를 때 가장 짧고 직관적으로 내뱉는 키즈 감탄사입니다.',
                  "진짜 빠르다! (직관적 감탄)", "Extremely slow.", "느리다는 오답이에요.", "Good night.", "자러 가는 인사예요."),
        make_turn(3, "Sammy", "🦊", "The wind is picking up! Can you beat your own record?", "바람 더 불기 시작했어! 너 아까 세운 신기록 깰 수 있어?",
                  '"한 번 더 하자!"라고 도전 정신을 불태워보세요!', "One more time!",
                  "Yes! Let's aim for the big oak tree this time!", "좋아! 이번엔 저 큰 참나무까지 날려보는 거야!",
                  '놀이나 게임이 너무 재미있어서 또 하자고 조를 때 미국 아이들이 가장 많이 쓰는 관용구입니다.',
                  "한 번 더! (신나는 재도전)", "I quit forever.", "영원히 때려치운다는 말이에요.", "I am thirty years old.", "나이 거짓말이에요."),
        make_turn(4, "Sammy", "🦊", "The jet glided all the way onto the soft grass field!", "종이 제트기가 저기 부드러운 잔디밭 위까지 미끄러져 날아갔어!",
                  '"얼른 주우러 가자!"라고 구동사 pick up을 써서 말해보세요!', "Let's pick it up!",
                  "Got it! Not a single bend on the wings! Launch number two ready!", "찾았다! 날개 하나도 안 구겨졌어! 2차 발사 준비 완료!",
                  '구동사 "pick up"은 날아간 종이비행기나 장난감을 다시 집어 들 때 가장 많이 쓰는 기본 구동사입니다.',
                  "얼른 주우러 가자! (물건 회수 필수 구동사)", "Step on it.", "밟아 뭉개라는 나쁜 말이에요.", "Burn the paper.", "종이 태우라는 위험한 말이에요."),
        make_turn(5, "Sammy", "🦊", "If we fold the back wings upward like flaps, do you think it'll do a loop?", "뒷날개를 플랩처럼 위로 살짝 접으면 공중제비 돌 수 있을까?",
                  '"한번 시도해보자!"라고 기본동사 give를 써서 격려해보세요!', "Give it a shot!",
                  "It did a complete three-sixty loop in the air! That was epic!", "공중에서 360도 완벽하게 한 바퀴 돌았어! 완전 레전드다!",
                  '기본동사 "give"를 활용한 "Give it a shot!"(한번 해봐/시도해봐)은 "Give it a try"와 함께 시도를 북돋우는 최상위 빈도 표현입니다.',
                  "한번 시도해보자! (도전 권유 기본동사)", "Throw it in the trash.", "쓰레기통에 버리라는 오답이에요.", "Never fold paper.", "종이 접지 말라는 오답이에요."),
        make_turn(6, "Sammy", "🦊", "Whoa, that three-sixty loop landed right near the center fountain bench! Look at it glide!", "우와, 공중제비 돈 비행기가 분수대 벤치 바로 옆에 착륙했어! 활공하는 것 좀 봐!",
                  '"가서 가져오자!"라고 기본동사 go와 get을 써서 달려가보세요!', "Go get it!",
                  "Sprinting to the bench! Snapped it up safely! Ready for the supersonic altitude test!", "벤치로 전력 질주! 안전하게 낚아챘다! 초음속 고도 테스트 준비 완료!",
                  '기본동사 "go"와 "get"이 결합된 "Go get it!"(가서 가져와/잡아와!)은 날아간 공이나 물건을 주우러 갈 때 아이들이 가장 먼저 외치는 구어체입니다.',
                  "가서 가져오자! (회수 촉구 기본동사)", "Leave it in the rain.", "비 맞게 두라는 오답이에요.", "Burn the wings.", "날개 태우라는 위험한 오답이에요."),
        make_turn(7, "Sammy", "🦊", "We have our supersonic paper jet back in hand! Look at the playground trees waving in the breeze!", "종이 제트기 무사히 손에 되찾았다! 운동장 나뭇가지 바람에 흔들리는 것 좀 봐!",
                  "\"한 번 더 날려보자!\"라고 기본동사 fly를 써서 신나게 외쳐보세요!", "Let's fly it again!",
                  "Zoom! Up over the oak tree and gliding across the whole blue sky! Record officially broken!", "슝! 참나무 훌쩍 넘어서 푸른 하늘 가로질러 날아간다! 공식 신기록 달성!",
                  "기본동사 \"fly\"는 비행기나 연 등을 \"날리다\"라는 뜻으로 \"Let's fly it again!\"처럼 놀이 현장에서 입에 달고 사는 표현입니다.",
                  "한 번 더 날려보자! (비행 및 놀이 필수 기본동사)", "Rip wings off.", "날개 뜯으라는 심술이에요.", "Bury plane in dirt.", "흙에 묻으라는 오답이에요.")
    ]),

    make_ep("t1_e10", "tier1", "하교 작별 인사", "📍 Episode 10/10: After-School Farewell", "cafeteria", [
        make_turn(1, "Penny", "🐧", "The yellow bus is here! Grab your backpack!", "노란 스쿨버스가 왔어! 얼른 책가방 챙겨!",
                  '"내일 또 보자!"라고 밝게 작별 인사를 건네보세요!', "See you tomorrow!",
                  "Don't forget to bring your toy dinosaur tomorrow!", "내일 공룡 장난감 가져오는 거 잊지 마!",
                  '학교나 유치원에서 하교할 때 매일 친구들과 나누는 가장 표준적인 작별 인사입니다.',
                  "내일 봐! (가장 자연스러운 작별)", "Never see you.", "다신 안 보겠다는 거친 말이에요.", "Good morning.", "아침 인사예요."),
        make_turn(2, "Penny", "🐧", "I'm going to the bouncy trampoline park with my cousin!", "나 사촌이랑 트램펄린 방방이 파크 갈 거야!",
                  '"재밌게 놀아!"라고 즐거운 시간을 응원해주세요!', "Have fun!",
                  "Thanks! I'll tell you all about the giant pit tomorrow!", "고마워! 내일 볼풀장 얘기 다 해줄게!",
                  '어딘가 놀러 가는 친구에게 건네는 가장 대중적이고 기분 좋은 축원 표현입니다.',
                  "재밌게 놀아! (따뜻한 응원)", "Be very sad.", "슬퍼하라는 악담이에요.", "Where is my pencil?", "연필 찾는 엉뚱한 말이에요."),
        make_turn(3, "Penny", "🐧", "The bus driver is honking! Quick, jump on board!", "버스 기사님이 경적 울리신다! 얼른 올라타!",
                  '"이따 또 봐!"라고 손을 흔들며 외쳐보세요!', "Catch you later!",
                  "Save me a window seat next to you tomorrow morning! Bye!", "내일 아침에 내 창가 옆자리 맡아놔줘! 안녕!",
                  '친구와 헤어질 때 "또 봐, 나중에 봐"의 뜻으로 가볍고 경쾌하게 쓰는 키즈 구어체입니다.',
                  "이따 또 봐! (경쾌한 작별)", "I am trapped.", "갇혔다는 공포스런 말이에요.", "My name is John.", "자기소개예요."),
        make_turn(4, "Penny", "🐧", "The yellow bus doors are folding open! The driver says hop in!", "노란 스쿨버스 문이 덜컹 열린다! 기사님이 얼른 타래!",
                  '"얼른 버스 타!"라고 구동사 get on을 써서 말해보세요!', "Get on!",
                  "Climbing the steps! Save me a seat tomorrow morning! Bye!", "계단 올라탄다! 내일 아침에도 창가 자리 맡아줘! 안녕!",
                  '구동사 "Get on"은 버스나 기차 등 대형 교통수단에 탑승할 때 "얼른 타!"라는 의미로 쓰이는 필수 구동사입니다.',
                  "얼른 올라타! (교통수단 탑승 구동사)", "Fall off.", "떨어지라는 악담이에요.", "Sleep outside.", "밖에서 자라는 엉뚱한 말이에요."),
        make_turn(5, "Penny", "🐧", "The bus driver is closing the door and shifting into drive! Wave bye-bye!", "버스 기사님이 문 닫으시고 출발 기어 넣으신다! 창밖으로 손 흔들어!",
                  '"몸조심하고 잘 가!"라고 기본동사 take를 써서 다정하게 인사해보세요!', "Take care!",
                  "You too! Have a great afternoon and see you tomorrow morning!", "너도! 즐거운 오후 보내고 내일 아침에 보자!",
                  '기본동사 "take"를 사용한 "Take care!"(잘 지내, 몸조심해!)는 헤어질 때 따뜻한 정을 담아 건네는 가장 대중적인 원어민 작별 인사입니다.',
                  "몸조심하고 잘 가! (따뜻한 작별 기본동사)", "Fall off the bus.", "버스에서 떨어지라는 오답이에요.", "Forget my name.", "이름 까먹으라는 오답이에요."),
        make_turn(6, "Penny", "🐧", "The bus is rolling out of the school driveway! Look at Leo waving through the back window!", "스쿨버스가 학교 진입로 벗어나는 중이야! 뒷유리창으로 레오 손 흔드는 것 좀 봐!",
                  '"내일 또 보자!"라고 기본동사 catch를 써서 쿨하게 작별 인사를 건네보세요!', "Catch you tomorrow!",
                  "You bet! Bringing my new superhero comic book tomorrow morning! Peace out!", "당연하지! 내일 아침에 새 슈퍼히어로 만화책 가져올게! 잘 가!",
                  '기본동사 "catch"를 활용한 "Catch you tomorrow!"(내일 봐!)는 또래 아이들이 헤어질 때 쿨하고 친근하게 매일 쓰는 자연스러운 구어체입니다.',
                  "내일 또 보자! (친근한 작별 기본동사)", "Never talk to me.", "말 걸지 말라는 절교 선언이에요.", "Stay in school all weekend.", "주말 내내 학교에 있으라는 오답이에요."),
        make_turn(7, "Penny", "🐧", "I see my mom waving at the bus stop corner! Have a super yummy dinner and rest up at home!", "버스 정류장 모퉁이에서 우리 엄마 손 흔드신다! 집에서 맛있는 저녁 먹고 푹 쉬어!",
                  "\"너도 좋은 저녁 보내!\"라고 기본동사 have를 써서 다정하게 인사해보세요!", "You have a good one!",
                  "You too! Eating yummy mac and cheese tonight! See you on the yellow bus tomorrow morning!", "너도! 오늘 밤엔 맛난 맥앤치즈 먹을 거야! 내일 아침 노란 버스에서 봐!",
                  "기본동사 \"have\"를 활용한 \"Have a good one!\"은 \"좋은 하루/저녁 보내!\"라는 뜻으로 미국인들이 헤어질 때 남녀노소 가장 친근하게 쓰는 대표 관용구입니다.",
                  "너도 좋은 시간 보내! (친근한 작별 축원 기본동사)", "Sleep on bus all night.", "밤새 버스에서 자라는 오답이에요.", "Lose your backpack.", "가방 잃어버리라는 악담이에요.")
    ])
]
