"""Tier 4 Scenarios: Ages 14-16 (10 episodes x 10 turns = 100 turns)."""
from scenarios_common import make_ep, make_turn

t4 = [
    make_ep("t4_e1", "tier4", "락커룸 농구 내기", "📍 Episode 1/10: Locker Room Free Throw Bet", "basketball", [
        make_turn(1, "Jordan", "🏀", "I bet I can sink five half-court shots in a row today! No joke!", "오늘 하프라인에서 슛 연속 다섯 개 클린으로 꽂는다에 내기 건다! 진심이야!",
                  '"진짜 실화야? 거짓말 아니고?"라고 확인해보세요!', "No cap!",
                  "Dead serious! If I miss even one, I'm buying you pizza rolls!", "진짜 거짓말 아니고! 하나라도 빗나가면 내가 너 피자롤 쏜다!",
                  '"No cap"은 "거짓말 아니고, 진짜 실화야"라는 미국의 대표적인 Z세대 슬랭입니다.',
                  "진짜 실화야! 거짓말 아니고! (Z세대 진실 슬랭)", "Wear a baseball cap.", "모자 쓰라는 오역이에요.", "Basketball is a ball.", "농구공은 공이라는 딴소리예요."),
        make_turn(2, "Jordan", "🏀", "So do you take the wager? High stakes at the school gym!", "그래서 내기 받을 거야 말 거야? 체육관에서 큰 판 한번 벌여봐?",
                  '"콜! 당연하지! 약속이야!"라고 패기 있게 받아치세요!', "Bet!",
                  "You're on! Let's lace up and head straight to the court right now!", "좋았어 받아줬다! 신발 끈 꽉 매고 지금 바로 코트로 간다!",
                  '상대의 도전이나 제안에 "콜! 당연하지! 좋아!"라고 쿨하게 화답하는 대표 단어입니다.',
                  "콜! 당연하지! (화답 슬랭)", "I am gambling money.", "도박한다는 오역이에요.", "Class is boring.", "수업 지루하다는 딴소리예요."),
        make_turn(3, "Jordan", "🏀", "I need you to grab the rebound under the net and pass it back smooth!", "네가 골대 밑에서 리바운드 잡고 공 스무스하게 튕겨 패스해 줘!",
                  '"더 말할 것도 없어, 접수 완료!"라고 쿨하게 끄덕이세요!', "Say less.",
                  "Perfect teammate! Shot number one going up... Swish! Clean through the rim!", "최고의 팀원! 1번 슛 올라간다... 철썩! 그물만 깔끔하게 통과!",
                  '상대방의 요청을 듣자마자 "말 길게 할 필요 없어, 다 이해했어, 접수 완료"라고 할 때 씁니다.',
                  "더 말할 것도 없어, 접수! (쿨한 이해와 접수)", "Talk very quietly.", "조용히 말하라는 오역이에요.", "I have no hands.", "손 없다는 엉뚱한 말이에요."),
        make_turn(4, "Jordan", "🏀", "Shot number two and three just went through without even brushing the iron!", "2번이랑 3번 슛도 림에 닿지도 않고 클린으로 들어갔어!",
                  '"그물만 철렁! 완전 나이스 샷!"라고 환호해보세요!', "Swish nothing but net.",
                  "Shot four... Bang! One more left from the logo!", "4번 슛도 꽂혔다! 이제 로고에서 던지는 마지막 한 방 남았다!",
                  '농구공이 림을 스치지도 않고 그물만 찰랑이며 깨끗하게 꽂혔을 때 쓰는 전문 농구 구어체입니다.',
                  "그물만 철렁! (클린 샷 찬사)", "Hit the metal hard.", "철봉 때렸다는 오답이에요.", "I want to go home.", "집 가고 싶다는 징징거림이에요."),
        make_turn(5, "Jordan", "🏀", "Shot five... Clank off the back rim! Aaargh, I missed the last one!", "5번 슛... 백림 맞고 튕겨 나갔어! 으아악, 마지막 하나를 놓쳤네!",
                  '"내기 졌으니까 피자롤 뱉어내라!"라고 유쾌하게 요구하세요!', "Pay up!",
                  "A deal's a deal! Extra cheese pizza rolls at the cafeteria table tomorrow!", "약속은 약속이지! 내일 급식실에서 치즈 듬뿍 피자롤 내가 산다!",
                  '내기에서 이겼을 때 "약속한 거 내놔라, 계산해라"고 당당하고 유쾌하게 외치는 표현입니다.',
                  "약속한 거 내놔라! (유쾌한 내기 정산)", "Keep your money.", "돈 가지라는 바보 같은 말이에요.", "The ball is orange.", "공 주황색이라는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "Four out of five from half-court was still insane though! High five!", "그래도 하프라인에서 5개 중 4개 넣은 건 레전드였다! 하이파이브!",
                  '"좋은 승부였어, 인정한다!"라고 승자의 여유를 보여주세요!', "GG, good game!",
                  "Catch you at the cafeteria tomorrow at noon! Have your appetite ready!", "내일 점심 정오에 식당에서 봐! 위장 싹 비우고 와라!",
                  '게임이나 시합이 끝난 뒤 상대방을 존중하며 깔끔하게 악수를 청하는 게이머/하이틴 필수 인사입니다.',
                  "좋은 승부였어! (깔끔한 스포츠맨십)", "You are the worst.", "최악이라는 악담이에요.", "Cancel the game.", "경기 취소하라는 헛소리예요."),
        make_turn(7, "Jordan", "🏀", "The gym lights are clicking off and our pizza rolls are scheduled for noon tomorrow!", "체육관 불 꺼지고 내일 정오에 피자롤 먹기로 약속됐잖아!",
                  '"내일 점심 진짜 기대된다!"라고 구동사 look forward to를 써서 말해보세요!', "I'm looking forward to it!",
                  "You earned those rolls fair and square! Double pepperoni on my dime tomorrow at twelve!", "네 실력으로 정당하게 딴 거니까! 내일 12시에 페퍼로니 두 배로 내가 쏜다!",
                  '구동사 "look forward to ~"는 다가올 일을 "설레는 마음으로 고대하다/기대하다"라는 뜻으로 일상과 대화에서 매일 쓰입니다.',
                  "진짜 기대돼! (설레는 기대의 대표 구동사)", "I dread eating pizza.", "피자 먹기 두렵다는 딴소리예요.", "Cancel lunch forever.", "점심 영원히 취소하자는 엉뚱한 말이에요."),
        make_turn(8, "Jordan", "🏀", "Before we lock up the gym, help me bag these five practice basketballs!", "체육관 문 잠그기 전에, 연습용 농구공 다섯 개 공가방에 넣는 것 좀 도와줘!",
                  '"제자리에 치워두자!"라고 구동사 put away를 써서 말해보세요!', "Let's put them away!",
                  "Zipped into the mesh rack! Court is spotless and ready for tomorrow's tournament!", "그물망 보관함에 지퍼 잠갔다! 코트 완전 깔끔하게 정리 끝, 내일 대회 준비 완료!",
                  '구동사 "put away"는 스포츠 용품이나 물건을 "제자리에 정리하다/치워두다"라는 뜻의 최상위 빈도 구동사입니다.',
                  "제자리에 치워두자! (정리 및 수납 필수 구동사)", "Kick balls outside.", "공 밖으로 차라는 오답이에요.", "Leave balls on court.", "코트에 방치하라는 오답이에요."),
        make_turn(9, "Jordan", "🏀", "Coach locked up the equipment room and the janitor is turning off the hallway lights! Subway station next?", "코치님이 장비실 잠그셨고 관리원 아저씨가 복도 불 끄신다! 이제 지하철역 갈까?",
                  '"내일 봐!"라고 구동사 catch you later를 써서 쿨하게 작별 인사를 건네보세요!', "Catch you later!",
                  "Catch you at noon by the cafeteria vending machines! Have that pizza roll appetite ready! Peace out!", "내일 정오에 급식실 자판기 앞에서 만나! 피자롤 먹을 위장 비워둬라! 피스 아웃!",
                  '구동사 "catch [someone] later"(이따 봐, 나중에 봐)는 헤어질 때 미국 10대들이 가장 쿨하고 친근하게 쓰는 대표 작별 구동사입니다.',
                  "내일 봐! (쿨한 작별 필수 구동사)", "Lock me in gym forever.", "체육관에 평생 가두라는 오답이에요.", "Burn basketball shoes.", "농구화 태우라는 오답이에요."),
        make_turn(10, "Jordan", "🏀", "Walking out into the sunset breeze outside the athletic wing! Don't you dare forget about those pepperoni pizza rolls at noon tomorrow!", "체육관 밖으로 나오니 시원한 노을 바람 분다! 내일 정오에 페퍼로니 피자롤 사주기로 한 거 절대 잊지 마라!",
                  "\"내가 언제 약속 어긴 적 있어?\"라고 관용 표현 You have my word를 써서 확답해보세요!", "You have my word!",
                  "Bet! Vending machine plaza at twelve sharp! Sleep well tonight, free throw champion!", "콜! 12시 정각에 자판기 광장에서 보자! 오늘 밤 푹 자둬라, 자유투 챔피언!",
                  "관용구 \"You have my word!\"(내 말 믿어, 약속할게/내가 보증해!)는 신뢰와 약속을 굳게 다짐할 때 격식과 캐주얼 모두에서 쓰이는 무게감 있는 표현입니다.",
                  "내 말 믿어, 약속해! (약속과 보증 필수 관용구)", "I lie about everything.", "다 거짓말이라는 오답이에요.", "Lose all your money.", "돈 다 날리라는 악담이에요.")
    ]),

    make_ep("t4_e2", "tier4", "방과 후 버블티 번개", "📍 Episode 2/10: After-School Boba Cravings", "bubbleTea", [
        make_turn(1, "Chloe", "🎨", "The 7th period bell finally rang! My brain is officially melted from chemistry!", "7교시 종 드디어 쳤다! 화학 수업 때문에 내 뇌 완전히 녹아내렸어!",
                  '"나 은근 버블티 엄청 땡겨."라고 속마음을 흘려보세요!', "I'm lowkey craving boba.",
                  "Stop reading my mind! Brown sugar milk tea with extra pearls right now!", "내 마음 그만 읽어! 당장 흑당 밀크티에 타피오카 펄 추가하러 가자!",
                  '자신의 소망이나 상태를 부담 없이 넌지시 고백할 때 10대들이 가장 애용하는 슬랭입니다.',
                  "나 은근 버블티 땡겨. (은근한 욕구 고백)", "I dislike drinks.", "음료 싫다는 딴소리예요.", "Chemistry is easy.", "화학 쉽다는 거짓말이에요."),
        make_turn(2, "Chloe", "🎨", "The walk is like eight blocks... Is it worth the trek in this heat?", "걸어서 8블록이나 되는데... 이 더위에 걸어갈 만한 가치가 있을까?",
                  '"완전 그만한 가치 있지!"라고 등을 떠밀어보세요!', "Worth every penny.",
                  "That's all the motivation I need! Put on your shades, let's move!", "그 한마디면 충분해! 선글라스 끼고 지금 바로 출발하자!",
                  '돈이나 시간, 노력을 들일 만큼 100% 가치 있고 보람찰 때 쓰는 대표 관용구입니다.',
                  "완전 그만한 가치가 있어! (100% 가치 보장)", "Worth zero cents.", "0원의 가치라는 반대말이에요.", "I have no legs.", "다리 없다는 엉뚱한 말이에요."),
        make_turn(3, "Chloe", "🎨", "Look at that line out the door! It wraps all the way around the corner!", "문 밖으로 늘어선 줄 좀 봐! 코너 돌아서까지 줄 서 있어!",
                  '"말도 안 돼, 실화야?"라고 기막혀해보세요!', "You gotta be kidding me.",
                  "Don't worry, the boba baristas here are speed demons! It moves fast!", "걱정 마 여기 버블티 알바생들 손 진짜 번개야! 줄 금방 빠져!",
                  '황당하거나 믿기 힘든 난관을 마주했을 때 헛웃음을 치며 외치는 구어체입니다.',
                  "말도 안 돼, 장난해? (기막힌 리액션)", "I am kidding myself.", "나 스스로에게 장난친다는 오역이에요.", "Lines are straight.", "줄은 직선이라는 딴소리예요."),
        make_turn(4, "Chloe", "🎨", "They just put out the chalkboard: Buy one brown sugar boba, get one free!", "방금 칠판 입간판 걸렸어: 흑당 버블티 1+1 원플러스원 행사한대!",
                  '"대박 횡재다! 완전 거저네!"라고 환호해보세요!', "What a score!",
                  "Score of the century! We each get a large cup for three bucks!", "세기의 득템이다! 우리 각자 대용량 컵 3달러에 마시는 꼴이야!",
                  '기대 이상의 큰 득템이나 행운을 잡았을 때 속 시원하게 외치는 슬랭입니다.',
                  "대박 횡재야! 완전 거저다! (행운의 득템 환호)", "I hate free drinks.", "공짜 싫다는 억지예요.", "One plus one is two.", "수학 공식 읊는 오답이에요."),
        make_turn(5, "Chloe", "🎨", "Straw punched through the sealed plastic lid on the first try!", "밀봉된 플라스틱 뚜껑에 빨대 원샷 원킬로 팍 꽂았어!",
                  '"크, 이 맛이지!"라고 첫 모금을 삼키며 감탄해보세요!', "Hits the spot.",
                  "Mmmmm! Chewy brown sugar heaven! Chemistry exam stress totally erased!", "음~! 쫀득한 흑당 천국이다! 화학 시험 스트레스 완벽하게 싹 지워졌어!",
                  '음식이나 음료가 갈증과 피로를 완벽하게 해소해 줄 때 외치는 최고의 미식 찬사입니다.',
                  "크, 바로 이 맛이지! (피로 해소 찬사)", "Hits my foot.", "발을 때렸다는 직역 오역이에요.", "Too much sugar.", "설탕 많다는 투덜거림이에요."),
        make_turn(6, "Chloe", "🎨", "The outdoor neon benches are open! Let's sit and gossip about the dance!", "야외 네온 벤치 자리 났다! 앉아서 이번 학교 축제 댄스파티 썰 풀자!",
                  '"수다 맘껏 떨어보자!"라고 자리에 앉으세요!', "Spill the tea.",
                  "So basically, Leo asked Penny with a giant teddy bear in the hallway...", "그래서 말인데, 레오가 복도에서 페니한테 왕 곰 인형 들고 신청했대...",
                  '흥미진진한 뒷이야기나 최신 비밀 소식을 털어놓으라고 재촉할 때 쓰는 대표적인 Z세대 유행어입니다.',
                  "썰 한번 풀어봐! (비밀 수다 개시)", "Do not drink tea.", "차 마시지 말라는 오역이에요.", "I love coffee.", "커피 좋다는 딴소리예요."),
        make_turn(7, "Chloe", "🎨", "The boba barista called our order number 42 on the loudspeaker!", "버블티 직원이 확성기로 우리 주문 번호 42번 부르셨어!",
                  '"음료 받으러 가자!"라고 구동사 pick up을 써서 말해보세요!', "Let's pick it up!",
                  "Straws poked in and boba pearls settled! Double large cups ready for our street stroll!", "빨대 꽂고 펄 가라앉혔다! 대형 사이즈 두 잔 들고 길거리 산책 가자!",
                  '구동사 "pick up"은 주문한 음료나 음식을 카운터에서 "수령하다/받아오다"라는 뜻으로 일상 1위 구동사입니다.',
                  "음료 받아오자! (수령 및 픽업 필수 구동사)", "Drop the drinks on floor.", "바닥에 쏟으라는 오답이에요.", "Throw straws away.", "빨대 버리라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "The sun is setting behind the high school clock tower and our cups are half empty!", "고등학교 시계탑 뒤로 해가 뉘엿뉘엿 지고 컵도 절반쯤 비었어!",
                  '"이제 슬슬 마무리하고 가자!"라고 구동사 wrap up을 써서 말해보세요!', "Let's wrap it up!",
                  "Tossing empty cups in recycling! Walking home while the evening breeze is nice and cool!", "빈 컵 분리수거함에 쏙 버리기! 저녁 바람 시원할 때 집으로 걸어가자!",
                  '구동사 "wrap up"은 모임이나 수다, 일정을 깔끔하게 "마무리하다/정리하다"라는 뜻의 핵심 구동사입니다.',
                  "이제 슬슬 정리하자! (일정 종료 필수 구동사)", "Scream on street.", "길거리에서 비명 지르라는 오답이에요.", "Buy fifty more cups.", "50잔 더 사라는 억지예요."),
        make_turn(9, "Chloe", "🎨", "We drank all the brown sugar boba and finished our chemistry flashcards! The street is packed with students heading to the subway!", "흑당 버블티 다 마셨고 화학 플래시카드 복습도 끝났어! 지하철역 가는 길에 학생들 꽉 찼다!",
                  '"이제 출발하자!"라고 구동사 hit the road를 써서 길을 나서보세요!', "Let's hit the road!",
                  "Skateboards down on asphalt! Cruising to the train station in style! See you tomorrow morning!", "아스팔트에 스케이트보드 내렸다! 간지나게 지하철역까지 슝 크루징 가자! 내일 아침에 봐!",
                  '구동사 "hit the road"는 자리를 털고 길을 나설 때 "이제 출발하자/떠나자"라는 뜻으로 쓰이는 대표적인 미국 관용구입니다.',
                  "이제 출발하자! (출발 필수 구동사)", "Pour boba on sidewalk.", "인도에 음료 쏟으라는 오답이에요.", "Sleep under the table.", "식탁 밑에서 자자는 오답이에요."),
        make_turn(10, "Chloe", "🎨", "The subway turnstiles are clicking and the downtown streetlights are buzzing alive! Boba pearls fully digested!", "지하철 개찰구 찰칵 돌아가고 시내 가로등 불 켜진다! 버블티 펄 뱃속에서 소화 완료!",
                  "\"오늘 같이 놀아서 진짜 재밌었어!\"라고 감사의 마음을 나눠보세요!", "I had a blast!",
                  "Me too! Let's do this again next Friday after AP Chem! Text me when your train pulls into your station!", "나도! 다음 주 금요일 AP 화학 끝나고 또 뭉치자! 전철 역 도착하면 톡해!",
                  "관용구 \"I had a blast!\"(진짜 시간 가는 줄 모르게 신나게 놀았어/대박 재밌었어!)는 만남이나 파티를 마치고 헤어질 때 건네는 최고의 감사 찬사입니다.",
                  "진짜 대박 재밌었어! (최고의 만남 자축)", "I was miserable.", "비참했다는 최악의 오답이에요.", "Break the subway gate.", "개찰구 부수라는 오답이에요.")
    ]),

    make_ep("t4_e3", "tier4", "금요일 풋볼 경기 열기", "📍 Episode 3/10: Friday Night Lights Spirit", "football", [
        make_turn(1, "Jordan", "🏀", "Look at the student section bleachers! Packed wall to wall in varsity blue!", "학생 응원석 스탠드 좀 봐! 학교 상징 파란색 옷 입고 꽉 찼어!",
                  '"오늘 분위기 진짜 미쳤다!"라고 응원 열기에 취해보세요!', "Vibes are immaculate!",
                  "Fourth quarter, two minutes left, and we're down by just two points!", "4쿼터 2분 남았고 딱 2점 차로 뒤지고 있어!",
                  '파티나 경기장의 분위기가 더할 나위 없이 환상적일 때 외치는 최신 유행어입니다.',
                  "분위기 완전 찢었다! (극상의 경기장 분위기)", "The room is dusty.", "먼지 많다는 오역이에요.", "I hate blue shirts.", "파란 셔츠 싫다는 딴청이에요."),
        make_turn(2, "Jordan", "🏀", "Our quarterback is stepping up into the pocket... Looking deep downfield!", "우리 쿼터백이 포켓 안쪽으로 파고들며... 엔드존 깊숙이 시선 고정!",
                  '"깊게 패스 찔러넣어라!"라고 목청껏 외쳐보세요!', "Throw a hail mary!",
                  "The ball is in the air... Spiral arching fifty yards down the sideline!", "공 떴다... 사이드라인 타고 50야드 날아가는 나선형 패스!",
                  '미식축구에서 승부를 뒤집기 위해 던지는 장거리 결승 패스를 뜻하는 명표현입니다.',
                  "결승 패스 찔러라! (역전 승부수 외침)", "Hail is falling from sky.", "우박 떨어진다는 직역 오역이에요.", "Catch the bird.", "새 잡으라는 엉뚱한 말이에요."),
        make_turn(3, "Jordan", "🏀", "TOUCHDOWN! Our wide receiver dragged both toes in the corner of the end zone!", "터치다운! 와이드 리시버가 엔드존 구석에서 양 발끝 찍고 잡아냈어!",
                  '"완전 영화 같은 명장면이다!"라고 포효해보세요!', "Straight out of a movie!",
                  "Stadium siren blaring! Bleachers literally shaking under our feet!", "경기장 사이렌 울린다! 우리 발밑 스탠드가 지진 난 것처럼 흔들려!",
                  '눈앞의 플레이나 상황이 영화 속 클라이맥스처럼 비현실적으로 멋질 때 쓰는 극찬입니다.',
                  "완전 영화 속 명장면이야! (비현실적 극찬)", "Movies are long.", "영화 길다는 딴소리예요.", "Sit down quietly.", "조용히 앉으라는 찬물이에요."),
        make_turn(4, "Jordan", "🏀", "Defense needs one final stop on 4th down! Thirty seconds remaining!", "이제 4번째 공격권 수비 딱 한 번만 막아내면 끝나! 30초 남았어!",
                  '"우리가 이긴다, 굳혀라!"라고 수비 응원을 이끌어보세요!', "Lock them down!",
                  "DEFENSE! DEFENSE! The whole stadium is chanting with one voice!", "디펜스! 디펜스! 온 경기장이 한목소리로 떼창하고 있어!",
                  '상대 팀의 공격을 철통같이 봉쇄하라고 수비진을 독려할 때 쓰는 전문 슬랭입니다.',
                  "철통 수비로 굳혀라! (수비 독려)", "Unlock the cage.", "새장 열라는 엉뚱한 오역이에요.", "Game is over.", "아직 안 끝났어요."),
        make_turn(5, "Jordan", "🏀", "Incomplete pass! The clock runs out! WE WON THE REGIONAL TITLE!", "패스 미완성! 시계 0초 찍혔다! 우리 학교가 지역 리그 우승했어!",
                  '"우리 학교 전교생 축제 시작이다!"라고 폭죽을 쏘아 올리세요!', "School spirit forever!",
                  "Storm the field! High fives with the mascot! Best Friday night lights of high school!", "그라운드로 뛰어 내려가! 마스코트랑 하이파이브! 인생 최고의 금요일 밤 풋볼이다!",
                  '학교의 승리를 자축하며 학교에 대한 애교심과 자부심을 폭발시킬 때 외치는 구호입니다.',
                  "우리 학교 영원하라! (애교심 대폭발)", "I am changing schools.", "전학 가겠다는 패륜이에요.", "Turn off lights.", "불 끄라는 김빠지는 소리예요."),
        make_turn(6, "Jordan", "🏀", "Look at our running back diving through the center line defense!", "중앙 수비 뚫고 다이빙하는 우리 러닝백 좀 봐봐!",
                  '"계속 힘내서 밀어붙여!"라고 구동사 keep on을 써서 응원해보세요!', "Keep on pushing!",
                  "Plowed through three defenders! First down on the fifteen-yard line!", "수비수 세 명 밀어붙이고 뚫었어! 15야드 라인에서 1st 다운 획득!",
                  '구동사 "keep on"은 멈추지 않고 하던 동작을 "계속 밀고 나가다"라는 뜻의 격려 구동사입니다.',
                  "계속 밀어붙여! (전진과 지속 필수 구동사)", "Stop and drop ball.", "멈추고 공 떨구라는 트롤 오답이에요.", "Run backward.", "뒤로 뛰라는 자폭 오답이에요."),
        make_turn(7, "Jordan", "🏀", "The stadium is freezing and the third quarter is kicking off! We need warm gloves!", "경기장 완전 쌀쌀해지고 3쿼터 킥오프 시작한다! 따뜻한 장갑 필요해!",
                  '"장갑 꼭 껴!"라고 구동사 put on을 써서 추위를 막아보세요!', "Put on your gloves!",
                  "Fleece gloves on tight! Now our hands are warm enough to wave the foam fingers!", "기모 장갑 꽉 꼈다! 이제 응원용 스펀지 손가락 흔들 만큼 손 따뜻해!",
                  '구동사 "put on"은 장갑, 패딩, 모자 등을 "착용하다"라는 의미의 필수 표현입니다.',
                  "장갑 꼭 챙겨 껴! (보온 착용 필수 구동사)", "Throw gloves at coach.", "코치님께 장갑 던지라는 오답이에요.", "Freeze your fingers.", "손가락 얼리라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "Our offense is huddled up on 3rd down with forty yards to go! Sing the fight song loud!", "우리 공격진 3rd 다운에 40야드 남기고 작전 회의 중이야! 학교 응원가 크게 불러!",
                  '"우리 선수들 힘차게 응원하자!"라고 구동사 cheer on을 써서 외쳐보세요!', "Let's cheer them on!",
                  "Roaring with three thousand fans! The quarterback hears the crowd roar! Let's get that touchdown!", "3천 명 팬들과 함께 함성 발사! 쿼터백이 관중 함성 들었어! 터치다운 가자!",
                  '구동사 "cheer [someone] on"은 경기장에서 선수를 목청껏 "응원하다/북돋우다"라는 뜻의 필수 구동사입니다.',
                  "힘차게 응원하자! (열정 응원 필수 구동사)", "Boo our own team.", "우리 팀에 야유하라는 배신 오답이에요.", "Leave stadium early.", "일찍 나가자는 김빠지는 오답이에요."),
        make_turn(9, "Jordan", "🏀", "Three seconds left on the stadium clock! Our kicker is lining up a forty-yard field goal right between the uprights!", "전광판 3초 남았다! 키커가 골대 정중앙 40야드 필드골 라인업 섰어!",
                  '"골 넣어라, 가보자!"라고 구동사 go for it을 써서 힘차게 외쳐보세요!', "Go for it!",
                  "The kick is UP... AND IT'S GOOD! IT SPLIT THE UPRIGHTS! FRIDAY NIGHT VICTORY!", "킥 떴다... 들어갔다! 골대 정중앙 갈랐어! 금요일 밤 미식축구 대역전 우승!",
                  '구동사 "go for it"(부딪쳐봐! 가보자! 해봐!)은 결정적인 승부처나 도전의 순간에 누구나 외치는 최고의 응원 구호입니다.',
                  "골 넣어라, 가보자! (결정적 도전과 응원 필수 구동사)", "Tackle the referee.", "심판 태클하라는 반칙 오답이에요.", "Run away from stadium.", "경기장에서 도망치라는 오답이에요."),
        make_turn(10, "Jordan", "🏀", "The stadium crowd rushed the goalposts! The marching band is playing the victory anthem under the bright stadium lights!", "관중들이 골대로 쏟아져 들어왔어! 조명탑 불빛 아래서 마칭 밴드가 승리의 응원가를 연주하고 있어!",
                  "\"오늘 밤 절대 못 잊을 거야!\"라고 벅찬 감동을 외쳐보세요!", "Unforgettable night!",
                  "History was made on this turf tonight! Regional championship rings coming our way! What a game!", "오늘 밤 이 잔디밭에서 역사가 쓰였다! 지역 챔피언십 우승 반지 우리 거다! 진짜 명경기였다!",
                  "\"Unforgettable [event]!\"는 일생일대의 역사적 순간이나 감동적인 경험을 영원히 기억하고 싶을 때 쓰는 명품 감탄사입니다.",
                  "절대 잊지 못할 밤이야! (역사적 순간 감탄)", "Forget tonight immediately.", "당장 잊으라는 김빠지는 오답이에요.", "I hate football.", "풋볼 싫다는 딴청이에요.")
    ]),

    make_ep("t4_e4", "tier4", "복도 꿀잼 드립 대잔치", "📍 Episode 4/10: Hallway Meme Banter", "teenLocker", [
        make_turn(1, "Chloe", "🎨", "Did you see that ridiculous viral cat video playing the recorder with its paws?", "발로 리코더 부는 황당한 레전드 고양이 릴스 영상 봤어?",
                  '"나 그거 보고 빵 터져서 뿜었잖아!"라고 배를 잡고 웃어보세요!', "I literally spat out my drink!",
                  "I watched it on loop five times before homeroom! Funniest thing this week!", "나 조례 시간 전에 5번 연속 돌려봤잖아! 이번 주 최고의 꿀잼 영상이야!",
                  '너무 웃겨서 마시던 음료나 물을 뿜을 뻔했거나 뿜었을 때 쓰는 유쾌한 과장 표현입니다.',
                  "나 그거 보고 뿜었잖아! (폭소 유발)", "I spat on floor.", "바닥에 침 뱉었다는 무례한 오역이에요.", "Cats cannot play instruments.", "설명충 반응이에요."),
        make_turn(2, "Chloe", "🎨", "Leo tried to recreate that recorder dance in third period Spanish...", "레오가 3교시 스페인어 시간에 그 고양이 춤 따라 하려다가...",
                  '"나 웃참 실패하고 현웃 터졌잖아!"라고 눈물을 닦아보세요!', "I lost my cool laughing!",
                  "Even Senora Martinez was biting her lip trying not to crack up!", "심지어 마르티네즈 선생님도 뿜는 거 참으려고 입술 깨물고 계시더라!",
                  '웃음을 참지 못하고 정줄을 놓은 채 빵 터졌을 때 쓰는 표현입니다.',
                  "웃참 실패하고 빵 터졌어! (웃음 통제 불가)", "I lost my money.", "돈 잃어버렸다는 엉뚱한 말이에요.", "Class was very quiet.", "조용했다는 거짓말이에요."),
        make_turn(3, "Chloe", "🎨", "The whole row of desks was vibrating from our suppressed giggles!", "책상 한 줄 전체가 우리 끅끅대며 웃는 진동으로 덜덜 떨렸잖아!",
                  '"배 아파 죽을 뻔했어!"라고 뒹굴어보세요!', "My stomach was hurting!",
                  "Pure abdominal workout from laughing so hard! Best period of the day!", "너무 쪼개서 복근 운동 제대로 됐다! 오늘 최고의 시간이었어!",
                  '너무 심하게 웃어서 배가 땡기고 아플 때 누구나 공감하는 생생한 표현입니다.',
                  "배 땡겨서 죽을 뻔했어! (포복절도 고백)", "Take me to hospital.", "병원 데려가라는 엉뚱한 말이에요.", "I hate comedy.", "코미디 싫다는 딴청이에요."),
        make_turn(4, "Chloe", "🎨", "Wait, someone recorded Leo's dance from the back row desk...", "잠깐, 맨 뒷자리에서 누가 레오 춤추는 거 영상 찍었대...",
                  '"그거 당장 보내줘!"라고 링크를 재촉하세요!', "Drop the link right now!",
                  "Sent it to the group chat! Prepare your ribs for round two!", "단톡방에 쐈다! 갈비뼈 부여잡을 2차전 준비해라!",
                  '재미있는 영상이나 웹사이트 링크를 공유해달라고 쿨하게 요구하는 디지털 구어체입니다.',
                  "그 링크 당장 쏴줘! (초스피드 공유 요청)", "Drop your phone.", "폰 떨어뜨리라는 오역이에요.", "I have no internet.", "인터넷 없다는 딴소리예요."),
        make_turn(5, "Chloe", "🎨", "If this video gets out on the school meme page...", "이 영상 학교 밈 계정에 올라가기라도 하면...",
                  '"완전 조회수 떡상하고 찢을걸!"라고 예견해보세요!', "It'll break the internet!",
                  "A million views by midnight guaranteed! Leo's gonna be a high school legend!", "자정까지 100만 뷰 무조건 보장! 레오 전설의 밈 스타 등극이다!",
                  '온라인상에서 엄청난 파장과 조회수를 일으키며 화제가 될 때 쓰는 대표 표현입니다.',
                  "인터넷 완전 찢어놓을걸! (조회수 대폭발 예고)", "Break your computer.", "컴퓨터 부수라는 위험한 말이에요.", "The internet is blue.", "인터넷 파란색이라는 딴소리예요."),
        make_turn(6, "Chloe", "🎨", "The hall monitor is walking this way! Stop giggling so loudly!", "복도 지도 선생님 이쪽으로 오신다! 그렇게 크게 낄낄거리지 마!",
                  '"목소리 낮춰, 조용히 해!"라고 구동사 keep it down을 써서 속삭이세요!', "Keep it down!",
                  "Whispering mode activated! Phew, she walked right into the teachers' lounge!", "속삭임 모드 전환! 휴, 교무실 안으로 쏙 들어가셨다 세이프!",
                  '구동사 "keep it down"은 소음이나 목소리를 "낮추다/조용히 하다"라는 뜻으로 교실과 도서관에서 매일 씁니다.',
                  "목소리 좀 낮춰! (소음 억제 필수 구동사)", "Scream louder.", "더 크게 소리 지르라는 반어적 트롤 오답이에요.", "Break locker lock.", "사물함 부수라는 오답이에요."),
        make_turn(7, "Chloe", "🎨", "Look at the teacher's stern face! Don't look at her or we'll burst out laughing again!", "선생님 정색하신 표정 봐봐! 쳐다보지 마 안 그러면 우리 또 빵 터진다!",
                  '"다른 데 쳐다봐!"라고 구동사 look away를 써서 웃참을 해보세요!', "Look away!",
                  "Biting my inner lip staring at the blue lockers! Phew, danger averted!", "파란 사물함 쳐다보면서 입술 꽉 깨물었어! 휴, 대참사 모면 성공!",
                  '구동사 "look away"는 시선을 딴 데로 "돌리다/외면하다"라는 뜻으로 웃참할 때 쓰는 표현입니다.',
                  "딴 데 쳐다봐! (시선 회피 필수 구동사)", "Stare into her eyes.", "선생님 눈 똑바로 째려보라는 위험한 오답이에요.", "Burst into tears.", "눈물 쏟으라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "Senora Martinez walked past, but we have five lockers between us and room 204!", "마르티네즈 선생님 지나가셨는데, 204호 교실까지 사물함 다섯 개 더 지나야 해!",
                  '"자세를 낮추고 조용히 가자!"라고 구동사 keep down을 써서 말해보세요!', "Keep down!",
                  "Ducking low beneath the locker tops! Slipped into our desks right before the bell!", "사물함 위쪽 아래로 몸 숙이고 전진! 종 치기 직전에 우리 자리에 쏙 착석했다!",
                  '구동사 "keep down"은 몸을 낮추거나 소리를 낮추어 "들키지 않다"라는 뜻으로 쓰입니다.',
                  "자세 낮추고 가자! (은폐 및 잠행 필수 구동사)", "Jump on locker roof.", "사물함 지붕 위로 뛰라는 오답이에요.", "Sing opera loud.", "오페라 부르라는 엉뚱한 오답이에요."),
        make_turn(9, "Chloe", "🎨", "The hall monitor finally turned the corner and the coast is clear! I forgot my gym locker padlock key inside locker 104!", "복도 지도 선생님 코너 도셨고 사방 안전해! 나 104번 사물함 안에 체육관 자물쇠 열쇠 두고 왔단 말이야!",
                  '"사물함 얼른 열어봐!"라고 구동사 open up을 써서 열어보세요!', "Open it up!",
                  "Twirled the dial and popped the door! Grabbed the neon sneakers! Safe from the tardy sweep!", "다이얼 돌려서 문 툭 열었다! 네온 운동화 낚아챘어! 지각 단속 완벽 회피 성공!",
                  '구동사 "open up"은 문, 상자, 사물함 등을 "활짝 열다"라는 뜻으로 일상에서 가장 흔하게 쓰이는 기본 구동사입니다.',
                  "사물함 얼른 열어! (개방 필수 구동사)", "Kick the locker door off.", "문짝 발로 차서 뜯으라는 오답이에요.", "Swallow locker padlock.", "자물쇠 삼키라는 엉뚱한 오답이에요."),
        make_turn(10, "Chloe", "🎨", "The tardy bell stopped ringing and the teacher turned to the whiteboard! We made it into our seats with five seconds to spare!", "지각 종 멈췄고 선생님이 칠판으로 돌아서셨어! 우리 5초 남기고 자리에 무사히 착석 완료!",
                  "\"진짜 아슬아슬했다!\"라고 가슴을 쓸어내리며 속삭여보세요!", "Talk about close!",
                  "Phew! Sliding into our desks ninja style! Now let's try not to crack up remembering that cat recorder video!", "휴! 닌자처럼 자리로 미끄러져 들어왔다! 이제 수업 중에 그 고양이 춤 영상 생각나서 웃참 실패하지 않게 조심하자!",
                  "관용구 \"Talk about [adjective]!\"는 \"정말이지 ~했네! 진짜로 ~하구먼!\"이라며 상황의 극단성(아슬아슬함, 대단함)을 강조할 때 쓰는 구어체입니다.",
                  "진짜 간발의 차였어! (위기 모면 안도 표현)", "We were caught red-handed.", "현행범으로 잡혔다는 오답이에요.", "Scream during math lecture.", "수학 시간에 소리 지르라는 오답이에요.")
    ]),

    make_ep("t4_e5", "tier4", "틱톡 댄스 바이럴 영상", "📍 Episode 5/10: TikTok Dance Viral Take", "dance", [
        make_turn(1, "Jordan", "🏀", "Camera tripod is set up by the brick archway! Ready for take three?", "벽돌 아치 옆에 카메라 삼각대 설치 끝! 3번째 촬영 갈 준비 됐어?",
                  '"완전 무대 찢을 준비 끝났지!"라고 자신감을 장전하세요!', "Ready to kill this beat!",
                  "Music cue in three, two, one... Kick-spin on the bass drop!", "음악 큐 사인 셋, 둘, 하나... 베이스 떨어질 때 킥 스핀 회전!",
                  '무대나 카메라 앞에서 완벽한 퍼포먼스를 선보이겠다고 결의를 다지는 강렬한 슬랭입니다.',
                  "완전 찢어버릴 준비 됐지! (퍼포먼스 자신감)", "Beat is beating me.", "비트가 날 때린다는 직역 오역이에요.", "Turn off camera.", "카메라 끄라는 찬물이에요."),
        make_turn(2, "Jordan", "🏀", "That synchronized jump at the chorus was razor sharp! Perfect unison!", "후렴구에서 둘이 동시에 점프한 타이밍 칼각이었어! 완벽한 칼군무!",
                  '"완전 싱크 100% 칼군무였다!"라고 만족스러워해보세요!', "Perfect sync!",
                  "Look at the playback! Our shadows even line up identical against the wall!", "다시보기 모니터링 좀 봐봐! 벽에 비친 우리 그림자까지 데칼코마니처럼 일치해!",
                  '동작이나 안무의 타이밍이 1초의 오차도 없이 맞아떨어졌을 때 극찬하는 표현입니다.',
                  "완전 100% 칼군무였어! (완벽한 싱크 극찬)", "Very out of sync.", "완전 안 맞았다는 반대말이에요.", "I hate dancing.", "춤 싫다는 딴소리예요."),
        make_turn(3, "Jordan", "🏀", "Do we need one more safety take, or is this the master cut?", "혹시 안전빵으로 한 번 더 찍을까, 아니면 이게 마스터 컷일까?",
                  '"원테이크로 끝내자, 이게 바로 찐이야!"라고 확신을 가지세요!', "That's the one.",
                  "Done! Exporting in 4K resolution with the trending audio tag!", "촬영 끝! 트렌딩 공식 오디오 태그 달고 4K 화질로 내보내는 중!",
                  '수많은 시도 끝에 완벽한 결과물을 골라내며 "이거야, 이게 진짜야"라고 낙점하는 표현입니다.',
                  "이거야! 바로 이거다! (완벽한 마스터 컷 낙점)", "Delete everything.", "다 지우라는 자폭이에요.", "I want to record 100 times.", "100번 더 찍자는 무리수예요."),
        make_turn(4, "Jordan", "🏀", "I'm adding the chromatic zoom transition on the beat drop right now!", "베이스 비트 떨어지는 구간에 색수차 줌 화면전환 효과 넣는 중이야!",
                  '"편집 감각 진짜 미쳤다!"라고 기술력을 칭찬해보세요!', "The edit is insane!",
                  "Smooth blur transitions make the choreo look twice as fast and slick!", "부드러운 블러 전환 넣으니까 안무가 두 배는 더 빠르고 세련돼 보여!",
                  '영상이나 사진 편집 퀄리티가 전문가 뺨치게 훌륭할 때 쓰는 하이틴 찬사입니다.',
                  "편집 감각 진짜 미쳤다! (고퀄리티 편집 찬사)", "Edit is broken.", "편집 망했다는 반대말이에요.", "Computers are slow.", "느리다는 불평이에요."),
        make_turn(5, "Jordan", "🏀", "Posting to the feed with three trending dance challenge hashtags!", "트렌딩 댄스 챌린지 해시태그 3개 달아서 피드에 업로드한다!",
                  '"좋아요 떡상 가보자고!"라고 기대에 부풀어보세요!', "Let's go viral!",
                  "Notification bell already buzzing! Fifty comments in the first sixty seconds!", "알림 벨 벌써부터 징징 울려! 첫 60초 만에 댓글 50개 달렸어!",
                  '소셜 미디어에 게시물을 올리며 전 세계적 인기를 끌어보자고 외치는 만능 구호입니다.',
                  "바이럴 떡상 가보자고! (폭발적 인기 기대)", "Zero likes expected.", "좋아요 0개라는 악담이에요.", "Block all accounts.", "계정 차단하라는 엉뚱한 말이에요."),
        make_turn(6, "Jordan", "🏀", "The video is rendering on the screen! Ten seconds left on the export bar!", "화면에서 영상 렌더링 돌아간다! 내보내기 진행 바 10초 남았어!",
                  '"조금만 더 참아봐!"라고 구동사 hold on을 써서 진정시켜보세요!', "Hold on a second!",
                  "100% exported in ultra HD! The colors look so crisp against the courtyard brick wall!", "초고화질로 100% 추출 완료! 안뜰 벽돌 벽 배경 색감이 진짜 선명하다!",
                  '구동사 "hold on"은 로딩이나 준비 중에 "잠깐만 기다려"라고 차분하게 기다리게 할 때 씁니다.',
                  "잠깐만 기다려봐! (대기 필수 구동사)", "Smash the phone.", "폰 부수라는 난폭한 오답이에요.", "Unplug battery.", "배터리 뽑으라는 오답이에요."),
        make_turn(7, "Jordan", "🏀", "The caption box is blinking! What should our hook sentence be?", "캡션 글 입력창 깜빡거린다! 첫 줄 후킹 문구 뭘로 적을까?",
                  '"영상 꼭 확인해봐!"라고 구동사 check out을 써서 유도해보세요!', "Check this out!",
                  "Typed: 'Wait for the beat drop kick-spin... Check this out!' Ready to hit publish!", "'비트 드롭 킥 스핀까지 꼭 보세요... 이것 좀 봐봐!' 타이핑 완료! 발행 버튼 누를 준비 끝!",
                  '구동사 "check out"은 사람들의 시선을 사로잡고 "확인해봐!"라고 유도할 때 쓰는 최고빈도 구동사입니다.',
                  "이것 좀 확인해봐! (주목 유도 필수 구동사)", "Don't look at video.", "영상 보지 말라는 오답이에요.", "Delete the post.", "글 지우라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "The upload finished! But look at our comments, people are demanding the slow-mo tutorial!", "업로드 끝났다! 근데 댓글 좀 봐, 사람들이 슬로우 모션 튜토리얼 올려달라고 난리야!",
                  '"튜토리얼 싹 정리해서 올리자!"라고 구동사 break down을 써서 제안해보세요!', "Let's break it down!",
                  "Recording the three-step breakdown! Step one, pivot right foot! Viral creators at work!", "3단계 튜토리얼 녹화 들어간다! 1단계, 오른발 피벗 돌기! 바이럴 크리에이터 열일 모드!",
                  '구동사 "break down"은 복잡한 동작이나 내용을 알기 쉽게 "하나하나 쪼개서 설명하다"라는 뜻의 전문 구동사입니다.',
                  "하나씩 쪼개서 가르쳐주자! (단계별 설명 필수 구동사)", "Complicate the steps.", "더 복잡하게 꼬라는 오답이에요.", "Ignore all followers.", "팔로워 무시하라는 오답이에요."),
        make_turn(9, "Jordan", "🏀", "The synced kick-spin transition looks so cinematic with the courtyard sunset! All filters and captions are ready!", "안뜰 노을 배경으로 칼군무 킥스핀 전환 씬 완전 영화 같아! 필터랑 자막 준비 다 됐어!",
                  '"영상 온라인에 올려보자!"라고 구동사 put it up을 써서 게시해보세요!', "Put it up!",
                  "Tapped post! 500 likes in two minutes already! The algorithm is definitely pushing us to the For You page!", "발행 탭 쾅! 2분 만에 좋아요 500개 돌파! 알고리즘이 우리 추천 피드로 밀어주는 중이다!",
                  '구동사 "put up" 또는 post up은 소셜 미디어나 게시판에 영상/사진을 "게시하다/올리다"라는 뜻으로 매일 쓰입니다.',
                  "영상 온라인에 올려보자! (게시 및 업로드 필수 구동사)", "Delete your phone account.", "계정 삭제하라는 오답이에요.", "Smash smartphone camera.", "카메라 부수라는 오답이에요."),
        make_turn(10, "Jordan", "🏀", "The dance challenge video just crossed 10,000 likes on the app! Even the varsity cheer captain left a fire comment!", "댄스 챌린지 영상 1만 좋아요 돌파했어! 심지어 치어리더 주장도 불꽃 댓글 달았어!",
                  "\"우리 완전 대박 터졌어!\"라고 흥분을 감추지 못하고 외쳐보세요!", "We blew up!",
                  "Overnight internet sensation! High five! Tomorrow during free period we film part two!", "하룻밤 만에 인터넷 스타 등극! 하이파이브! 내일 공강 시간에 2탄 찍는 거다!",
                  "속어 \"blow up\"은 소셜 미디어나 대중 사이에서 \"조회수/인기가 폭발적으로 터지다\"라는 뜻으로 Z세대가 가장 열광하는 표현입니다.",
                  "우리 완전 떡상 폭발했어! (바이럴 대박 환호)", "The bomb exploded.", "폭탄 터졌다는 엉뚱한 직역이에요.", "Delete the video now.", "영상 지우라는 오답이에요.")
    ]),

    make_ep("t4_e6", "tier4", "기말고사 끝 해방", "📍 Episode 6/10: Finals Freedom Countdown", "classroom", [
        make_turn(1, "Chloe", "🎨", "The proctor just announced: Five minutes remaining on the Algebra final!", "감독관 선생님이 발표하셨어: 대수학 기말고사 종료 5분 전입니다!",
                  '"우리 다 끝나간다, 조금만 힘내자!"라고 서로를 격려해보세요!', "Almost at the finish line!",
                  "Pen on paper for the last quadratic equation... Solved with two minutes to spare!", "마지막 2차 방정식 펜으로 마무리... 2분 남기고 완벽하게 풀었어!",
                  '길고 험난했던 시험이나 프로젝트의 끝이 눈앞에 보일 때 외치는 결승선 비유 표현입니다.',
                  "결승선이 코앞이야! (마무리 스퍼트 격려)", "Finish line is broken.", "결승선 부서졌다는 엉뚱한 말이에요.", "I hate algebra.", "수학 싫다는 투덜거림이에요."),
        make_turn(2, "Chloe", "🎨", "Pencils down! Pass your exam packets forward to the front aisle!", "모두 연필 내려놓으세요! 시험지 답안지 복도 앞쪽으로 제출하세요!",
                  '"드디어 끝났다! 해방이다!"라고 두 팔을 번쩍 들어보세요!', "Free at last!",
                  "We survived high school sophomore finals! No more formulas for three whole months!", "우리 고등학교 2학년 기말고사에서 살아남았다! 석 달 동안 공식 암기여 안녕!",
                  '극심한 구속이나 시험 압박에서 마침내 벗어나 자유를 쟁취했을 때 역사적으로도 유명한 해방의 찬사입니다.',
                  "드디어 해방이다! (자유의 환호)", "I am imprisoned.", "수감되었다는 반대말이에요.", "Give me more tests.", "시험 더 달라는 망언이에요."),
        make_turn(3, "Chloe", "🎨", "I can literally feel the physical weight lifting off my shoulders!", "어깨를 짓누르던 돌덩이가 실제로 쑥 빠져나가는 기분이야!",
                  '"완전 무거운 짐 덜었다, 후련해!"라고 가슴을 펴보세요!', "Huge weight off my chest!",
                  "Right? My brain feels lighter than helium! Where to first to celebrate?", "그치? 내 뇌가 헬륨가스보다 더 가벼워진 것 같아! 자축하러 어디부터 갈까?",
                  '큰 부담이나 스트레스가 사라져 후련하고 홀가분할 때 쓰는 대표적인 신체적 관용구입니다.',
                  "완전 무거운 짐 덜었어! 후련해! (홀가분한 해방감)", "My chest is heavy.", "가슴 답답하다는 반대말이에요.", "Buy heavy rocks.", "돌 사라는 엉뚱한 말이에요."),
        make_turn(4, "Chloe", "🎨", "Let's throw our scratch paper into the recycling bin with a fadeaway jump shot!", "이면지 연습장 페이더웨이 슛으로 재활용 쓰레기통에 골인시키자!",
                  '"슛 꽂아버려!"라고 신나게 종이를 던져보세요!', "Kobe, nothing but net!",
                  "Swish into the blue bin! The semester is officially and permanently over!", "파란 통으로 클린 골인! 이번 학기는 공식적으로 영원히 영결식 끝났다!",
                  '종이나 쓰레기를 던져 넣을 때 농구 레전드 코비 브라이언트의 이름을 외치며 기분 좋게 슛하는 문화입니다.',
                  "코비! 그물만 철렁! (유쾌한 세리머니)", "Miss the bin.", "빗나가라는 오답이에요.", "Save scratch paper forever.", "이면지 평생 간직하라는 오답이에요."),
        make_turn(5, "Chloe", "🎨", "Summer break starts the second that three-o'clock bell rings!", "3시 종 땡 치는 그 찰나의 순간부터 공식 여름방학 개막이야!",
                  '"제대로 인생 즐겨보자고!"라고 환호성을 질러보세요!', "Let the good times roll!",
                  "Beach road trips, midnight stargazing, and sleeping in until noon every single day!", "해변 로드트립에 한밤중 별 보기, 그리고 매일 정오까지 늦잠 자기!",
                  '축제나 휴가가 시작될 때 "즐거운 시간을 마음껏 누리자, 신나게 놀아보자"며 샴페인을 터뜨리는 표현입니다.',
                  "제대로 신나게 놀아보자! (축제와 방학 개막)", "Roll down the cliff.", "절벽에서 구르라는 무서운 오역이에요.", "Summer is boring.", "방학 지루하다는 거짓말이에요."),
        make_turn(6, "Chloe", "🎨", "Look at all these scratch sheets and loose-leaf notes all over the desk!", "책상 위에 흩어진 이면지 연습장이랑 필기 노트 좀 봐!",
                  '"깨끗이 다 치우자!"라고 구동사 clean out을 써서 말해보세요!', "Clean it out!",
                  "Scraped all old sheets into the recycling bin! Desk is completely empty and ready for summer!", "오래된 종이 재활용 통에 다 쓸어 담았어! 책상 텅 비우고 방학 맞이 준비 완료!",
                  '구동사 "clean out"은 서랍이나 사물함, 책상을 "완전히 비우다/치우다"라는 뜻의 필수 정리 구동사입니다.',
                  "깨끗이 싹 비우자! (완전 청소 필수 구동사)", "Burn the desk.", "책상 태우라는 범죄예요.", "Leave trash on floor.", "바닥에 쓰레기 버리라는 오답이에요."),
        make_turn(7, "Chloe", "🎨", "The proctor is holding the final exam receipt envelope by the front door!", "감독관 선생님이 앞문에서 기말고사 수령 확인 봉투를 들고 계셔!",
                  '"시험지 제출하러 가자!"라고 구동사 hand in을 써서 말해보세요!', "Let's hand it in!",
                  "Answer sheets sealed inside the envelope! Official high school sophomore finals COMPLETE!", "답안지 봉투 안에 쏙 봉인 완료! 고등학교 2학년 기말고사 공식 종료!",
                  '구동사 "hand in"은 과제나 시험지를 권한이 있는 사람에게 "직접 건네다/제출하다"라는 뜻의 필수 학교 구동사입니다.',
                  "시험지 제출하자! (서류 제출 필수 구동사)", "Tear into confetti.", "꽃가루로 찢으라는 오답이에요.", "Hide under rug.", "카펫 밑에 숨기라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "The classroom door is wide open! What's the plan for the next twelve weeks?", "교실 문 활짝 열렸다! 앞으로 12주 방학 동안 계획이 뭐야?",
                  '"오늘부터 인생 화끈하게 즐기자!"라고 구동사 live it up을 써서 외쳐보세요!', "Let's live it up!",
                  "Bonfires on the sand dunes, sleeping until noon, zero homework! Summer vacation is HERE!", "모래언덕 모닥불에 정오까지 늦잠, 숙제 제로! 여름방학이 드디어 왔다!",
                  '구동사 "live it up"은 인생이나 휴가를 "화끈하게 즐기다/신나게 살다"라는 뜻으로 방학 때 쓰는 최고의 구동사입니다.',
                  "화끈하게 인생을 즐기자! (만끽과 향유 필수 구동사)", "Study algebra 24 hours.", "24시간 수학 공부하라는 오답이에요.", "Lock yourself in cellar.", "지하실에 갇히라는 오답이에요."),
        make_turn(9, "Chloe", "🎨", "All pencils are down, test packets are sealed in envelopes, and summer vacation has officially begun! 90 days of pure freedom!", "연필 다 내려놨고, 시험지 봉투 봉인 끝났고, 여름방학 공식 개막이야! 90일간의 온전한 자유다!",
                  '"신나게 즐기자!"라고 구동사 live it up을 써서 환호해보세요!', "Let's live it up!",
                  "Beach trips, late night movies, and zero algebra homework for three whole months! Summer mode ACTIVATED!", "해변 드라이브에 심야 영화, 3달 내내 대수학 숙제 제로! 여름 모드 공식 가동!",
                  '구동사 "live it up"(인생을 맘껏 즐기다/화끈하게 놀다)은 방학이나 휴일, 축제를 맞이할 때 청소년들이 가장 설레며 외치는 표현입니다.',
                  "신나게 즐기자! (만끽과 향유 필수 구동사)", "Lock yourself in library.", "도서관에 스스로 갇히라는 오답이에요.", "Study for 100 hours straight.", "100시간 공부하라는 오답이에요."),
        make_turn(10, "Chloe", "🎨", "The final dismissal bell echoed across the campus! Students are throwing notebook pages into the air outside the glass doors!", "마지막 하교 종소리가 캠퍼스 전체에 울려 퍼졌어! 유리문 밖에서 애들이 공책 종이 하늘로 던지고 있어!",
                  "\"우리 진짜 자유다!\"라고 양팔을 벌려 환호해보세요!", "We're finally free!",
                  "No more study guides, no more alarms, no more pop quizzes! Hello 90 days of sunshine and beach sand!", "공부 요약본 안녕, 알람 시계 안녕, 쪽지시험 안녕! 90일간의 눈부신 햇살과 해변 모래사장아 반갑다!",
                  "\"We're finally free!\"(드디어 자유다!/마침내 해방이다!)는 길고 고된 학기나 시험이 끝나고 진정한 방학을 만끽할 때 누구나 외치는 구호입니다.",
                  "우리 드디어 자유야! (시험 끝 해방의 환호)", "Give us ten more finals.", "시험 10개 더 달라는 오답이에요.", "Cry alone in closet.", "벽장에서 혼자 울라는 오답이에요.")
    ]),

    make_ep("t4_e7", "tier4", "관중석 비밀 고민 상담", "📍 Episode 7/10: Bleacher Deep Talk", "football", [
        make_turn(1, "Jordan", "🏀", "Everyone went home... The stadium lights are humming. You looked down all day.", "애들 다 집에 가고... 경기장 라이트만 웅웅거리네. 너 오늘 하루 종일 기운 없어 보이더라.",
                  '"나 요즘 생각이 좀 많아."라고 차분하게 털어놓으세요!', "Just in my head lately.",
                  "Hey, you know you can tell me anything, right? Real friends listen.", "야, 나한테는 뭐든 다 털어놔도 되는 거 알지? 찐친은 들어주는 법이야.",
                  '머릿속에 고민이나 생각이 가득 차서 혼자 끙끙 앓고 있을 때 털어놓는 솔직한 표현입니다.',
                  "나 요즘 생각이 좀 많아. (차분한 고민 토로)", "I am out of my head.", "미쳤다는 과격한 오역이에요.", "Stadium is empty.", "경기장 비었다는 딴소리예요."),
        make_turn(2, "Jordan", "🏀", "Is it about college applications, or family pressure, or track team cuts?", "대학 입시 원서 문제야, 아니면 가족 부담감이야, 육상부 탈락 때문이야?",
                  '"솔직히 다 겹쳐서 번아웃 왔어."라고 속내를 열어보세요!', "It's honestly a lot at once.",
                  "Man, that's heavy. Anyone would feel overwhelmed carrying all that alone.", "와 진짜 무겁겠다. 그 모든 걸 혼자 짊어지면 누구라도 벅차지.",
                  '여러 악재나 중압감이 한꺼번에 몰아닥쳐 지치고 버거울 때 공감을 이끌어내는 고백입니다.',
                  "한꺼번에 다 몰려와서 벅차. (솔직한 중압감 고백)", "It is very light.", "엄청 가볍다는 반대말이에요.", "I like homework.", "과제 좋다는 거짓말이에요."),
        make_turn(3, "Jordan", "🏀", "Remember when I broke my wrist last season and almost quit basketball?", "나 지난 시즌에 손목 부러져서 농구 거의 때려치울 뻔했던 거 기억나?",
                  '"네가 내 곁을 지켜줬잖아."라고 고마웠던 기억을 꺼내세요!', "You were there for me.",
                  "And you'll bounce back twice as strong just like I did! I'm in your corner.", "너도 나처럼 두 배는 더 강하게 일어설 거야! 내가 무조건 네 편에서 응원할게.",
                  '어려운 시절 곁에서 큰 힘이 되어주었던 친구의 존재를 인정하고 감사할 때 쓰는 깊이 있는 표현입니다.',
                  "네가 내 곁에 있어 줬잖아. (고마운 존재감 회상)", "You were absent.", "너 결석했다는 차가운 말이에요.", "My wrist hurts.", "손목 아프다는 엉뚱한 말이에요."),
        make_turn(4, "Jordan", "🏀", "Take it one single day at a time. You don't have to figure out your whole life today.", "하루에 딱 하루씩만 살아. 오늘 당장 네 인생 전체를 다 결정할 필요 없어.",
                  '"진짜 네 말이 맞아, 고마워."라고 깊은 위로를 받으세요!', "I needed to hear that.",
                  "Anytime, always! Let's walk the track once in the cool night breeze.", "언제든, 당연하지! 시원한 밤바람 맞으면서 트랙 한 바퀴 천천히 돌자.",
                  '마음이 힘들 때 꼭 필요했던 따뜻한 조언을 듣고 깊은 위안과 감사를 전하는 성숙한 문장입니다.',
                  "진짜 그 말이 필요했어, 고마워. (깊은 위로 수용)", "I don't need words.", "말 필요 없다는 쌀쌀맞은 말이에요.", "The night is dark.", "밤 어둡다는 딴소리예요."),
        make_turn(5, "Jordan", "🏀", "Look up at the stadium floodlights cutting through the mist... We got this.", "안개 뚫고 쏟아지는 경기장 조명탑 불빛 봐봐... 우린 다 이겨낼 수 있어.",
                  '"우리 꼭 이겨낼 거야."라고 다짐을 굳혀보세요!', "We'll get through it.",
                  "Unbreakable bond! Tomorrow at sunrise, we train together at the gym!", "절대 안 깨지는 의리! 내일 해 뜨면 체육관에서 같이 땀 흘리는 거다!",
                  '어떤 시련이나 고난도 서로 의지하며 반드시 극복해 낼 수 있다고 확신할 때 쓰는 표현입니다.',
                  "우리 꼭 이겨낼 거야. (끈끈한 극복 다짐)", "We will fail.", "우린 실패할 거라는 패배주의예요.", "Turn off lights.", "불 끄라는 김빠지는 소리예요."),
        make_turn(6, "Jordan", "🏀", "Talking it all out on this bleacher bench made my chest feel ten pounds lighter!", "스탠드 벤치에서 다 털어놓으니까 가슴에 얹힌 10파운드 돌덩이가 싹 내려간 것 같아!",
                  '"다 털어놓고 말하길 잘했어!"라고 구동사 talk it out을 써서 말해보세요!', "Glad we talked it out!",
                  "Anytime, man! A problem shared is a problem cut in half! That's what brothers are for!", "언제든 친구야! 고민을 나누면 반으로 줄어드는 법이지! 그게 바로 형제지!",
                  '구동사 "talk out"은 묵혀둔 갈등이나 고민을 "대화로 속 시원히 풀다/해결하다"라는 뜻의 필수 심리 구동사입니다.',
                  "대화로 다 풀어서 다행이야! (소통과 해소 필수 구동사)", "Never speak again.", "다신 말하지 말자는 절교예요.", "Swallow your tears.", "눈물 삼키라는 가혹한 말이에요."),
        make_turn(7, "Jordan", "🏀", "Tomorrow morning at 6 AM sharp, meet me by the stadium stairs! Let's run bleachers!", "내일 아침 6시 정각에 경기장 계단 앞으로 나와! 계단 달리기 같이 뛰자!",
                  '"나만 믿어!"라고 구동사 count on을 써서 든든하게 화답해보세요!', "Count on me!",
                  "Set two alarms! We're gonna run those bleachers until sunrise! You're a true brother!", "알람 두 개 맞춰놔! 일출 볼 때까지 스탠드 계단 전력 질주하는 거다! 넌 진짜 의리 넘치는 형제야!",
                  '구동사 "count on [someone]"은 상대방을 "믿다/기대하다"라는 뜻으로 깊은 신뢰를 주고받을 때 쓰는 필수 구동사입니다.',
                  "나만 믿어! (신뢰와 의리의 필수 구동사)", "Count to ten.", "10까지 세라는 오답이에요.", "Never wake up.", "영원히 일어나지 말라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "Whatever crazy curveballs senior year throws at us, we have a game plan!", "고3이 어떤 험난한 변화구를 던지더라도, 우리에겐 확실한 작전이 있어!",
                  '"하나씩 차근차근 해결해가자!"라고 구동사 figure out을 써서 말해보세요!', "We can figure it out!",
                  "One challenge at a time! We're gonna graduate with honors and memories! High five!", "한 번에 하나씩 격파하기! 우리 우등 졸업에 최고의 추억까지 다 챙길 거야! 하이파이브!",
                  '구동사 "figure out"은 어려운 난관이나 해법을 "머리 맞대고 찾아내다/해결하다"라는 뜻의 대표적 구동사입니다.',
                  "우리 차근차근 해결할 수 있어! (난관 극복 필수 구동사)", "Give up completely.", "완전 포기하라는 패배자 오답이에요.", "Run away to desert.", "사막으로 도망치라는 오답이에요."),
        make_turn(9, "Jordan", "🏀", "Talking it out here on the quiet bleachers really helped clear my mind! I don't feel so alone anymore.", "조용한 스탠드에서 다 털어놓으니까 머릿속이 진짜 맑아졌어! 이제 더 이상 혼자가 아닌 것 같아.",
                  '"언제든 나한테 기대도 돼!"라고 구동사 count on me를 써서 든든한 버팀목이 되어주세요!', "You can count on me!",
                  "I appreciate that more than you know! Best friends through everything, no cap! High five!", "진짜 말로 다 못 할 만큼 고마워! 어떤 시련이 와도 우린 찐친이야, 레알! 하이파이브!",
                  '구동사 "count on ~"은 누군가를 "믿다/의지하다"라는 뜻으로 "You can count on me!"는 신뢰를 약속하는 가장 따뜻한 구어체입니다.',
                  "언제든 나한테 기대도 돼! (신뢰와 지지 필수 구동사)", "Betray your secrets immediately.", "비밀 배신하라는 악행이에요.", "Tell everyone your private drama.", "소문내라는 나쁜 말이에요."),
        make_turn(10, "Jordan", "🏀", "The stadium floodlights clicked off one by one, leaving only the stars above the empty bleachers! We've got each other's backs.", "경기장 조명탑 불이 하나씩 꺼지고 텅 빈 관중석 위로 별들만 남았어! 우린 서로의 든든한 지원군이야.",
                  "\"우린 최고의 팀이야.\"라고 진심 어린 우정을 확인해보세요!", "Best team ever.",
                  "Brothers for life! Sunrise stairs workout tomorrow morning at six! Go get some rest, brother!", "평생 가는 형제지! 내일 아침 6시에 일출 보며 계단 달리기 뛰자! 얼른 들어가서 푹 쉬어!",
                  "\"Best team ever!\"는 가장 힘든 순간을 함께 나누고 이겨낸 동료나 친구에게 건네는 가장 끈끈하고 묵직한 찬사입니다.",
                  "우리가 최고의 팀이야. (진한 우정과 신뢰 확인)", "I will abandon you.", "버리겠다는 배신 오답이에요.", "Never speak again.", "다신 말하지 말자는 오답이에요.")
    ]),

    make_ep("t4_e8", "tier4", "콘서트 티켓팅 성공", "📍 Episode 8/10: Front Row Ticket Drop", "mall", [
        make_turn(1, "Chloe", "🎨", "Ten seconds on the ticket queue! Refresh button is turning blue!", "티켓팅 대기열 10초 카운트다운! 새로고침 버튼 파란색으로 바뀌고 있어!",
                  '"심장 터질 것 같아, 로딩 돌아간다!"라고 발을 동동 굴러보세요!', "Heart is pounding!",
                  "It loaded! Section A Row 1 floor seats are flashing in green!", "새로고침 됐다! 플로어 A구역 1열 좌석이 초록색으로 깜빡거려!",
                  '극도의 긴장과 설렘으로 심장이 쿵쾅거릴 때 직관적으로 내뱉는 긴박한 표현입니다.',
                  "심장 터질 것 같아! (극도의 긴장감)", "Heart is stopped.", "심장 멎었다는 사망 선고예요.", "Tickets are useless.", "티켓 쓸모없다는 딴소리예요."),
        make_turn(2, "Chloe", "🎨", "Click complete purchase! Payment approved! ORDER CONFIRMED!", "결제 완료 클릭! 승인 떨어졌다! 예약 확정!",
                  '"가보자고! 나이스! 소리 질러!"라고 포효해보세요!', "Let's gooo!",
                  "WE GOT FRONT ROW PIT TICKETS! WE'RE GONNA BE THREE FEET FROM THE STAGE!", "우리 스탠딩 맨 앞줄 잡았어! 무대에서 딱 1미터 코앞이야!",
                  '승리나 대박 성공의 순간에 "가보자고! 나이스!" 하며 길게 늘여 지르는 10대들의 대표 환호성입니다.',
                  "가보자고! 나이스! (승리의 포효)", "Walk away slowly.", "천천히 걸어가라는 오역이에요.", "I want a refund.", "환불해달라는 엉뚱한 말이에요."),
        make_turn(3, "Chloe", "🎨", "I'm looking at the digital barcode on my screen right now in disbelief!", "내 폰 화면에 뜬 디지털 바코드 보면서도 아직 안 믿겨!",
                  '"이거 꿈 아니지? 진짜 실화 맞지?"라고 뺨을 꼬집어보세요!', "Is this real life?",
                  "Completely real! Not a glitch, not a drill, our names are printed on it!", "완전 진짜 실화! 오류도 아니고 훈련도 아니고 우리 이름 딱 박혔어!",
                  '믿기지 않는 행운을 마주했을 때 멍하니 감격하며 묻는 관용적 질문입니다.',
                  "이거 진짜 실화 맞지? (꿈같은 행운 확인)", "Life is a simulation.", "시뮬레이션이라는 음모론이에요.", "Go back to sleep.", "다시 자라는 엉뚱한 말이에요."),
        make_turn(4, "Chloe", "🎨", "My fingers won't stop twitching over the keypad haha!", "키패드 위에서 내 손가락이 떨려서 멈추질 않아 ㅋㅋㅋ!",
                  '"나 지금 온몸이 떨려!"라고 벅찬 흥분을 고백해보세요!', "My hands are shaking!",
                  "Same! My adrenaline is spiking through the roof of this coffee shop!", "나도 그래! 이 카페 천장 뚫을 정도로 아드레날린 폭발하고 있어!",
                  '감격이나 충격으로 흥분이 가라앉지 않을 때 신체적 떨림을 전하는 자연스러운 표현입니다.',
                  "나 지금 손 떨려! (벅찬 흥분 고백)", "Stop shaking hands.", "악수 멈추라는 오역이에요.", "Drink hot water.", "뜨거운 물 마시라는 딴소리예요."),
        make_turn(5, "Chloe", "🎨", "We have to memorize every single bridge lyric for the acoustic encore!", "어쿠스틱 앵콜 곡 브릿지 파트 가사 한 글자도 안 틀리고 다 외워 가야 해!",
                  '"오늘 밤 목 쉴 때까지 떼창각이다!"라고 결의를 다져보세요!', "Lost our voices tonight!",
                  "Singing every word at the top of our lungs until our vocal cords give out!", "목청 다 터질 때까지 목 터져라 전곡 떼창하는 거야!",
                  '콘서트나 페스티벌에서 목이 쉴 때까지 떼창하고 열광하겠다고 선언할 때 쓰는 표현입니다.',
                  "목 쉴 때까지 떼창각! (열광의 떼창 선언)", "Be completely silent.", "완전 침묵하라는 도서관 모드예요.", "I don't know the songs.", "노래 모른다는 고백이에요."),
        make_turn(6, "Chloe", "🎨", "Friday night at the arena with our favorite band under the strobe lights!", "금요일 밤 스트로브 조명 아래서 최애 밴드와 함께하는 경기장 콘서트!",
                  '"우리 인생 최고의 밤이 될 거야!"라고 축배를 들어보세요!', "Best night of our lives!",
                  "Countdown starts now! Best concert squad ever assembled!", "카운트다운 지금 시작이다! 역사상 최고의 콘서트 원정대 결성!",
                  '인생에 길이 남을 황홀한 순간을 맞이하며 건네는 극상의 찬사입니다.',
                  "우리 인생 최고의 밤이야! (황홀한 찬사)", "Worst night ever.", "최악의 밤이라는 악담이에요.", "Stay home forever.", "집에만 박혀있으라는 저주예요."),
        make_turn(7, "Chloe", "🎨", "The concert arena parking gets backed up for three miles on tour nights!", "콘서트 날 경기장 주차장 5킬로씩 밀려서 완전 꽉 막힌대!",
                  '"그날 일찍 출발하자!"라고 구동사 head out을 써서 작전을 세우세요!', "Let's head out early!",
                  "Smart move! We beat the traffic, grab merchandise shirts first, and claim the barricade!", "똑똑해! 차 막히는 거 피해서 굿즈 티셔츠 먼저 사고 스탠딩 펜스 바로 잡는 거야!",
                  '구동사 "head out"은 어딘가로 길을 나서거나 "출발하다"라는 의미로 원어민들이 약속을 잡을 때 매일 쓰는 표현입니다.',
                  "일찍 출발하자! (출발 계획 필수 구동사)", "Arrive midnight.", "자정에 도착하라는 헛소리예요.", "Cancel the tickets.", "티켓 취소하라는 망언이에요."),
        make_turn(8, "Chloe", "🎨", "Our alarms are set for 3 PM on concert Friday! What about the digital tickets on my phone?", "콘서트 금요일 3시 알람 맞춰뒀어! 내 폰에 든 디지털 티켓은 어떻게 해둘까?",
                  '"사본 백업해둬!"라고 구동사 back up을 써서 안전을 챙기세요!', "Back them up!",
                  "Screenshots saved and barcodes printed on paper just in case! We are 100% prepared!", "스크린샷 캡처해두고 만약을 대비해 바코드 종이 출력까지 완료! 우리 100% 준비 끝났다!",
                  '구동사 "back up"은 데이터나 티켓을 안전하게 "백업해 두다/사본을 만들어두다"라는 뜻의 필수 IT 및 생활 구동사입니다.',
                  "사본 백업해둬! (데이터 보관 필수 구동사)", "Delete the barcodes.", "바코드 삭제하라는 오답이에요.", "Throw phone away.", "폰 버리라는 오답이에요."),
        make_turn(9, "Chloe", "🎨", "The two general admission floor pit tickets are sitting right in my digital Apple Wallet! Screen-shotted the barcodes just in case!", "스탠딩 플로어 티켓 두 장 내 애플 지갑에 딱 모셔뒀어! 만약을 대비해 바코드 캡처까지 완료!",
                  '"티켓 잘 챙겨둬!"라고 구동사 hold on to를 써서 당부해보세요!', "Hold on to them!",
                  "Saved to cloud and pinned to favorites! Friday night stadium lights, front row center, here we come!", "클라우드 저장에 즐겨찾기 핀 고정 완료! 금요일 밤 경기장 조명탑 맨 앞줄 한가운데, 우리가 간다!",
                  '구동사 "hold on to ~"는 가치 있는 티켓이나 물건을 "잃어버리지 않게 잘 간직하다"라는 뜻으로 매일 쓰입니다.',
                  "티켓 잘 챙겨둬! (소중한 보관 필수 구동사)", "Post barcodes publicly online.", "바코드 온라인 유출하라는 오답이에요.", "Delete wallet app.", "지갑 앱 삭제하라는 오답이에요."),
        make_turn(10, "Chloe", "🎨", "The digital tickets are locked in Apple Wallet, emergency paper backups printed, and outfits coordinated! Friday night arena concert ready!", "디지털 티켓 애플 지갑에 락 걸어뒀고 비상용 종이 출력 완료에 콘서트 룩 코디까지 끝! 금요일 밤 아레나 콘서트 준비 완료!",
                  "\"진짜 완전 기대돼!\"라고 설레는 마음을 표현해보세요!", "Beyond excited!",
                  "Front row barricade center, screaming the lyrics to every single anthem under the lasers! It's gonna be historical!", "펜스 맨 앞줄 정중앙에서 레이저 맞으며 모든 명곡 전곡 떼창하기! 역사에 남을 밤이 될 거야!",
                  "\"Beyond excited!\"(단순히 신나는 수준을 넘어섰어!/완전 설레서 미치겠어!)는 기대감의 극치를 표현할 때 원어민들이 즐겨 쓰는 표현입니다.",
                  "완전 기대돼서 미칠 것 같아! (설렘 극치 필수 표현)", "I dread going there.", "가기 두렵다는 김빠지는 오답이에요.", "Burn the tickets.", "티켓 불태우자는 오답이에요.")
    ]),

    make_ep("t4_e9", "tier4", "빈티지 패션 칭찬", "📍 Episode 9/10: Flea Market Vintage Glow-Up", "teenLocker", [
        make_turn(1, "Chloe", "🎨", "I thrifted this oversized 90s denim jacket over the weekend. How is it?", "주말에 구제 벼룩시장에서 90년대 오버핏 청자켓 건졌는데, 어때 보여?",
                  '"완전 찰떡이야, 찢었어!"라고 스타일을 극찬해보세요!', "You ate that up!",
                  "Thank you! I was worried it looked too baggy around the cuffs!", "고마워! 소매 쪽이 너무 벙벙해 보일까 봐 살짝 걱정했거든!",
                  '"You ate that up" (또는 "Left no crumbs")은 스타일이나 퍼포먼스를 "완벽하게 찢었다, 소화했다"는 최신 Z세대 찬사입니다.',
                  "완전 찰떡이야, 찢었어! (스타일 완벽 소화 극찬)", "Do not eat denim.", "청바지 먹지 말라는 직역 오역이에요.", "Clothes are expensive.", "옷 비싸다는 딴소리예요."),
        make_turn(2, "Chloe", "🎨", "It was only twelve dollars in the vintage bin behind the downtown diner!", "시내 다이너 식당 뒤편 빈티지 바구니에서 단돈 12달러 주고 건졌어!",
                  '"완전 거저 얻었네, 꿀득템이다!"라고 감탄해보세요!', "What a steal!",
                  "Right? The brass buttons and washed denim wash are totally authentic!", "그치? 황동 단추랑 워싱 빠진 청 데님 느낌이 진짜 오리지널 빈티지잖아!",
                  '터무니없이 싼 가격에 엄청난 득템을 했을 때 외치는 대표적인 관용구입니다.',
                  "완전 거저네, 꿀득템이다! (횡재 감탄)", "You committed a crime.", "범죄 저질렀다는 오역이에요.", "I never go shopping.", "쇼핑 안 한다는 딴청이에요."),
        make_turn(3, "Chloe", "🎨", "The distressed collar and the cropped hem sit right at the hip line!", "목 부분 빈티지 헤짐이랑 크롭 기장이 딱 골반 라인에 걸쳐져!",
                  '"부스러기 하나 없이 완벽 소화했어!"라고 감탄을 더해보세요!', "Left no crumbs!",
                  "Haha, you know the exact fashion vocabulary to make my day!", "하하 네가 패션 용어 딱딱 집어서 칭찬해주니까 오늘 기분 째진다!",
                  '"Left no crumbs"는 "남긴 부스러기조차 없이 완벽하게 먹어치웠다/소화했다"는 최고의 트렌드 표현입니다.',
                  "부스러기 없이 완벽해! (최고의 스타일 칭찬)", "Sweep the floor.", "바닥 쓸라는 엉뚱한 오역이에요.", "Eat a sandwich.", "샌드위치 먹으라는 딴소리예요."),
        make_turn(4, "Chloe", "🎨", "I paired it with high-waisted beige cargo pants and retro skate high-tops!", "하이웨이스트 베이지 카고 팬츠에 레트로 스케이트 하이탑으로 매치했어!",
                  '"완전 구제 패션 아이콘이다!"라고 패션 감각을 치켜세워주세요!', "Thrifted fashion icon.",
                  "You're making me blush! Maybe I should start a vintage fashion blog!", "나 부끄럽잖아! 진짜 빈티지 패션 블로그 하나 팔까 봐!",
                  '감각적인 스타일링을 뽐내는 친구에게 "패션 아이콘"이라 칭하며 띄워주는 세련된 표현입니다.',
                  "구제 패션의 아이콘이야! (패션 감각 극찬)", "Throw clothes away.", "옷 버리라는 악담이에요.", "I have no mirror.", "거울 없다는 엉뚱한 말이에요."),
        make_turn(5, "Chloe", "🎨", "Look at the silhouette in the full-length locker mirror!", "사물함 전신거울에 비친 전체 실루엣 좀 봐봐!",
                  '"핏이 흠잡을 데 없이 완벽해!"라고 쐐기를 박아주세요!', "The fit is immaculate.",
                  "Ten out of ten! Best twelve dollars I ever spent in my entire life!", "10점 만점에 10점! 내 평생 쓴 12달러 중에 제일 보람차다!",
                  '"immaculate"은 티끌 하나 없이 정결하고 완벽하다는 뜻으로, 옷의 핏이나 스타일링이 무결점일 때 씁니다.',
                  "핏이 무결점 완벽해! (흠잡을 데 없는 핏)", "The fit is dirty.", "더럽다는 반대말이에요.", "Buy cheaper clothes.", "더 싼 옷 사라는 잔소리예요."),
        make_turn(6, "Chloe", "🎨", "I'm definitely hitting that flea market again next Saturday morning!", "다음 주 토요일 아침에 그 벼룩시장 무조건 또 털러 갈 거야!",
                  '"이 코디에 나 완전 꽂혔어!"라고 함께 신나해보세요!', "Obsessed with this look.",
                  "You're coming with me! We're gonna find you an epic vintage bomber jacket next!", "너도 나랑 같이 가는 거다! 다음엔 네 오버핏 빈티지 항공점퍼 같이 찾아줄게!",
                  '어떤 스타일이나 아이템이 너무 매력적이어서 마음을 빼앗겼을 때 쓰는 최신 하이틴 표현입니다.',
                  "이 코디에 완전 꽂혔어! (스타일 매료)", "I hate this look.", "싫다는 반대말이에요.", "Wear uniform only.", "교복만 입으라는 꼰대 반응이에요."),
        make_turn(7, "Chloe", "🎨", "There's also a retro suede fringe jacket on the back rack! Wanna try it for yourself?", "저기 뒤쪽 행거에 레트로 스웨이드 술 재킷도 하나 있어! 너도 한번 걸쳐볼래?",
                  '"얼른 한번 입어볼게!"라고 구동사 try on을 써서 화답해보세요!', "I'll try it on!",
                  "Looking like a 70s rockstar right now! We are officially the best-dressed duo in town!", "너 지금 완전 70년대 록스타 같아! 우리 공식적으로 동네에서 옷 제일 잘 입는 듀오 인정이다!",
                  '구동사 "try on"은 옷이나 모자, 신발 등을 사기 전에 직접 "착용해 보다/입어보다"라는 쇼핑 필수 구동사입니다.',
                  "얼른 한번 입어볼게! (의류 착용 시험 필수 구동사)", "Rip the sleeves.", "소매 찢으라는 나쁜 말이에요.", "Throw it in mud.", "진흙에 던지라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "You look like an album cover star in that suede fringe! The price tag says only fifteen bucks!", "너 그 스웨이드 재킷 입으니까 앨범 커버 모델 같아! 가격표 보니까 단돈 15달러래!",
                  '"당장 사자, 꿀득템이야!"라고 구동사 pick up을 써서 말해보세요!', "Let's pick it up!",
                  "Handing the cash to the vendor! Two vintage treasures bagged in one afternoon!", "상인분께 현금 건네기 완료! 반나절 만에 빈티지 보물 두 개나 득템 완료!",
                  '구동사 "pick up"은 물건을 집어 올리는 것뿐만 아니라 상점이나 시장에서 물건을 "사다/득템하다"라는 뜻으로 원어민들이 매일 사용합니다.',
                  "당장 득템하자! 사자! (쇼핑 및 구매 필수 구동사)", "Drop it in mud.", "진흙에 떨어뜨리라는 오답이에요.", "Rip the pockets.", "주머니 찢으라는 오답이에요."),
        make_turn(9, "Chloe", "🎨", "The distressed 90s denim jacket with the corduroy collar is bagged and tagged! But I wanna wear it right now on the subway!", "골덴 카라 달린 빈티지 청자켓 포장 끝났어! 근데 나 지금 지하철에서 바로 걸치고 싶어!",
                  '"당장 갈아입어!"라고 구동사 change into it을 써서 권해보세요!', "Change into it!",
                  "Denim on, sleeves cuffed once! Walking down the avenue looking like an album cover! Thrift king status!", "청자켓 입고 소매 딱 한 단 접었다! 대로변 걸어가는데 완전 앨범 자켓 모델 간지! 구제 패션 킹 인정!",
                  '구동사 "change into ~"는 새 옷이나 편한 옷으로 "갈아입다"라는 뜻으로 쇼핑 후나 외출 시 가장 자주 쓰이는 구동사입니다.',
                  "당장 갈아입어! (환복 필수 구동사)", "Cut the denim sleeves off.", "소매 가위로 자르라는 오답이에요.", "Throw jacket in puddle.", "웅덩이에 버리라는 오답이에요."),
        make_turn(10, "Chloe", "🎨", "We walked out of the flea market carrying our brown paper bags with the vintage denim and suede fringe jackets! The street style photographers are turning heads!", "빈티지 청자켓이랑 스웨이드 재킷 종이봉투에 챙겨서 벼룩시장 나왔어! 스트릿 패션 사진작가들이 돌아보네!",
                  "\"우리 핏 완전 미쳤다!\"라고 쿨하게 자부심을 드러내보세요!", "Serving pure looks!",
                  "Street fashion royalty! Tomorrow let's grab coffee downtown in our new retro outfits! Catch you later, fashion icon!", "스트릿 패션의 왕족 등극! 내일 새 레트로 옷 입고 시내에서 커피 한잔하자! 이따 봐, 패션 아이콘!",
                  "슬랭 \"Serving looks!\"는 자신의 패션과 스타일이 압도적으로 멋져 사람들의 시선을 사로잡을 때 쓰는 최신 유행어입니다.",
                  "우리 핏 완전 시선 강탈이야! (패션 자부심 극찬)", "We look like garbage.", "쓰레기 같다는 자폭 오답이에요.", "Hide from cameras.", "카메라에서 숨으라는 오답이에요.")
    ]),

    make_ep("t4_e10", "tier4", "방학 카운트다운", "📍 Episode 10/10: Summer Break Countdown", "teenLocker", [
        make_turn(1, "Jordan", "🏀", "Ten seconds until the final bell of the school year! Countdown with me!", "이번 학년 마지막 종 치기 10초 전! 카운트다운 같이 세자!",
                  '"진짜 실감 안 난다!"라고 벅찬 마음을 표현해보세요!', "It feels surreal!",
                  "Three, two, one... Summer vacation is officially here!", "셋, 둘, 하나... 드디어 여름방학 공식 시작이다!",
                  '꿈만 같거나 비현실적일 정도로 벅차오를 때 "실감이 안 나, 꿈같아"라는 고급 구어체입니다.',
                  "진짜 꿈같아, 실감 안 나! (벅찬 감정)", "It is a fake dream.", "가짜 꿈이라는 오답이에요.", "I like homework.", "숙제 좋다는 거짓말이에요."),
        make_turn(2, "Jordan", "🏀", "Three whole months of sun, beach, and zero alarms!", "알람 시계 없는 햇살과 해변의 석 달 방학이다!",
                  '"이 순간만을 기다렸어!"라고 환호해보세요!', "Living the dream!",
                  "We survived finals week! You crushed that math exam!", "기말고사 지옥에서 살아남았다! 너 수학 시험도 제대로 찢었잖아!",
                  '원하던 최고의 상황을 누리고 있을 때 "인생 살맛 난다, 꿈같은 순간이다"라고 자축하는 표현입니다.',
                  "살맛 난다, 꿈같은 순간이야! (최고의 자축)", "I am sleeping in bed.", "침대에서 잔다는 오역이에요.", "Summer is hot.", "덥다는 불평이에요."),
        make_turn(3, "Jordan", "🏀", "Honestly, I thought you were gonna ace it all along!", "솔직히 난 네가 수학 만점 받을 줄 진작부터 알고 있었어!",
                  '"그 정도까진 아니야!"라고 겸손하게 손사래를 쳐보세요!', "I wouldn't go that far!",
                  "Stop being humble! You're literally a math wizard!", "겸손 떨지 마! 너 솔직히 거의 수학 마법사 수준이었거든!",
                  '과한 칭찬에 "에이 그 정도까지는 아니야~" 하며 유쾌하게 겸손을 표할 때 쓰는 관용구입니다.',
                  "그 정도까진 아니야! (유쾌한 겸손)", "I walked very far.", "멀리 걸어갔다는 직역 오역이에요.", "Give me more tests.", "시험 더 달라는 망언이에요."),
        make_turn(4, "Jordan", "🏀", "So, beach bonfire party tonight at six! Are you coming?", "그래서 오늘 저녁 6시에 해변 모닥불 파티 할 건데! 올 거지?",
                  '"나 무조건 낄래!"라고 망설임 없이 답해보세요!', "Count me in!",
                  "Bring your bluetooth speaker! We need the best beats!", "블루투스 스피커 챙겨와! 최고의 비트가 필요하니까!",
                  '재미있는 모임이나 이벤트에 망설임 없이 참여하겠다고 손을 들 때 쓰는 만능 표현입니다.',
                  "나 무조건 낄래! (적극적 참여)", "Count numbers.", "숫자 세라는 엉뚱한 말이에요.", "Beach has sand.", "모래 있다는 설명이에요."),
        make_turn(5, "Jordan", "🏀", "I'll grab the s'mores kit and graham crackers. Can you bring cold soda?", "내가 스모어 키트랑 통밀 크래커 챙길 테니까, 시원한 탄산음료 좀 가져올래?",
                  '"음료수는 내가 쏠게!"라고 쿨하게 맡아보세요!', "It's on me!",
                  "You're a legend! See you at Sunset Beach!", "너 진짜 최고다! 이따 선셋 비치에서 만나!",
                  '자신이 비용이나 준비물을 시원하게 쏘겠다고 자청할 때 쓰는 멋진 호언장담입니다.',
                  "내가 쏠게! (시원한 한턱)", "Drink water only.", "물만 마시라는 짠돌이 말이에요.", "Soda is unhealthy.", "탄산음료 건강에 나쁘다는 잔소리예요."),
        make_turn(6, "Jordan", "🏀", "Don't be late or we'll start without you!", "늦지 마라, 안 그러면 너 빼고 먼저 시작한다!",
                  '"이따 거기서 봐!"라고 손을 흔들며 작별 인사를 건네보세요!', "Catch you later!",
                  "Peace out! Have the best summer ever!", "피스 아웃! 우리 인생 최고의 여름 보내자!",
                  '친구와 헤어질 때 "이따 봐, 나중에 봐" 하며 쿨하게 짓는 마지막 작별 인사입니다.',
                  "이따 거기서 봐! (쿨한 작별 인사)", "I am trapped inside.", "갇혔다는 공포스런 말이에요.", "School starts now.", "개학이라는 악담이에요."),
        make_turn(7, "Jordan", "🏀", "The trunk is packed with towels, speakers, and snacks! Everyone is in the car!", "트렁크에 비치타월, 스피커, 간식 다 실었다! 애들 다 차에 탔어!",
                  '"이제 신나게 출발하자!"라고 구동사 hit the road를 써서 외쳐보세요!', "Let's hit the road!",
                  "Blasting the playlist! Windows down, ocean breeze in our faces! Best summer begins NOW!", "플레이리스트 볼륨 업! 창문 다 내리고 바닷바람 맞으면서! 최고의 여름이 지금 시작된다!",
                  '구동사 "hit the road"는 여행이나 드라이브를 떠나며 "신나게 길을 나서다/출발하다"라는 대표적인 미국식 구어체입니다.',
                  "신나게 출발하자! (여행 출발 대표 구어체)", "Sleep in garage.", "차고에서 자라는 엉뚱한 말이에요.", "Break the steering wheel.", "핸들 부수라는 위험한 말이에요."),
        make_turn(8, "Jordan", "🏀", "The ocean breeze is blasting through the windows! What song starts the ultimate road trip playlist?", "바닷바람 창문 틈으로 쌩쌩 들어온다! 레전드 로드트립 플레이리스트 첫 곡으로 뭐 틀까?",
                  '"볼륨 크게 키워봐!"라고 구동사 turn up을 써서 외쳐보세요!', "Turn it up loud!",
                  "Bass maxed out, speakers shaking the doors! Hello summer vacation!", "베이스 최대로 올리고 스피커가 차 문을 흔든다! 안녕 여름방학!",
                  '구동사 "turn up"은 음악이나 볼륨을 "더 크게 키우다/올리다"라는 뜻으로 드라이브나 파티에서 매 순간 쓰이는 표현입니다.',
                  "볼륨 빵빵하게 키워! (음량 증폭 필수 구동사)", "Turn off all music.", "음악 다 끄라는 오답이에요.", "Break car speakers.", "스피커 부수라는 오답이에요."),
        make_turn(9, "Jordan", "🏀", "Zero seconds! The final dismissal bell is ringing across the entire high school! Front double doors burst wide open!", "0초 찍혔다! 고등학교 전체에 마지막 하교 종 울려 퍼진다! 정문 양문 활짝 열렸어!",
                  '"여름방학 신나게 시작해보자!"라고 구동사 kick off를 써서 환호해보세요!', "Let's kick it off!",
                  "Backpacks in the air! Sunlight on our faces! Have the most legendary summer vacation of your life! WE DID IT!", "가방 하늘로 던져! 얼굴에 쏟아지는 햇살! 인생에서 가장 레전드인 여름방학 보내자! 우리가 해냈다!",
                  '구동사 "kick off"는 축제, 방학, 새 시즌을 "신나게 시작하다/개막하다"라는 뜻으로 미국인들이 입버릇처럼 외치는 대표적 구동사입니다.',
                  "여름방학 신나게 시작해보자! (화려한 시작 필수 구동사)", "Stay in school all July.", "7월 내내 학교에 남으라는 오답이에요.", "Cry in the empty cafeteria.", "빈 식당에서 울라는 오답이에요."),
        make_turn(10, "Jordan", "🏀", "The convertible trunk is shut, the s'mores kit is packed, and the coastal highway sunset is painting the ocean pink! Summer starts now!", "오픈카 트렁크 닫았고 스모어 키트 실었고 해안 도로 노을이 바다를 분홍빛으로 물들이고 있어! 여름이 지금 시작된다!",
                  "\"이보다 더 좋을 순 없어!\"라고 최고의 순간을 만끽해보세요!", "Couldn't be better!",
                  "Bonfire crackling, music blasting, best friends by our side! Welcome to the greatest summer vacation of our lives!", "모닥불 타닥타닥 타고, 음악 빵빵하게 울리고, 곁에는 찐친들! 우리 인생 최고의 여름방학에 온 걸 환영한다!",
                  "관용구 \"Couldn't be better!\"(이보다 더 좋을 순 없어!/더 바랄 게 없이 완벽해!)는 더할 나위 없이 완벽하고 행복한 순간에 내뱉는 최고의 관용구입니다.",
                  "이보다 더 좋을 순 없어! (완벽한 행복 찬사)", "Life is terrible.", "인생 끔찍하다는 악담이에요.", "Drive car off cliff.", "절벽으로 차 몰라는 위험한 오답이에요.")
    ])
]
