"""Tier 4 Scenarios: Ages 14-16 (10 episodes x 8 turns = 80 turns)."""
from scenarios_common import make_ep, make_turn

t4 = [
    make_ep("t4_e1", "tier4", "락커룸 농구 내기", "📍 Episode 1/10: Locker Room Free Throw Bet", "basketball", [
        make_turn(1, "Jordan", "🏀", "I bet I can sink five half-court shots in a row today! No joke!", "오늘 하프라인에서 슛 연속 다섯 개 클린으로 꽂는다에 내기 건다! 진심이야!",
                  '"진짜 실화야? 거짓말 아니고?"라고 확인해보세요!', "No cap!",
                  "Dead serious! If I miss even one, I'm buying you pizza rolls!", "진짜 거짓말 아니고! 하나라도 빗나가면 내가 너 피자롤 쏜다!",
                  '"No cap"은 "거짓말 아니고, 진짜 실화야"라는 미국의 대표적인 Z세대 슬랭입니다.',
                  "진짜 실화야! 거짓말 아니고! (Z세대 진실 슬랭)", "Wear a baseball cap.", "모자 쓰라는 오역이에요.", "Basketball is a ball.", "농구공은 공이라는 딴소리예요."),
        make_turn(2, "Jordan", "🏀", "So do you take the wager? High stakes at the school gym!", "그래서 내기 받을 거야 말 거야? 체육관에서 큰 판 한번 벌여봐?",
                  '"콜! 당연하지! 약속이야!"라고 패기 있게 받아치세요!', "Bet!",
                  "You're on! Let's lace up and head straight to the court right now!", "좋았어 받아줬다! 신발 끈 꽉 매고 지금 바로 코트로 간다!",
                  '상대의 도전이나 제안에 "콜! 당연하지! 좋아!"라고 쿨하게 화답하는 대표 단어입니다.',
                  "콜! 당연하지! (화답 슬랭)", "I am gambling money.", "도박한다는 오역이에요.", "Class is boring.", "수업 지루하다는 딴소리예요."),
        make_turn(3, "Jordan", "🏀", "I need you to grab the rebound under the net and pass it back smooth!", "네가 골대 밑에서 리바운드 잡고 공 스무스하게 튕겨 패스해 줘!",
                  '"더 말할 것도 없어, 접수 완료!"라고 쿨하게 끄덕이세요!', "Say less.",
                  "Perfect teammate! Shot number one going up... Swish! Clean through the rim!", "최고의 팀원! 1번 슛 올라간다... 철썩! 그물만 깔끔하게 통과!",
                  '상대방의 요청을 듣자마자 "말 길게 할 필요 없어, 다 이해했어, 접수 완료"라고 할 때 씁니다.',
                  "더 말할 것도 없어, 접수! (쿨한 이해와 접수)", "Talk very quietly.", "조용히 말하라는 오역이에요.", "I have no hands.", "손 없다는 엉뚱한 말이에요."),
        make_turn(4, "Jordan", "🏀", "Shot number two and three just went through without even brushing the iron!", "2번이랑 3번 슛도 림에 닿지도 않고 클린으로 들어갔어!",
                  '"그물만 철렁! 완전 나이스 샷!"라고 환호해보세요!', "Swish nothing but net.",
                  "Shot four... Bang! One more left from the logo!", "4번 슛도 꽂혔다! 이제 로고에서 던지는 마지막 한 방 남았다!",
                  '농구공이 림을 스치지도 않고 그물만 찰랑이며 깨끗하게 꽂혔을 때 쓰는 전문 농구 구어체입니다.',
                  "그물만 철렁! (클린 샷 찬사)", "Hit the metal hard.", "철봉 때렸다는 오답이에요.", "I want to go home.", "집 가고 싶다는 징징거림이에요."),
        make_turn(5, "Jordan", "🏀", "Shot five... Clank off the back rim! Aaargh, I missed the last one!", "5번 슛... 백림 맞고 튕겨 나갔어! 으아악, 마지막 하나를 놓쳤네!",
                  '"내기 졌으니까 피자롤 뱉어내라!"라고 유쾌하게 요구하세요!', "Pay up!",
                  "A deal's a deal! Extra cheese pizza rolls at the cafeteria table tomorrow!", "약속은 약속이지! 내일 급식실에서 치즈 듬뿍 피자롤 내가 산다!",
                  '내기에서 이겼을 때 "약속한 거 내놔라, 계산해라"고 당당하고 유쾌하게 외치는 표현입니다.',
                  "약속한 거 내놔라! (유쾌한 내기 정산)", "Keep your money.", "돈 가지라는 바보 같은 말이에요.", "The ball is orange.", "공 주황색이라는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "Four out of five from half-court was still insane though! High five!", "그래도 하프라인에서 5개 중 4개 넣은 건 레전드였다! 하이파이브!",
                  '"좋은 승부였어, 인정한다!"라고 승자의 여유를 보여주세요!', "GG, good game!",
                  "Catch you at the cafeteria tomorrow at noon! Have your appetite ready!", "내일 점심 정오에 식당에서 봐! 위장 싹 비우고 와라!",
                  '게임이나 시합이 끝난 뒤 상대방을 존중하며 깔끔하게 악수를 청하는 게이머/하이틴 필수 인사입니다.',
                  "좋은 승부였어! (깔끔한 스포츠맨십)", "You are the worst.", "최악이라는 악담이에요.", "Cancel the game.", "경기 취소하라는 헛소리예요."),
        make_turn(7, "Jordan", "🏀", "The gym lights are clicking off and our pizza rolls are scheduled for noon tomorrow!", "체육관 불 꺼지고 내일 정오에 피자롤 먹기로 약속됐잖아!",
                  '"내일 점심 진짜 기대된다!"라고 구동사 look forward to를 써서 말해보세요!', "I'm looking forward to it!",
                  "You earned those rolls fair and square! Double pepperoni on my dime tomorrow at twelve!", "네 실력으로 정당하게 딴 거니까! 내일 12시에 페퍼로니 두 배로 내가 쏜다!",
                  '구동사 "look forward to ~"는 다가올 일을 "설레는 마음으로 고대하다/기대하다"라는 뜻으로 일상과 대화에서 매일 쓰입니다.',
                  "진짜 기대돼! (설레는 기대의 대표 구동사)", "I dread eating pizza.", "피자 먹기 두렵다는 딴소리예요.", "Cancel lunch forever.", "점심 영원히 취소하자는 엉뚱한 말이에요."),
        make_turn(8, "Jordan", "🏀", "Before we lock up the gym, help me bag these five practice basketballs!", "체육관 문 잠그기 전에, 연습용 농구공 다섯 개 공가방에 넣는 것 좀 도와줘!",
                  '"제자리에 치워두자!"라고 구동사 put away를 써서 말해보세요!', "Let's put them away!",
                  "Zipped into the mesh rack! Court is spotless and ready for tomorrow's tournament!", "그물망 보관함에 지퍼 잠갔다! 코트 완전 깔끔하게 정리 끝, 내일 대회 준비 완료!",
                  '구동사 "put away"는 스포츠 용품이나 물건을 "제자리에 정리하다/치워두다"라는 뜻의 최상위 빈도 구동사입니다.',
                  "제자리에 치워두자! (정리 및 수납 필수 구동사)", "Kick balls outside.", "공 밖으로 차라는 오답이에요.", "Leave balls on court.", "코트에 방치하라는 오답이에요.")
    ]),

    make_ep("t4_e2", "tier4", "방과 후 버블티 번개", "📍 Episode 2/10: After-School Boba Cravings", "bubbleTea", [
        make_turn(1, "Chloe", "🎨", "The 7th period bell finally rang! My brain is officially melted from chemistry!", "7교시 종 드디어 쳤다! 화학 수업 때문에 내 뇌 완전히 녹아내렸어!",
                  '"나 은근 버블티 엄청 땡겨."라고 속마음을 흘려보세요!', "I'm lowkey craving boba.",
                  "Wait, are you telepathic?! I was literally just drooling over brown sugar milk tea!", "잠깐, 너 텔레파시 통했냐?! 나 방금 흑당 밀크티 생각하면서 침 흘리고 있었는데!",
                  '"lowkey"는 "은근히, 대놓고는 아니지만 은근하게"라는 뜻의 필수 Z세대 부사입니다.',
                  "나 은근 버블티 땡겨. (은근한 욕구 표현)", "I am shouting very loud.", "크게 소리친다는 엉뚱한 뜻이에요.", "Tea is hot water.", "차는 뜨거운 물이라는 설명이에요."),
        make_turn(2, "Chloe", "🎨", "Brown sugar milk tea with extra chewy boba sounds like heaven right now!", "쫄깃한 펄 추가한 흑당 밀크티 지금 마시면 완전 천국이겠다!",
                  '"인정, 완전 타당한 선택이야!"라고 폭풍 공감해보세요!', "Valid.",
                  "So valid! There is literally no better cure for a ruined school day!", "완전 인정! 망친 학교 하루를 위로하는 데 이보다 완벽한 약은 없지!",
                  '상대방의 의견이나 행동, 취향이 전적으로 납득되고 공감될 때 딱 한마디로 건네는 슬랭입니다.',
                  "인정, 완전 타당해! (폭풍 공감 슬랭)", "Invalid completely.", "무효라는 차가운 말이에요.", "I have no opinion.", "의견 없다는 무미건조한 말이에요."),
        make_turn(3, "Chloe", "🎨", "The weather is so crisp outside too! Are we walking or taking our skateboards?", "바깥 날씨도 엄청 선선해! 걸어갈까 아니면 스케이트보드 타고 갈까?",
                  '"우리 이제 어떻게 할까? 계획이 뭐야?"라고 작전을 물어보세요!', "What's the move?",
                  "Grab our boards! We can cruise down Elm Street and beat the school rush in five minutes!", "보드 챙겨! 엘름 스트리트 타고 내려가면 5분 컷으로 하교 인파 뚫을 수 있어!",
                  '친구 무리에서 "다음 행선지는 어디야? 우리 계획이 뭐야?"라고 물을 때 쓰는 Z세대 관용구입니다.',
                  "우리 이제 어떻게 할까? (작전/계획 묻기)", "Move your furniture.", "가구 옮기라는 직역 오역이에요.", "Stay still forever.", "가만히 있으라는 엉뚱한 말이에요."),
        make_turn(4, "Chloe", "🎨", "Wait, before we push off... Did you hear about what happened in the hallway at lunch?", "잠깐, 출발하기 전에... 너 오늘 점심시간 복도에서 무슨 일 있었는지 들었어?",
                  '"썰 풀어봐, 속 시원히 털어놔!"라고 눈을 빛내보세요!', "Spill the tea.",
                  "Okay, so Liam accidentally dropped his entire tray of spaghetti right in front of the principal!", "좋아, 그러니까 리암이 교장선생님 바로 코앞에서 스파게티 식판을 통째로 쏟았잖아!",
                  '"tea"는 "소문, 가십, 비하인드 스토리"를 뜻하며, "비하인드 썰 풀어봐!"라고 재촉할 때 씁니다.',
                  "썰 풀어봐! (흥미진진한 가십 요청)", "Pour boiling tea on table.", "뜨거운 차 쏟으라는 위험한 오역이에요.", "Be quiet forever.", "조용히 하라는 핀잔이에요."),
        make_turn(5, "Chloe", "🎨", "And the principal's white sneakers got completely splattered with red marinara sauce!", "그리고 교장선생님 하얀 스니커즈에 빨간 토마토소스가 완전 튀었대!",
                  '"말도 안 돼, 진짜 실화야?"라고 턱 빠지게 놀라보세요!', "No way, for real?",
                  "Dead serious! Liam turned redder than the pasta sauce and froze like a statue!", "진짜 거짓말 아니고! 리암 얼굴이 파스타 소스보다 더 빨개져서 석상처럼 굳었대!",
                  '믿기지 않는 충격적인 썰을 듣고 "실화냐, 진짜냐"고 거듭 되물을 때 쓰는 자연스러운 콤보입니다.',
                  "말도 안 돼, 진짜 실화야? (충격 리액션)", "I am sleeping now.", "자고 있다는 딴소리예요.", "Sneakers are shoes.", "신발은 신발이라는 설명이에요."),
        make_turn(6, "Chloe", "🎨", "I literally had to bite my cheek so hard not to laugh out loud in the hallway!", "나 복도에서 진짜 빵 안 터지려고 볼 안쪽 꽉 깨물었잖아!",
                  '"너무 웃겨서 나 기절/사망할 뻔했어!"라고 폭소해보세요!', "Dead, I can't even!",
                  "Haha, my stomach hurts from laughing! Now let's go get that boba!", "하하 웃겨서 배 아파 죽겠다! 이제 얼른 버블티 마시러 쏘자!",
                  '너무 어이없고 웃겨서 "말문이 막히고 빵 터져 죽겠다"는 하이틴 최고의 리액션입니다.',
                  "웃겨서 나 기절/사망! (폭소 리액션)", "Call the ambulance now.", "진짜 구급차 부르라는 오역이에요.", "I feel zero emotion.", "아무 감정 없다는 로봇 반응이에요."),
        make_turn(7, "Chloe", "🎨", "We drank all the brown sugar milk tea and finished our homework review! What should we do now?", "흑당 밀크티 다 마셨고 과제 검토도 끝났어! 우리 이제 뭐 할까?",
                  '"소파에서 편하게 좀 쉬자!"라고 구동사 chill out을 써서 말해보세요!', "Let's just chill out!",
                  "Putting on my lo-fi playlist right now! Pure peaceful vibes after a hectic Monday!", "로파이 플레이리스트 지금 튼다! 빡센 월요일 보내고 즐기는 순도 100% 평화로운 힐링 바이브!",
                  '구동사 "chill out"은 긴장을 풀고 편안하게 빈둥거리며 쉴 때 미국 청소년들이 입버릇처럼 쓰는 대표 구동사입니다.',
                  "편하게 좀 쉬자! (휴식과 힐링의 대표 구동사)", "Run five miles.", "5마일 뛰라는 무리한 말이에요.", "Study three textbooks.", "교과서 세 권 더 보자는 고문이에요."),
        make_turn(8, "Chloe", "🎨", "The sun is completely down and the streetlights on Elm Street are flickering on! What time do you need to be home?", "해 완전히 지고 엘름 스트리트 가로등 깜빡거리기 시작했어! 너 몇 시까지 집 가야 해?",
                  '"나 이제 가봐야 해!"라고 기본동사 get going을 써서 말해보세요!', "I should get going!",
                  "Grab your board! I'll cruise with you to the corner! See ya tomorrow!", "보드 챙겨! 골목 모퉁이까지 같이 타고 갈게! 내일 봐!",
                  '기본동사 "get"을 활용한 "get going"(출발하다, 자리를 뜨다)은 "I should get going"(나 이제 가봐야 해/출발해야 해)처럼 모임을 마무리할 때 원어민들이 가장 자연스럽게 쓰는 표현입니다.',
                  "나 이제 가봐야 해! (모임 마무리 필수 기본동사)", "Sleep on street corner.", "길모퉁이에서 자라는 오답이에요.", "Forget where I live.", "집 까먹었다는 엉뚱한 오답이에요.")
    ]),

    make_ep("t4_e3", "tier4", "고교 풋볼 금요일 경기", "📍 Episode 3/10: Friday Night Football Lights", "teenLocker", [
        make_turn(1, "Jordan", "🏀", "Look at the stadium lights shining through the fog! The student section is chanting!", "안개 뚫고 쏟아지는 스타디움 조명 좀 봐! 전교생 응원단 챈트 부르고 난리 났어!",
                  '"분위기 진짜 미쳤다, 텐션 폭발이야!"라고 감탄해보세요!', "The hype is unreal!",
                  "Electric! Five thousand students shaking the metal bleachers with stomps!", "짜릿하다! 5천 명 학생들이 발 구르면서 철제 스탠드 통째로 뒤흔들고 있어!",
                  '경기나 축제의 열기와 흥분이 상상을 초월할 정도로 뜨거울 때 쓰는 하이틴 표현입니다.',
                  "텐션 진짜 미쳤다! (열광의 도가니)", "The hype is fake.", "가짜라는 초 치기예요.", "Stadium is made of concrete.", "콘크리트라는 설명이에요."),
        make_turn(2, "Jordan", "🏀", "Touchdown! Our quarterback threw a forty-yard bomb into the end zone!", "터치다운! 우리 쿼터백이 엔드존으로 40야드 대포알 패스 꽂아 넣었어!",
                  '"폼 미쳤다, 완전 찢었다!"라고 환호성을 질러보세요!', "He is him!",
                  "Absolute MVP! He juked two blitzers and released the ball off-balance!", "진짜 살아있는 MVP! 수비수 둘 페이크로 제치고 중심 잃으면서 던졌잖아!",
                  '어떤 선수가 독보적인 실력으로 영웅적인 플레이를 펼칠 때 "그가 바로 주인공이다, 신이다"라고 찬양하는 최신 Z세대 슬랭입니다.',
                  "폼 미쳤다! 그가 바로 주인공이야! (영웅적 찬양)", "He is someone else.", "다른 사람이라는 엉뚱한 오역이에요.", "Football is dangerous.", "위험하다는 딴소리예요."),
        make_turn(3, "Jordan", "🏀", "Four seconds left on the clock! Opponent kicker is lining up for the field goal!", "남은 시간 단 4초! 상대 팀 키커가 필드골 차려고 라인 서고 있어!",
                  '"제발 빗나가라, 제발 막아라!"라고 간절하게 빌어보세요!', "Lock in defense!",
                  "BLOCKED! Our linebacker swatted the football out of the sky! WE WON!", "블락 성공! 우리 라인배커가 하늘에서 공 쳐냈어! 우리가 이겼다!",
                  '중요한 순간에 온 신경을 집중하고 결속할 때 쓰는 전의 충전 슬랭입니다.',
                  "수비에 초집중해! (결정적 순간 집중)", "Unlock the door.", "문 따라는 엉뚱한 오역이에요.", "Go buy popcorn.", "팝콘 사러 가자는 딴청이에요."),
        make_turn(4, "Jordan", "🏀", "The whole bleacher crowd is storming onto the green turf!", "스탠드에 있던 전교생이 초록색 잔디 필드로 쏟아져 들어가고 있어!",
                  '"완전 축제 분위기 난리 났다!"라고 필드로 뛰어나가세요!', "Pure pandemonium!",
                  "Confetti, marching band blasting, coaches getting ice water dumped on them!", "색종이 날리고 마칭밴드 나팔 불고 코치님들한테 얼음물 붓고 난리 났어!",
                  '통제할 수 없을 정도로 기쁨과 환희가 폭발해 경기장이 축제의 장이 되었을 때 쓰는 고급 표현입니다.',
                  "완전 축제 난리 났어! (환희의 대혼란)", "Everyone is sad.", "다 슬프다는 거짓말이에요.", "Sit quietly.", "조용히 앉아있으라는 오답이에요."),
        make_turn(5, "Jordan", "🏀", "Quarterback hoisted up on everyone's shoulders holding the silver trophy!", "쿼터백이 은색 트로피 높이 들고 전교생 어깨 위로 무등 탔어!",
                  '"이 순간은 영원히 기억될 거야!"라고 가슴 벅차해보세요!', "Core memory unlocked.",
                  "Ten years from now, people will still be talking about this Friday night comeback!", "10년 뒤에도 사람들은 오늘 금요일 밤 역전극 얘기하고 있을걸!",
                  '인생에 평생 잊지 못할 결정적인 명장면을 마주했을 때 쓰는 감각적인 표현입니다.',
                  "평생 잊지 못할 명장면이야! (평생의 추억)", "Lock memory away.", "기억 지우라는 반대말이에요.", "I forgot my jacket.", "자켓 두고 왔다는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "Look at coach wiping a tear while hoisting the regional plaque!", "코치님이 지역 우승 명패 치켜드시면서 눈물 훔치시는 것 좀 봐!",
                  '"살아있는 전설이야, 레전드다!"라고 진심 어린 존경을 표하세요!', "Living legend.",
                  "Forty years of coaching, and he brought our school the gold ring! Iconic!", "코치 인생 40년 만에 우리 학교에 금반지 안겨주셨어! 진짜 역사적인 순간이다!",
                  '역대급 활약이나 업적을 세운 사람을 "살아있는 전설"이라고 칭송할 때 쓰는 극상의 표현입니다.',
                  "살아있는 전설이야! (극상의 찬사)", "Nobody knows him.", "듣보잡이라는 악담이에요.", "I lost my shoes.", "신발 잃어버렸다는 딴소리예요."),
        make_turn(7, "Jordan", "🏀", "The victory fireworks smoke is clearing! The team bus is heading to the all-night diner!", "승리 축포 연기 걷히고 있다! 선수단 버스가 밤샘 다이너 식당으로 가고 있어!",
                  '"우리도 거기로 넘어가자!"라고 구동사 head over를 써서 제안해보세요!', "Let's head over there!",
                  "Catching the next ride! Milkshakes and waffle fries with the whole school champion squad!", "다음 차 타고 바로 쏜다! 전교 우승 선수단이랑 밀크셰이크에 와플 감자튀김 파티다!",
                  '구동사 "head over"는 어딘가 약속 장소나 이벤트 현장으로 "자리를 이동하다/건너가다"라는 뜻의 필수 구동사입니다.',
                  "우리도 거기로 넘어가자! (이동 및 합류 필수 구동사)", "Stay on the grass.", "잔디밭에 밤새 남으라는 엉뚱한 말이에요.", "Walk backwards home.", "뒤로 걸어가라는 이상한 소리예요."),
        make_turn(8, "Jordan", "🏀", "The diner booth is crowded with jerseys, but our friends are sliding over to make space!", "다이너 테이블에 유니폼 입은 애들로 꽉 찼는데, 애들이 자리 만들어주려고 옆으로 당겨 앉고 있어!",
                  '"자리 좀 만들어줘!"라고 기본동사 make room을 써서 말해보세요!', "Make some room!",
                  "Sliding over right now! Squeeze in! A giant plate of cheese fries is landing in the center!", "옆으로 싹 붙었다! 얼른 낑겨 앉아! 가운데에 대왕 치즈 감자튀김 나온다!",
                  '기본동사 "make"를 활용한 "Make room!"(공간을 만들다, 자리를 비켜주다)은 붐비는 테이블이나 장소에서 자리를 마련할 때 쓰는 핵심 표현입니다.',
                  "자리 좀 만들어줘! (공간 확보 필수 기본동사)", "Block the doorway.", "출입문 막으라는 오답이에요.", "Eat off the floor.", "바닥에서 먹자는 엉뚱한 오답이에요.")
    ]),

    make_ep("t4_e4", "tier4", "친구의 어이없는 드립", "📍 Episode 4/10: Hallway Brainrot Standup", "classroom", [
        make_turn(1, "Chloe", "🎨", "If tomatoes are a fruit, then ketchup is technically a fruit smoothie!", "토마토가 과일이면, 케첩은 엄밀히 말해서 과일 스무디인 거잖아!",
                  '"너무 웃겨서 나 기절하겠다 ㅋㅋㅋ!"라고 빵 터져보세요!', "I'm dead!",
                  "Stop, my mascara is running from crying laughing right in the hallway!", "그만해, 복도에서 눈물 나게 웃느라 마스카라 다 번지고 있잖아!",
                  '상대의 어이없는 농담이나 말도 안 되는 드립에 "너무 웃겨서 나 죽겠다"며 쓰러질 때 씁니다.',
                  "나 너무 웃겨서 사망 ㅋㅋㅋ! (폭소 리액션)", "I am literally dead.", "진짜 사망했다는 직역 오역이에요.", "Ketchup has vinegar.", "식초 들었다는 진지충 반응이에요."),
        make_turn(2, "Chloe", "🎨", "And strawberry milk is just cow milk mixed with melted ice cream thoughts!", "그리고 딸기우유는 그냥 녹은 아이스크림 생각을 우유에 섞은 거라니까!",
                  '"제발 멈춰, 배 아파 죽겠어!"라고 배를 잡고 웃어보세요!', "Please stop!",
                  "I have ten more philosophy food thoughts saved in my notes app!", "내 폰 메모장에 이런 음식 철학 드립 열 개는 더 적혀있단 말이야!",
                  '너무 웃겨서 숨이 찰 때 "제발 그만해, 숨넘어가겠다"며 말리는 유쾌한 호소입니다.',
                  "제발 멈춰! 배 찢어져! (유쾌한 만류)", "Keep speaking forever.", "평생 말하라는 무관심 반응이에요.", "Cow produces milk.", "젖소 설명이에요."),
        make_turn(3, "Chloe", "🎨", "Who gave you permission to be this unhinged before second period?!", "2교시 시작도 안 했는데 누가 너한테 이렇게 고삐 풀리라고 허락했냐고?!",
                  '"그냥 웃기니까 인정해 ㅋㅋㅋ!"라고 너스레를 떨어보세요!', "Just roll with it.",
                  "Fine! But if Mr. Davis hears you talking about ketchup smoothies, you're on your own!", "알았어! 근데 데이비스 선생님이 케첩 스무디 얘기 들으시면 난 모르는 일이다!",
                  '황당하거나 기상천외한 상황도 "그냥 즐겨, 흐름에 몸을 맡겨"라며 유연하게 넘길 때 씁니다.',
                  "그냥 즐겨, 받아들여 ㅋㅋㅋ! (유연한 순응)", "Roll on the carpet.", "카펫에서 구르라는 오역이에요.", "Class is canceled.", "수업 취소라는 헛소문이에요."),
        make_turn(4, "Chloe", "🎨", "Seriously though, where do you even come up with these bizarre shower thoughts?", "근데 진지하게, 너 이런 기상천외한 샤워 생각들은 대체 어디서 떠올리는 거야?",
                  '"내 뇌는 미스터리야."라고 장난스럽게 답해보세요!', "Brain is a mystery.",
                  "Certified comic genius! You need to do stand-up at the school talent show!", "공인 개그 천재 인정! 너 학교 장기자랑 때 스탠드업 코미디 무대 서야 해!",
                  '자신의 독특한 발상이나 엉뚱함을 유머러스하고 신비롭게 포장할 때 쓰는 표현입니다.',
                  "내 뇌는 미스터리지. (능청스러운 포장)", "Brain is a muscle.", "근육이라는 엉뚱한 과학 설명이에요.", "I have no brain.", "뇌 없다는 자폭이에요."),
        make_turn(5, "Chloe", "🎨", "The talent show flyer on the locker board has three open comedy slots left!", "사물함 게시판 장기자랑 포스터에 코미디 부문 딱 세 자리 남았대!",
                  '"너 진심이야? 설마?"라고 동공 지진을 일으켜보세요!', "Are you serious?",
                  "Hundred percent! I will literally be in the front row holding a giant neon sign with your face!", "100퍼센트 진심이지! 내가 맨 앞줄에서 네 얼굴 박힌 대형 네온 피켓 들고 응원할 거야!",
                  '믿기지 않는 진지한 제안에 "너 설마 진심이야?"라고 화들짝 놀라며 물을 때 씁니다.',
                  "너 진심이야? 설마? (동공 지진 확인)", "I am a clown.", "광대라는 오역이에요.", "Good night everyone.", "자러 가자는 인사예요."),
        make_turn(6, "Chloe", "🎨", "You've got natural stage presence! What do you have to lose? Just sign up!", "너 천성적인 무대 체질이잖아! 밑져야 본전인데 뭘 망설여? 얼른 신청해!",
                  '"그 말도 일리 있네, 고민해볼게!"라고 귀를 기울여보세요!', "You make a good point.",
                  "Draft five minutes of food jokes tonight! We test them on the lunch table tomorrow!", "오늘 밤에 5분짜리 음식 드립 대본 써와! 내일 점심 테이블에서 애들 반응 테스트해보자!",
                  '상대방의 설득력 있는 논리에 수긍하며 "네 말에 일리가 있다"고 고개를 끄덕일 때 씁니다.',
                  "듣고 보니 일리 있네! (설득력 인정)", "Point your finger.", "손가락질하라는 직역 오역이에요.", "I hate microphones.", "마이크 싫다는 투정이에요."),
        make_turn(7, "Chloe", "🎨", "Mr. Davis started writing calculus formulas on the board! Act like we've been taking notes!", "선생님이 칠판에 미적분 공식 쓰기 시작하셨어! 계속 필기하고 있던 척해!",
                  '"긴장 풀고 진정하자."라고 구동사 calm down을 써서 속삭여보세요!', "Let's calm down.",
                  "Deep breath... Serious academic face engaged! Not laughing again until lunch bell rings!", "심호흡... 진지한 모범생 표정 장착 완료! 점심 종 칠 때까지 절대 안 웃는다!",
                  '구동사 "calm down"은 웃음이나 긴장, 흥분을 가라앉히고 마음을 "진정시키다"라는 뜻의 일상 필수 구동사입니다.',
                  "진정하고 가라앉히자. (진정과 평정심 구동사)", "Scream at the ceiling.", "천장에 소리 지르라는 미친 짓이에요.", "Throw notebook.", "공책 던지라는 테러예요."),
        make_turn(8, "Chloe", "🎨", "Pencils are scribbling, but look under my binder! I slipped your missing blue highlighter into your pencil pouch!", "필기는 열심히 하고 있는데, 내 바인더 밑에 봐봐! 너 아까 잃어버렸던 파란색 형광펜 필통에 쏙 넣어뒀어!",
                  '"다시 갖다 줘서 고마워!"라고 구동사 bring back을 써서 말해보세요!', "Thanks for bringing it back!",
                  "Anytime! Now back to calculus before Mr. Davis turns around!", "언제든 말해! 이제 선생님 뒤돌아보시기 전에 다시 미적분 집중!",
                  '구동사 "bring back"은 빌린 물건을 "다시 가져다주다/돌려주다"라는 뜻으로 교실과 일상에서 물건을 돌려받을 때 가장 흔히 쓰이는 표현입니다.',
                  "다시 갖다 줘서 고마워! (물건 반환 감사 필수 구동사)", "Throw it out window.", "창밖으로 던지라는 오답이에요.", "Break highlighter.", "형광펜 부러뜨리라는 오답이에요.")
    ]),

    make_ep("t4_e5", "tier4", "틱톡 댄스 챌린지", "📍 Episode 5/10: Viral Skatepark Transition", "skatepark", [
        make_turn(1, "Jordan", "🏀", "Check our phone notifications! The skate transition reel just hit fifty thousand views!", "폰 알림 좀 확인해 봐! 우리 스케이트 트랜지션 릴스 조회수 방금 5만 뷰 찍었어!",
                  '"우리 알고리즘 탔다, 대박 터졌어!"라고 환호해보세요!', "We are blowing up!",
                  "Notifications won't stop pinging! Comments are flying in every two seconds!", "알림 진동이 안 멈춰! 2초마다 댓글 쏟아지고 있어!",
                  'SNS 콘텐츠나 인기가 폭발적으로 치솟을 때 "알고리즘 탔다, 떡상했다"는 의미로 쓰는 대표 슬랭입니다.',
                  "우리 알고리즘 탔어! 떡상했어! (폭발적 바이럴)", "Explode with dynamite.", "다이너마이트로 폭발하라는 오역이에요.", "Delete my phone.", "폰 지우라는 오답이에요."),
        make_turn(2, "Jordan", "🏀", "Even that pro skater from California liked it and dropped three fire emojis!", "심지어 캘리포니아 프로 스케이터 선수도 좋아요 누르고 불꽃 이모티콘 3개 달아줬어!",
                  '"인정받았다, 게임 끝났네!"라고 자부심을 뽐내보세요!', "Validated!",
                  "That's the ultimate seal of approval! We officially have street cred now!", "그건 궁극의 공식 인증 마크지! 우리 이제 공식적으로 스트리트 인정받은 거다!",
                  '권위자나 동경하는 사람에게 실력을 인정받아 뿌듯함과 가치를 확신할 때 외치는 단어입니다.',
                  "인정받았어! 완전 인정! (궁극의 자부심)", "Invalid password.", "비밀번호 틀렸다는 엉뚱한 말이에요.", "Dislike the comment.", "싫어요 누르라는 반대말이에요."),
        make_turn(3, "Jordan", "🏀", "Top comment with four thousand likes says: 'Cleanest footwork on the entire app!'", "좋아요 4천 개 달린 베스트 댓글 봐봐: '앱 전체에서 제일 깔끔한 발기술이다!'",
                  '"부스러기 하나 없이 완벽 찢었지!"라고 댓글을 읽으며 맞장구쳐보세요!', "Left no crumbs!",
                  "We spent three hours perfecting that kickflip transition and it totally paid off!", "그 킥플립 트랜지션 3시간 동안 연습해서 완벽하게 딴 보람이 있네!",
                  '퍼포먼스나 연출을 흠잡을 데 없이 완벽하게 소화해냈을 때 쓰는 최신 극찬 표현입니다.',
                  "부스러기 없이 찢었지! (완벽한 퍼포먼스)", "Eat bread crumbs.", "빵부스러기 먹으라는 직역 오역이에요.", "Camera is blurry.", "화면 흐리다는 딴소리예요."),
        make_turn(4, "Jordan", "🏀", "Should we drop part two with the stair set drop tomorrow afternoon?", "내일 오후에 계단 세트 드롭하는 2편 영상도 바로 풀어버릴까?",
                  '"물 들어올 때 노 저어야지!"라고 추진력을 더해보세요!', "Strike while the iron is hot.",
                  "Exactly! Ride the momentum while the algorithm is pushing our page to the Explore tab!", "맞아! 알고리즘이 탐색 탭으로 우리 영상 밀어줄 때 이 기세 그대로 타야지!",
                  '기회가 찾아왔을 때 망설이지 말고 즉시 행동에 옮겨야 함을 나타내는 명언 관용구입니다.',
                  "물 들어올 때 노 저어야지! (기회의 포착)", "Iron your t-shirt.", "티셔츠 다림질하라는 엉뚱한 오역이에요.", "Turn off internet.", "인터넷 끄라는 반대말이에요."),
        make_turn(5, "Jordan", "🏀", "What track should we use for part two? That viral Brazilian phonk beat?", "2편 영상 배경음악은 뭘로 깔까? 요즘 떡상 중인 브라질 퐁크 비트?",
                  '"탁월한 선택이야, 그거 얹어!"라고 찬성해보세요!', "Elite choice.",
                  "Bass drops right as the back wheels clear the final concrete step! Cinema!", "뒷바퀴가 마지막 콘크리트 계단 턱 넘을 때 딱 베이스 드롭 터지는 거지! 완전 영화다!",
                  '아이디어나 선택이 최고의 수준으로 완벽할 때 "엘리트급 선택이다"라고 치켜세우는 슬랭입니다.',
                  "탁월한 선택이야! (최고의 선택 찬사)", "Worst music ever.", "최악의 음악이라는 악담이에요.", "I have no speakers.", "스피커 없다는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "We're meeting at the skatepark at four sharp tomorrow! Charge your camera gimbal!", "내일 딱 4시에 스케이트파크 집합이다! 카메라 짐벌 배터리 완충해와!",
                  '"더 말할 것도 없어, 완벽 준비 완료!"라고 쿨하게 화답하세요!', "Say less.",
                  "Part two is gonna hit one million views! Let's make internet history tomorrow!", "2편 영상은 무조건 100만 뷰 뚫는다! 내일 인터넷 역사 한번 써보자!",
                  '상대의 지시나 제안에 "더 이상 긴말 필요 없이 100% 접수했다"고 쿨하게 답할 때 씁니다.',
                  "더 말할 필요 없어, 접수 완료! (쿨한 약속 접수)", "Talk very loudly.", "크게 말하라는 오역이에요.", "I broke the camera.", "카메라 깨졌다는 거짓말이에요."),
        make_turn(7, "Jordan", "🏀", "People in the comments keep asking what skate shoes and bearings we use!", "댓글 창에서 우리가 무슨 보드 신발이랑 베어링 쓰는지 계속 물어봐!",
                  '"상세 정보 짚어주자!"라고 구동사 point out을 써서 말해보세요!', "Let's point that out!",
                  "Pinning a comment right at the top with all the gear specs! Community engagement 100%!", "장비 스펙 싹 다 적어서 맨 위 댓글 고정한다! 팬 소통 100점 만점!",
                  '구동사 "point out"은 중요한 정보나 사실을 콕 집어 "명확히 알려주다/지적하다"라는 뜻의 핵심 구동사입니다.',
                  "정보를 콕 짚어 알려주자! (명확한 정보 안내 구동사)", "Delete all comments.", "댓글 다 지우라는 오답이에요.", "Lie about shoes.", "거짓말하라는 나쁜 말이에요."),
        make_turn(8, "Jordan", "🏀", "The video just crossed one hundred thousand views! Everyone in the comments wants part two!", "영상 조회수가 방금 10만 뷰를 돌파했어! 댓글 창 애들이 전부 파트 2 원하고 있어!",
                  '"이 기세 계속 이어나가자!"라고 기본동사 keep it up을 써서 파이팅을 외쳐보세요!', "Let's keep it up!",
                  "The momentum is unstoppable! Filming the stair drop tutorial tomorrow after school!", "이 기세 아무도 못 막아! 내일 방과 후에 계단 드롭 튜토리얼 2편 바로 찍자!",
                  '기본동사 표현 "keep it up"은 "계속 잘해나가다, 지금 이 기세를 유지하다"라는 뜻으로 찬사와 격려를 전할 때 전 세계에서 가장 많이 쓰이는 구어체입니다.',
                  "이 기세 계속 유지하자! (기세 지속과 격려의 기본동사)", "Delete the channel.", "채널 삭제하라는 오답이에요.", "Quit skating forever.", "영원히 때려치우라는 오답이에요.")
    ]),

    make_ep("t4_e6", "tier4", "기말고사 끝 해방", "📍 Episode 6/10: Finals Week Liberation", "classroom", [
        make_turn(1, "Chloe", "🎨", "Pencils down! Hand in your scantron sheets to the front desk!", "연필 내려놓으세요! OMR 카드 앞쪽 교탁으로 제출하세요!",
                  '"우리 드디어 해방이다!"라고 두 팔을 번쩍 들어보세요!', "We're finally free!",
                  "The weight of ten thousand tons of algebra just evaporated off my chest!", "가슴을 짓누르던 1만 톤짜리 대수학 무게가 방금 눈 녹듯 사라졌어!",
                  '시험이나 힘든 의무가 끝나고 완전한 해방감을 만끽할 때 터져 나오는 외침입니다.',
                  "우리 드디어 자유야! (해방의 환호)", "I love exams.", "시험 사랑한다는 거짓말이에요.", "School continues forever.", "학교 영원하다는 악몽이에요."),
        make_turn(2, "Chloe", "🎨", "No more 6 AM alarms, no more history flashcards, no more cafeteria mystery meat!", "이제 아침 6시 알람도 없고, 역사 플래시카드도 없고, 급식 미스터리 고기도 끝이야!",
                  '"진짜 천국이 따로 없네!"라고 행복에 겨워보세요!', "Pure bliss.",
                  "Walking out those double doors right now feels like floating on a cloud!", "지금 학교 정문 나서는 발걸음이 구름 위를 둥둥 떠다니는 기분이야!",
                  '완벽하고 더할 나위 없는 행복과 평온함을 누릴 때 쓰는 우아한 감탄사입니다.',
                  "진짜 천국이 따로 없어! (더없는 행복)", "Pure misery.", "극심한 고통이라는 반대말이에요.", "I want more homework.", "숙제 더 달라는 망언이에요."),
        make_turn(3, "Chloe", "🎨", "What is the very first thing on your summer bucket list?", "네 여름방학 버킷리스트 1번 항목이 대체 뭐야?",
                  '"잠 실컷 자고 밤새 게임하기!"라고 소박한 로망을 밝혀보세요!', "Sleep in and game.",
                  "Valid! I am not setting an alarm until mid-August at the earliest!", "인정! 나도 빨라야 8월 중순 전까진 알람 시계 절대 안 맞출 거야!",
                  '방학이나 휴가 때 알람 없이 늦잠 자고 취미에 몰두하는 자유를 만끽할 때 씁니다.',
                  "늦잠 자고 게임 몰아하기! (방학 로망)", "Wake up at four AM.", "새벽 4시에 일어나라는 고문이에요.", "Clean the whole house.", "대청소하자는 잔소리예요."),
        make_turn(4, "Chloe", "🎨", "Should we do a celebratory bonfire at the beach tonight?", "오늘 밤에 해변에서 종강 기념 축하 모닥불 파티 할래?",
                  '"말해 뭐해, 무조건 가지!"라고 격하게 찬성해보세요!', "You bet!",
                  "I'll bring the giant bluetooth speaker and two bags of giant marshmallows!", "내가 대형 블루투스 스피커랑 대왕 마시멜로 두 봉지 챙겨갈게!",
                  '상대방의 제안에 "당연하지! 두말하면 잔소리지!"라며 확실한 찬성을 표할 때 씁니다.',
                  "말해 뭐해, 무조건이지! (격한 찬성)", "I decline completely.", "완전 거절이라는 차가운 말이에요.", "Fire is dangerous.", "불 위험하다는 교과서 문장이에요."),
        make_turn(5, "Chloe", "🎨", "Sunset beach bonfire with the entire sophomore squad!", "전체 2학년 친구들과 노을 지는 해변 모닥불 파티라니!",
                  '"상상만 해도 가슴이 웅장해진다!"라고 설렘을 표현해보세요!', "I'm so hyped!",
                  "Music, ocean waves, s'mores, and zero homework worries until September!", "음악에 파도 소리, 스모어에 9월까지 숙제 걱정 0퍼센트라니!",
                  '다가올 신나는 이벤트나 파티에 텐션이 최대로 솟구쳤을 때 외치는 대표 슬랭입니다.',
                  "나 완전 흥분돼! 기대치 폭발이야! (설렘의 정점)", "I am depressed.", "우울하다는 반대말이에요.", "Stay inside room.", "방 안에만 박혀있자는 오답이에요."),
        make_turn(6, "Chloe", "🎨", "This is gonna be the summer they make movies about!", "이번 여름방학은 나중에 영화로 만들어도 될 레전드 여름이 될 거야!",
                  '"우리 청춘의 황금기다!"라고 건배사를 띄워보세요!', "Peak moments.",
                  "Making memories we will talk about at our twenty-year high school reunion!", "20년 뒤 고등학교 동창회에서도 무조건 회자될 레전드 추억 만드는 거다!",
                  '인생에서 가장 빛나고 소중한 절정의 순간들을 맞이했을 때 자축하는 멋진 표현입니다.',
                  "우리 인생 최고의 황금기야! (절정의 순간)", "Worst moments.", "최악의 순간이라는 악담이에요.", "I hate youth.", "청춘 싫다는 딴소리예요."),
        make_turn(7, "Chloe", "🎨", "All backpacks dumped in the grass! The school gate is officially behind us!", "가방 다 잔디밭에 던져뒀고! 교문은 이제 공식적으로 우리 등 뒤에 있어!",
                  '"이 순간을 제대로 만끽하자!"라고 구동사 soak in을 써서 외쳐보세요!', "Let's soak it all in!",
                  "Basking in the golden summer sunshine! Three months of pure freedom, here we go!", "황금빛 여름 햇살 온몸으로 만끽 중! 순도 100% 석 달간의 자유, 가보자고!",
                  '구동사 "soak in" 또는 "take in"은 분위기나 감격스러운 순간을 온몸으로 "흠뻑 만끽하다/음미하다"라는 고급 구어체입니다.',
                  "이 순간을 흠뻑 만끽하자! (감격 만끽 구동사)", "Go back to classroom.", "교실로 돌아가자는 악몽이에요.", "Cry in rain.", "비 맞고 울자는 엉뚱한 말이에요."),
        make_turn(8, "Chloe", "🎨", "Three whole months of summer vacation stretched right before our eyes! How do we celebrate day one?", "석 달간의 여름방학이 우리 눈앞에 쫙 펼쳐졌어! 오늘 첫날 어떻게 기념할래?",
                  '"오늘 밤에 같이 어울려 놀자!"라고 구동사 hang out을 써서 제안해보세요!', "Let's hang out tonight!",
                  "Bonfire, beach volleyball, and unlimited pizza! Meeting up at six PM sharp!", "모닥불에 비치발리볼, 무제한 피자 파티! 저녁 6시 정각에 바로 뭉쳐!",
                  '구동사 "hang out"은 친구들과 부담 없이 시간 보내며 어울릴 때 미국 청소년들이 가장 매일 쓰는 대표 구동사입니다.',
                  "오늘 밤에 같이 놀자! (친구 어울림 필수 구동사)", "Study for winter exams.", "겨울 시험 공부하자는 악몽이에요.", "Sit alone in dark.", "어둠 속에 혼자 앉아있자는 오답이에요.")
    ]),

    make_ep("t4_e7", "tier4", "비밀 고민 털어놓기", "📍 Episode 7/10: Bleacher Confessions", "sunset", [
        make_turn(1, "Jordan", "🏀", "Can I tell you something that I haven't even told my older brother yet?", "우리 친형한테도 아직 말 안 한 비밀인데, 너한테 하나 털어놔도 돼?",
                  '"우리 둘만의 비밀로 지켜줄게, 말해봐."라고 귀를 기울여보세요!', "Between you and me.",
                  "Promise not to laugh? I've been feeling super overwhelmed about college tryouts.", "웃지 않는다고 약속해 줘. 나 사실 대학 입시 트라이아웃 때문에 부담감 엄청 심해.",
                  '비밀이나 속마음을 나누기 전 "우리 둘만의 비밀이다"라고 보안을 걸어둘 때 쓰는 관용구입니다.',
                  "우리 둘만의 비밀이야, 털어놔 봐. (신뢰의 약속)", "Tell the principal.", "교장선생님께 이르라는 오답이에요.", "I will post on Instagram.", "인스타에 올린다는 배신이에요."),
        make_turn(2, "Jordan", "🏀", "Everyone thinks I have it all together, but some nights I can't even sleep.", "다들 내가 아무 걱정 없는 줄 아는데, 어떤 날 밤엔 잠도 제대로 안 와.",
                  '"겉으로 티가 안 나서 몰랐네."라고 따뜻하게 공감해주세요!', "Never would have guessed.",
                  "I put on a confident face at practice, but the pressure feels like a boulder on my neck.", "훈련할 때는 자신 있는 척 표정 짓는데, 압박감이 목덜미에 얹힌 바위처럼 무거워.",
                  '겉보기와 다른 상대방의 속마음을 듣고 "전혀 짐작도 못 했다"며 놀라움과 위로를 건넬 때 씁니다.',
                  "전혀 짐작도 못 했어. (따뜻한 이해)", "You look terrible.", "너 꼴 보기 싫다는 상처 주는 말이에요.", "Stop complaining.", "투덜대지 말라는 냉정한 반응이에요."),
        make_turn(3, "Jordan", "🏀", "What if I miss the cut and let the whole team down?", "내가 만약 컷오프에서 탈락해서 팀 전체를 실망하게 하면 어떡하지?",
                  '"너무 자책하지 마, 넌 충분히 잘하고 있어."라고 다독여주세요!', "Don't be hard on yourself.",
                  "You have no idea how badly I needed to hear someone say that.", "누군가 나한테 그 말 해주는 게 얼마나 절실했는지 넌 모를 거야.",
                  '스스로를 몰아세우며 자책하는 친구에게 "너무 스스로에게 가혹하게 굴지 마"라고 보듬어주는 표현입니다.',
                  "스스로를 너무 몰아세우지 마. (따뜻한 보듬음)", "Be harder on yourself.", "더 몰아세우라는 매정한 말이에요.", "You will definitely fail.", "망할 거라는 악담이에요."),
        make_turn(4, "Jordan", "🏀", "You really think I still have a legit shot at making varsity?", "너 진짜 내가 주전 1군 팀에 들어갈 실력이 된다고 진심으로 생각해?",
                  '"난 언제나 네 편이야, 기억해!"라고 든든한 아군이 되어주세요!', "I'm always in your corner.",
                  "Having you say that means the absolute world to me right now.", "네가 그렇게 말해주니까 진짜 온 세상 얻은 것처럼 힘이 난다.",
                  '권투 링의 코너에서 선수를 지키는 세컨드처럼 "난 무조건 네 편이고 널 지지해"라는 최고의 의리 표현입니다.',
                  "난 언제나 네 편이야! (든든한 아군 선언)", "Stand in the corner.", "구석에 서서 벌 서라는 오역이에요.", "You are completely alone.", "넌 혼자라는 매정한 말이에요."),
        make_turn(5, "Jordan", "🏀", "Just saying all this out loud to someone who actually gets it feels so much better.", "내 마음 진짜 알아주는 너한테 다 털어놓고 나니까 훨씬 살 것 같아.",
                  '"가슴에 얹혀있던 짐이 싹 내려갔네!"라고 함께 안도해보세요!', "Weight off my chest.",
                  "Literally like twenty pounds of heavy anxiety just lifted off my lungs!", "진짜 폐를 짓누르던 10킬로짜리 불안감이 싹 걷힌 기분이야!",
                  '고민을 털어놓거나 문제를 해결한 뒤 속이 후련해졌을 때 쓰는 시원한 표현입니다.',
                  "가슴의 짐이 싹 내려갔어! (후련한 안도)", "Put heavy bricks on chest.", "가슴에 벽돌 얹으라는 반대말이에요.", "My chest hurts.", "가슴 아프다는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "We're hitting the practice field tomorrow together! You and me till the end!", "우리 내일 연습 구장 같이 뛰자! 너랑 나랑 끝까지 함께 가는 거다!",
                  '"우린 죽을 때까지 함께할 찐친이야!"라고 우정을 확인하세요!', "Ride or die friend.",
                  "Ride or die forever! Next season the varsity coach won't be able to ignore us!", "평생 함께할 찐친이지! 다음 시즌엔 코치님도 우릴 절대 외면 못 할걸!",
                  '어떤 역경이나 시련이 와도 끝까지 의리를 지키며 함께할 진정한 단짝을 뜻하는 슬랭입니다.',
                  "우린 평생 함께할 찐친이야! (불변의 찐친 우정)", "Die alone.", "혼자 죽으라는 저주예요.", "I don't know you.", "너 모른다는 남남 반응이에요."),
        make_turn(7, "Jordan", "🏀", "Next season tryouts are in five months. I'm hitting the weight room starting tomorrow morning!", "다음 시즌 트라이아웃 다섯 달 남았어. 나 내일 아침부터 당장 웨이트 트레이닝 들어갈 거야!",
                  '"절대 포기하지 마!"라고 구동사 give up을 써서 힘을 실어주세요!', "Never give up!",
                  "Never! We're gonna run sprints and dribble cones together until I'm un-cuttable! Let's do this!", "절대 안 포기해! 탈락시키려야 탈락시킬 수 없을 때까지 너랑 같이 전력 질주하고 콘 드리블 훈련할 거다! 가자!",
                  '구동사 "give up"은 "포기하다"라는 뜻으로, "Never give up!(절대 포기하지 마!)"은 시련을 이겨낼 때 나누는 최고의 의리 표현입니다.',
                  "절대 포기하지 마! (불굴의 의지 대표 구동사)", "Give up right now.", "지금 당장 포기하라는 초 치기예요.", "Quit all sports.", "운동 다 때려치우라는 악담이에요."),
        make_turn(8, "Jordan", "🏀", "6 AM conditioning starts tomorrow morning on the track! You really down to spot me?", "내일 아침 6시에 트랙 체력 훈련 바로 시작이야! 너 진짜 나 서포트해 줄 준비 됐지?",
                  '"나만 믿어!"라고 구동사 count on을 써서 든든하게 화답해보세요!', "Count on me!",
                  "Set two alarms! We're gonna run those bleachers until sunrise! You're a true brother!", "알람 두 개 맞춰놔! 일출 볼 때까지 스탠드 계단 전력 질주하는 거다! 넌 진짜 의리 넘치는 형제야!",
                  '구동사 "count on [someone]"은 상대방을 "믿다/기대하다"라는 뜻으로 깊은 신뢰를 주고받을 때 쓰는 필수 구동사입니다.',
                  "나만 믿어! (신뢰와 의리의 필수 구동사)", "Count to ten.", "10까지 세라는 오답이에요.", "Never wake up.", "영원히 일어나지 말라는 오답이에요.")
    ]),

    make_ep("t4_e8", "tier4", "콘서트 티켓팅 성공", "📍 Episode 8/10: Front Row Ticket Drop", "mall", [
        make_turn(1, "Chloe", "🎨", "Ten seconds on the ticket queue! Refresh button is turning blue!", "티켓팅 대기열 10초 카운트다운! 새로고침 버튼 파란색으로 바뀌고 있어!",
                  '"심장 터질 것 같아, 로딩 돌아간다!"라고 발을 동동 굴러보세요!', "Heart is pounding!",
                  "It loaded! Section A Row 1 floor seats are flashing in green!", "새로고침 됐다! 플로어 A구역 1열 좌석이 초록색으로 깜빡거려!",
                  '극도의 긴장과 설렘으로 심장이 쿵쾅거릴 때 직관적으로 내뱉는 긴박한 표현입니다.',
                  "심장 터질 것 같아! (극도의 긴장감)", "Heart is stopped.", "심장 멎었다는 사망 선고예요.", "Tickets are useless.", "티켓 쓸모없다는 딴소리예요."),
        make_turn(2, "Chloe", "🎨", "Click complete purchase! Payment approved! ORDER CONFIRMED!", "결제 완료 클릭! 승인 떨어졌다! 예약 확정!",
                  '"가보자고! 나이스! 소리 질러!"라고 포효해보세요!', "Let's gooo!",
                  "WE GOT FRONT ROW PIT TICKETS! WE'RE GONNA BE THREE FEET FROM THE STAGE!", "우리 스탠딩 맨 앞줄 잡았어! 무대에서 딱 1미터 코앞이야!",
                  '승리나 대박 성공의 순간에 "가보자고! 나이스!" 하며 길게 늘여 지르는 10대들의 대표 환호성입니다.',
                  "가보자고! 나이스! (승리의 포효)", "Walk away slowly.", "천천히 걸어가라는 오역이에요.", "I want a refund.", "환불해달라는 엉뚱한 말이에요."),
        make_turn(3, "Chloe", "🎨", "I'm looking at the digital barcode on my screen right now in disbelief!", "내 폰 화면에 뜬 디지털 바코드 보면서도 아직 안 믿겨!",
                  '"이거 꿈 아니지? 진짜 실화 맞지?"라고 뺨을 꼬집어보세요!', "Is this real life?",
                  "Completely real! Not a glitch, not a drill, our names are printed on it!", "완전 진짜 실화! 오류도 아니고 훈련도 아니고 우리 이름 딱 박혔어!",
                  '믿기지 않는 행운을 마주했을 때 멍하니 감격하며 묻는 관용적 질문입니다.',
                  "이거 진짜 실화 맞지? (꿈같은 행운 확인)", "Life is a simulation.", "시뮬레이션이라는 음모론이에요.", "Go back to sleep.", "다시 자라는 엉뚱한 말이에요."),
        make_turn(4, "Chloe", "🎨", "My fingers won't stop twitching over the keypad haha!", "키패드 위에서 내 손가락이 떨려서 멈추질 않아 ㅋㅋㅋ!",
                  '"나 지금 온몸이 떨려!"라고 벅찬 흥분을 고백해보세요!', "My hands are shaking!",
                  "Same! My adrenaline is spiking through the roof of this coffee shop!", "나도 그래! 이 카페 천장 뚫을 정도로 아드레날린 폭발하고 있어!",
                  '감격이나 충격으로 흥분이 가라앉지 않을 때 신체적 떨림을 전하는 자연스러운 표현입니다.',
                  "나 지금 손 떨려! (벅찬 흥분 고백)", "Stop shaking hands.", "악수 멈추라는 오역이에요.", "Drink hot water.", "뜨거운 물 마시라는 딴소리예요."),
        make_turn(5, "Chloe", "🎨", "We have to memorize every single bridge lyric for the acoustic encore!", "어쿠스틱 앵콜 곡 브릿지 파트 가사 한 글자도 안 틀리고 다 외워 가야 해!",
                  '"오늘 밤 목 쉴 때까지 떼창각이다!"라고 결의를 다져보세요!', "Lost our voices tonight!",
                  "Singing every word at the top of our lungs until our vocal cords give out!", "목청 다 터질 때까지 목 터져라 전곡 떼창하는 거야!",
                  '콘서트나 페스티벌에서 목이 쉴 때까지 떼창하고 열광하겠다고 선언할 때 쓰는 표현입니다.',
                  "목 쉴 때까지 떼창각! (열광의 떼창 선언)", "Be completely silent.", "완전 침묵하라는 도서관 모드예요.", "I don't know the songs.", "노래 모른다는 고백이에요."),
        make_turn(6, "Chloe", "🎨", "Friday night at the arena with our favorite band under the strobe lights!", "금요일 밤 스트로브 조명 아래서 최애 밴드와 함께하는 경기장 콘서트!",
                  '"우리 인생 최고의 밤이 될 거야!"라고 축배를 들어보세요!', "Best night of our lives!",
                  "Countdown starts now! Best concert squad ever assembled!", "카운트다운 지금 시작이다! 역사상 최고의 콘서트 원정대 결성!",
                  '인생에 길이 남을 황홀한 순간을 맞이하며 건네는 극상의 찬사입니다.',
                  "우리 인생 최고의 밤이야! (황홀한 찬사)", "Worst night ever.", "최악의 밤이라는 악담이에요.", "Stay home forever.", "집에만 박혀있으라는 저주예요."),
        make_turn(7, "Chloe", "🎨", "The concert arena parking gets backed up for three miles on tour nights!", "콘서트 날 경기장 주차장 5킬로씩 밀려서 완전 꽉 막힌대!",
                  '"그날 일찍 출발하자!"라고 구동사 head out을 써서 작전을 세우세요!', "Let's head out early!",
                  "Smart move! We beat the traffic, grab merchandise shirts first, and claim the barricade!", "똑똑해! 차 막히는 거 피해서 굿즈 티셔츠 먼저 사고 스탠딩 펜스 바로 잡는 거야!",
                  '구동사 "head out"은 어딘가로 길을 나서거나 "출발하다"라는 의미로 원어민들이 약속을 잡을 때 매일 쓰는 표현입니다.',
                  "일찍 출발하자! (출발 계획 필수 구동사)", "Arrive midnight.", "자정에 도착하라는 헛소리예요.", "Cancel the tickets.", "티켓 취소하라는 망언이에요."),
        make_turn(8, "Chloe", "🎨", "Our alarms are set for 3 PM on concert Friday! What about the digital tickets on my phone?", "콘서트 금요일 3시 알람 맞춰뒀어! 내 폰에 든 디지털 티켓은 어떻게 해둘까?",
                  '"사본 백업해둬!"라고 구동사 back up을 써서 안전을 챙기세요!', "Back them up!",
                  "Screenshots saved and barcodes printed on paper just in case! We are 100% prepared!", "스크린샷 캡처해두고 만약을 대비해 바코드 종이 출력까지 완료! 우리 100% 준비 끝났다!",
                  '구동사 "back up"은 데이터나 티켓을 안전하게 "백업해 두다/사본을 만들어두다"라는 뜻의 필수 IT 및 생활 구동사입니다.',
                  "사본 백업해둬! (데이터 보관 필수 구동사)", "Delete the barcodes.", "바코드 삭제하라는 오답이에요.", "Throw phone away.", "폰 버리라는 오답이에요.")
    ]),

    make_ep("t4_e9", "tier4", "빈티지 패션 칭찬", "📍 Episode 9/10: Flea Market Vintage Glow-Up", "teenLocker", [
        make_turn(1, "Chloe", "🎨", "I thrifted this oversized 90s denim jacket over the weekend. How is it?", "주말에 구제 벼룩시장에서 90년대 오버핏 청자켓 건졌는데, 어때 보여?",
                  '"완전 찰떡이야, 찢었어!"라고 스타일을 극찬해보세요!', "You ate that up!",
                  "Thank you! I was worried it looked too baggy around the cuffs!", "고마워! 소매 쪽이 너무 벙벙해 보일까 봐 살짝 걱정했거든!",
                  '"You ate that up" (또는 "Left no crumbs")은 스타일이나 퍼포먼스를 "완벽하게 찢었다, 소화했다"는 최신 Z세대 찬사입니다.',
                  "완전 찰떡이야, 찢었어! (스타일 완벽 소화 극찬)", "Do not eat denim.", "청바지 먹지 말라는 직역 오역이에요.", "Clothes are expensive.", "옷 비싸다는 딴소리예요."),
        make_turn(2, "Chloe", "🎨", "It was only twelve dollars in the vintage bin behind the downtown diner!", "시내 다이너 식당 뒤편 빈티지 바구니에서 단돈 12달러 주고 건졌어!",
                  '"완전 거저 얻었네, 꿀득템이다!"라고 감탄해보세요!', "What a steal!",
                  "Right? The brass buttons and washed denim wash are totally authentic!", "그치? 황동 단추랑 워싱 빠진 청 데님 느낌이 진짜 오리지널 빈티지잖아!",
                  '터무니없이 싼 가격에 엄청난 득템을 했을 때 외치는 대표적인 관용구입니다.',
                  "완전 거저네, 꿀득템이다! (횡재 감탄)", "You committed a crime.", "범죄 저질렀다는 오역이에요.", "I never go shopping.", "쇼핑 안 한다는 딴청이에요."),
        make_turn(3, "Chloe", "🎨", "The distressed collar and the cropped hem sit right at the hip line!", "목 부분 빈티지 헤짐이랑 크롭 기장이 딱 골반 라인에 걸쳐져!",
                  '"부스러기 하나 없이 완벽 소화했어!"라고 감탄을 더해보세요!', "Left no crumbs!",
                  "Haha, you know the exact fashion vocabulary to make my day!", "하하 네가 패션 용어 딱딱 집어서 칭찬해주니까 오늘 기분 째진다!",
                  '"Left no crumbs"는 "남긴 부스러기조차 없이 완벽하게 먹어치웠다/소화했다"는 최고의 트렌드 표현입니다.',
                  "부스러기 없이 완벽해! (최고의 스타일 칭찬)", "Sweep the floor.", "바닥 쓸라는 엉뚱한 오역이에요.", "Eat a sandwich.", "샌드위치 먹으라는 딴소리예요."),
        make_turn(4, "Chloe", "🎨", "I paired it with high-waisted beige cargo pants and retro skate high-tops!", "하이웨이스트 베이지 카고 팬츠에 레트로 스케이트 하이탑으로 매치했어!",
                  '"완전 구제 패션 아이콘이다!"라고 패션 감각을 치켜세워주세요!', "Thrifted fashion icon.",
                  "You're making me blush! Maybe I should start a vintage fashion blog!", "나 부끄럽잖아! 진짜 빈티지 패션 블로그 하나 팔까 봐!",
                  '감각적인 스타일링을 뽐내는 친구에게 "패션 아이콘"이라 칭하며 띄워주는 세련된 표현입니다.',
                  "구제 패션의 아이콘이야! (패션 감각 극찬)", "Throw clothes away.", "옷 버리라는 악담이에요.", "I have no mirror.", "거울 없다는 엉뚱한 말이에요."),
        make_turn(5, "Chloe", "🎨", "Look at the silhouette in the full-length locker mirror!", "사물함 전신거울에 비친 전체 실루엣 좀 봐봐!",
                  '"핏이 흠잡을 데 없이 완벽해!"라고 쐐기를 박아주세요!', "The fit is immaculate.",
                  "Ten out of ten! Best twelve dollars I ever spent in my entire life!", "10점 만점에 10점! 내 평생 쓴 12달러 중에 제일 보람차다!",
                  '"immaculate"은 티끌 하나 없이 정결하고 완벽하다는 뜻으로, 옷의 핏이나 스타일링이 무결점일 때 씁니다.',
                  "핏이 무결점 완벽해! (흠잡을 데 없는 핏)", "The fit is dirty.", "더럽다는 반대말이에요.", "Buy cheaper clothes.", "더 싼 옷 사라는 잔소리예요."),
        make_turn(6, "Chloe", "🎨", "I'm definitely hitting that flea market again next Saturday morning!", "다음 주 토요일 아침에 그 벼룩시장 무조건 또 털러 갈 거야!",
                  '"이 코디에 나 완전 꽂혔어!"라고 함께 신나해보세요!', "Obsessed with this look.",
                  "You're coming with me! We're gonna find you an epic vintage bomber jacket next!", "너도 나랑 같이 가는 거다! 다음엔 네 오버핏 빈티지 항공점퍼 같이 찾아줄게!",
                  '어떤 스타일이나 아이템이 너무 매력적이어서 마음을 빼앗겼을 때 쓰는 최신 하이틴 표현입니다.',
                  "이 코디에 완전 꽂혔어! (스타일 매료)", "I hate this look.", "싫다는 반대말이에요.", "Wear uniform only.", "교복만 입으라는 꼰대 반응이에요."),
        make_turn(7, "Chloe", "🎨", "There's also a retro suede fringe jacket on the back rack! Wanna try it for yourself?", "저기 뒤쪽 행거에 레트로 스웨이드 술 재킷도 하나 있어! 너도 한번 걸쳐볼래?",
                  '"얼른 한번 입어볼게!"라고 구동사 try on을 써서 화답해보세요!', "I'll try it on!",
                  "Looking like a 70s rockstar right now! We are officially the best-dressed duo in town!", "너 지금 완전 70년대 록스타 같아! 우리 공식적으로 동네에서 옷 제일 잘 입는 듀오 인정이다!",
                  '구동사 "try on"은 옷이나 모자, 신발 등을 사기 전에 직접 "착용해 보다/입어보다"라는 쇼핑 필수 구동사입니다.',
                  "얼른 한번 입어볼게! (의류 착용 시험 필수 구동사)", "Rip the sleeves.", "소매 찢으라는 나쁜 말이에요.", "Throw it in mud.", "진흙에 던지라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "You look like an album cover star in that suede fringe! The price tag says only fifteen bucks!", "너 그 스웨이드 재킷 입으니까 앨범 커버 모델 같아! 가격표 보니까 단돈 15달러래!",
                  '"당장 사자, 꿀득템이야!"라고 구동사 pick up을 써서 말해보세요!', "Let's pick it up!",
                  "Handing the cash to the vendor! Two vintage treasures bagged in one afternoon!", "상인분께 현금 건네기 완료! 반나절 만에 빈티지 보물 두 개나 득템 완료!",
                  '구동사 "pick up"은 물건을 집어 올리는 것뿐만 아니라 상점이나 시장에서 물건을 "사다/득템하다"라는 뜻으로 원어민들이 매일 사용합니다.',
                  "당장 득템하자! 사자! (쇼핑 및 구매 필수 구동사)", "Drop it in mud.", "진흙에 떨어뜨리라는 오답이에요.", "Rip the pockets.", "주머니 찢으라는 오답이에요.")
    ]),

    make_ep("t4_e10", "tier4", "방학 카운트다운", "📍 Episode 10/10: Summer Break Countdown", "teenLocker", [
        make_turn(1, "Jordan", "🏀", "Ten seconds until the final bell of the school year! Countdown with me!", "이번 학년 마지막 종 치기 10초 전! 카운트다운 같이 세자!",
                  '"진짜 실감 안 난다!"라고 벅찬 마음을 표현해보세요!', "It feels surreal!",
                  "Three, two, one... Summer vacation is officially here!", "셋, 둘, 하나... 드디어 여름방학 공식 시작이다!",
                  '꿈만 같거나 비현실적일 정도로 벅차오를 때 "실감이 안 나, 꿈같아"라는 고급 구어체입니다.',
                  "진짜 꿈같아, 실감 안 나! (벅찬 감정)", "It is a fake dream.", "가짜 꿈이라는 오답이에요.", "I like homework.", "숙제 좋다는 거짓말이에요."),
        make_turn(2, "Jordan", "🏀", "Three whole months of sun, beach, and zero alarms!", "알람 시계 없는 햇살과 해변의 석 달 방학이다!",
                  '"이 순간만을 기다렸어!"라고 환호해보세요!', "Living the dream!",
                  "We survived finals week! You crushed that math exam!", "기말고사 지옥에서 살아남았다! 너 수학 시험도 제대로 찢었잖아!",
                  '원하던 최고의 상황을 누리고 있을 때 "인생 살맛 난다, 꿈같은 순간이다"라고 자축하는 표현입니다.',
                  "살맛 난다, 꿈같은 순간이야! (최고의 자축)", "I am sleeping in bed.", "침대에서 잔다는 오역이에요.", "Summer is hot.", "덥다는 불평이에요."),
        make_turn(3, "Jordan", "🏀", "Honestly, I thought you were gonna ace it all along!", "솔직히 난 네가 수학 만점 받을 줄 진작부터 알고 있었어!",
                  '"그 정도까진 아니야!"라고 겸손하게 손사래를 쳐보세요!', "I wouldn't go that far!",
                  "Stop being humble! You're literally a math wizard!", "겸손 떨지 마! 너 솔직히 거의 수학 마법사 수준이었거든!",
                  '과한 칭찬에 "에이 그 정도까지는 아니야~" 하며 유쾌하게 겸손을 표할 때 쓰는 관용구입니다.',
                  "그 정도까진 아니야! (유쾌한 겸손)", "I walked very far.", "멀리 걸어갔다는 직역 오역이에요.", "Give me more tests.", "시험 더 달라는 망언이에요."),
        make_turn(4, "Jordan", "🏀", "So, beach bonfire party tonight at six! Are you coming?", "그래서 오늘 저녁 6시에 해변 모닥불 파티 할 건데! 올 거지?",
                  '"나 무조건 낄래!"라고 망설임 없이 답해보세요!', "Count me in!",
                  "Bring your bluetooth speaker! We need the best beats!", "블루투스 스피커 챙겨와! 최고의 비트가 필요하니까!",
                  '재미있는 모임이나 이벤트에 망설임 없이 참여하겠다고 손을 들 때 쓰는 만능 표현입니다.',
                  "나 무조건 낄래! (적극적 참여)", "Count numbers.", "숫자 세라는 엉뚱한 말이에요.", "Beach has sand.", "모래 있다는 설명이에요."),
        make_turn(5, "Jordan", "🏀", "I'll grab the s'mores kit and graham crackers. Can you bring cold soda?", "내가 스모어 키트랑 통밀 크래커 챙길 테니까, 시원한 탄산음료 좀 가져올래?",
                  '"음료수는 내가 쏠게!"라고 쿨하게 맡아보세요!', "It's on me!",
                  "You're a legend! See you at Sunset Beach!", "너 진짜 최고다! 이따 선셋 비치에서 만나!",
                  '자신이 비용이나 준비물을 시원하게 쏘겠다고 자청할 때 쓰는 멋진 호언장담입니다.',
                  "내가 쏠게! (시원한 한턱)", "Drink water only.", "물만 마시라는 짠돌이 말이에요.", "Soda is unhealthy.", "탄산음료 건강에 나쁘다는 잔소리예요."),
        make_turn(6, "Jordan", "🏀", "Don't be late or we'll start without you!", "늦지 마라, 안 그러면 너 빼고 먼저 시작한다!",
                  '"이따 거기서 봐!"라고 손을 흔들며 작별 인사를 건네보세요!', "Catch you later!",
                  "Peace out! Have the best summer ever!", "피스 아웃! 우리 인생 최고의 여름 보내자!",
                  '친구와 헤어질 때 "이따 봐, 나중에 봐" 하며 쿨하게 짓는 마지막 작별 인사입니다.',
                  "이따 거기서 봐! (쿨한 작별 인사)", "I am trapped inside.", "갇혔다는 공포스런 말이에요.", "School starts now.", "개학이라는 악담이에요."),
        make_turn(7, "Jordan", "🏀", "The trunk is packed with towels, speakers, and snacks! Everyone is in the car!", "트렁크에 비치타월, 스피커, 간식 다 실었다! 애들 다 차에 탔어!",
                  '"이제 신나게 출발하자!"라고 구동사 hit the road를 써서 외쳐보세요!', "Let's hit the road!",
                  "Blasting the playlist! Windows down, ocean breeze in our faces! Best summer begins NOW!", "플레이리스트 볼륨 업! 창문 다 내리고 바닷바람 맞으면서! 최고의 여름이 지금 시작된다!",
                  '구동사 "hit the road"는 여행이나 드라이브를 떠나며 "신나게 길을 나서다/출발하다"라는 대표적인 미국식 구어체입니다.',
                  "신나게 출발하자! (여행 출발 대표 구어체)", "Sleep in garage.", "차고에서 자라는 엉뚱한 말이에요.", "Break the steering wheel.", "핸들 부수라는 위험한 말이에요."),
        make_turn(8, "Jordan", "🏀", "The ocean breeze is blasting through the windows! What song starts the ultimate road trip playlist?", "바닷바람 창문 틈으로 쌩쌩 들어온다! 레전드 로드트립 플레이리스트 첫 곡으로 뭐 틀까?",
                  '"볼륨 크게 키워봐!"라고 구동사 turn up을 써서 외쳐보세요!', "Turn it up loud!",
                  "Bass maxed out, speakers shaking the doors! Hello summer vacation!", "베이스 최대로 올리고 스피커가 차 문을 흔든다! 안녕 여름방학!",
                  '구동사 "turn up"은 음악이나 볼륨을 "더 크게 키우다/올리다"라는 뜻으로 드라이브나 파티에서 매 순간 쓰이는 표현입니다.',
                  "볼륨 빵빵하게 키워! (음량 증폭 필수 구동사)", "Turn off all music.", "음악 다 끄라는 오답이에요.", "Break car speakers.", "스피커 부수라는 오답이에요.")
    ])
]
