"""Tier 3 Scenarios: Ages 11-13 (10 episodes x 8 turns = 80 turns)."""
from scenarios_common import make_ep, make_turn

t3 = [
    make_ep("t3_e1", "tier3", "보드게임 카페 제안", "📍 Episode 1/10: Boba & Board Games", "bubbleTea", [
        make_turn(1, "Maya", "🛹", "We're hitting the new boba spot after school! Who's coming with?", "방과 후에 새로 생긴 버블티 집 갈 건데! 같이 갈 사람 누구?",
                  '"완전 콜이지! 무조건 가!"라고 흔쾌히 응답해보세요!', "I'm totally down.",
                  "Sick! They have brown sugar boba and giant Jenga tables!", "대박! 거기 흑당 버블티랑 대형 젠가 보드게임 테이블도 있대!",
                  '미국 10대들이 어떤 제안이나 계획에 100% 적극 동의할 때 쓰는 대표 구어체입니다.',
                  "완전 콜이지! (적극적 수락)", "I am descending down.", "아래로 내려간다는 오역이에요.", "Boba is round.", "버블티 둥글다는 딴소리예요."),
        make_turn(2, "Maya", "🛹", "Awesome! I'll order a mango slushie with tapioca pearls!", "신난다! 난 타피오카 펄 넣은 망고 스무디 시켜야지!",
                  '"내가 쏠게! 오늘은 내가 사!"라고 쿨하게 외쳐보세요!', "It's on me.",
                  "Whoa, really? Are you sure? You don't have to do that!", "우와 진짜? 너 확실해? 굳이 안 그래도 되는데!",
                  '식사나 음료값을 자신이 대신 지불하겠다고 멋지게 나설 때 쓰는 관용구입니다.',
                  "내가 쏠게! (쿨한 한턱내기)", "It is on top of my head.", "내 머리 위에 있다는 직역이에요.", "Give me your credit card.", "카드 달라는 무례한 말이에요."),
        make_turn(3, "Maya", "🛹", "I mean, you bought snacks last Friday too! Are you really sure?", "아니 너 지난주 금요일에도 간식 샀잖아! 진짜 괜찮아?",
                  '"진짜 괜찮아, 맘 편히 먹어!"라고 안심시켜주세요!', "Don't sweat it.",
                  "You're the coolest friend in middle school! Thank you!", "너 우리 중학교에서 제일 쿨한 친구다! 고마워!",
                  '상대방이 미안해하거나 망설일 때 "걱정 마, 부담 갖지 마, 신경 꺼"라고 안심시키는 슬랭입니다.',
                  "신경 쓰지 마, 부담 갖지 마! (편안한 안심)", "Sweat heavily please.", "땀 뻘뻘 흘리라는 오역이에요.", "You owe me five bucks.", "돈 내놓으라는 말이에요."),
        make_turn(4, "Maya", "🛹", "Alright, then next week when we go to the taco truck, the tacos are all mine to buy!", "알았어, 그럼 다음 주 타코 트럭 갈 때는 내가 타코 싹 다 쏠게!",
                  '"다음엔 네가 쏴!"라고 웃으며 약속을 잡으세요!', "Next time is on you.",
                  "Deal! Double spicy beef tacos on my tab next Friday!", "콜! 다음 주 금요일엔 매콤 소고기 타코 내 카드로 긁는다!",
                  '상대방의 호의를 기분 좋게 핑퐁으로 주고받으며 다음 번을 기약할 때 쓰는 세련된 표현입니다.',
                  "다음엔 네가 쏴! (세련된 호의 핑퐁)", "Never buy anything.", "절대 사지 말라는 말이에요.", "Where is my wallet?", "지갑 없다는 당황이에요."),
        make_turn(5, "Maya", "🛹", "Meet by the flagpole right after the 3 PM bell rings?", "3시 종 치자마자 교문 국기 게양대 앞에서 만날까?",
                  '"그렇게 하자! 딱 좋다!"라고 약속을 확정하세요!', "Sounds like a plan!",
                  "Boom! Board games and boba at four PM sharp! See you there!", "좋았어! 정확히 4시에 버블티 마시며 보드게임 격파하자!",
                  '약속 시간과 장소가 확정되었을 때 "그 계획 완벽해, 그렇게 하자"며 확답하는 관용구입니다.',
                  "그렇게 하자! 딱 좋다! (완벽한 일정 확정)", "I reject this scheme.", "계획 거부한다는 딱딱한 말이에요.", "Class is canceled.", "수업 취소라는 엉뚱한 말이에요."),
        make_turn(6, "Maya", "🛹", "We finish school at 3 PM and boba opens right next door! What's the whole afternoon plan?", "3시에 학교 끝나고 버블티 집 바로 옆에 열어! 오후 전체 계획이 뭐야?",
                  '"방과 후에 같이 어울려 놀자!"라고 구동사 hang out을 써서 제안해보세요!', "Let's hang out after school!",
                  "Definitely! Boba, Uno tournaments, and good music all afternoon!", "무조건이지! 오후 내내 버블티 마시며 우노 보드게임 토너먼트 뜨자!",
                  '구동사 "hang out"은 친구들과 부담 없이 시간 보내며 어울려 놀 때 미국 10대들이 가장 기본적으로 쓰는 구동사입니다.',
                  "방과 후에 같이 놀자! (친구 어울림 대표 구동사)", "Let's fight outside.", "밖에서 싸우자는 엉뚱한 말이에요.", "Never talk again.", "다신 말하지 말라는 절교예요."),
        make_turn(7, "Maya", "🛹", "We're standing in front of the neon counter! The boba menu has forty different drinks!", "네온 카운터 앞에 섰어! 버블티 메뉴에 음료만 40가지나 있어!",
                  '"마음에 드는 거 하나 골라봐!"라고 구동사 pick out을 써서 말해보세요!', "Pick one out!",
                  "Taro milk tea with double brown sugar pearls! Ordering two right now!", "타로 밀크티에 흑당 펄 두 배 추가! 지금 바로 두 잔 주문 들어간다!",
                  '구동사 "pick out"은 여러 선택지 중에서 마음에 드는 것을 "고르다/선택하다"라는 뜻으로 쇼핑과 주문 시 매일 쓰입니다.',
                  "하나 골라봐! (선택과 결정의 필수 구동사)", "Spill the tea.", "차 엎지르라는 오답이에요.", "Drink tap water.", "수돗물 마시자는 오답이에요."),
        make_turn(8, "Maya", "🛹", "The boba cups are empty and our Uno tournament ended in a dramatic tie! The cafe lights are dimming!", "버블티 컵 다 비웠고 우노 대회는 극적인 무승부로 끝났어! 카페 조명 어둑해진다!",
                  '"이제 슬슬 나가자!"라고 구동사 head out을 써서 제안해보세요!', "Let's head out!",
                  "Grabbing my skateboard! Coasting down the sidewalk under the streetlights! Catch you tomorrow morning!", "스케이트보드 챙겼다! 가로등 불빛 아래 보도블록 타고 미끄러져 가자! 내일 아침에 봐!",
                  '구동사 "head out"은 모임이나 장소에서 자리를 털고 "출발하다/떠나다"라는 뜻으로 미국 10대들이 가장 쿨하게 쓰는 표현입니다.',
                  "이제 슬슬 나가자! (출발 필수 구동사)", "Break the cafe window.", "카페 창문 깨라는 오답이에요.", "Sleep on boba floor.", "바닥에서 자자는 오답이에요.")
    ]),

    make_ep("t3_e2", "tier3", "스케이트보드 묘기 성공", "📍 Episode 2/10: Skatepark Kickflip Landing", "skatepark", [
        make_turn(1, "Jordan", "🏀", "Check this out! I finally landed a clean kickflip off the curb!", "이것 좀 봐! 나 드디어 턱 위에서 킥플립 착지 깔끔하게 성공했어!",
                  '"대박 멋지다, 쩐다!"라고 환호해보세요!', "That's so sick!",
                  "Thanks! I scraped my shin like ten times before getting it right!", "고마워! 성공하기 전에 정강이 열 번은 긁혔잖아!",
                  '미국 10대들이 기술이나 스타일이 기가 막히게 멋질 때 "쩐다, 미쳤다"는 의미로 쓰는 대표 슬랭입니다.',
                  "대박 멋져, 쩐다! (기술 극찬)", "Go see a doctor.", "병원 가라는 직역 오역이에요.", "Skateboards are noisy.", "시끄럽다는 불평이에요."),
        make_turn(2, "Jordan", "🏀", "I almost chipped my board when it slammed the rail though...", "근데 보드가 난간에 쾅 부딪쳤을 때 앞코 깨질 뻔했어...",
                  '"신경 쓰지 마, 다 그런 거지!"라고 위로해보세요!', "Don't sweat it.",
                  "True, scratches just give a board character anyway! Let's drop into the bowl!", "맞아 기스 좀 나야 보드에 간지가 살지! 보울 코스로 뛰어들자!",
                  '상대방이 작은 실수나 손해에 아쉬워할 때 쿨하게 털어내도록 돕는 표현입니다.',
                  "신경 쓰지 마, 별거 아냐! (쿨한 위로)", "Sweat heavily.", "땀 흘리라는 오역이에요.", "Buy a golden board.", "금 보드 사라는 엉뚱한 말이에요."),
        make_turn(3, "Jordan", "🏀", "Watch this frontside ollie over the orange traffic cone!", "주황색 고깔콘 뛰어넘는 프론트사이드 알리 묘기 봐봐!",
                  '"실력 완전 늘었네, 대박이야!"라고 칭찬해주세요!', "You're killing it!",
                  "Hyped! All that weekend practice is finally paying off!", "신난다! 주말 내내 연습한 보람이 드디어 터지는구나!",
                  '어떤 분야나 무대에서 신들린 기량으로 맹활약할 때 "완전 찢었다, 찢고 있다"는 찬사입니다.',
                  "너 완전 찢었다! 대박이야! (역량 극찬)", "Stop killing people.", "살인 멈추라는 위험한 오역이에요.", "Where is my helmet?", "헬멧 찾는 딴소리예요."),
        make_turn(4, "Jordan", "🏀", "The sun is beating down! I'm grabbing ice water from the fountain!", "햇빛 쨍쨍 내리쬔다! 식수대에서 시원한 얼음물 좀 마시고 올게!",
                  '"나도 좀만 남겨줘!"라고 시원하게 부탁해보세요!', "Save me some!",
                  "I'll fill up both our bottles with ice cubes! Stay hydrated!", "우리 둘 물병에 얼음까지 가득 채워 올게! 수분 보충 필수!",
                  '음식이나 음료를 먹으러 가는 친구에게 "내 몫도 남겨둬"라고 편하게 부탁하는 표현입니다.',
                  "내 것도 좀 남겨줘! (친근한 나눔 요청)", "Save the planet.", "지구를 구하라는 엉뚱한 말이에요.", "Water is liquid.", "물은 액체라는 설명이에요."),
        make_turn(5, "Jordan", "🏀", "The skate park is clearing out, wanna stay for twenty more minutes?", "스케이트파크 애들 슬슬 빠지는데 20분만 더 타다 갈래?",
                  '"완전 찬성이지! 무조건 타자!"라고 외쳐보세요!', "I'm all for it.",
                  "Let's master the 180 spin before dusk sets in! Game on!", "해 지기 전에 180도 스핀 회전까지 마스터하고 가자! 드루와!",
                  '상대방의 연장 제안이나 계획에 흔쾌히 전적으로 동의할 때 쓰는 표현입니다.',
                  "완전 찬성이지! (전적인 동의)", "I am against games.", "게임 반대한다는 말이에요.", "It is midnight.", "자정이라는 엉뚱한 말이에요."),
        make_turn(6, "Jordan", "🏀", "That halfpipe curve is super steep! My knees are shaking a little bit!", "저 하프파이프 경사 진짜 가파르다! 무릎이 살짝 떨려!",
                  '"조금만 더 버텨봐, 포기하지 마!"라고 구동사 hang in there를 써서 응원해보세요!', "Hang in there!",
                  "Dropping in on three! One, two, three... WHOOOOOA! Landed both trucks clean!", "셋 셀 때 뛰어든다! 하나, 둘, 셋... 우와아아! 바퀴 축 둘 다 깔끔하게 착지 성공!",
                  '구동사 "hang in there"는 두렵거나 힘든 상황을 버텨내야 할 때 "포기하지 말고 버텨!"라고 외치는 1위 응원 표현입니다.',
                  "조금만 버텨봐, 힘내! (인내와 격려의 필수 구동사)", "Fall off the rail.", "난간에서 떨어지라는 악담이에요.", "Give up right now.", "당장 포기하라는 김빠지는 소리예요."),
        make_turn(7, "Jordan", "🏀", "The concrete ledge is chipped and there's a loose rusty screw near the transition!", "콘크리트 턱 모서리가 깨졌고 경사면 근처에 녹슨 나사 하나 튀어나와 있어!",
                  '"발밑 잘 보고 피해!"라고 구동사 watch out을 써서 경고해보세요!', "Watch out for that!",
                  "Ollied right over the rusty screw! That could have shredded my urethane wheels!", "녹슨 나사 위로 훌쩍 알리 뛰었어! 바퀴 우레탄 싹 다 찢어질 뻔했네!",
                  '구동사 "watch out for ~"는 장애물이나 위험을 발견했을 때 "조심해!"라고 경각심을 일깨우는 필수 구동사입니다.',
                  "저거 조심해! (위험 경고 필수 구동사)", "Crash into the wall.", "벽에 들이받으라는 오답이에요.", "Break the skateboard.", "보드 부러뜨리라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "My kickflips are landing clean on the curb! But look, my right shoelace came completely untied!", "턱 위에서 킥플립 착지 깔끔해! 근데 봐봐, 오른쪽 신발 끈이 완전히 풀렸어!",
                  '"신발 끈 다시 묶어!"라고 기본동사 tie를 써서 당부해보세요!', "Tie your shoes!",
                  "Double knot tied tight! Dropping into the halfpipe with zero tripping hazard! Watch this high air!", "두 번 꽉 묶었다! 걸려 넘어질 위험 0%로 하프파이프 진입! 이 높은 에어 기술 좀 봐!",
                  '기본동사 "tie"는 끈이나 매듭을 "묶다"라는 뜻으로 "Tie your shoes!"(신발 끈 묶어!)는 운동할 때 매일 쓰는 표현입니다.',
                  "신발 끈 묶어! (매듭 묶기 필수 기본동사)", "Cut off shoelaces.", "신발 끈 자르라는 오답이에요.", "Skate without shoes on glass.", "유리 위에서 맨발로 타라는 오답이에요.")
    ]),

    make_ep("t3_e3", "tier3", "과학 화산 실험 대성공", "📍 Episode 3/10: Volcano Chemistry Blast", "classroom", [
        make_turn(1, "Maya", "🛹", "Ready with the red food coloring and baking soda mix?", "빨간 식용색소랑 베이킹소다 혼합물 준비됐어?",
                  '"준비 완료, 가자!"라고 출격 신호를 보내세요!', "Good to go!",
                  "Three, two, one... Pour the vinegar into the crater now!", "셋, 둘, 하나... 분화구에 식초 지금 부어!",
                  '모든 준비가 완벽히 끝나 즉시 시작할 수 있음을 경쾌하게 알리는 표현입니다.',
                  "준비 완료, 가자! (완벽한 준비 신호)", "I am bad to go.", "말이 안 되는 엉뚱한 문장이에요.", "Science is red.", "과학은 빨갛다는 딴소리예요."),
        make_turn(2, "Maya", "🛹", "Whooooosh! Foamy red lava is bubbling three feet in the air!", "콰아아아! 거품 빨간 용암이 1미터 높이로 솟구쳐 오르고 있어!",
                  '"우리 완전히 대박 터뜨렸어!"라고 환호해보세요!', "We crushed it!",
                  "Look at the teacher's jaw drop! Guaranteed A-plus project!", "선생님 입 떡 벌어지신 것 좀 봐! 무조건 A+ 확정 프로젝트다!",
                  '과제나 시험, 발표를 완벽하게 성공시켰을 때 "우리가 찢었다/박살 냈다"며 자축하는 단어입니다.',
                  "우리 완전 대박 터뜨렸어! (성공 자축)", "We crushed paper.", "종이 구겼다는 오역이에요.", "I hate volcanoes.", "화산 싫다는 투정이에요."),
        make_turn(3, "Maya", "🛹", "Wait, the foam overflowed onto the lab table edge! Hand me paper towels!", "잠깐 거품 넘쳐서 실험대 모서리로 흐른다! 키친타월 좀 줘!",
                  '"내가 청소 도와줄게!"라고 의리를 발휘해보세요!', "I'll help clean up.",
                  "Fast teamwork! Not a single red drop touched the clean floor!", "환상의 팀워크! 깨끗한 바닥에 빨간 방울 하나도 안 닿았어!",
                  '난장판이 된 주변을 정리하고 치울 때 솔선수범하며 건네는 든든한 문장입니다.',
                  "내가 치우는 거 도울게! (든든한 청소 협동)", "Run away fast.", "도망치라는 얌체 같은 말이에요.", "Lick the vinegar.", "식초 핥으라는 엉뚱한 말이에요."),
        make_turn(4, "Maya", "🛹", "The teacher just stamped our lab report with the shiny gold star!", "선생님이 방금 우리 실험 보고서에 반짝이는 황금 별 도장 찍어주셨어!",
                  '"역시 우리야! 최고야!"라고 하이파이브를 쳐보세요!', "That's how we roll!",
                  "Best science duo in 7th grade! Science fair champions next!", "7학년 최강의 과학 듀오! 다음엔 과학 경진대회 제패다!",
                  '멋진 결과를 해내고 나서 "이게 바로 우리 스타일이지, 우린 원래 이렇게 잘해"라며 뽐내는 슬랭입니다.',
                  "이게 바로 우리 스타일이지! (자신감 뿜뿜)", "Rolling down hills.", "언덕 구른다는 직역 오역이에요.", "Science is boring.", "과학 지루하다는 불평이에요."),
        make_turn(5, "Maya", "🛹", "Our clay volcano looks so realistic with the dried red streaks!", "빨간 용암 자국 굳으니까 우리 찰흙 화산 진짜 실물 화산 같아!",
                  '"진짜 실물 같아, 찐이야!"라고 감탄해보세요!', "So legit!",
                  "We should definitely enter it into the district science fair next month!", "이거 다음 달 교육청 과학 박람회에 무조건 출품해야 해!",
                  '"legit(legitimate)"은 10대들이 어떤 것이 진짜 같고 퀄리티가 대단할 때 외치는 최애 슬랭입니다.',
                  "진짜 실물 같아! 찐이다! (퀄리티 극찬)", "Very illegal.", "불법이라는 반대말이에요.", "I want to sleep.", "자고 싶다는 딴소리예요."),
        make_turn(6, "Maya", "🛹", "The chemistry lab bell is ringing in two minutes! All test tubes must be washed and put away!", "화학 실험실 종 2분 뒤에 쳐! 모든 시험관 씻어서 제자리에 치워둬야 해!",
                  '"실험실 깨끗이 정리하자!"라고 구동사 clean up을 써서 말해보세요!', "Let's clean up the lab!",
                  "Beakers rinsed and rack dried! Mr. Henderson gave our station an A for lab safety!", "비커 헹구고 거치대 건조 끝! 헨더슨 선생님이 실험실 안전 점수 A 주셨어!",
                  '구동사 "clean up"은 실험이나 활동이 끝난 후 주변을 "청소하다/정돈하다"라는 뜻의 필수 표현입니다.',
                  "실험실 깨끗이 치우자! (정리정돈 필수 구동사)", "Smash all beakers.", "비커 다 깨라는 위험한 오답이에요.", "Pour acid on floor.", "바닥에 산 쏟으라는 범죄예요."),
        make_turn(7, "Maya", "🛹", "Look at the corner shelf! The golden volcano trophy for first place is sitting right there!", "구석 선반 좀 봐! 1등에게 주는 황금 화산 트로피가 바로 저기 올려져 있어!",
                  '"이것 좀 봐봐!"라고 구동사 check out을 써서 가리켜보세요!', "Check that out!",
                  "Solid brass with our names engraved! We officially won the middle school science blast!", "황동 메탈에 우리 이름 각인됐어! 우리가 중학교 과학 경진대회 공식 우승이다!",
                  '구동사 "check out"은 눈앞의 놀라운 대상이나 물건을 "확인하다/봐봐!"라고 주목시킬 때 매일 쓰는 표현입니다.',
                  "이것 좀 봐봐! (주목과 확인 필수 구동사)", "Don't look at it.", "보지 말라는 오답이에요.", "Break the trophy.", "트로피 부수라는 오답이에요."),
        make_turn(8, "Maya", "🛹", "The papier-mâché volcano exploded red foam everywhere! The plastic lab table is covered in vinegar drops!", "신문지 화산에서 빨간 거품 사방으로 튀었어! 플라스틱 실험대가 식초 방울로 뒤덮였네!",
                  '"실험대 깨끗이 닦아내자!"라고 구동사 wipe down을 써서 청소해보세요!', "Let's wipe it down!",
                  "Paper towels soaked up all the red foam! Spotless lab bench! First prize for our volcano chemistry squad!", "키친타월이 빨간 거품 싹 흡수했어! 티끌 하나 없는 실험대! 우리 화산 화학 분대 1등이다!",
                  '구동사 "wipe down"은 책상이나 카운터의 액체를 걸레/티슈로 "싹 닦아내다"라는 뜻의 필수 청소 구동사입니다.',
                  "실험대 깨끗이 닦아내자! (청소 및 닦기 필수 구동사)", "Lick up the red vinegar.", "식초 핥아 먹으라는 오답이에요.", "Pour vinegar on textbooks.", "교과서에 쏟으라는 오답이에요.")
    ]),

    make_ep("t3_e4", "tier4", "빈티지 후드티 쇼핑", "📍 Episode 4/10: Mint Hoodie Thrift Hunting", "thrift", [
        make_turn(1, "Jordan", "🏀", "Look at this rack of 90s vintage windbreakers! Straight heat!", "이 90년대 빈티지 바람막이 행거 좀 봐! 완전 힙하다!",
                  '"완전 내 스타일이야!"라고 눈을 반짝여보세요!', "Totally my style!",
                  "Right? Check out that pastel oversized mint hoodie on the third hanger!", "그치? 세 번째 옷걸이에 걸린 파스텔 민트색 오버핏 후드티 좀 봐봐!",
                  '자신의 취향과 패션 스타일에 완벽하게 들어맞을 때 외치는 감탄사입니다.',
                  "완전 내 스타일이야! (취향 저격)", "I dislike fashion.", "패션 싫다는 딴소리예요.", "Wind is blowing cold.", "바람 분다는 오역이에요."),
        make_turn(2, "Jordan", "🏀", "It says twenty dollars on the vintage yellow tag! What a steal!", "노란 빈티지 택에 20달러라고 적혀 있어! 완전 거저네!",
                  '"완전 득템이다! 거저야!"라고 가격에 감탄해보세요!', "What a steal!",
                  "Original retro embroidery for twenty bucks? Try it on right now!", "오리지널 복고풍 자수 박힌 게 20달러? 지금 당장 입어봐!",
                  '명품이나 좋은 물건을 믿기지 않을 만큼 싼 가격에 건졌을 때 외치는 대표 슬랭입니다.',
                  "완전 거저네! 대박 득템! (가성비 극찬)", "You are a thief.", "너 도둑이라는 무례한 말이에요.", "Money is green.", "돈 초록색이라는 딴소리예요."),
        make_turn(3, "Jordan", "🏀", "The fitting room mirror is free! Go test the fit and sleeve length!", "탈의실 거울 비었다! 핏이랑 소매 기장 어떤지 얼른 입어보고 와!",
                  '"핏 완전 딱 맞아!"라고 거울 앞에서 감탄해보세요!', "Fits like a glove!",
                  "Clean drop shoulder fit! You look like a retro pop star!", "깔끔한 드롭 숄더 오버핏! 너 완전 레트로 팝스타 같다!",
                  '옷이나 신발 사이즈가 몸에 맞춘 듯 한 치의 오차 없이 꼭 맞을 때 쓰는 관용구입니다.',
                  "완전 맞춤처럼 딱 맞아! (완벽한 핏)", "Glove is on hand.", "장갑 손에 꼈다는 직역이에요.", "Tear the hoodie.", "후드티 찢으라는 나쁜 말이에요."),
        make_turn(4, "Jordan", "🏀", "Are you taking it home today? The cashier line is short right now!", "오늘 이거 바로 업어갈 거야? 지금 계산대 줄 짧은데!",
                  '"무조건 사야지!"라고 단호하게 구매를 결정하세요!', "A must-buy.",
                  "Bring it to the counter! Best vintage thrift find of the entire season!", "계산대로 들고 가자! 이번 시즌 역대 최고의 빈티지 구제 득템이다!",
                  '놓치면 후회할 만큼 매력적인 아이템을 발견했을 때 "무조건 사야 해"라며 결단하는 표현입니다.',
                  "이건 무조건 사야 해! (확고한 구매 결정)", "Never buy clothes.", "옷 사지 말라는 말이에요.", "I have no dollars.", "돈 없다는 김빠지는 말이에요."),
        make_turn(5, "Jordan", "🏀", "Look at the front kangaroo pocket! It has a hidden zipper compartment!", "앞판 캥거루 주머니 봐봐! 숨겨진 히든 지퍼 수납공간도 있어!",
                  '"디테일 진짜 살아있네!"라고 세심한 디자인을 칭찬하세요!', "Love the details.",
                  "Hidden pocket for your earbuds and transit pass! Complete score!", "이어폰이랑 교통카드 넣기 딱 좋은 비밀 주머니! 완벽한 득템이다!",
                  '의류나 전자기기의 작은 디테일과 기능미를 보고 만족할 때 쓰는 세련된 표현입니다.',
                  "디테일 진짜 살아있네! (디테일 찬사)", "Hate everything.", "다 싫다는 악담이에요.", "Zippers are metal.", "지퍼 금속이라는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "Look at this retro leather bomber jacket! But is it too large for my shoulders?", "이 복고풍 가죽 봄버 재킷 봐봐! 근데 내 어깨에 너무 큰가?",
                  '"한번 입어봐!"라고 구동사 try on을 써서 권해보세요!', "Try it on!",
                  "Zipping it up in front of the mirror! Sleeves fall right at my wrists! It looks incredible!", "거울 앞에서 지퍼 올리는 중! 소매가 손목에 딱 떨어져! 완전 기가 막히게 어울린다!",
                  '구동사 "try on"은 옷, 신발, 모자 등을 구매 전 "입어보다/착용해보다"라는 뜻의 쇼핑 1위 구동사입니다.',
                  "한번 입어봐! (착용 권유 필수 구동사)", "Burn the jacket.", "재킷 태우라는 위험한 오답이에요.", "Throw in trash.", "쓰레기통에 버리라는 오답이에요."),
        make_turn(7, "Jordan", "🏀", "The vintage cash register is ringing up our mint hoodie! The cashier says total is $18.50 with student discount!", "빈티지 금전등록기에서 민트 후드티 바코드 찍혔어! 점원분이 학생 할인받아서 총 18.50달러래!",
                  '"얼른 계산하자!"라고 구동사 pay for를 써서 말해보세요!', "Let's pay for it!",
                  "Card tapped on the reader! Bagged in brown paper! Best vintage thrift hunt in town!", "단말기에 카드 탭 완료! 종이 쇼핑백에 쏙 담았어! 우리 동네 최고의 빈티지 쇼핑 성공!",
                  '구동사 "pay for"는 물건이나 음식의 대가를 "지불하다/계산하다"라는 뜻으로 매일 쓰는 기본 구동사입니다.',
                  "얼른 계산하자! (결제 및 구매 필수 구동사)", "Run away stealing.", "물건 훔쳐 달아나라는 오답이에요.", "Tear paper bag.", "쇼핑백 찢으라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "The oversized mint hoodie looks fire in the fitting room mirror! And the thrift clerk said it's 50% off today!", "탈의실 거울로 보니까 오버핏 민트 후드티 핏 완전 미쳤어! 게다가 점원분이 오늘 50% 반값 세일이래!",
                  '"계산하러 가자!"라고 구동사 check out을 써서 계산대로 가보세요!', "Let's check out!",
                  "Tossing it on the counter! Ten bucks for a vintage brand masterpiece! Best thrift jackpot ever!", "카운터에 턱 올렸다! 빈티지 브랜드 명작이 단돈 10달러! 역대급 구제 잭팟이다!",
                  '구동사 "check out"은 매장 계산대에서 상품을 "결제하다/계산하다"라는 뜻으로 쇼핑할 때 무조건 쓰는 필수 구동사입니다.',
                  "계산하러 가자! (계산 및 결제 필수 구동사)", "Sprint out without paying.", "도둑질하라는 위험한 오답이에요.", "Tear the hoodie hood.", "모자 찢으라는 오답이에요.")
    ]),

    make_ep("t3_e5", "tier3", "이어폰 명곡 공유", "📍 Episode 3/10: Earbud Beat Drop", "earbuds", [
        make_turn(1, "Maya", "🛹", "Take my left earbud! Listen to this unreleased bass drop!", "내 왼쪽 이어폰 꽂아봐! 아직 미발매된 이 베이스 비트 드롭 좀 들어봐!",
                  '"나한테 넘겨줘!"라고 귀에 이어폰을 꽂아보세요!', "Pass it over.",
                  "Wait for the thirty-second mark... Bass build-up starting now!", "30초 구간까지 기다려봐... 베이스 빌드업 지금 시작된다!",
                  '이어폰이나 휴대폰, 물건을 건네받을 때 자연스럽게 쓰는 요청입니다.',
                  "이리 넘겨줘! (물건 전달 요청)", "Keep it away.", "멀리 치우라는 반대말이에요.", "Earbuds are plastic.", "이어폰 플라스틱이라는 딴소리예요."),
        make_turn(2, "Maya", "🛹", "BOOM! Deep sub-bass shaking your whole skull right now!", "쿵! 묵직한 서브 베이스가 지금 네 두개골을 울리지?!",
                  '"비트 미쳤다, 대박이다!"라고 리듬을 타보세요!', "This beat goes hard!",
                  "Told you! The producer dropped this secret mix at midnight!", "내가 뭐랬어! 프로듀서가 자정에 이 비밀 리믹스 깜짝 공개했잖아!",
                  '힙합이나 전자음악 비트가 강렬하고 미치도록 좋을 때 미국 10대들이 연발하는 극찬 슬랭입니다.',
                  "비트 완전 미쳤다! 쩐다! (비트 극찬)", "The music is too soft.", "음악 너무 부드럽다는 딴소리예요.", "Turn off sound.", "소리 끄라는 찬물이에요."),
        make_turn(3, "Maya", "🛹", "My older brother engineered the synth track in his bedroom studio!", "우리 오빠가 자기 방 스튜디오에서 이 신디사이저 트랙 직접 믹싱했어!",
                  '"진짜 천재네, 재능 대박이다!"라고 칭찬을 아끼지 마세요!', "Pure genius!",
                  "He's gonna be so hyped when I tell him you loved it!", "네가 극찬했다고 전해주면 우리 오빠 기분 날아갈걸!",
                  '상대방이나 창작자의 뛰어난 재능을 한마디로 극찬할 때 쓰는 명쾌한 감탄사입니다.',
                  "진짜 천재야! 대박이야! (재능 극찬)", "He has zero talent.", "재능 없다는 심한 악담이에요.", "I dislike synthesizers.", "신스 싫다는 투정이에요."),
        make_turn(4, "Maya", "🛹", "He's dropping the full mixtape on streaming this Friday at midnight!", "이번 주 금요일 자정에 스트리밍 사이트에 믹스테이프 전곡 푼대!",
                  '"바로 플레이리스트에 담을게!"라고 기대감을 드러내세요!', "Adding to my playlist!",
                  "Track number four has an electric guitar bridge that will melt your mind!", "4번 트랙에 일렉트릭 기타 브릿지 나오는데 뇌가 녹아내릴 거다!",
                  '좋은 노래를 발견했을 때 자신의 재생목록에 즉시 추가하겠다고 약속하는 표현입니다.',
                  "플레이리스트에 바로 추가할게! (재생목록 추가)", "Delete all music.", "음악 다 삭제하라는 오답이에요.", "Friday is far.", "금요일 멀다는 불평이에요."),
        make_turn(5, "Maya", "🛹", "Here, plug into both earbuds! The stereo sound panning is wild!", "여기 이어폰 양쪽 다 꽂아봐! 좌우 스테레오 입체 음향 공간감 장난 아냐!",
                  '"소리 빵빵하게 더 키워봐!"라고 볼륨을 올리라고 하세요!', "Turn up the volume!",
                  "Max volume! Feel that kick drum thump in your chest!", "최대 볼륨! 가슴을 쿵쿵 울리는 킥드럼 쿵쾅거림 느껴봐!",
                  '음악이나 영상 소리가 너무 좋아서 볼륨을 높여달라고 할 때 쓰는 대표 구어체입니다.',
                  "볼륨 더 키워봐! (볼륨 업 요청)", "Turn down the sound.", "소리 줄이라는 반대말이에요.", "Earbuds are broken.", "고장 났다는 엉뚱한 말이에요."),
        make_turn(6, "Maya", "🛹", "The song is over and the school bell is ringing! Unplug the earbuds!", "노래 끝나고 학교 수업 종 친다! 이어폰 얼른 뽑아!",
                  '"소리 볼륨 줄여!"라고 구동사 turn down을 써서 말해보세요!', "Turn it down!",
                  "Volume lowered to zero! Earbuds packed safe in the charging case! Ready for math class!", "볼륨 0으로 내렸다! 충전 케이스에 이어폰 안전하게 쏙 넣었어! 이제 수학 시간 준비 끝!",
                  '구동사 "turn down"은 음악이나 TV 볼륨을 "줄이다"라는 뜻으로 교실이나 공공장소에서 매일 씁니다.',
                  "소리 볼륨 좀 줄여! (볼륨 감소 필수 구동사)", "Scream at teacher.", "선생님께 소리 지르라는 오답이에요.", "Break the phone.", "폰 부수라는 나쁜 말이에요."),
        make_turn(7, "Maya", "🛹", "Listen to that acoustic guitar intro! It's whisper quiet, turn the dial up a little!", "통기타 인트로 들어봐! 소리 너무 작아서 속삭이는 것 같아, 다이얼 좀 올려봐!",
                  '"볼륨 좀 더 키워봐!"라고 구동사 turn up을 써서 말해보세요!', "Turn it up!",
                  "Cranking up the gain! Crisp nylon guitar strings ringing like crystal!", "볼륨 쭉 올리는 중! 맑은 기타 줄 소리가 크리스털처럼 울려 퍼진다!",
                  '구동사 "turn up"은 소리나 온도를 "높이다/키우다"라는 뜻으로 일상에서 가장 많이 쓰이는 구동사입니다.',
                  "볼륨 좀 더 키워봐! (볼륨 증가 필수 구동사)", "Mute forever.", "영원히 음소거하라는 오답이에요.", "Smash the speaker.", "스피커 부수라는 오답이에요."),
        make_turn(8, "Maya", "🛹", "Turn up that volume! Here comes the electric guitar bridge solo... Get ready for goosebumps!", "볼륨 더 올려봐! 일렉기타 브릿지 솔로 터진다... 소름 돋을 준비해!",
                  '"이 부분 잘 들어봐!"라고 기본동사 listen을 써서 집중시켜보세요!', "Listen to this!",
                  "Whoa, that guitar riff literally gave me chills! Adding this track to my permanent favorites playlist!", "우와, 저 기타 리프 진짜 온몸에 전율 돋았어! 이 곡 평생 즐겨찾기 플리에 바로 저장!",
                  '기본동사 "listen"을 활용한 "Listen to this!"(이것 좀 들어봐!)는 좋은 음악이나 흥미로운 이야기를 들려줄 때 가장 먼저 외치는 구어체입니다.',
                  "이 부분 잘 들어봐! (집중 경청 기본동사)", "Plug both ears tight.", "귀 꽉 틀어막으라는 오답이에요.", "Smash the earbuds.", "이어폰 부수라는 오답이에요.")
    ]),

    make_ep("t3_e6", "tier3", "사물함 비밀번호 멘붕", "📍 Episode 6/10: Locker Combo Emergency", "lockers", [
        make_turn(1, "Jordan", "🏀", "Panic mode! My metal dial lock won't click open! Math starts in four minutes!", "멘붕 터졌다! 내 다이얼 자물쇠가 딸깍 안 열려! 수학 4분 뒤에 시작인데!",
                  '"심호흡하고 침착해봐!"라고 친구를 진정시켜보세요!', "Take a deep breath.",
                  "Phew... Okay, inhaling. My hands were shaking so bad I misdialed!", "후우... 알았어 숨 들이쉬는 중. 손이 너무 떨려서 번호를 잘못 돌렸나 봐!",
                  '당황하고 흥분한 사람을 차분하게 달랠 때 건네는 가장 성숙하고 따뜻한 권유입니다.',
                  "심호흡하고 침착해! (차분한 진정)", "Scream louder.", "더 크게 소리 지르라는 패닉 유도예요.", "Math is easy.", "수학 쉽다는 약 올리기예요."),
        make_turn(2, "Jordan", "🏀", "Spin clockwise twice to clear it... What was my second number again?", "초기화하게 시계 방향으로 두 번 돌리고... 내 두 번째 숫자가 뭐였더라?",
                  '"천천히 차근차근 생각해봐."라고 기억을 유도해보세요!', "Think back slowly.",
                  "Right! It's twenty-four! My basketball jersey number!", "맞다! 24번이었어! 내 농구 유니폼 등번호!",
                  '잊어버린 기억이나 정보를 차분하게 되짚어보라고 격려할 때 쓰는 표현입니다.',
                  "천천히 떠올려봐. (기억 되살리기 유도)", "Hit head on metal.", "머리 쇠에 박으라는 위험한 말이에요.", "Locker is broken.", "사물함 고장 났다는 포기예요."),
        make_turn(3, "Jordan", "🏀", "Click! The latch finally popped open! Grab the blue binder on top!", "딸깍! 빗장 드디어 툭 열렸다! 저기 맨 위 파란 바인더 좀 꺼내줘!",
                  '"내가 꺼내줄게!"라고 신속하게 지원해주세요!', "I got your back.",
                  "Blue binder secured! Slam the locker door shut quick!", "파란 바인더 확보 완료! 사물함 문 쾅 닫아버려 얼른!",
                  '친구의 다급한 부탁에 "내가 든든하게 도와줄게/해줄게"라며 척척 해결하는 팀워크 표현입니다.',
                  "내가 챙겨줄게! (신속한 지원)", "Leave binder inside.", "바인더 두고 가라는 오답이에요.", "Break the locker door.", "문짝 뜯으라는 오답이에요."),
        make_turn(4, "Jordan", "🏀", "Two minutes till the tardy bell! We need to sprint across the main hall!", "지각 종 2분 남았다! 본관 복도 가로질러 전력 질주해야 해!",
                  '"달려, 서둘러!"라고 발걸음을 재촉해보세요!', "Make a run for it!",
                  "Sliding through the classroom door right on the bell! Safe!", "종 울리는 순간 교실 문으로 미끄러져 골인! 세이프다!",
                  '시간이 촉박할 때 "전력으로 달려보자/돌진하자"며 긴박하게 속도를 낼 때 쓰는 구어체입니다.',
                  "전력 질주하자! (긴박한 돌진)", "Walk very slowly.", "느릿느릿 걸으라는 지각 유도예요.", "Sleep in hallway.", "복도에서 자라는 엉뚱한 말이에요."),
        make_turn(5, "Jordan", "🏀", "Phew! Mr. Davis hasn't even opened his grade book yet!", "휴! 데이비스 선생님 아직 출석부 펼치지도 않으셨어!",
                  '"아슬아슬하게 통과했다!"라고 가슴을 쓸어내리세요!', "Clutch timing!",
                  "Zero tardy points on my record! You're my lifesaver buddy!", "내 생활기록부 지각 점수 0점 사수! 너 진짜 내 구세주다 친구야!",
                  '절체절명의 위기에서 극적으로 타이밍을 맞췄을 때 외치는 Z세대 찬사입니다.',
                  "진짜 기적 같은 타이밍이었어! (아슬아슬 세이프)", "Bad timing.", "최악의 타이밍이라는 반대말이에요.", "I hate watches.", "시계 싫다는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "I keep forgetting my three-digit locker combination every Monday morning!", "월요일 아침마다 세 자리 사물함 비밀번호를 자꾸 까먹어!",
                  '"폰에 적어둬!"라고 구동사 write down을 써서 해결책을 주세요!', "Write it down!",
                  "Saved in my phone's secret notes app! Never getting locked out on Monday again!", "휴대폰 비밀 메모장에 저장 완료! 이제 월요일마다 사물함 갇힐 일 절대 없어!",
                  '구동사 "write down"은 잊지 않기 위해 종이나 메모장에 "기록하다/적어두다"라는 뜻의 필수 구동사입니다.',
                  "적어둬, 메모해둬! (기록 및 메모 필수 구동사)", "Erase your brain.", "뇌를 지우라는 황당한 말이에요.", "Burn the locker.", "사물함 태우라는 범죄예요."),
        make_turn(7, "Jordan", "🏀", "The dial is stuck between numbers 18 and 19! Don't panic, we have three minutes!", "다이얼이 18번이랑 19번 사이에 살짝 걸렸어! 당황하지 마, 우리 아직 3분 있어!",
                  '"어떻게든 해결해보자!"라고 구동사 figure out을 써서 말해보세요!', "We can figure it out!",
                  "Wiggled the handle twice and turned to zero... CLICK! Door popped open! We solved it!", "손잡이 두 번 흔들고 0으로 돌렸더니... 딸깍! 문 열렸다! 우리가 해결해냈어!",
                  '구동사 "figure out"은 복잡한 문제나 비밀번호를 "알아내다/해결하다"라는 뜻으로 매일 쓰이는 핵심 구동사입니다.',
                  "우리 해결할 수 있어! (문제 해결 필수 구동사)", "Smash locker with hammer.", "망치로 부수라는 오답이에요.", "Cry in bathroom.", "화장실 가서 울라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "Click! The three-digit combo worked and the locker door swung open! But three thick algebra binders are sliding toward the edge!", "딸깍! 세 자리 번호 맞아서 사물함 문 활짝 열렸다! 근데 두꺼운 대수학 바인더 세 권이 모서리로 와르르 쏟아지려 해!",
                  '"떨어지지 않게 잡아!"라고 구동사 hold on to를 써서 챙겨보세요!', "Hold on to them!",
                  "Caught all three binders against my chest! Stacked neatly on the bottom shelf! Disaster averted!", "가슴으로 바인더 세 권 다 받아냈어! 아래 칸에 가지런히 정리 끝! 대참사 모면 성공!",
                  '구동사 "hold on to"는 떨어지거나 미끄러지는 물건을 "놓치지 않고 꽉 붙잡다"라는 뜻으로 위급한 순간마다 쓰입니다.',
                  "떨어지지 않게 잡아! (추락 방지 필수 구동사)", "Kick binders down hallway.", "복도로 바인더 차버리라는 오답이에요.", "Shred the homework.", "숙제 파쇄하라는 오답이에요.")
    ]),

    make_ep("t3_e7", "tier3", "급식 미스터리 고기", "📍 Episode 7/10: Mystery Meat Verdict", "cafeteria", [
        make_turn(1, "Chloe", "🎨", "Look at today's hot lunch special... What on earth is this gray patty?", "오늘의 특식 메뉴 좀 봐... 도대체 이 회색 고기 패티의 정체는 뭐지?",
                  '"비주얼 완전 의심스러운데..."라고 눈살을 찌푸려보세요!', "Looks suspicious.",
                  "Right? It wobbles like jello and smells like boiled socks!", "그치? 젤리처럼 출렁거리고 삶은 양말 냄새가 나!",
                  '외관이나 형태가 수상하고 께름칙할 때 미국 10대들이 직관적으로 내뱉는 한마디입니다.',
                  "완전 의심스러워 보여... (의심스러운 외관)", "Looks delicious.", "맛있어 보인다는 맹목적 오답이에요.", "I love gray meat.", "회색 고기 좋다는 이상한 말이에요."),
        make_turn(2, "Chloe", "🎨", "I dare you to take a bite! A single fork-full!", "너 한 입만 먹어봐라! 딱 포크 한 입만!",
                  '"절대 사양할게! 꿈도 꾸지 마!"라고 단호히 거절하세요!', "Hard pass.",
                  "Haha, wise choice! Even the cafeteria cat walked away from it!", "하하 현명한 선택! 길고양이도 냄새 맡고 그냥 지나치더라!",
                  '제안이나 음식을 일말의 망설임도 없이 단칼에 거절할 때 쓰는 세련된 슬랭입니다.',
                  "절대 사양할게! 완전 패스! (단호한 거절)", "I will eat all.", "다 먹겠다는 위험한 선택이에요.", "Give me ten forks.", "포크 열 개 달라는 딴소리예요."),
        make_turn(3, "Chloe", "🎨", "So what are we supposed to eat? My stomach is growling like a chainsaw!", "그럼 우리 이제 뭐 먹냐? 내 배에서 전기톱 소리 나는데!",
                  '"대신 감자튀김이나 먹자."라고 차선책을 골라보세요!', "Stick to fries.",
                  "Golden crispy curly fries never betray us! Three trays, please!", "황금빛 바삭한 케이준 감자튀김은 우릴 배신 안 하지! 세 접시 주세요!",
                  '위험한 모험 대신 안전하고 검증된 선택지를 고수하자고 할 때 쓰는 관용구입니다.',
                  "감자튀김이나 먹자. (안전한 차선책)", "Eat the plate.", "접시를 먹으라는 엉뚱한 말이에요.", "Starve forever.", "굶어 죽자는 극단적 말이에요."),
        make_turn(4, "Chloe", "🎨", "Wait, isn't there a snack vending machine in the west corridor?", "잠깐, 서쪽 복도에 스낵 자판기 있지 않아?",
                  '"복도 자판기 털러 가자!"라고 탈출구를 제안해보세요!', "Vending machine run.",
                  "Genius idea! I've got two crisp dollar bills in my pocket!", "천재적인 생각! 내 주머니에 빳빳한 1달러 지폐 두 장 있어!",
                  '간식을 사러 자판기나 편의점으로 급히 달려가는 것을 "run"을 붙여 표현하는 생활 영어입니다.',
                  "자판기 털러 가자! (간식 원정 제안)", "Break the vending machine.", "자판기 부수라는 범죄예요.", "Dieting is fun.", "다이어트 재밌다는 거짓말이에요."),
        make_turn(5, "Chloe", "🎨", "They just restocked the spicy cheese puffs and peach iced tea!", "방금 매콤 치즈 스낵이랑 복숭아 아이스티 꽉 채워 넣으셨대!",
                  '"나도 무조건 낄래!"라고 지갑을 챙겨 일어나세요!', "Count me in.",
                  "Race you to the hall! Lunch crisis solved with snacks!", "복도까지 달리기다! 점심 위기는 스낵으로 완벽 해결!",
                  '어떤 행동이나 모임에 빠짐없이 동참하겠다고 활기차게 선언하는 만능 표현입니다.',
                  "나도 무조건 낄래! (활기찬 동참 선언)", "Leave me alone.", "혼자 내버려 두라는 쌀쌀맞은 말이에요.", "I love broccoli.", "브로콜리 좋다는 거짓말이에요."),
        make_turn(6, "Chloe", "🎨", "The snack vending machine has delicious barbecue chips and cold soda!", "자판기에 맛있는 바비큐 감자칩이랑 시원한 탄산음료 가득 차 있어!",
                  '"얼른 뽑아먹자!"라고 기본동사 get을 써서 말해보세요!', "Let's go get some!",
                  "Dollar bills accepted! Crunchy chips dropped into the slot! Lunch is saved!", "지폐 투입 완료! 바삭한 칩이 슬롯으로 툭 떨어졌다! 점심 위기 탈출!",
                  '기본동사 "go"와 "get"이 결합한 "go get ~"은 음식이나 간식을 사러 가거나 가져올 때 가장 자연스럽게 쓰입니다.',
                  "얼른 사 먹으러 가자! (간식 획득 기본동사)", "Drop the coins.", "동전 떨어뜨리라는 오답이에요.", "Starve until dinner.", "저녁까지 굶자는 포기예요."),
        make_turn(7, "Chloe", "🎨", "We got two bags of barbecue potato chips and cold peach iced tea! The picnic table outside is open in the sunshine!", "바비큐 감자칩 두 봉지에 시원한 복숭아 아이스티 득템! 바깥 피크닉 테이블 햇살 아래 비어있어!",
                  '"저기 가서 자리 잡고 앉자!"라고 기본동사 take a seat을 써서 제안해보세요!', "Let's take a seat!",
                  "Cracking open the chips under the sun! Best outdoor lunch ever!", "햇살 아래서 감자칩 봉지 뜯기! 최고의 야외 점심이다!",
                  '기본동사 "take"를 활용한 "Take a seat!"(자리에 앉다)은 정중하고 자연스럽게 앉을 자리를 권하거나 잡을 때 쓰는 필수 표현입니다.',
                  "저기 자리 잡고 앉자! (착석과 휴식의 기본동사)", "Stand on table.", "식탁 위에 서라는 오답이에요.", "Throw chips away.", "감자칩 버리라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "That mystery meat tray is officially in the cafeteria disposal bin! But my stomach is still rumbling like thunder!", "의심스러운 회색 고기 식판 퇴식구에 버렸어! 근데 내 배에서 아직 천둥소리 난단 말이야!",
                  '"대신 다른 거 먹으러 가자!"라고 기본동사 get을 써서 제안해보세요!', "Let's get that instead!",
                  "Swapping over to the grilled chicken wrap stand! Fresh lettuce, toasted tortilla, crisis officially resolved!", "구운 치킨랩 매대로 바로 갈아탔다! 신선한 양상추에 또띠아 구이, 위기 공식 종결!",
                  '기본동사 "get"을 활용한 "Let\'s get that instead"(대신 저거 먹자/사자)는 대안을 선택할 때 매일 쓰는 실전 표현입니다.',
                  "대신 다른 거 먹으러 가자! (대안 선택 필수 기본동사)", "Eat napkins from dispenser.", "냅킨 씹어 먹자는 오답이에요.", "Starve until tomorrow.", "내일까지 굶자는 오답이에요.")
    ]),

    make_ep("t3_e8", "tier3", "방과 후 자전거 라이딩", "📍 Episode 8/10: Sunset Ridge Bike Climb", "sunset", [
        make_turn(1, "Jordan", "🏀", "The scenic hill trail is completely clear! Race to the lookout point!", "전망대 언덕 코스 길 뻥 뚫렸다! 저 위 쉼터까지 레이스 뜨자!",
                  '"따라올 수 있으면 따라와 봐!"라고 패기 있게 페달을 밟으세요!', "Catch me if you can!",
                  "Oh, you're kicking into high gear? Challenge accepted!", "오, 최고 기어로 변속했다 이거지? 도전 받아주지!",
                  '술래잡기나 자전거 대결에서 자신만만하게 앞서 나가며 외치는 도발 명대사입니다.',
                  "따라와 볼 테면 따라와 봐! (자신만만한 질주 도발)", "Stop my bicycle.", "자전거 멈추라는 오답이에요.", "It is raining cats.", "비 온다는 딴소리예요."),
        make_turn(2, "Jordan", "🏀", "This steep incline is brutal! My calves are on fire!", "여기 오르막길 경사 장난 아니다! 종아리 타들어 갈 것 같아!",
                  '"나 살짝 뒤처지고 있어!"라고 숨차게 고백해보세요!', "I'm lagging behind.",
                  "Drop down to gear one! Don't look at the summit, just pedal steady!", "1단 기어로 낮춰! 꼭대기 보지 말고 발만 꾸준히 굴려!",
                  '게임이나 달리기, 라이딩에서 페이스가 떨어져 뒤로 밀릴 때 쓰는 현대적인 표현입니다.',
                  "나 좀 뒤처지고 있어! (솔직한 페이스 고백)", "I am running computer.", "컴퓨터 돌린다는 엉뚱한 오역이에요.", "Bikes have wheels.", "바퀴 있다는 설명이에요."),
        make_turn(3, "Jordan", "🏀", "Here is a flat wooden bench under the big pine tree!", "여기 큰 소나무 아래 평평한 나무 벤치 하나 있다!",
                  '"잠깐 숨 좀 돌리자."라고 휴식을 제안해보세요!', "Take a breather.",
                  "Phew! Cold water never tasted so heavenly in my life!", "휴! 얼음물이 내 평생 이렇게 꿀맛인 적은 처음이다!",
                  '격렬한 운동이나 활동 도중 잠시 멈추고 숨을 고르며 쉴 때 건네는 자연스러운 권유입니다.',
                  "잠깐 숨 좀 돌리자. (편안한 휴식 권유)", "Stop breathing forever.", "숨 영원히 쉬지 말라는 위험한 말이에요.", "Throw away bicycle.", "자전거 버리라는 억지예요."),
        make_turn(4, "Jordan", "🏀", "Stand up and look over the railing towards the valley below!", "일어나서 저 난간 너머 아래 계곡 쪽 한번 내려다봐!",
                  '"언덕 올라온 보람이 진짜 있네!"라고 감탄해보세요!', "Worth the climb.",
                  "Totally! The orange and purple sunset clouds look painted!", "완전! 주황빛이랑 보랏빛 노을 구름이 그림 그려놓은 것 같아!",
                  '힘든 과정이나 고생 끝에 멋진 결과를 보았을 때 "올라온 보람이 있다"고 자축하는 말입니다.',
                  "올라온 보람이 있어! (노력의 가치 실감)", "Climbing was useless.", "올라온 거 헛수고라는 불평이에요.", "I hate mountains.", "산 싫다는 투정이에요."),
        make_turn(5, "Jordan", "🏀", "The whole city lights are starting to twinkle in the dusk!", "황혼 속에서 도시 전체 불빛들이 반짝거리기 시작했어!",
                  '"풍경 진짜 대박이다!"라고 노을을 바라보며 외치세요!', "What a view!",
                  "Golden hour perfection! Best bike ride of the entire year!", "골든 아워의 정석이다! 올해 최고의 자전거 라이딩이었어!",
                  '숨 막히게 아름다운 경치나 풍경을 마주했을 때 감탄을 쏟아내는 대표 관용구입니다.',
                  "풍경 진짜 대박이야! (절경 감탄)", "I cannot see anything.", "아무것도 안 보인다는 오답이에요.", "Close your eyes.", "눈 감으라는 엉뚱한 말이에요."),
        make_turn(6, "Jordan", "🏀", "The mountain air is getting pretty chilly, and the twilight streetlights are turning on!", "산 공기가 꽤 쌀쌀해지고, 땅거미 내려앉으면서 가로등이 켜지고 있어!",
                  '"이제 자전거 타고 내려가자!"라고 구동사 head down을 써서 말해보세요!', "Let's head down!",
                  "Flipping bike headlights on! Coasting smooth down the asphalt all the way home!", "자전거 전조등 ON! 아스팔트 길 타고 집까지 시원하게 미끄러져 내려가자!",
                  '구동사 "head down"은 특정 방향(아래쪽, 남쪽, 시내 등)을 향해 "내려가다/출발하다"라는 이동 구동사입니다.',
                  "이제 내려가자! (방향 이동 필수 구동사)", "Sleep on the hill.", "언덕에서 자라는 엉뚱한 말이에요.", "Crash the bicycle.", "자전거 박으라는 위험한 말이에요."),
        make_turn(7, "Jordan", "🏀", "We coasted all the way down the smooth hill into the neighborhood! But look, my front tire is a bit soft!", "완만한 언덕 타고 동네까지 시원하게 미끄러져 내려왔어! 근데 앞바퀴 타이어 공기가 살짝 빠졌네!",
                  '"공기 좀 가득 채우자!"라고 구동사 fill up을 써서 말해보세요!', "Let's fill it up!",
                  "Pumping air with the hand pump! Tire is rock solid and ready to roll again!", "휴대용 펌프로 공기 주입 완료! 타이어 완전 짱짱해져서 다시 쌩쌩 달릴 수 있어!",
                  '구동사 "fill up"은 공기, 연료, 물병 등을 "가득 채우다"라는 뜻으로 일상생활에서 매일 쓰이는 구동사입니다.',
                  "공기 가득 채우자! (주입 및 충전 필수 구동사)", "Flatten the tire.", "타이어 펑크 내라는 오답이에요.", "Leave bike in bush.", "자전거 풀숲에 버리라는 오답이에요."),
        make_turn(8, "Jordan", "🏀", "We pumped the front tire rock hard and the hill is behind us! But look, an ambulance is zooming up the avenue with sirens on!", "앞바퀴 빵빵하게 채웠고 언덕 다 내려왔어! 근데 저기 대로에서 구급차가 사이렌 울리며 올라온다!",
                  '"길가로 자전거 바짝 세우자!"라고 구동사 pull over를 써서 비켜주세요!', "Let's pull over!",
                  "Bikes parked safe on the sidewalk curb! Siren zoomed past! Safety first on two wheels!", "자전거 인도 턱에 안전하게 정차 완료! 사이렌 쌩 지나갔다! 자전거는 안전이 제일이지!",
                  '구동사 "pull over"는 자전거, 킥보드, 자동차를 도로변이나 갓길에 "정차하다/차를 대다"라는 뜻의 필수 운행 구동사입니다.',
                  "길가로 바짝 세우자! (갓길 정차 필수 구동사)", "Pedal directly into siren.", "사이렌으로 돌진하라는 위험한 오답이에요.", "Throw bike into river.", "자전거 강에 던지라는 오답이에요.")
    ]),

    make_ep("t3_e9", "tier3", "시험 전날 스터디 그룹", "📍 Episode 9/10: Pre-Exam Flashcard Sprint", "library", [
        make_turn(1, "Maya", "🛹", "Tomorrow is the big American History unit exam on three chapters!", "내일 3개 단원 분량의 미국 역사 단원 평가 큰 시험이야!",
                  '"나 스트레스 엄청 받아!"라고 솔직한 심정을 털어놓으세요!', "I'm stressed out.",
                  "Same here! My brain feels like a stuffed hard drive!", "나도 그래! 내 뇌가 용량 꽉 찬 외장하드 같아!",
                  '학업이나 일로 극심한 긴장과 부담감을 느낄 때 일상적으로 외치는 고백입니다.',
                  "나 스트레스 엄청 받아! (솔직한 부담 토로)", "I am very relaxed.", "엄청 여유롭다는 거짓말이에요.", "History was long ago.", "역사는 옛날이라는 딴소리예요."),
        make_turn(2, "Maya", "🛹", "Stressing won't help us memorize dates! We can conquer this together!", "스트레스받아 봤자 연도 외우는 데 도움 안 돼! 우리 같이 격파하자!",
                  '"우리 할 수 있어, 힘내자!"라고 서로를 다독여보세요!', "We got this.",
                  "That's what I needed to hear! Let's conquer the American Revolution first!", "바로 그 말이 듣고 싶었어! 일단 미국 독립혁명 파트부터 박살 내자!",
                  '어려운 시험이나 시합을 앞두고 "우린 해낼 수 있어"라고 용기를 북돋우는 최강의 응원 구호입니다.',
                  "우리 할 수 있어! (용기를 주는 응원)", "We will fail 100%.", "무조건 떨어진다는 패배주의예요.", "I don't care.", "상관없다는 무책임한 말이에요."),
        make_turn(3, "Maya", "🛹", "I prepared twenty index flashcards with questions on one side!", "한쪽에 질문 적어둔 인덱스 단어 카드 20장 만들어왔어!",
                  '"서로 깜짝 퀴즈 내주자!"라고 스터디 방식을 제안해보세요!', "Pop quiz each other.",
                  "Draw a card! Question one: What year was the Declaration of Independence signed?", "카드 뽑아봐! 1번 문제: 독립선언서가 서명된 연도는?",
                  '상대방과 문답식으로 기습 문제를 내며 실력을 점검할 때 쓰는 학습 구어체입니다.',
                  "서로 깜짝 퀴즈 내주자! (문답 퀴즈 제안)", "Tear up flashcards.", "카드 찢어버리라는 훼방이에요.", "Silence forever.", "영원히 침묵하라는 말이에요."),
        make_turn(4, "Maya", "🛹", "July 4th, 1776 in Philadelphia!", "1776년 7월 4일, 필라델피아에서 서명됨!",
                  '"정답 제대로 맞혔어, 완벽해!"라고 확인 도장을 찍어주세요!', "You nailed that answer.",
                  "Flawless! Card two: Who was the commander of the Continental Army? George Washington!", "완벽해! 2번 카드: 대륙군 총사령관은? 조지 워싱턴!",
                  '상대방이 질문에 한 치의 오차도 없이 똑 부러지게 정답을 맞혔을 때 칭찬하는 표현입니다.',
                  "정답 제대로 맞혔어! (완벽한 정답 확인)", "Wrong completely.", "완전 틀렸다는 거짓말이에요.", "Nobody knows history.", "아무도 모른다는 핑계예요."),
        make_turn(5, "Maya", "🛹", "We just recited all twenty cards backwards without a single hesitation!", "우리 방금 20장 카드 거꾸로 넘기면서도 한 번도 안 막히고 다 외웠어!",
                  '"시험 치를 준비 완전 완료!"라고 자신감을 뽐내보세요!', "Ready for battle!",
                  "Tomorrow's exam doesn't stand a chance against us! Sleep well tonight!", "내일 시험지는 우리 손에 박살 날 일만 남았다! 오늘 밤 푹 자자!",
                  '모든 준비를 완벽하게 마치고 결전의 날을 당당하게 맞이할 때 외치는 전의에 찬 구호입니다.',
                  "실전 준비 완료! (자신감 충천)", "I surrender tomorrow.", "내일 항복하겠다는 오답이에요.", "Cancel the school.", "학교 취소하라는 헛소리예요."),
        make_turn(6, "Maya", "🛹", "Our eyes are getting dry and we covered all twenty flashcard questions three times!", "눈도 뻑뻑해지고 플래시카드 20개 질문 세 번이나 전수 복습했어!",
                  '"오늘은 이만 정리하자!"라고 구동사 wrap up을 써서 제안해보세요!', "Let's wrap it up!",
                  "Packing up highlighters! A good night of sleep is our final secret weapon for an A!", "형광펜 정리 끝! 오늘 밤 푹 자는 게 만점 받는 마지막 비밀 무기야!",
                  '구동사 "wrap up"은 공부나 회의, 프로젝트를 만족스럽게 "마무리짓다/끝마치다"라는 뜻의 핵심 구동사입니다.',
                  "오늘은 이만 마무리하자! (학습 종료 필수 구동사)", "Study all night long.", "밤새우라는 무리한 말이에요.", "Rip the textbooks.", "교과서 찢으라는 나쁜 말이에요."),
        make_turn(7, "Maya", "🛹", "Everything is packed in our bags and our brains are fully prepped for the history test! Let's recharge!", "가방 정리 다 끝났고 우리 뇌도 역사 시험 준비 100% 완료됐어! 이제 재충전하자!",
                  '"푹 자고 쉬어!"라고 기본동사 get을 써서 따뜻하게 인사해보세요!', "Get some rest!",
                  "Eight hours of solid sleep tonight! We're gonna crush that history exam tomorrow morning!", "오늘 밤 8시간 꿀잠 자기! 내일 아침 역사 시험 완전 찢어버리자!",
                  '기본동사 "get"을 활용한 "Get some rest!"(푹 쉬어, 휴식 취해)는 시험이나 큰일을 앞둔 친구를 격려하고 배려할 때 매일 쓰는 표현입니다.',
                  "푹 자고 쉬어! (휴식 권유 필수 기본동사)", "Stay awake all night.", "밤새 깨어있으라는 오답이에요.", "Forget everything.", "다 까먹으라는 오답이에요."),
        make_turn(8, "Maya", "🛹", "Our flashcard stack is conquered and we know every single date from 1776 to 1783! Midnight is creeping close!", "플래시카드 뭉치 다 뗐고 1776년부터 1783년까지 연도 전수 암기 끝! 자정이 다가온다!",
                  '"푹 자둬!"라고 기본동사 get을 써서 숙면을 권해보세요!', "Get some sleep!",
                  "Closing laptop and setting alarm for 7 AM sharp! We're gonna ace this test tomorrow! Good night!", "노트북 덮고 알람 아침 7시 정각 맞춰놨어! 내일 시험 만점 가자! 잘 자!",
                  '기본동사 "get"과 sleep이 결합한 "Get some sleep!"(푹 자, 수면 좀 취해!)은 밤늦게 헤어질 때 건네는 가장 대중적인 인사말입니다.',
                  "푹 자둬! (숙면 권유 기본동사)", "Stare at the ceiling all night.", "밤새 천장 보라는 오답이에요.", "Rip textbooks into confetti.", "교과서 찢으라는 오답이에요.")
    ]),

    make_ep("t3_e10", "tier3", "주말 캠핑 불멍", "📍 Episode 10/10: Fireside S'mores & Lore", "campfire", [
        make_turn(1, "Chloe", "🎨", "The campfire wood is glowing red hot! The roasting sticks are ready!", "장작불 숯이 빨갛게 제대로 달아올랐어! 마시멜로 꼬치 준비 완료!",
                  '"마시멜로 봉지 좀 넘겨줘!"라고 부탁해보세요!', "Pass the marshmallows.",
                  "Catch! Don't let it touch the flames or it'll turn into charcoal!", "받아! 불꽃에 바로 닿게 하지 마, 안 그러면 시커먼 숯덩이 된다!",
                  '캠핑이나 식탁에서 재료나 음식을 건네달라고 요청할 때 쓰는 가장 편안한 문장입니다.',
                  "마시멜로 좀 넘겨줘! (재료 전달 요청)", "Keep them away.", "멀리 치우라는 반대말이에요.", "Fire is cold.", "불이 차갑다는 엉뚱한 말이에요."),
        make_turn(2, "Chloe", "🎨", "Hover it two inches above the embers and spin it slow like a rotisserie!", "숯불 5센티 위에 띄우고 전기구이 통닭처럼 살살 돌려봐!",
                  '"노릇노릇 완벽하게 구워졌다!"라고 감탄해보세요!', "Golden brown toast.",
                  "Perfection! Squeeze it between two graham crackers with dark chocolate!", "완벽해! 다크초콜릿이랑 통밀 크래커 사이에 넣고 꾹 눌러봐!",
                  '마시멜로나 토스트가 타지 않고 황금빛 갈색으로 기가 막히게 익었을 때 쓰는 미식 표현입니다.',
                  "노릇노릇 완벽하게 구웠어! (굽기 장인 감탄)", "Burnt black rock.", "새까맣게 탄 돌이라는 오답이에요.", "Throw it in water.", "물에 던지라는 낭비예요."),
        make_turn(3, "Chloe", "🎨", "Crunch! The melted chocolate is oozing out! Now that the mood is set...", "바삭! 녹은 초콜릿이 줄줄 흘러나와! 이제 분위기도 무르익었으니...",
                  '"무서운 괴담 이야기할 시간이야!"라고 으스스하게 운을 띄워보세요!', "Ghost story time.",
                  "Ooh, let me tell you about the Whispering Pine Cabin on this very ridge!", "오오, 바로 이 능선에 있던 '속삭이는 소나무 오두막' 괴담 내가 풀어줄게!",
                  '캠프파이어에 둘러앉았을 때 미국 아이들이 눈을 빛내며 외치는 전통적인 이벤트 선언입니다.',
                  "괴담 풀 시간이다! (캠프파이어 괴담 선언)", "Go to sleep immediately.", "즉시 자러 가라는 김빠지는 소리예요.", "Sing nursery rhymes.", "동요 부르자는 딴소리예요."),
        make_turn(4, "Chloe", "🎨", "...And every full moon, the antique rocking chair rocks all by itself!", "...그리고 보름달이 뜨는 날마다, 앤티크 흔들의자가 혼자서 삐걱거리며 흔들린대!",
                  '"진짜 온몸에 닭살 돋았어!"라고 몸을 부르르 떨어보세요!', "Gave me goosebumps!",
                  "Look at your arms, your hairs are standing on end haha!", "네 팔뚝 봐봐, 털이 바짝 곤두섰잖아 ㅋㅋㅋ!",
                  '무서운 이야기나 충격적인 반전을 듣고 실제로 소름이 돋았을 때 쓰는 가장 생생한 구어체입니다.',
                  "진짜 닭살 돋았어! 소름 쫙 끼쳤어! (오싹한 반응)", "Gave me geese.", "거위를 줬다는 엉뚱한 직역이에요.", "I feel very warm.", "따뜻하다는 딴청이에요."),
        make_turn(5, "Chloe", "🎨", "The sparks are drifting up into the Milky Way... It's so peaceful out here.", "불꽃 불씨들이 은하수 하늘로 흩날려 올라가... 여기 진짜 너무 평화롭다.",
                  '"진짜 아늑하고 힐링되는 분위기야."라고 편안한 밤을 음미해보세요!', "Cozy vibes.",
                  "Crackling logs and a sky full of shooting stars... Best campout ever!", "타닥타닥 타는 장작불에 별똥별 가득한 하늘... 인생 최고의 캠핑이야!",
                  '따뜻하고 편안하며 감성적인 힐링 무드를 한마디로 요약할 때 10대들이 가장 사랑하는 표현입니다.',
                  "진짜 아늑하고 힐링되는 분위기야. (감성적인 힐링)", "Horrible terrible mood.", "끔찍한 분위기라는 악담이에요.", "I hate camping.", "캠핑 싫다는 투덜거림이에요."),
        make_turn(6, "Chloe", "🎨", "The night breeze is blowing sparks toward the dry pine needles!", "밤바람이 마른 솔잎 쪽으로 불씨를 날리고 있어!",
                  '"불씨 완전히 꺼두자!"라고 구동사 put out을 써서 말해보세요!', "Put the fire out!",
                  "Pouring the water bucket over the embers! Hiss... completely extinguished and safe!", "숯불 위에 양동이 물 붓는 중! 치이익... 완전히 진화 완료, 안전해!",
                  '구동사 "put out"은 모닥불, 촛불, 담배 등의 불을 "끄다/진화하다"라는 뜻으로 캠핑과 안전에서 필수입니다.',
                  "불씨 완전히 꺼둬! (소화 및 진화 필수 구동사)", "Pour gasoline.", "휘발유 부으라는 위험천만한 말이에요.", "Run away leaving fire.", "불 두고 도망치라는 범죄예요."),
        make_turn(7, "Chloe", "🎨", "The campfire is completely cold and dark! The stars above our tent are shining like diamonds!", "모닥불 완전 차갑고 어둡게 꺼졌어! 우리 텐트 위로 별들이 다이아몬드처럼 빛나!",
                  '"텐트 안으로 들어가자!"라고 구동사 get in을 써서 말해보세요!', "Let's get in the tent!",
                  "Zipping up the mesh flap! Slipping into cozy sleeping bags under the stars!", "모기장 지퍼 쓱 잠그기! 별빛 아래 포근한 침낭 속으로 쏙 들어왔어!",
                  '구동사 "get in"은 방, 텐트, 자동차 등 안으로 "들어가다/타다"라는 뜻으로 하루에도 수십 번 쓰이는 최상위 빈도 구동사입니다.',
                  "텐트 안으로 들어가자! (진입 및 탑승 필수 구동사)", "Sleep in campfire ashes.", "재 속에서 자라는 위험한 오답이에요.", "Tear down tent.", "텐트 찢으라는 오답이에요."),
        make_turn(8, "Chloe", "🎨", "Campfire embers are doused, sleeping bags are unrolled, and the pine wind is howling outside the nylon walls!", "모닥불 불씨 싹 꺼졌고, 침낭 폈고, 텐트 벽 밖에서 솔잎 바람 쌩쌩 분다!",
                  '"텐트 지퍼 꼭 잠가!"라고 구동사 zip up을 써서 따뜻하게 봉인해보세요!', "Zip it up!",
                  "Zipped all the way down! Cozy, warm, and zero mosquitoes! Best night under the pine ridge stars!", "끝까지 지퍼 꽉 잠갔어! 아늑하고 따뜻하고 모기 0마리! 솔잎 능선 별빛 아래 최고의 밤이다!",
                  '구동사 "zip up"은 텐트, 재킷, 가방의 지퍼를 "끝까지 잠그다"라는 뜻의 초특급 생활 구동사입니다.',
                  "텐트 지퍼 꼭 잠가! (지퍼 잠그기 필수 구동사)", "Cut open the tent roof.", "텐트 지붕 찢으라는 오답이에요.", "Sleep out in the rain.", "비 맞으며 자라는 오답이에요.")
    ])
]
