"""Tier 3 Scenarios: Ages 11-13 (10 episodes x 6 turns = 60 turns)."""
from scenarios_common import make_ep, make_turn

t3 = [
    make_ep("t3_e1", "tier3", "보드게임 카페 제안", "📍 Episode 1/10: Boba & Board Games", "bubbleTea", [
        make_turn(1, "Maya", "🛹", "We're hitting the new boba spot after school! Who's coming with?", "방과 후에 새로 생긴 버블티 집 갈 건데! 같이 갈 사람 누구?",
                  '"완전 콜이지! 무조건 가!"라고 흔쾌히 응답해보세요!', "I'm totally down.",
                  "Sick! They have brown sugar boba and giant Jenga tables!", "대박! 거기 흑당 버블티랑 대형 젠가 보드게임 테이블도 있대!",
                  '미국 10대들이 어떤 제안이나 계획에 100% 적극 동의할 때 쓰는 대표 구어체입니다.',
                  "완전 콜이지! (적극적 수락)", "I am descending down.", "아래로 내려간다는 오역이에요.", "Boba is round.", "버블티 둥글다는 딴소리예요."),
        make_turn(2, "Maya", "🛹", "Awesome! I'll order a mango slushie with tapioca pearls!", "신난다! 난 타피오카 펄 넣은 망고 스무디 시켜야지!",
                  '"내가 쏠게! 오늘은 내가 사!"라고 쿨하게 외쳐보세요!', "It's on me.",
                  "Whoa, really? Are you sure? You don't have to do that!", "우와 진짜? 너 확실해? 굳이 안 그래도 되는데!",
                  '식사나 음료값을 자신이 대신 지불하겠다고 멋지게 나설 때 쓰는 관용구입니다.',
                  "내가 쏠게! (쿨한 한턱내기)", "It is on top of my head.", "내 머리 위에 있다는 직역이에요.", "Give me your credit card.", "카드 달라는 무례한 말이에요."),
        make_turn(3, "Maya", "🛹", "I mean, you bought snacks last Friday too! Are you really sure?", "아니 너 지난주 금요일에도 간식 샀잖아! 진짜 괜찮아?",
                  '"진짜 괜찮아, 맘 편히 먹어!"라고 안심시켜주세요!', "Don't sweat it.",
                  "You're the coolest friend in middle school! Thank you!", "너 우리 중학교에서 제일 쿨한 친구다! 고마워!",
                  '상대방이 미안해하거나 망설일 때 "걱정 마, 부담 갖지 마, 신경 꺼"라고 안심시키는 슬랭입니다.',
                  "신경 쓰지 마, 부담 갖지 마! (편안한 안심)", "Sweat heavily please.", "땀 뻘뻘 흘리라는 오역이에요.", "You owe me five bucks.", "돈 내놓으라는 말이에요."),
        make_turn(4, "Maya", "🛹", "Alright, then next week when we go to the taco truck, the tacos are all mine to buy!", "알았어, 그럼 다음 주 타코 트럭 갈 때는 내가 타코 싹 다 쏠게!",
                  '"다음엔 네가 쏴!"라고 웃으며 약속을 잡으세요!', "Next time is on you.",
                  "Deal! Double spicy beef tacos on my tab next Friday!", "콜! 다음 주 금요일엔 매콤 소고기 타코 내 카드로 긁는다!",
                  '상대방의 호의를 기분 좋게 핑퐁으로 주고받으며 다음 번을 기약할 때 쓰는 세련된 표현입니다.',
                  "다음엔 네가 쏴! (세련된 호의 핑퐁)", "Never buy anything.", "절대 사지 말라는 말이에요.", "Where is my wallet?", "지갑 없다는 당황이에요."),
        make_turn(5, "Maya", "🛹", "Meet by the flagpole right after the 3 PM bell rings?", "3시 종 치자마자 교문 국기 게양대 앞에서 만날까?",
                  '"그렇게 하자! 딱 좋다!"라고 약속을 확정하세요!', "Sounds like a plan!",
                  "Boom! Board games and boba at four PM sharp! See you there!", "좋았어! 정확히 4시에 버블티 마시며 보드게임 격파하자!",
                  '약속 시간과 장소가 확정되었을 때 "그 계획 완벽해, 그렇게 하자"며 확답하는 관용구입니다.',
                  "그렇게 하자! 딱 좋다! (완벽한 일정 확정)", "I reject this scheme.", "계획 거부한다는 딱딱한 말이에요.", "Class is canceled.", "수업 취소라는 엉뚱한 말이에요."),
        make_turn(6, "Maya", "🛹", "We finish school at 3 PM and boba opens right next door! What's the whole afternoon plan?", "3시에 학교 끝나고 버블티 집 바로 옆에 열어! 오후 전체 계획이 뭐야?",
                  '"방과 후에 같이 어울려 놀자!"라고 구동사 hang out을 써서 제안해보세요!', "Let's hang out after school!",
                  "Definitely! Boba, Uno tournaments, and good music all afternoon!", "무조건이지! 오후 내내 버블티 마시며 우노 보드게임 토너먼트 뜨자!",
                  '구동사 "hang out"은 친구들과 부담 없이 시간 보내며 어울려 놀 때 미국 10대들이 가장 기본적으로 쓰는 구동사입니다.',
                  "방과 후에 같이 놀자! (친구 어울림 대표 구동사)", "Let's fight outside.", "밖에서 싸우자는 엉뚱한 말이에요.", "Never talk again.", "다신 말하지 말라는 절교예요.")
    ]),

    make_ep("t3_e2", "tier3", "스케이트보드 묘기 성공", "📍 Episode 2/10: Skatepark Kickflip Landing", "skatepark", [
        make_turn(1, "Jordan", "🏀", "Check this out! I finally landed a clean kickflip off the curb!", "이것 좀 봐! 나 드디어 턱 위에서 킥플립 착지 깔끔하게 성공했어!",
                  '"대박 멋지다, 쩐다!"라고 환호해보세요!', "That's so sick!",
                  "Thanks! I scraped my shin like ten times before getting it right!", "고마워! 성공하기 전에 정강이 열 번은 긁혔잖아!",
                  '미국 10대들이 기술이나 스타일이 기가 막히게 멋질 때 "쩐다, 미쳤다"는 의미로 쓰는 대표 슬랭입니다.',
                  "대박 멋져, 쩐다! (기술 극찬)", "Go see a doctor.", "병원 가라는 직역 오역이에요.", "Skateboards are noisy.", "시끄럽다는 불평이에요."),
        make_turn(2, "Jordan", "🏀", "I almost chipped my board when it slammed the rail though...", "근데 보드가 난간에 쾅 부딪쳤을 때 앞코 깨질 뻔했어...",
                  '"신경 쓰지 마, 다 그런 거지!"라고 위로해보세요!', "Don't sweat it.",
                  "True, scratches on a skateboard just mean you're practicing hard!", "맞아, 스케이트보드에 난 흠집은 열심히 연습했다는 훈장이지!",
                  '작은 실수나 흠집에 속상해하는 친구를 "괜찮아, 털어버려" 하고 격려할 때 씁니다.',
                  "신경 쓰지 마! (털어내는 위로)", "Sweat more.", "땀 더 흘리라는 엉뚱한 말이에요.", "Buy a bicycle.", "자전거 사라는 딴소리예요."),
        make_turn(3, "Jordan", "🏀", "Did you see how the board did a full three-sixty spin under my sneakers?", "내 운동화 밑에서 보드가 정확히 360도 공중 회전한 거 봤어?",
                  '"완벽하게 해냈어!"라고 칭찬해보세요!', "You nailed it!",
                  "Appreciate it! All those hours watching tutorial clips paid off!", "고마워! 튜토리얼 영상 몇 시간씩 본 보람이 있네!",
                  '어려운 묘기나 과제를 완벽무결하게 성공시켰을 때 "딱 해냈다, 제대로 찢었다"는 찬사입니다.',
                  "완벽하게 해냈어! (기술 완수 찬사)", "You hammered a nail.", "못 박았다는 직역 오역이에요.", "I broke my phone.", "폰 깨졌다는 딴소리예요."),
        make_turn(4, "Jordan", "🏀", "Your turn! Your ollie is super high, you can definitely learn this next!", "이제 네 차례야! 너 알리 높이 엄청 높으니까 킥플립도 금방 배울걸!",
                  '"나도 그거 알려줘!"라고 배움을 청해보세요!', "Teach me that!",
                  "Gladly! Place your front foot right on the edge at a slight angle!", "기꺼이! 앞발을 모서리에 약간 대각선 각도로 놓아봐!",
                  '친구의 멋진 기술을 전수받고 싶을 때 적극적으로 요청하는 표현입니다.',
                  "나도 알려줘! (기술 전수 요청)", "I refuse to learn.", "배우기 싫다는 거절이에요.", "Go home now.", "집에 가라는 매정한 말이에요."),
        make_turn(5, "Jordan", "🏀", "Focus on the flick with your toe! Ready to roll?", "발끝으로 튕겨주는 감각에 집중해! 출발할 준비 됐어?",
                  '"나 해볼 수 있어, 맡겨줘!"라고 자신감을 장착하세요!', "I got this!",
                  "That's the spirit! Pop the tail and commit to the landing!", "바로 그 기세지! 꼬리 차고 착지에 몸을 던져!",
                  '자신 있게 도전에 임하며 "내가 해낼게, 걱정 마"라고 스스로와 동료에게 힘을 실어주는 말입니다.',
                  "나 해낼 수 있어! (자신만만한 도전)", "I have forgotten everything.", "다 까먹었다는 포기예요.", "Skating is illegal.", "불법이라는 엉뚱한 말이에요."),
        make_turn(6, "Jordan", "🏀", "The sunset session is wrapping up! My board is packed and ready!", "일몰 스케이트 세션 마무리됐어! 내 보드 다 챙겼다!",
                  '"이따가 메시지로 연락해!"라고 구동사 hit up을 써서 작별해보세요!', "Hit me up later!",
                  "For sure! I'll drop the slow-mo kickflip video in our group chat! Peace out!", "당연하지! 우리 단톡방에 슬로모션 킥플립 영상 올릴게! 안녕!",
                  '구동사 "hit up"은 전화, 문자, SNS 등으로 "나한테 연락해"라고 쿨하게 말할 때 쓰는 대중적인 구어체입니다.',
                  "이따가 연락해! (쿨한 연락 요청 구동사)", "Punch me in face.", "얼굴 때리라는 무서운 오역이에요.", "Block my number.", "차단하라는 엉뚱한 말이에요.")
    ]),

    make_ep("t3_e3", "tier3", "과학 프로젝트 파트너", "📍 Episode 3/10: Volcano Chemistry Lab", "scienceLab", [
        make_turn(1, "Maya", "🛹", "Our paper-mache volcano model dried super smooth and realistic!", "우리 신문지 화산 모형 표면 엄청 매끄럽고 실감 나게 말랐어!",
                  '"우리 팀워크 대박이다!"라고 자축해보세요!', "We make a great team.",
                  "Right? Your red lava paint gradient makes it look active!", "그치? 네가 칠한 붉은 용암 그라데이션 때문에 진짜 활화산 같아!",
                  '파트너와 완벽한 호흡을 맞추며 성과를 낼 때 서로를 북돋우는 표현입니다.',
                  "우리 팀워크 진짜 대박이야! (팀워크 찬사)", "You did nothing.", "친구 탓하는 무례한 말이에요.", "Science is difficult.", "과학 어렵다는 징징거림이에요."),
        make_turn(2, "Maya", "🛹", "Just so you know, Mr. Clark said baking soda goes in before red food dye!", "참고로 클라크 선생님이 식용색소 넣기 전에 베이킹소다 먼저 넣어야 한대!",
                  '"미리 알려줘서 고마워!"라고 감사 인사를 건네보세요!', "Thanks for the heads-up!",
                  "No problem! If we messed that up, it would have fizzed all over the desk!", "별말을! 순서 틀렸으면 책상 전체에 거품 폭발할 뻔했잖아!",
                  '상대방이 중요한 정보나 주의사항을 사전에 미리 귀띔해주었을 때 쓰는 최고의 감사 표현입니다.',
                  "미리 알려줘서 고마워! (사전 정보 감사)", "Keep your head down.", "고개 숙이라는 엉뚱한 오역이에요.", "I love soda.", "탄산음료 좋아한다는 딴소리예요."),
        make_turn(3, "Maya", "🛹", "We still need to measure three tablespoons of vinegar in the beaker!", "비커에 식초 딱 세 큰술 정밀하게 계량해야 해!",
                  '"내가 지금 바로 처리할게!"라고 민첩하게 나서보세요!', "I'm on it.",
                  "Precision work! Pour it slow right up to the 50ml line!", "정밀 작업 완료! 50ml 눈금선까지 천천히 부어봐!",
                  '어떤 임무나 부탁을 받았을 때 "내가 당장 맡아서 처리할게"라는 신뢰감 넘치는 답변입니다.',
                  "내가 바로 처리할게! (민첩한 임무 수행)", "I am sitting on it.", "깔고 앉아있다는 직역 오역이에요.", "Vinegar smells bad.", "식초 냄새 고약하다는 불평이에요."),
        make_turn(4, "Maya", "🛹", "What if we add a drop of dish soap to make the foam last three times longer?", "주방세제 한 방울 섞으면 거품이 세 배는 오래 유지되지 않을까?",
                  '"좋은 생각이야, 센스 있네!"라고 감탄해보세요!', "Good thinking!",
                  "Chemistry wizard move! The foam is gonna cascade like real magma!", "화학 천재의 한 수! 거품이 진짜 마그마처럼 흘러내릴 거야!",
                  '상대방의 기발하고 창의적인 아이디어를 칭찬할 때 쓰는 스마트한 감탄사입니다.',
                  "좋은 생각이야! (아이디어 칭찬)", "Stop thinking.", "생각 멈추라는 무례한 말이에요.", "Soap is slippery.", "비누 미끄럽다는 딴소리예요."),
        make_turn(5, "Maya", "🛹", "Look at Mr. Clark's smile! He wrote a big glowing A+ on our clipboard!", "클라크 선생님 표정 봐! 클립보드에 반짝이는 A+ 크게 적어주셨어!",
                  '"우리 만점 받았다, 해냈어!"라고 환호해보세요!', "We aced it!",
                  "First place ribbon for our volcanic lab! Best partners ever!", "화산 실험 전교 1등 리본 달았다! 우리 최고의 파트너야!",
                  '시험이나 발표, 프로젝트에서 최고점(A학점)을 받고 완벽하게 성공했을 때 외치는 단어입니다.',
                  "우리 만점 받았어! (최고 성취 환호)", "We failed totally.", "완전 망했다는 오답이에요.", "Clean the floor.", "바닥 닦으라는 잔소리예요."),
        make_turn(6, "Maya", "🛹", "The crimson foam overflowed exactly like planned! But the lab desk is all foamy!", "붉은 거품이 계획대로 완벽하게 넘쳤어! 근데 실험실 책상이 온통 거품투성이야!",
                  '"실험대 깨끗이 치우자!"라고 구동사 clean up을 써서 말해보세요!', "Let's clean up the lab!",
                  "Grabbing paper towels right now! Mr. Clark is gonna give us an easy A+!", "지금 페이퍼 타월 가져올게! 클라크 선생님이 무조건 A+ 주실 거야!",
                  '구동사 "clean up"은 과학 실험실이나 작업 공간을 원상태로 말끔히 정리정돈할 때 쓰는 기본 표현입니다.',
                  "실험실 깨끗이 치우자! (공간 정리정돈 구동사)", "Leave the mess.", "어지럽힌 채 두라는 무책임한 말이에요.", "Pour it on floor.", "바닥에 쏟으라는 오답이에요.")
    ]),

    make_ep("t3_e4", "tier4_preview_or_t3", "쇼핑몰 후드티 쇼핑", "📍 Episode 4/10: Mint Green Hoodie Hunt", "mall", [
        make_turn(1, "Chloe", "🎨", "I'm trying on this oversized mint green hoodie. How does it look?", "나 이 오버핏 민트색 후드티 입어봤는데, 어때 보여?",
                  '"너한테 찰떡이다, 완전 잘 어울려!"라고 칭찬해보세요!', "It suits you!",
                  "Really? I usually only wear black, so I wasn't totally sure!", "진짜? 나 평소에 검은색만 입어서 살짝 긴가민가했거든!",
                  '옷이나 헤어스타일, 색상이 상대방에게 기가 막히게 잘 어울릴 때 쓰는 표준 구어체입니다.',
                  "너한테 완전 찰떡이야! (스타일 찬사)", "Take off your suit.", "정장 벗으라는 오역이에요.", "Clothes are made of fabric.", "옷은 천이라는 설명이에요."),
        make_turn(2, "Chloe", "🎨", "Are you just saying that to be nice, or does it genuinely look cool?", "너 그냥 착하게 보이려고 빈말하는 거 아니지? 진심으로 멋져 보여?",
                  '"솔직히 말해서, 진짜 역대급이야!"라고 진정성을 보여주세요!', "Not gonna lie.",
                  "Aww thank you! Honesty is why you're my favorite shopping partner!", "어머 고마워! 솔직하게 말해줘서 너랑 쇼핑하는 게 제일 좋아!",
                  '자신의 의견이 100% 진심임을 강조할 때 문두에 붙이는 필수 슬랭입니다 ("NGL").',
                  "솔직히 말해서! (진정성 강조)", "I always lie.", "항상 거짓말한다는 오답이에요.", "Do not speak truth.", "진실을 말하지 말라는 뜻이에요."),
        make_turn(3, "Chloe", "🎨", "It's thirty-five dollars, but I have a twenty percent student coupon!", "원래 35달러인데, 나 20퍼센트 학생 할인 쿠폰 있거든!",
                  '"너 어떻게 생각해? 네 생각은 어때?"라고 최종 의견을 물어보세요!', "What do you think?",
                  "With the coupon, it's twenty-eight dollars for premium fleece!", "쿠폰 적용하면 최고급 기모 후드가 단돈 28달러야!",
                  '결정을 내리기 전 상대방의 직관적인 견해를 물어볼 때 가장 자연스러운 표현입니다.',
                  "너 어떻게 생각해? (의견 묻기)", "What do you eat?", "뭐 먹냐는 엉뚱한 질문이에요.", "Money grows on trees.", "돈이 나무에서 열린다는 속담이에요."),
        make_turn(4, "Chloe", "🎨", "Should I put it back on the rack or take it to the register?", "다시 매대에 걸어둘까, 아니면 계산대로 들고 갈까?",
                  '"고민 말고 질러버려!"라고 결단을 촉구해보세요!', "Go for it!",
                  "Heading to the cashier right now before someone grabs the last size!", "누가 마지막 사이즈 채가기 전에 지금 바로 계산대로 돌진한다!",
                  '망설이는 친구에게 "망설이지 말고 도전해! 질러!"라고 용기를 북돋워 주는 만능 구호입니다.',
                  "질러버려! 추진해! (결단 촉구)", "Go away from here.", "여기서 저리 가라는 쫓아내는 말이에요.", "Stores are crowded.", "가게 붐빈다는 불평이에요."),
        make_turn(5, "Chloe", "🎨", "The bag is in my hand! Mint green hoodie officially acquired!", "쇼핑백 내 손에 들렸다! 민트색 후드티 공식 득템 완료!",
                  '"후회 없는 선택이야!"라고 든든하게 지지해주세요!', "No regrets!",
                  "Zero regrets! Wearing this to school first thing Monday morning!", "후회 0퍼센트! 월요일 아침에 학교 가자마자 이거 입을 거야!",
                  '좋은 선택을 내린 후 "절대 후회 따윈 없다"고 확신하며 만족감을 표현할 때 씁니다.',
                  "후회 없는 완벽한 선택이야! (만족감 확신)", "I regret everything.", "모든 걸 후회한다는 반대말이에요.", "Return it tomorrow.", "내일 환불하라는 초 치기예요."),
        make_turn(6, "Chloe", "🎨", "The shopping mall food court is right upstairs! I smell warm cinnamon pretzels!", "쇼핑몰 푸드코트 바로 위층이야! 따끈한 시나몬 프레첼 냄새 난다!",
                  '"저기 한번 구경 가보자!"라고 구동사 check out을 써서 제안해보세요!', "Let's check it out!",
                  "Warm butter glaze and sweet iced lemonade! Best shopping finale ever!", "따끈한 버터 글레이즈에 시원한 레모네이드! 최고의 쇼핑 마무리 코스다!",
                  '구동사 "check out"은 새로운 장소나 음식, 볼거리를 "확인하다/구경하러 가다"라는 뜻의 만능 구동사입니다.',
                  "저기 한번 구경 가보자! (탐색과 방문 필수 구동사)", "Run away from food.", "음식에서 도망치라는 딴소리예요.", "Close your nose.", "코 막으라는 엉뚱한 말이에요.")
    ]),

    make_ep("t3_e5", "tier3", "음악 플레이리스트 공유", "📍 Episode 5/10: Shared Headphone Jams", "teenLocker", [
        make_turn(1, "Jordan", "🏀", "Put in this earbud! Check out the synth bass drop on this track!", "이 이어폰 한쪽 꽂아봐! 이 곡 신스 베이스 드롭 터지는 것 좀 들어봐!",
                  '"이 노래 진짜 찢었다! 비트 미쳤어!"라고 감탄해보세요!', "This song slaps!",
                  "Right? That 808 bass kick gives me goosebumps every single time!", "그치? 저 808 베이스 쿵쿵거릴 때마다 온몸에 소름 돋는다니까!",
                  '음악이나 노래의 비트가 너무 좋을 때 "귀를 때린다, 찢었다"는 의미로 쓰는 대표 Z세대 슬랭입니다.',
                  "이 노래 진짜 찢었다! (음악 극찬 슬랭)", "Slap my face.", "내 뺨 때리라는 무서운 오역이에요.", "I hate music.", "음악 싫다는 악담이에요."),
        make_turn(2, "Jordan", "🏀", "I have an eighty-song playlist for our weekend road trips!", "우리 주말 드라이브 갈 때 들을 80곡짜리 플레이리스트 만들어뒀어!",
                  '"재생목록 대기열에 바로 추가해!"라고 요청해보세요!', "Add it to queue.",
                  "Added! It's playing right after this electric guitar solo!", "추가 완료! 이 일렉 기타 솔로 끝나자마자 바로 재생된다!",
                  '스마트폰 음악 앱에서 다음에 들을 곡으로 예약 목록에 올릴 때 쓰는 표준 IT/일상 표현입니다.',
                  "대기열에 추가해줘! (재생목록 추가)", "Delete all songs.", "곡 다 지우라는 테러예요.", "My ears are hurting.", "귀 아프다는 불평이에요."),
        make_turn(3, "Jordan", "🏀", "The vocalist's falsetto notes are so smooth and effortless!", "보컬 가성 올라가는 거 진짜 부드럽고 자연스럽지 않아?",
                  '"이 노래 부른 사람 누구야?"라고 가수를 물어보세요!', "Who sings this?",
                  "It's an indie producer from Seattle! Only nineteen years old!", "시애틀 출신 인디 프로듀서야! 나이가 겨우 열아홉 살이래!",
                  '흘러나오는 멋진 노래의 원곡자가 궁금할 때 가장 직관적으로 묻는 질문입니다.',
                  "이거 누가 부른 거야? (가수 묻기)", "Who is talking?", "누가 말하냐는 엉뚱한 질문이에요.", "Sing louder please.", "더 크게 부르라는 주문이에요."),
        make_turn(4, "Jordan", "🏀", "I downloaded their whole album last night and listened till 2 AM!", "나 어젯밤에 그 사람 앨범 전곡 다운받아서 새벽 2시까지 들었잖아!",
                  '"하루 종일 무한 반복 중이야!"라고 공감해보세요!', "On repeat all day.",
                  "Same here! My Spotify replay stats are gonna be completely dominated!", "나도 그래! 내 스포티파이 올해 결산 차트 이 노래가 다 먹을걸!",
                  '마음에 드는 노래를 하루 종일 끊임없이 반복해서 들을 때 쓰는 일상 구어체입니다.',
                  "하루 종일 무한 반복 중! (무한 스트리밍 공감)", "Stop repeating words.", "말 반복하지 말라는 엉뚱한 뜻이에요.", "Turn off radio.", "라디오 끄라는 말이에요."),
        make_turn(5, "Jordan", "🏀", "Every track on this EP has zero skips, pure masterpiece!", "이 미니앨범 수록곡은 버릴 곡이 하나도 없어, 전곡이 명작이야!",
                  '"진짜 버릴 게 없는 순도 100% 명곡이다!"라고 극찬해보세요!', "Pure gold.",
                  "Shared the link to our group chat! Everyone needs this on their radar!", "우리 단톡방에 링크 쐈다! 애들 다 이 노래 들어야 해!",
                  '품질이나 완성도가 흠잡을 데 없이 뛰어난 작품이나 곡을 "순금 같다, 명작이다"라고 칭송하는 말입니다.',
                  "순도 100% 명작이야! (최고의 찬사)", "Fake gold plastic.", "가짜 금이라는 악담이에요.", "I have no headphones.", "이어폰 없다는 딴소리예요."),
        make_turn(6, "Jordan", "🏀", "My phone battery just dipped to fifteen percent! The music might cut off!", "내 폰 배터리 방금 15퍼센트로 떨어졌어! 노래 끊길지도 몰라!",
                  '"얼른 충전기 꽂아!"라고 구동사 plug in을 써서 말해보세요!', "Plug it in!",
                  "Connected to the portable power bank! The music marathon keeps rolling uninterrupted!", "보조배터리에 연결 완료! 음악 마라톤은 끊김 없이 계속된다!",
                  '구동사 "plug in"은 전자기기나 충전기를 전원에 꽂아 연결할 때 전 세계에서 매일 쓰는 기본 구동사입니다.',
                  "얼른 충전기 꽂아! (전원 연결 필수 구동사)", "Unplug everything.", "다 뽑으라는 반대말이에요.", "Throw phone away.", "폰 버리라는 극단적인 오답이에요.")
    ]),

    make_ep("t3_e6", "tier3", "락커룸 사물함 자물쇠", "📍 Episode 6/10: Locker Combination Amnesia", "teenLocker", [
        make_turn(1, "Maya", "🛹", "Three minutes before the bell! What is my locker combination?!", "수업 종 치기 3분 전인데! 내 사물함 비밀번호가 뭐였지?!",
                  '"갑자기 머릿속이 새하얘졌어!"라고 당황해보세요!', "My mind went blank.",
                  "Don't freak out! It happens to everyone on Monday mornings!", "멘붕하지 마! 월요일 아침엔 누구나 다 겪는 일이야!",
                  '기억하던 정보가 갑자기 백지장처럼 증발했을 때 미국인들이 가장 자주 쓰는 표현입니다.',
                  "머릿속이 하얘졌어! (일시적 기억 상실)", "My head is white.", "내 머리가 흰색이라는 직역 오역이에요.", "Locker is broken.", "사물함 고장 났다는 핑계예요."),
        make_turn(2, "Maya", "🛹", "Your hands are shaking! Close your eyes and shake out your shoulders!", "너 손 떨고 있잖아! 눈 감고 어깨 힘부터 툭 빼봐!",
                  '"심호흡 한번 크게 해봐."라고 침착하게 조언해주세요!', "Take a deep breath.",
                  "Inhale, exhale... Okay, pulse is slowing down a bit.", "들이쉬고, 내쉬고... 좋아, 심장 박동 좀 가라앉았어.",
                  '당황하거나 패닉에 빠진 상대방을 차분하게 진정시킬 때 건네는 필수 케어 표현입니다.',
                  "심호흡 한번 크게 쉬어. (차분한 진정)", "Stop breathing now.", "숨 쉬지 말라는 위험한 오역이에요.", "Run away fast.", "도망치라는 엉뚱한 조언이에요."),
        make_turn(3, "Maya", "🛹", "Was the first number twenty-four or fourteen? I knew it on Friday!", "첫 숫자가 24였나 14였나? 금요일까지만 해도 알았는데!",
                  '"완전 깜빡 잊어버렸네!"라고 안타까워해보세요!', "It slipped my mind.",
                  "Wait, did you write it on the inner flap of your science notebook?", "잠깐, 너 과학 공책 안쪽 표지 날개에 적어두지 않았어?",
                  '기억하고 있어야 할 내용을 실수로 깜빡 잊었을 때 쓰는 세련된 관용구입니다.',
                  "깜빡 잊어버렸어! (자연스러운 망각)", "Mind is slipping on ice.", "얼음에 미끄러진다는 직역 오역이에요.", "Notebook is stolen.", "도둑맞았다는 거짓말이에요."),
        make_turn(4, "Maya", "🛹", "Look at the corner of your binder! A little sticky note!", "네 바인더 모서리 봐봐! 작은 포스트잇 붙어있잖아!",
                  '"기억났다! 번뜩 떠올랐어!"라고 환호해보세요!', "It clicked!",
                  "Twenty-four, seven, thirty-two! Spin the dial quick!", "24, 7, 32! 다이얼 얼른 돌려봐!",
                  '갑자기 해답이나 아이디어가 머릿속에서 딱 맞춰지듯 떠올랐을 때 쓰는 감탄사입니다.',
                  "번뜩 떠올랐어! 딱 기억났어! (순간의 깨달음)", "Click the mouse.", "마우스 클릭하라는 오역이에요.", "Turn off lights.", "불 끄라는 딴소리예요."),
        make_turn(5, "Maya", "🛹", "Click! The latch popped open with twenty seconds to spare!", "철컥! 20초 남겨두고 걸쇠 활짝 열렸다!",
                  '"위기 넘겼다, 살았다!"라고 가슴을 쓸어내려 보세요!', "Crisis averted!",
                  "Grab your sneakers and sprint! We made it by the skin of our teeth!", "운동화 챙겨서 뛰어! 우리 진짜 간발의 차로 세이프했다!",
                  '큰 곤경이나 재난 상황을 아슬아슬하게 피했을 때 안도하며 외치는 멋진 구어체입니다.',
                  "위기 넘겼다, 살았다! (안도의 한숨)", "Crisis started.", "위기 시작이라는 반대말이에요.", "I failed gym class.", "체육 낙제라는 오답이에요."),
        make_turn(6, "Maya", "🛹", "We grabbed our sneakers, but my locker door is swinging wide open!", "운동화는 챙겼는데, 내 사물함 문이 활짝 열려있어!",
                  '"얼른 문 닫아!"라고 기본동사 shut을 써서 말해보세요!', "Shut it close!",
                  "Slammed and clicked shut! Hallway is clear, sprint to the gymnasium!", "쾅 닫히면서 잠겼다! 복도 비었다, 체육관으로 전력 질주!",
                  '기본동사 "shut"은 문이나 뚜껑을 빠르고 단단하게 닫을 때 직관적으로 쓰이는 핵심 동사입니다.',
                  "얼른 딱 닫아! (문 단속 기본동사)", "Leave it open.", "열어두라는 위험한 말이에요.", "Break the hinges.", "경첩 부수라는 오답이에요.")
    ]),

    make_ep("t3_e7", "tier3", "급식 메뉴 실망", "📍 Episode 7/10: Cafeteria Mystery Loaf", "cafeteria", [
        make_turn(1, "Chloe", "🎨", "What on earth is that grey scoop on the lunch tray today?", "오늘 급식판에 저 회색 덩어리는 대체 정체가 뭐야?",
                  '"또 정체불명의 미스터리 고기네."라고 한탄해보세요!', "Mystery meat again.",
                  "It jiggles when the lunch lady puts it down with the tongs!", "배식원 선생님이 집게로 툭 내려놓으시는데 푸딩처럼 흔들려!",
                  '학교 급식에서 정체를 알 수 없는 패티나 요리가 나왔을 때 미국 학생들이 쓰는 고유 표현입니다.',
                  "또 정체불명 고기야. (급식 단골 한탄)", "I love mystery novels.", "추리소설 좋아한다는 딴소리예요.", "Meat is healthy.", "고기는 건강하다는 교과서 문장이에요."),
        make_turn(2, "Chloe", "🎨", "The menu board says 'Chef's Surprise Meatloaf'...", "메뉴판에 '주방장 특선 서프라이즈 미트로프'라고 적혀있어...",
                  '"난 절대 사양할래, 거절이야!"라고 단호히 손을 내저어보세요!', "Hard pass.",
                  "Agreed! I value my stomach way too much to touch that!", "인정! 내 소중한 위장을 위해서 저건 절대 입에도 못 대지!",
                  '어떤 제안이나 음식, 선택지를 단호하게 거절할 때 쓰는 가장 직관적인 현대 슬랭입니다.',
                  "난 절대 사양! 거절이야! (단호한 거부 슬랭)", "Soft pass.", "부드러운 패스라는 오역이에요.", "Please give me more.", "더 달라는 반대말이에요."),
        make_turn(3, "Chloe", "🎨", "The whole table pushed their trays away in solidarity haha!", "우리 테이블 애들 다 일제히 식판 밀어냈어 ㅋㅋㅋ!",
                  '"다른 메뉴는 뭐 있대?"라고 대안을 물어보세요!', "What else they got?",
                  "Just soggy steamed broccoli and dry whole wheat rolls...", "눅눅하게 삶은 브로콜리랑 퍽퍽한 통밀빵뿐이야...",
                  '대체 가능한 다른 선택지가 있는지 물어볼 때 구어체로 가장 편하게 묻는 질문입니다.',
                  "다른 건 뭐 있대? (대안 메뉴 확인)", "Who are they?", "그들은 누구냐는 엉뚱한 질문이에요.", "Eat everything fast.", "얼른 다 먹으라는 잔소리예요."),
        make_turn(4, "Chloe", "🎨", "My stomach is growling like an angry motorcycle engine!", "내 배에서 성난 오토바이 엔진 소리처럼 꼬르륵거려!",
                  '"복도 자판기 털러 가자!"라고 탈출구를 제안해보세요!', "Vending machine run.",
                  "Genius idea! I've got two crisp dollar bills in my pocket!", "천재적인 생각! 내 주머니에 빳빳한 1달러 지폐 두 장 있어!",
                  '간식을 사러 자판기나 편의점으로 급히 달려가는 것을 "run"을 붙여 표현하는 생활 영어입니다.',
                  "자판기 털러 가자! (간식 원정 제안)", "Break the vending machine.", "자판기 부수라는 범죄예요.", "Dieting is fun.", "다이어트 재밌다는 거짓말이에요."),
        make_turn(5, "Chloe", "🎨", "They just restocked the spicy cheese puffs and peach iced tea!", "방금 매콤 치즈 스낵이랑 복숭아 아이스티 꽉 채워 넣으셨대!",
                  '"나도 무조건 낄래!"라고 지갑을 챙겨 일어나세요!', "Count me in.",
                  "Race you to the hall! Lunch crisis solved with snacks!", "복도까지 달리기다! 점심 위기는 스낵으로 완벽 해결!",
                  '어떤 행동이나 모임에 빠짐없이 동참하겠다고 활기차게 선언하는 만능 표현입니다.',
                  "나도 무조건 낄래! (활기찬 동참 선언)", "Leave me alone.", "혼자 내버려 두라는 쌀쌀맞은 말이에요.", "I love broccoli.", "브로콜리 좋다는 거짓말이에요."),
        make_turn(6, "Chloe", "🎨", "The snack vending machine has delicious barbecue chips and cold soda!", "자판기에 맛있는 바비큐 감자칩이랑 시원한 탄산음료 가득 차 있어!",
                  '"얼른 뽑아먹자!"라고 기본동사 get을 써서 말해보세요!', "Let's go get some!",
                  "Dollar bills accepted! Crunchy chips dropped into the slot! Lunch is saved!", "지폐 투입 완료! 바삭한 칩이 슬롯으로 툭 떨어졌다! 점심 위기 탈출!",
                  '기본동사 "go"와 "get"이 결합한 "go get ~"은 음식이나 간식을 사러 가거나 가져올 때 가장 자연스럽게 쓰입니다.',
                  "얼른 사 먹으러 가자! (간식 획득 기본동사)", "Drop the coins.", "동전 떨어뜨리라는 오답이에요.", "Starve until dinner.", "저녁까지 굶자는 포기예요.")
    ]),

    make_ep("t3_e8", "tier3", "방과 후 자전거 라이딩", "📍 Episode 8/10: Sunset Ridge Bike Climb", "sunset", [
        make_turn(1, "Jordan", "🏀", "The scenic hill trail is completely clear! Race to the lookout point!", "전망대 언덕 코스 길 뻥 뚫렸다! 저 위 쉼터까지 레이스 뜨자!",
                  '"따라올 수 있으면 따라와 봐!"라고 패기 있게 페달을 밟으세요!', "Catch me if you can!",
                  "Oh, you're kicking into high gear? Challenge accepted!", "오, 최고 기어로 변속했다 이거지? 도전 받아주지!",
                  '술래잡기나 자전거 대결에서 자신만만하게 앞서 나가며 외치는 도발 명대사입니다.',
                  "따라와 볼 테면 따라와 봐! (자신만만한 질주 도발)", "Stop my bicycle.", "자전거 멈추라는 오답이에요.", "It is raining cats.", "비 온다는 딴소리예요."),
        make_turn(2, "Jordan", "🏀", "This steep incline is brutal! My calves are on fire!", "여기 오르막길 경사 장난 아니다! 종아리 타들어 갈 것 같아!",
                  '"나 살짝 뒤처지고 있어!"라고 숨차게 고백해보세요!', "I'm lagging behind.",
                  "Drop down to gear one! Don't look at the summit, just pedal steady!", "1단 기어로 낮춰! 꼭대기 보지 말고 발만 꾸준히 굴려!",
                  '게임이나 달리기, 라이딩에서 페이스가 떨어져 뒤로 밀릴 때 쓰는 현대적인 표현입니다.',
                  "나 좀 뒤처지고 있어! (솔직한 페이스 고백)", "I am running computer.", "컴퓨터 돌린다는 엉뚱한 오역이에요.", "Bikes have wheels.", "바퀴 있다는 설명이에요."),
        make_turn(3, "Jordan", "🏀", "Here is a flat wooden bench under the big pine tree!", "여기 큰 소나무 아래 평평한 나무 벤치 하나 있다!",
                  '"잠깐 숨 좀 돌리자."라고 휴식을 제안해보세요!', "Take a breather.",
                  "Phew! Cold water never tasted so heavenly in my life!", "휴! 얼음물이 내 평생 이렇게 꿀맛인 적은 처음이다!",
                  '격렬한 운동이나 활동 도중 잠시 멈추고 숨을 고르며 쉴 때 건네는 자연스러운 권유입니다.',
                  "잠깐 숨 좀 돌리자. (편안한 휴식 권유)", "Stop breathing forever.", "숨 영원히 쉬지 말라는 위험한 말이에요.", "Throw away bicycle.", "자전거 버리라는 억지예요."),
        make_turn(4, "Jordan", "🏀", "Stand up and look over the railing towards the valley below!", "일어나서 저 난간 너머 아래 계곡 쪽 한번 내려다봐!",
                  '"언덕 올라온 보람이 진짜 있네!"라고 감탄해보세요!', "Worth the climb.",
                  "Totally! The orange and purple sunset clouds look painted!", "완전! 주황빛이랑 보랏빛 노을 구름이 그림 그려놓은 것 같아!",
                  '힘든 과정이나 고생 끝에 멋진 결과를 보았을 때 "올라온 보람이 있다"고 자축하는 말입니다.',
                  "올라온 보람이 있어! (노력의 가치 실감)", "Climbing was useless.", "올라온 거 헛수고라는 불평이에요.", "I hate mountains.", "산 싫다는 투정이에요."),
        make_turn(5, "Jordan", "🏀", "The whole city lights are starting to twinkle in the dusk!", "황혼 속에서 도시 전체 불빛들이 반짝거리기 시작했어!",
                  '"풍경 진짜 대박이다!"라고 노을을 바라보며 외치세요!', "What a view!",
                  "Golden hour perfection! Best bike ride of the entire year!", "골든 아워의 정석이다! 올해 최고의 자전거 라이딩이었어!",
                  '숨 막히게 아름다운 경치나 풍경을 마주했을 때 감탄을 쏟아내는 대표 관용구입니다.',
                  "풍경 진짜 대박이야! (절경 감탄)", "I cannot see anything.", "아무것도 안 보인다는 오답이에요.", "Close your eyes.", "눈 감으라는 엉뚱한 말이에요."),
        make_turn(6, "Jordan", "🏀", "The mountain air is getting pretty chilly, and the twilight streetlights are turning on!", "산 공기가 꽤 쌀쌀해지고, 땅거미 내려앉으면서 가로등이 켜지고 있어!",
                  '"이제 자전거 타고 내려가자!"라고 구동사 head down을 써서 말해보세요!', "Let's head down!",
                  "Flipping bike headlights on! Coasting smooth down the asphalt all the way home!", "자전거 전조등 ON! 아스팔트 길 타고 집까지 시원하게 미끄러져 내려가자!",
                  '구동사 "head down"은 특정 방향(아래쪽, 남쪽, 시내 등)을 향해 "내려가다/출발하다"라는 이동 구동사입니다.',
                  "이제 내려가자! (방향 이동 필수 구동사)", "Sleep on the hill.", "언덕에서 자라는 엉뚱한 말이에요.", "Crash the bicycle.", "자전거 박으라는 위험한 말이에요.")
    ]),

    make_ep("t3_e9", "tier3", "시험 전날 스터디 그룹", "📍 Episode 9/10: Pre-Exam Flashcard Sprint", "library", [
        make_turn(1, "Maya", "🛹", "Tomorrow is the big American History unit exam on three chapters!", "내일 3개 단원 분량의 미국 역사 단원 평가 큰 시험이야!",
                  '"나 스트레스 엄청 받아!"라고 솔직한 심정을 털어놓으세요!', "I'm stressed out.",
                  "Same here! My brain feels like a stuffed hard drive!", "나도 그래! 내 뇌가 용량 꽉 찬 외장하드 같아!",
                  '학업이나 일로 극심한 긴장과 부담감을 느낄 때 일상적으로 외치는 고백입니다.',
                  "나 스트레스 엄청 받아! (솔직한 부담 토로)", "I am very relaxed.", "엄청 여유롭다는 거짓말이에요.", "History was long ago.", "역사는 옛날이라는 딴소리예요."),
        make_turn(2, "Maya", "🛹", "Stressing won't help us memorize dates! We can conquer this together!", "스트레스받아 봤자 연도 외우는 데 도움 안 돼! 우리 같이 격파하자!",
                  '"우리 할 수 있어, 힘내자!"라고 서로를 다독여보세요!', "We got this.",
                  "That's what I needed to hear! Let's conquer the American Revolution first!", "바로 그 말이 듣고 싶었어! 일단 미국 독립혁명 파트부터 박살 내자!",
                  '어려운 시험이나 시합을 앞두고 "우린 해낼 수 있어"라고 용기를 북돋우는 최강의 응원 구호입니다.',
                  "우리 할 수 있어! (용기를 주는 응원)", "We will fail 100%.", "무조건 떨어진다는 패배주의예요.", "I don't care.", "상관없다는 무책임한 말이에요."),
        make_turn(3, "Maya", "🛹", "I prepared twenty index flashcards with questions on one side!", "한쪽에 질문 적어둔 인덱스 단어 카드 20장 만들어왔어!",
                  '"서로 깜짝 퀴즈 내주자!"라고 스터디 방식을 제안해보세요!', "Pop quiz each other.",
                  "Draw a card! Question one: What year was the Declaration of Independence signed?", "카드 뽑아봐! 1번 문제: 독립선언서가 서명된 연도는?",
                  '상대방과 문답식으로 기습 문제를 내며 실력을 점검할 때 쓰는 학습 구어체입니다.',
                  "서로 깜짝 퀴즈 내주자! (문답 퀴즈 제안)", "Tear up flashcards.", "카드 찢어버리라는 훼방이에요.", "Silence forever.", "영원히 침묵하라는 말이에요."),
        make_turn(4, "Maya", "🛹", "July 4th, 1776 in Philadelphia!", "1776년 7월 4일, 필라델피아에서 서명됨!",
                  '"정답 제대로 맞혔어, 완벽해!"라고 확인 도장을 찍어주세요!', "You nailed that answer.",
                  "Flawless! Card two: Who was the commander of the Continental Army? George Washington!", "완벽해! 2번 카드: 대륙군 총사령관은? 조지 워싱턴!",
                  '상대방이 질문에 한 치의 오차도 없이 똑 부러지게 정답을 맞혔을 때 칭찬하는 표현입니다.',
                  "정답 제대로 맞혔어! (완벽한 정답 확인)", "Wrong completely.", "완전 틀렸다는 거짓말이에요.", "Nobody knows history.", "아무도 모른다는 핑계예요."),
        make_turn(5, "Maya", "🛹", "We just recited all twenty cards backwards without a single hesitation!", "우리 방금 20장 카드 거꾸로 넘기면서도 한 번도 안 막히고 다 외웠어!",
                  '"시험 치를 준비 완전 완료!"라고 자신감을 뽐내보세요!', "Ready for battle!",
                  "Tomorrow's exam doesn't stand a chance against us! Sleep well tonight!", "내일 시험지는 우리 손에 박살 날 일만 남았다! 오늘 밤 푹 자자!",
                  '모든 준비를 완벽하게 마치고 결전의 날을 당당하게 맞이할 때 외치는 전의에 찬 구호입니다.',
                  "실전 준비 완료! (자신감 충천)", "I surrender tomorrow.", "내일 항복하겠다는 오답이에요.", "Cancel the school.", "학교 취소하라는 헛소리예요."),
        make_turn(6, "Maya", "🛹", "Our eyes are getting dry and we covered all twenty flashcard questions three times!", "눈도 뻑뻑해지고 플래시카드 20개 질문 세 번이나 전수 복습했어!",
                  '"오늘은 이만 정리하자!"라고 구동사 wrap up을 써서 제안해보세요!', "Let's wrap it up!",
                  "Packing up highlighters! A good night of sleep is our final secret weapon for an A!", "형광펜 정리 끝! 오늘 밤 푹 자는 게 만점 받는 마지막 비밀 무기야!",
                  '구동사 "wrap up"은 공부나 회의, 프로젝트를 만족스럽게 "마무리짓다/끝마치다"라는 뜻의 핵심 구동사입니다.',
                  "오늘은 이만 마무리하자! (학습 종료 필수 구동사)", "Study all night long.", "밤새우라는 무리한 말이에요.", "Rip the textbooks.", "교과서 찢으라는 나쁜 말이에요.")
    ]),

    make_ep("t3_e10", "tier3", "주말 캠핑 불멍", "📍 Episode 10/10: Fireside S'mores & Lore", "campfire", [
        make_turn(1, "Chloe", "🎨", "The campfire wood is glowing red hot! The roasting sticks are ready!", "장작불 숯이 빨갛게 제대로 달아올랐어! 마시멜로 꼬치 준비 완료!",
                  '"마시멜로 봉지 좀 넘겨줘!"라고 부탁해보세요!', "Pass the marshmallows.",
                  "Catch! Don't let it touch the flames or it'll turn into charcoal!", "받아! 불꽃에 바로 닿게 하지 마, 안 그러면 시커먼 숯덩이 된다!",
                  '캠핑이나 식탁에서 재료나 음식을 건네달라고 요청할 때 쓰는 가장 편안한 문장입니다.',
                  "마시멜로 좀 넘겨줘! (재료 전달 요청)", "Keep them away.", "멀리 치우라는 반대말이에요.", "Fire is cold.", "불이 차갑다는 엉뚱한 말이에요."),
        make_turn(2, "Chloe", "🎨", "Hover it two inches above the embers and spin it slow like a rotisserie!", "숯불 5센티 위에 띄우고 전기구이 통닭처럼 살살 돌려봐!",
                  '"노릇노릇 완벽하게 구워졌다!"라고 감탄해보세요!', "Golden brown toast.",
                  "Perfection! Squeeze it between two graham crackers with dark chocolate!", "완벽해! 다크초콜릿이랑 통밀 크래커 사이에 넣고 꾹 눌러봐!",
                  '마시멜로나 토스트가 타지 않고 황금빛 갈색으로 기가 막히게 익었을 때 쓰는 미식 표현입니다.',
                  "노릇노릇 완벽하게 구웠어! (굽기 장인 감탄)", "Burnt black rock.", "새까맣게 탄 돌이라는 오답이에요.", "Throw it in water.", "물에 던지라는 낭비예요."),
        make_turn(3, "Chloe", "🎨", "Crunch! The melted chocolate is oozing out! Now that the mood is set...", "바삭! 녹은 초콜릿이 줄줄 흘러나와! 이제 분위기도 무르익었으니...",
                  '"무서운 괴담 이야기할 시간이야!"라고 으스스하게 운을 띄워보세요!', "Ghost story time.",
                  "Ooh, let me tell you about the Whispering Pine Cabin on this very ridge!", "오오, 바로 이 능선에 있던 '속삭이는 소나무 오두막' 괴담 내가 풀어줄게!",
                  '캠프파이어에 둘러앉았을 때 미국 아이들이 눈을 빛내며 외치는 전통적인 이벤트 선언입니다.',
                  "괴담 풀 시간이다! (캠프파이어 괴담 선언)", "Go to sleep immediately.", "즉시 자러 가라는 김빠지는 소리예요.", "Sing nursery rhymes.", "동요 부르자는 딴소리예요."),
        make_turn(4, "Chloe", "🎨", "...And every full moon, the antique rocking chair rocks all by itself!", "...그리고 보름달이 뜨는 날마다, 앤티크 흔들의자가 혼자서 삐걱거리며 흔들린대!",
                  '"진짜 온몸에 닭살 돋았어!"라고 몸을 부르르 떨어보세요!', "Gave me goosebumps!",
                  "Look at your arms, your hairs are standing on end haha!", "네 팔뚝 봐봐, 털이 바짝 곤두섰잖아 ㅋㅋㅋ!",
                  '무서운 이야기나 충격적인 반전을 듣고 실제로 소름이 돋았을 때 쓰는 가장 생생한 구어체입니다.',
                  "진짜 닭살 돋았어! 소름 쫙 끼쳤어! (오싹한 반응)", "Gave me geese.", "거위를 줬다는 엉뚱한 직역이에요.", "I feel very warm.", "따뜻하다는 딴청이에요."),
        make_turn(5, "Chloe", "🎨", "The sparks are drifting up into the Milky Way... It's so peaceful out here.", "불꽃 불씨들이 은하수 하늘로 흩날려 올라가... 여기 진짜 너무 평화롭다.",
                  '"진짜 아늑하고 힐링되는 분위기야."라고 편안한 밤을 음미해보세요!', "Cozy vibes.",
                  "Crackling logs and a sky full of shooting stars... Best campout ever!", "타닥타닥 타는 장작불에 별똥별 가득한 하늘... 인생 최고의 캠핑이야!",
                  '따뜻하고 편안하며 감성적인 힐링 무드를 한마디로 요약할 때 10대들이 가장 사랑하는 표현입니다.',
                  "진짜 아늑하고 힐링되는 분위기야. (감성적인 힐링)", "Horrible terrible mood.", "끔찍한 분위기라는 악담이에요.", "I hate camping.", "캠핑 싫다는 투덜거림이에요."),
        make_turn(6, "Chloe", "🎨", "The night breeze is blowing sparks toward the dry pine needles!", "밤바람이 마른 솔잎 쪽으로 불씨를 날리고 있어!",
                  '"불씨 완전히 꺼두자!"라고 구동사 put out을 써서 말해보세요!', "Put the fire out!",
                  "Pouring the water bucket over the embers! Hiss... completely extinguished and safe!", "숯불 위에 양동이 물 붓는 중! 치이익... 완전히 진화 완료, 안전해!",
                  '구동사 "put out"은 모닥불, 촛불, 담배 등의 불을 "끄다/진화하다"라는 뜻으로 캠핑과 안전에서 필수입니다.',
                  "불씨 완전히 꺼둬! (소화 및 진화 필수 구동사)", "Pour gasoline.", "휘발유 부으라는 위험천만한 말이에요.", "Run away leaving fire.", "불 두고 도망치라는 범죄예요.")
    ])
]
