"""Tier 2 Scenarios: Ages 9-10 (10 episodes x 7 turns = 70 turns)."""
from scenarios_common import make_ep, make_turn

t2 = [
    make_ep("t2_e1", "tier2", "그네 찜하기", "📍 Episode 1/10: Tire Swing Showdown", "swing", [
        make_turn(1, "Leo", "🦁", "Hey! The tire swing is finally open! Who's riding first?", "야! 타이어 그네 비었다! 누가 먼저 탈래?",
                  '"내가 찜했어!"라고 외치세요!', "I call dibs!",
                  "Aw man, you were fast! Okay, you ride first!", "아깝다, 너 진짜 빠르네! 좋아 네가 먼저 타!",
                  '미국 아이들이 무언가를 선점할 때 무조건 외치는 마법의 구어체 단어입니다.',
                  "내가 찜했어! (선점 구어체)", "I reserve the swing.", "너무 딱딱한 문장이에요.", "Good morning teacher.", "상황에 안 맞아요."),
        make_turn(2, "Leo", "🦁", "Can you give me a push? Let's take turns after twenty seconds!", "나 좀 밀어줄래? 20초 뒤에 바꿔 타자!",
                  '"좋아, 합의!"라고 쿨하게 답해보세요!', "Deal!",
                  "Sweet! Push me high into the clouds!", "나이스! 구름까지 닿게 높이 밀어줘!",
                  '협상이나 제안을 흔쾌히 수락할 때 외치는 짧고 강력한 단어입니다.',
                  "좋아, 그렇게 하자! (흔쾌한 합의)", "I reject this.", "거절하는 쌀쌀맞은 말이에요.", "My name is Leo.", "동문서답이에요."),
        make_turn(3, "Leo", "🦁", "Wait! Look, Sammy wants to ride too! Can he squeeze on with us?", "잠깐! 저기 새미도 타고 싶어 해! 우리랑 같이 낑겨 타도 돼?",
                  '"새미도 끼워주자!"라고 너그럽게 말해보세요!', "Count him in!",
                  "Awesome! Three kids on the tire swing! Hold on tight!", "신난다! 타이어 그네에 세 명 탑승 완료! 꽉 잡아!",
                  '놀이나 모임에 누군가를 참여시킬 때 "Count [someone] in"은 필수 표현입니다.',
                  "걔도 끼워주자! (포용과 참여)", "Kick him out.", "너무 심술궂은 말이에요.", "I want to sleep.", "졸리다는 엉뚱한 말이에요."),
        make_turn(4, "Leo", "🦁", "Whoa, we are spinning so fast! This is the most fun recess ever!", "우와, 우리 엄청 뱅글뱅글 돈다! 이번 쉬는 시간 역대급으로 재밌어!",
                  '"오늘 진짜 최고의 날이다!"라고 환호해보세요!', "Best day ever!",
                  "Totally! We rule the playground today!", "완전 인정! 오늘 놀이터는 우리가 접수했다!",
                  '신나게 놀며 행복이 폭발할 때 미국 아이들이 매일 쓰는 대표적 찬사입니다.',
                  "진짜 최고의 날이야! (행복의 찬사)", "Worst day ever.", "최악의 날이라는 반대말이에요.", "School starts now.", "쉬는 시간 끝났다는 찬물이에요."),
        make_turn(5, "Leo", "🦁", "I'm gonna push the tire swing in a giant spinning whirlpool! 3, 2, 1!", "내가 타이어 그네를 거대한 회오리처럼 뱅글뱅글 밀어줄게! 3, 2, 1!",
                  '"손잡이 꽉 잡아!"라고 구동사 hang on을 써서 외쳐보세요!', "Hang on tight!",
                  "Holding on with both hands! Wheeeeee, we're flying through the clouds!", "두 손으로 꽉 잡았어! 우와아아 우리 구름 속을 나는 것 같아!",
                  '구동사 "Hang on"은 손으로 무언가를 꽉 붙잡거나, 잠깐 멈춰 기다릴 때 "Hang on tight!(꽉 잡아!)"로 일상에서 쓰입니다.',
                  "손잡이 꽉 잡아! (안전 필수 구동사)", "Let go now.", "손 놓으라는 위험한 말이에요.", "Close your eyes.", "눈 감으라는 엉뚱한 말이에요."),
        make_turn(6, "Leo", "🦁", "The warning whistle blew! Our feet are wobbling, let's step down onto the grass!", "마무리 호루라기 불렸다! 다리 후들거리는데, 잔디밭으로 얼른 발 내리자!",
                  '"그네에서 조심히 내려!"라고 구동사 get off를 써서 말해보세요!', "Get off carefully!",
                  "Stuck the landing without falling! That was the greatest spin of fourth grade!", "안 넘어지고 착지 성공! 4학년 최고의 그네 스핀이었다!",
                  '구동사 "get off"는 그네, 놀이기구, 자전거, 버스 등에서 "내리다"라고 할 때 매일 쓰는 필수 구동사입니다.',
                  "조심히 내려와! (하차 및 착지 필수 구동사)", "Jump on high roof.", "높은 지붕 위로 뛰라는 오답이에요.", "Spin for ten hours.", "10시간 동안 돌라는 오답이에요."),
        make_turn(7, "Leo", "🦁", "The school warning bell just rang three times! Look, our orange windbreaker jackets are still sitting on the wooden bench!", "학교 마무리 종 세 번 울렸다! 봐봐, 우리 주황색 바람막이 재킷이 나무 벤치에 아직 있어!",
                  '"겉옷 챙겨!"라고 기본동사 grab을 써서 외쳐보세요!', "Grab your jacket!",
                  "Zipped up and sprinting! We made it through the gym double doors with ten seconds to spare!", "지퍼 올리고 전력 질주! 10초 남기고 체육관 문 통과 세이프다!",
                  '기본동사 "grab"은 바쁘거나 급할 때 물건을 "재빨리 챙기다/집다"라는 뜻으로 미국 아이들과 어른들이 매일 쓰는 대표적 기본동사입니다.',
                  "겉옷 챙겨! (소지품 수거 필수 기본동사)", "Leave jacket in the dirt.", "흙에 버려두라는 오답이에요.", "Tear the zipper off.", "지퍼 찢으라는 오답이에요.")
    ]),

    make_ep("t2_e2", "tier2", "급식실 자리 맡기", "📍 Episode 2/10: Cafeteria Seat Rescue", "cafeteria", [
        make_turn(1, "Penny", "🐧", "The cafeteria is packed! I'm heading over to get chocolate milk!", "급식실 꽉 찼어! 나 초코우유 가져오러 갈게!",
                  '"내 자리 좀 맡아줘!"라고 부탁해보세요!', "Save me a seat!",
                  "Got your back! I'll put my jacket right on this chair!", "맡겨둬! 이 의자에 내 겉옷 딱 올려놓을게!",
                  '급식실, 영화관, 버스에서 자리를 지켜달라고 부탁할 때 가장 빈번히 쓰이는 표현입니다.',
                  "자리 맡아줘! (자리 선점 요청)", "Sit down alone.", "혼자 앉으라는 차가운 말이에요.", "I dislike milk.", "우유 싫다는 딴소리예요."),
        make_turn(2, "Penny", "🐧", "Here comes someone eyeing this empty chair... But I told them it's taken!", "누가 이 빈자리 쳐다보면서 오길래... 이미 사람 있다고 말해줬지!",
                  '"너 진짜 짱이다!"라고 칭찬해보세요!', "You rock!",
                  "Haha, anytime! Best friends sit together, always!", "하하 언제든! 절친은 무조건 같이 앉아야지!",
                  '상대방이 고마운 행동을 했을 때 가볍고 기분 좋게 칭찬하는 표현입니다.',
                  "너 진짜 짱이야! (친근한 극찬)", "You are a stone.", "너는 돌이라는 직역 오역이에요.", "Excuse me.", "자리 비켜달라는 말이에요."),
        make_turn(3, "Penny", "🐧", "Guess what? Today is double pizza Friday! They gave us two huge slices!", "너 그거 알아? 오늘 피자 두 배 금요일이라 큰 조각 두 개씩 줬어!",
                  '"말도 안 돼, 실화야?"라고 깜짝 놀라보세요!', "No way!",
                  "Yes way! Look at all this melted gooey cheese!", "진짜라니까! 이 흘러내리는 끈적한 치즈 좀 봐!",
                  '믿기지 않는 좋은 소식을 들었을 때 턱 빠지게 놀라며 외치는 필수 리액션입니다.',
                  "말도 안 돼! 실화야? (깜짝 리액션)", "I knew that.", "재미없게 아는 척하는 말이에요.", "Pizza is round.", "피자는 둥글다는 뜬금없는 말이에요."),
        make_turn(4, "Penny", "🐧", "I got garlic breadsticks, but I really wanted chocolate pudding like yours!", "난 마늘빵 스틱 받았는데, 사실 너처럼 초코 푸딩 먹고 싶었거든!",
                  '"나랑 바꾸자!"라고 신나게 제안해보세요!', "Trade ya!",
                  "Deal! Warm breadsticks for cold pudding! Win-win!", "콜! 따끈한 마늘빵이랑 시원한 푸딩 맞교환! 윈윈이다!",
                  '급식실이나 놀이터에서 간식을 맞바꿀 때 아이들이 리드미컬하게 외치는 슬랭입니다.',
                  "나랑 바꾸자! (신나는 간식 교환)", "I keep everything.", "욕심부리는 쌀쌀맞은 말이에요.", "Throw it away.", "버리라는 나쁜 말이에요."),
        make_turn(5, "Penny", "🐧", "Our trays are settled and the pizza cheese is still warm and stretchy!", "우리 식판 자리 잡았고 피자 치즈 아직 따끈따끈 쭉 늘어나!",
                  '"얼른 맛있게 다 먹자!"라고 구동사 eat up을 써서 말해보세요!', "Eat up!",
                  "Om nom nom! The pepperoni crunch is out of this world! Best cafeteria Friday!", "냠냠 쩝쩝! 페퍼로니 바삭함이 완전 천상계야! 최고의 급식 금요일이다!",
                  '구동사 "eat up"은 접시의 음식을 "맛있게 남김없이 다 먹다"라는 뜻으로 식사 시간마다 쓰이는 대표 구동사입니다.',
                  "얼른 다 먹자! (맛있는 식사 필수 구동사)", "Drop the tray.", "식판 엎으라는 나쁜 말이에요.", "Never eat cheese.", "치즈 먹지 말라는 오답이에요."),
        make_turn(6, "Penny", "🐧", "Lunch period is ending in two minutes! Look at all these empty milk cartons and napkins!", "점심시간 2분 남았어! 빈 우유갑이랑 냅킨 널려 있는 것 좀 봐!",
                  '"쓰레기통에 버리자!"라고 기본동사 put을 써서 정리해보세요!', "Put them in the trash!",
                  "Tray cleared and stacked on the conveyor belt! We're ready for recess sprint!", "식판 싹 비워서 퇴식구 벨트에 착착 쌓았어! 이제 쉬는 시간 달리기 갈 준비 완료!",
                  '기본동사 "put"은 물건을 특정 장소에 "놓다/넣다"라는 의미로 쓰레기 분리수거나 자리 정돈 시 매일 쓰입니다.',
                  "쓰레기통에 버리자! (정리 및 청결 기본동사)", "Leave trash on floor.", "바닥에 버리라는 오답이에요.", "Eat empty carton.", "우유갑 씹어 먹으라는 오답이에요."),
        make_turn(7, "Penny", "🐧", "Trays are cleared into the recycling bin! Look at Mr. Davis raising the silent hand signal for fourth graders!", "식판 재활용 통에 다 치웠어! 데이비스 선생님이 4학년들 조용히 손 드는 신호 하신다!",
                  '"줄 서러 가자!"라고 구동사 get in line을 써서 제안해보세요!', "Let's get in line!",
                  "Standing quietly behind Maya! Fourth grade is officially the best-behaved table today!", "마야 뒤에 얌전히 섰어! 오늘 4학년이 공식적으로 가장 모범 테이블이야!",
                  '구동사 "get in line"(줄을 서다)은 학교나 식당, 놀이공원에서 차례를 지킬 때 매일 쓰는 최고빈도 구동사입니다.',
                  "줄 서러 가자! (줄서기 필수 구동사)", "Cut in front of everyone.", "새치기하라는 나쁜 오답이에요.", "Hide under the table.", "식탁 밑에 숨자는 오답이에요.")
    ]),

    make_ep("t2_e3", "tier2", "피구 경기 작전", "📍 Episode 3/10: Dodgeball Tactics", "tag", [
        make_turn(1, "Leo", "🦁", "The other team's captain has the red rubber ball! He's targeting me!", "상대 팀 주장이 빨간 고무공 잡았어! 나를 노리고 있어!",
                  '"몸 숙여!"라고 긴박하게 외쳐보세요!', "Duck down!",
                  "Whoosh! The ball shaved my hair and hit the wall! Safe!", "쉭! 공이 내 머리칼을 스치고 벽을 맞췄어! 세이프!",
                  '날아오는 공이나 장애물을 피할 때 반사적으로 외치는 안전 구호입니다.',
                  "숙여! (긴박한 위험 회피)", "Catch with face.", "얼굴로 잡으라는 위험한 말이에요.", "I like turtles.", "거북이 좋다는 딴소리예요."),
        make_turn(2, "Leo", "🦁", "The ball bounced right to your feet! You've got the golden shot!", "공이 네 발밑으로 튕겨왔어! 너한테 황금 슛 찬스가 왔어!",
                  '"나한테 맡겨!"라고 자신감을 뿜어보세요!', "I got this.",
                  "Fire away! Aim for their back line!", "던져! 쟤네 뒷라인을 노리는 거야!",
                  '자신이 책임을 지고 해결할 수 있을 때 가장 멋있게 외치는 표현입니다.',
                  "나한테 맡겨! (자신감 넘치는 해결)", "I have a pen.", "펜 있다는 뜬금없는 말이에요.", "Run away crying.", "울면서 도망치라는 오답이에요."),
        make_turn(3, "Leo", "🦁", "Boom! You tagged both of their defenders in one single throw!", "쾅! 네가 한 방에 상대 수비수 두 명을 다 맞혀서 아웃시켰어!",
                  '"우리가 이기고 있어!"라고 분위기를 띄워보세요!', "We're on fire!",
                  "Unstoppable! We're winning the championship trophy today!", "누구도 못 막아! 오늘 우승 트로피는 무조건 우리 거다!",
                  '스포츠나 게임에서 신들린 듯 엄청난 기세를 탈 때 외치는 대표 슬랭입니다.',
                  "우리 지금 완전 날아다녀! (기세등등)", "Call the fire truck.", "소방차 부르라는 직역 오역이에요.", "I surrender.", "항복한다는 패배자 말이에요."),
        make_turn(4, "Leo", "🦁", "Their last player is cornered near the bleachers! Don't let him catch the rebound!", "상대 마지막 선수가 관람석 구석에 몰렸어! 리바운드 공 못 잡게 해!",
                  '"우리 다 이겼다!"라고 승리를 확신해보세요!', "We got this in the bag!",
                  "Final throw... Direct hit! Dodgeball legends of fourth grade!", "마지막 슛... 명중! 4학년 피구 레전드 등극이다!",
                  '승리나 성공이 100% 확실해졌을 때 "다 잡은 경기야, 따놓은 당상이야"라고 외치는 표현입니다.',
                  "다 잡은 승리야! (승리 확정)", "Put ball in bag.", "공을 가방에 넣으라는 오역이에요.", "Good luck next year.", "내년을 기약하자는 패배 말이에요."),
        make_turn(5, "Leo", "🦁", "Their tallest thrower is winding up his arm like a catapult! Look at that spin!", "상대 최장신 투수가 투석기처럼 팔을 휘두르고 있어! 회전 먹인 것 좀 봐!",
                  '"날아오는 공 조심해!"라고 구동사 watch out을 써서 외쳐보세요!', "Watch out for the ball!",
                  "Dived right onto the wooden floor! It zipped an inch above my ear!", "마룻바닥으로 바로 슬라이딩 다이빙했다! 귀 위 1인치로 쌩 지나갔어!",
                  '구동사 "watch out for ~"는 날아오는 물체나 위험을 "조심하다/주의하다"라는 뜻으로 경기장 필수 구동사입니다.',
                  "공 날아온다 조심해! (위험 경고 필수 구동사)", "Catch ball with teeth.", "이빨로 잡으라는 위험한 말이에요.", "Close eyes and sleep.", "눈 감고 자라는 오답이에요."),
        make_turn(6, "Leo", "🦁", "The final whistle blew! Five gym rubber balls are rolling around the center line!", "종료 호루라기 불렸다! 체육관 고무공 5개가 중앙선 근처에 굴러다녀!",
                  '"체육관 정리정돈하자!"라고 구동사 clean up을 써서 말해보세요!', "Let's clean up the gym!",
                  "Tossing the red balls into the wire storage cart! Ready for the trophy ceremony!", "철제 보관 카트에 빨간 공 다 던져 넣었어! 이제 트로피 수여식 준비 완료!",
                  '구동사 "clean up"은 놀이나 운동 후 주변을 "치우다/정리하다"라는 뜻으로 학교와 체육 시간에 매일 씁니다.',
                  "체육관 정리하자! (정리정돈 필수 구동사)", "Kick the teacher.", "선생님 차라는 나쁜 말이에요.", "Pop all the balls.", "공 다 터뜨리라는 오답이에요."),
        make_turn(7, "Leo", "🦁", "We dodged five balls and knocked out their captain with that double bounce shot! We only have one opponent left!", "우리 공 5개나 피하고 더블 바운스 슛으로 쟤네 주장 잡았어! 상대 딱 한 명 남았다!",
                  '"계속 이렇게 잘해보자!"라고 구동사 keep it up을 써서 팀원을 응원해보세요!', "Keep it up!",
                  "Focus locked! He throws... DODGED! Ball caught! WE WON THE DODGEBALL TOURNAMENT!", "집중력 풀가동! 걔가 던진다... 피했다! 공 낚아챘다! 우리가 피구 토너먼트 우승했어!",
                  '구동사 "keep it up"(지금처럼 계속 잘해라/유지해라)은 스포츠 경기나 시험공부 중인 친구를 북돋울 때 전 세계에서 가장 많이 쓰는 격려 표현입니다.',
                  "계속 이렇게 잘해보자! (격려와 지속 필수 구동사)", "Give up right now.", "지금 당장 포기하라는 패배주의 오답이에요.", "Throw ball at the referee.", "심판에게 공 던지라는 반칙 오답이에요.")
    ]),

    make_ep("t2_e4", "tier2", "만화책 스포 방어", "📍 Episode 4/10: Comic Spoiler Shield", "comic", [
        make_turn(1, "Sammy", "🦊", "I just finished Volume 5 of Galactic Ninja! You won't believe who the villain is!", "나 은하 닌자 5권 방금 다 읽었어! 악당이 누군지 들으면 너 기절할걸!",
                  '"스포일러 하지 마!"라고 단호하게 방어해보세요!', "No spoilers!",
                  "Okay okay, mouth zipped! I won't ruin the epic twist!", "알았어 입 닫을게! 소름 돋는 반전 절대 안 망칠게!",
                  '영화나 만화의 결말을 미리 밝히지 말라고 차단할 때 외치는 만능 단어입니다.',
                  "스포 금지! (단호한 결말 방어)", "Tell me everything.", "결말 다 말해달라는 반대말이에요.", "I can't read.", "글 못 읽는다는 엉뚱한 말이에요."),
        make_turn(2, "Sammy", "🦊", "Can I at least tell you which page has the giant robot explosion?", "대형 로봇 폭발하는 명장면이 몇 페이지인지는 알려줘도 돼?",
                  '"절대 안 돼! 힌트도 주지 마!"라고 차단해보세요!', "Don't even think about it!",
                  "Fine! You're gonna scream on page 87 though!", "알았다고! 그래도 너 87쪽 펼치면 소리 지르게 될걸!",
                  '상대방이 장난스레 선을 넘으려 할 때 "꿈도 꾸지 마!"라고 유쾌하게 쐐기를 박는 표현입니다.',
                  "꿈도 꾸지 마! (장난스런 원천 차단)", "I think deeply.", "깊이 생각한다는 엉뚱한 말이에요.", "Where is my comic?", "내 만화책 어디 있냐는 말이에요."),
        make_turn(3, "Sammy", "🦊", "Here, borrow my copy! Read it tonight so we can talk about it tomorrow!", "여기 내 책 빌려줄게! 오늘 밤에 읽고 내일 신나게 얘기하자!",
                  '"빌려줘서 고마워!"라고 감사 인사를 해보세요!', "Thanks for lending it!",
                  "Take good care of it! It's the first print collector's edition!", "소중히 다뤄줘! 이거 초판 한정판 소장용이거든!",
                  '친구에게 물건이나 책을 빌릴 때 고마운 마음을 정확하게 표현하는 문장입니다.',
                  "빌려줘서 고마워! (감사 표현)", "I will tear it.", "찢겠다는 악당 같은 말이에요.", "I hate reading.", "독서 싫다는 딴소리예요."),
        make_turn(4, "Sammy", "🦊", "Wait, don't bend the corner of page 87! Use this shiny holographic bookmark!", "잠깐, 87쪽 모서리 접지 마! 이 반짝이는 홀로그램 책갈피 써!",
                  '"약속할게!"라고 친구의 소중한 만화책을 지켜주세요!', "Cross my heart!",
                  "Phew! That bookmark was a limited convention drop! Happy reading tonight!", "휴 안심이다! 그 책갈피 행사 한정판이었거든! 오늘 밤 재밌게 읽어!",
                  '아이들이 가슴에 손을 얹으며 진심으로 약속을 지키겠다고 다짐할 때 쓰는 관용구입니다.',
                  "진심으로 약속할게! (진정성 있는 다짐)", "My heart hurts.", "심장이 아프다는 엉뚱한 말이에요.", "Throw comic book.", "만화책 던지라는 나쁜 말이에요."),
        make_turn(5, "Sammy", "🦊", "The bell is ringing and your backpack is bulging with folders! Where does the comic book go?", "종 치는데 네 가방 파일로 빵빵해! 이 만화책 어디다 넣을 거야?",
                  '"가방 속에 잘 넣어둘게!"라고 구동사 put away를 써서 안심시켜보세요!', "I'll put it away!",
                  "Safe inside the padded sleeve! Zero bent corners guaranteed!", "폭신한 안감 포켓에 쏙 넣었어! 모서리 구김 0% 보장 완료!",
                  '구동사 "put away"는 책이나 귀중품을 제자리에 "조심스럽게 넣어두다/정리하다"라는 뜻으로 쓰입니다.',
                  "가방에 잘 넣어둘게! (수납 필수 구동사)", "Drop in puddle.", "웅덩이에 빠뜨리라는 악담이에요.", "Fold in half.", "반으로 접으라는 무서운 오답이에요."),
        make_turn(6, "Sammy", "🦊", "Tomorrow after school, bring the comic book back to my locker so we can trade for Volume 6!", "내일 방과 후에 6권이랑 바꾸게 내 사물함으로 만화책 다시 가져와!",
                  '"내일 꼭 돌려줄게!"라고 구동사 give back을 써서 약속해보세요!', "I'll give it back tomorrow!",
                  "Awesome! Volume 6 has the secret shadow ninja reveals! See you tomorrow at locker 104!", "나이스! 6권에 그림자 닌자 비밀 다 풀려! 내일 104번 사물함에서 보자!",
                  '구동사 "give back"은 빌린 물건을 원래 주인에게 "돌려주다/반납하다"라는 뜻의 최상위 빈도 구동사입니다.',
                  "내일 꼭 돌려줄게! (반납과 신뢰 필수 구동사)", "Keep it forever.", "평생 안 돌려주겠다는 도둑 심보예요.", "Tear out pages.", "페이지 찢겠다는 오답이에요."),
        make_turn(7, "Sammy", "🦊", "Wait, on page 88... you won't believe what the robot sidekick reveals about the shadow master...", "잠깐, 88쪽에... 로봇 조수가 그림자 마스터에 대해 뭘 밝히는지 들으면 너 절대 안 믿길걸...",
                  '"나한테 말해주지 마!"라고 기본동사 tell을 써서 스포일러를 방어해보세요!', "Don't tell me!",
                  "Zipping my lips! You have to read the giant battle scene yourself tonight! No spoilers, promise!", "입술 지퍼 꽉 잠갔다! 오늘 밤에 거대 전투 씬 직접 봐야 해! 스포 절대 안 해, 약속!",
                  '기본동사 "tell"을 활용한 "Don\'t tell me!"(말하지 마! 스포하지 마!)는 영화나 책의 결말을 듣기 싫을 때 미국인들이 입버릇처럼 외치는 표현입니다.',
                  "나한테 말해주지 마! (스포일러 차단 기본동사)", "Tell me the whole ending.", "결말 다 말해달라는 반대말이에요.", "Rip page 88 out.", "88페이지 찢으라는 악행이에요.")
    ]),

    make_ep("t2_e5", "tier2", "쉬는 시간 1등 달리기", "📍 Episode 5/10: Recess 100m Sprint", "tag", [
        make_turn(1, "Sammy", "🦊", "Line up at the red brick line! Race all the way to the big oak tree!", "빨간 벽돌 선에 발 맞춰! 저기 큰 참나무까지 전력 달리기 시합이야!",
                  '"내가 이길걸!"이라고 유쾌하게 도발해보세요!', "You're going down!",
                  "Oh, it is ON! Don't trip over your shoelaces!", "오, 한판 제대로 붙어보자고! 신발 끈이나 밟지 마라!",
                  '경기나 승부 전에 "너 패배할 준비나 해!"라며 익살스럽고 자신만만하게 던지는 슬랭입니다.',
                  "너 오늘 각오해! (유쾌한 승부 도발)", "You are flying up.", "위로 날아간다는 직역 오역이에요.", "I like bricks.", "벽돌 좋아한다는 딴소리예요."),
        make_turn(2, "Sammy", "🦊", "Look at you sprint! You're zooming like a sports car!", "너 뛰는 것 좀 봐! 스포츠카처럼 날아가는데?!",
                  '"나 못 잡을걸!"이라고 신나게 약 올려보세요!', "Can't catch me!",
                  "Wait for me! My sneakers slipped on the gravel!", "기다려! 자갈밭에서 내 운동화가 헛돌았단 말이야!",
                  '술래잡기나 달리기에서 앞서 나갈 때 신나게 외치는 장난기 넘치는 도발입니다.',
                  "나 못 잡을걸! (신나는 달리기 도발)", "Please grab my shirt.", "내 옷 잡으라는 위험한 말이에요.", "Stop the world.", "세상을 멈추라는 오역이에요."),
        make_turn(3, "Sammy", "🦊", "Pant, pant... We both touched the oak bark at the exact same split second!", "헉, 헉... 우리 둘 다 정확히 똑같은 찰나에 참나무 껍질을 터치했어!",
                  '"무승부다, 비겼어!"라고 결과를 외쳐보세요!', "It's a tie!",
                  "Rematch tomorrow! First one to touch the swing set wins!", "내일 리매치 재대결이다! 그네 먼저 찍는 사람이 진짜 1등!",
                  '승부에서 동점이나 무승부가 되었을 때 쓰는 필수 단어입니다.',
                  "비겼다! 동점이야! (깔끔한 무승부 선언)", "Tie my shoelaces.", "신발 끈 묶으라는 오역이에요.", "I won three million dollars.", "거짓말이에요."),
        make_turn(4, "Sammy", "🦊", "That sprint was intense! Look, my shoelace is completely undone!", "이번 달리기 진짜 빡셌다! 봐봐, 내 신발 끈 아예 다 풀렸어!",
                  '"잠깐 멈춰봐!"라고 친구를 세워주세요!', "Hold up!",
                  "Phew, good eye! I almost tripped on that tree root! Tying a double knot now!", "휴, 잘 봤다! 저기 나무뿌리에 걸려 넘어질 뻔했네! 두 번 꽉 묶는 중!",
                  '친구가 위험하거나 급할 때 "잠깐만 멈춰봐, 기다려봐"라고 제지하는 생생한 구어체입니다.',
                  "잠깐 멈춰봐! (순간 정지 제지)", "Hold my hand forever.", "영원히 손잡자는 오역이에요.", "Kick my shoe away.", "신발 차버리라는 나쁜 말이에요."),
        make_turn(5, "Sammy", "🦊", "The recess warning buzzer is buzzing! The class doors are fifty meters away!", "쉬는 시간 끝나는 버저 울린다! 교실 문까지 아직 50미터나 남았어!",
                  '"얼른 서두르자!"라고 구동사 hurry up을 써서 달려보세요!', "Hurry up!",
                  "Sprinting through the hallway! We made it through the door right before the final bell!", "복도로 전력 질주! 마지막 종 치기 직전에 교실 문 쏙 통과했다!",
                  '구동사 "Hurry up"은 시간이나 상황이 촉박할 때 "서둘러!", "빨리!"라고 재촉하는 일상 1위 구동사입니다.',
                  "서둘러, 빨리 가자! (속도 촉구 필수 구동사)", "Walk as slow as a snail.", "달팽이처럼 걸으라는 오답이에요.", "Lie down on track.", "트랙에 누우라는 오답이에요."),
        make_turn(6, "Sammy", "🦊", "Both of us are sweating after sprinting across the soccer field in sixty seconds!", "축구장 가로질러 60초 만에 달렸더니 우리 둘 다 땀 뻘뻘 흘린다!",
                  '"숨 좀 돌리고 가자!"라고 기본동사 catch를 써서 말해보세요!', "Let's catch our breath!",
                  "Inhale, exhale! Heart rates returning to normal! That was fourth grade track gold medal sprint!", "들이마시고 내쉬고! 심장 박동 정상으로 돌아오는 중! 4학년 육상 금메달급 질주였어!",
                  '기본동사 "catch"를 활용한 "Catch one\\\'s breath"(숨을 고르다/돌리다)는 운동이나 달리기 후 숨찰 때 매일 쓰는 필수 관용구입니다.',
                  "숨 좀 고르자! (호흡 회복 기본동사)", "Stop breathing forever.", "숨 쉬지 말라는 무서운 오답이에요.", "Run ten more laps.", "10바퀴 더 뛰라는 탈진 오답이에요."),
        make_turn(7, "Sammy", "🦊", "Our lungs are burning and Sammy is sprinting right at our heels! Only ten meters to the finish line fence!", "우리 폐 터질 것 같고 새미가 바로 뒤꿈치까지 쫓아왔어! 결승선 울타리까지 딱 10미터 남았다!",
                  '"절대 포기하지 마!"라고 구동사 give up을 써서 버텨보세요!', "Don't give up!",
                  "Pushed with everything I had! Touched the fence post first! We won the recess sprint championship!", "남은 힘 다 쥐어짜냈다! 울타리 기둥 먼저 찍었다! 우리가 쉬는 시간 달리기 챔피언이야!",
                  '구동사 "give up"은 "포기하다"라는 뜻으로, 부정어 Don\'t와 결합된 "Don\'t give up!"(포기하지 마!)은 역경과 승부에서 가장 감동적인 필수 표현입니다.',
                  "절대 포기하지 마! (불굴의 용기 필수 구동사)", "Stop and lie down.", "누워서 포기하라는 오답이에요.", "Run backwards into the mud.", "진흙으로 뒷걸음질 치라는 오답이에요.")
    ]),

    make_ep("t2_e6", "tier2", "포켓몬 카드 교환", "📍 Episode 6/10: Legendary Card Trade", "toybox", [
        make_turn(1, "Penny", "🐧", "Look at this shiny Charizard card! It's super rare!", "이 반짝이는 리자몽 카드 좀 봐! 완전 초희귀 카드야!",
                  '"얼마나 가치 있는 거야?"라고 가치를 물어보세요!', "What's it worth?",
                  "It's worth fifty trading points! Everyone in 4th grade wants it!", "교환 포인트 50점짜리야! 4학년 전교생이 탐내고 있어!",
                  '카드나 장난감의 희소성이나 가격, 가치를 물을 때 쓰는 자연스러운 표현입니다.',
                  "얼마나 가치 있어? (가치 확인)", "How many money?", "문법이 완전히 틀린 말이에요.", "Charizard is green.", "리자몽 초록색이라는 오답이에요."),
        make_turn(2, "Penny", "🐧", "I'll trade it for your rainbow Pikachu and two energy cards!", "네 무지개 피카츄 카드랑 에너지 카드 두 장이랑 바꿀래!",
                  '"합당한 거래네, 좋아!"라고 공정함을 칭찬하세요!', "Fair deal.",
                  "Awesome! Slide them into the protective plastic sleeves!", "신난다! 투명 보호 비닐 슬리브에 쏙 집어넣자!",
                  '교환 조건이 서로에게 공평하고 만족스러울 때 깔끔하게 합의하는 구어체입니다.',
                  "공평한 거래네! (만족스러운 합의)", "Unfair thief.", "도둑이라고 욕하는 말이에요.", "I don't play cards.", "카드 안 한다는 딴소리예요."),
        make_turn(3, "Penny", "🐧", "Whoa, this rainbow foil reflects like a disco ball under the sun!", "우와, 이 무지개 홀로그램이 햇빛 받으니까 미러볼처럼 빛나!",
                  '"완전 보물이다!"라고 감탄해보세요!', "Total treasure!",
                  "Best trade of the entire school year! High five!", "이번 학년 통틀어 역대 최고의 카드 트레이드였다! 하이파이브!",
                  '얻은 물건이 너무 소중하고 귀할 때 극찬하는 표현입니다.',
                  "완전 보물이야! (소중한 득템 감탄)", "Total trash.", "완전 쓰레기라는 반대말이에요.", "I lost my shoes.", "신발 잃어버렸다는 딴소리예요."),
        make_turn(4, "Penny", "🐧", "Someone offered me four bent cards for this shiny one yesterday...", "어제 누가 이 반짝이 카드에 구겨진 카드 네 장 주겠다고 했거든...",
                  '"완전 사기잖아, 바가지야!"라고 비판해주세요!', "What a rip-off!",
                  "Right? Good thing I walked away! Best friends trade fair and square!", "그치? 나 그냥 가버리길 진짜 잘했지! 찐친끼리는 정정당당하게 교환해야지!",
                  '거래나 가격 조건이 터무니없이 불공평하거나 사기 같을 때 외치는 대표 슬랭입니다.',
                  "완전 바가지 사기네! (불공정 거래 비판)", "Rip my shirt.", "옷 찢으라는 오역이에요.", "I love bent cards.", "구겨진 카드 좋다는 이상한 말이에요."),
        make_turn(5, "Penny", "🐧", "A fourth grader from the next class is offering his secret gold box for our Pikachu!", "옆 반 4학년이 우리 피카츄 카드에 자기 비밀 골드 박스 주겠다고 제안하는데!",
                  '"조금 더 신중하게 생각해 봐!"라고 기본동사 think를 써서 조언해보세요!', "Think it over!",
                  "You're right! Gold boxes usually have cheap duplicate cards! Walking away!", "네 말이 맞아! 골드 박스엔 보통 싸구려 중복 카드만 들었잖아! 안 바꾼다!",
                  '기본동사 "think"를 활용한 "Think it over"(차분히 심사숙고해봐)는 성급한 결정을 막을 때 쓰는 필수 조언 표현입니다.',
                  "신중히 더 생각해 봐! (심사숙고 기본동사)", "Trade immediately blind.", "안 보고 당장 바꾸라는 무모한 오답이에요.", "Throw card in puddle.", "웅덩이에 카드 버리라는 오답이에요."),
        make_turn(6, "Penny", "🐧", "The trade is locked! Slide the holographic cards into plastic hard-cases so the corners stay razor sharp!", "교환 완료! 모서리 각 칼각으로 유지되게 플라스틱 하드케이스에 쏙 넣어!",
                  '"안전하게 잘 보관하자!"라고 구동사 hold on to를 써서 말해보세요!', "Let's hold on to them!",
                  "Stored safely in my top binder pocket! These cards will be worth gold in ten years!", "바인더 맨 위 포켓에 안전하게 모셔뒀어! 이 카드들 10년 뒤에 금값이 될걸!",
                  '구동사 "hold on to"는 가치 있는 수집품이나 물건을 팔지 않고 "소중히 간직하다/보유하다"라는 뜻으로 매일 쓰입니다.',
                  "소중하게 잘 간직하자! (보유 및 간직 필수 구동사)", "Bend all corners.", "모서리 다 구기라는 나쁜 말이에요.", "Spill water on cards.", "카드에 물 쏟으라는 오답이에요."),
        make_turn(7, "Penny", "🐧", "The holographic Charizard is safely in your sleeve! Wanna see my vintage Japanese Pikachu binder?", "홀로그램 리자몽 카드 네 슬리브에 안전하게 넣었어! 내 빈티지 일본판 피카츄 바인더도 구경해볼래?",
                  '"한번 구경해보자!"라고 구동사 check out을 써서 말해보세요!', "Let's check it out!",
                  "Flipping to page one! Look at that 1999 gold-stamped thunderbolt card! Pure nostalgia!", "1페이지 펼친다! 저 1999년 황금 도장 찍힌 번개 카드 봐봐! 완전 감성 터진다!",
                  '구동사 "check out"은 물건이나 장면을 "확인하다/살펴보다/구경하다"라는 뜻으로 미국 10대와 초등생들이 매일 쓰는 구동사 1위입니다.',
                  "한번 구경해보자! (탐색과 확인 필수 구동사)", "Throw binder in the trash.", "바인더 쓰레기통에 버리라는 오답이에요.", "Rip all cards in half.", "카드 반으로 찢으라는 오답이에요.")
    ]),

    make_ep("t2_e7", "tier2", "깜빡한 숙제 위기", "📍 Episode 7/10: Homework Crunch Time", "classroom", [
        make_turn(1, "Leo", "🦁", "Did you finish the three-page dinosaur science worksheet for Mr. Davis?", "데이비스 선생님 공룡 과학 워크시트 세 장짜리 다 풀었어?",
                  '"완전 깜빡 잊고 있었어!"라고 머리를 감싸 쥐어보세요!', "It slipped my mind!",
                  "We have ten minutes before the morning bell! Grab your pencil quick!", "아침 조회 종 치기까지 10분 남았어! 연필 얼른 쥐어!",
                  '해야 할 일이나 약속을 깜빡 잊었을 때 미국인들이 가장 세련되게 쓰는 표현입니다.',
                  "완전 깜빡했어! (세련된 망각 고백)", "My brain fell out.", "뇌가 떨어졌다는 직역 오역이에요.", "Science is ancient.", "과학은 고대라는 딴소리예요."),
        make_turn(2, "Leo", "🦁", "Question one: What dinosaur had three giant horns on its face?", "1번 문제: 얼굴에 커다란 뿔 세 개 달린 공룡은?",
                  '"트리케라톱스야!"라고 정답을 외쳐보세요!', "Triceratops!",
                  "Boom, nailed question one! Question two: What did Stegosaurus eat?", "좋았어 1번 정답 해결! 2번 문제: 스테고사우루스는 뭘 먹었을까요?",
                  '퀴즈나 문제의 정답을 확신을 가지고 시원하게 맞힐 때 외치는 단어입니다.',
                  "트리케라톱스! (시원한 정답)", "Hamburger and fries.", "햄버거 먹는다는 오답이에요.", "I don't know dinosaurs.", "모른다는 포기예요."),
        make_turn(3, "Leo", "🦁", "Five questions left and the two-minute warning chime is ringing!", "문제 다섯 개 남았는데 2분 전 예비 차임벨이 울려!",
                  '"초집중해서 다 끝내자!"라고 집중력을 끌어올리세요!', "Let's lock in!",
                  "Focus mode maximum! Writing with lightning speed!", "초집중 모드 최대 출력! 번개 속도로 글씨 쓰는 중!",
                  '시험 직전이나 급박한 과제를 마주했을 때 딴생각을 버리고 몰입하자고 외치는 최신 Z세대 슬랭입니다.',
                  "초집중해서 끝내자! (몰입과 집중 슬랭)", "Let us play games.", "게임하자는 엉뚱한 말이에요.", "Lock the door forever.", "문 잠그라는 오역이에요."),
        make_turn(4, "Leo", "🦁", "Final question done right as the teacher walked through the door!", "선생님이 교실 문 열고 들어오시는 순간 마지막 문제까지 완료!",
                  '"진짜 아슬아슬하게 세이프였다!"라고 가슴을 쓸어내리세요!', "That was close!",
                  "Phew! Clutch homework victory! High five under the desk!", "휴! 책상 밑에서 몰래 하이파이브! 기적 같은 숙제 성공이다!",
                  '위기 상황을 간발의 차이로 모면했을 때 안도의 한숨을 내쉬며 외치는 대표 표현입니다.',
                  "진짜 아슬아슬했다! (위기 모면 안도)", "The door is close.", "문이 가깝다는 오역이에요.", "Give me a F grade.", "F학점 달라는 오답이에요."),
        make_turn(5, "Leo", "🦁", "Our worksheets are filled with graphite pencil marks! What does the teacher need?", "워크시트 연필로 다 채웠다! 선생님이 지금 뭐라고 하시지?",
                  '"숙제 제출하자!"라고 구동사 turn in을 써서 말해보세요!', "Let's turn it in!",
                  "Placed right on the teacher's corner tray! 100% on time without tardy marks!", "선생님 코너 서류함에 쏙 올려놨어! 지각 도장 없이 100% 정시 제출 완료!",
                  '구동사 "turn in"은 숙제, 시험지, 보고서를 선생님이나 상사에게 "제출하다"라는 뜻의 학교 생활 필수 구동사입니다.',
                  "숙제 제출하자! (과제 제출 필수 구동사)", "Burn the paper.", "종이 태우라는 위험한 오답이에요.", "Hide under desk.", "책상 밑에 숨기라는 오답이에요."),
        make_turn(6, "Leo", "🦁", "Mr. Davis is walking up the aisles collecting papers with his green grading stamp!", "데이비스 선생님이 초록색 채점 도장 들고 복도 지나가시며 종이 걷으신다!",
                  '"얼른 서류함에 올려둬!"라고 기본동사 put을 써서 말해보세요!', "Put it on the desk!",
                  "Slid right under his green stamp! Stamped with a big smiley face! Mission accomplished!", "초록 도장 밑으로 쏙 들어갔어! 커다란 스마일 도장 쾅! 미션 완벽 성공!",
                  '기본동사 "put"은 물건을 특정 위치에 "올려놓다/두다"라는 뜻으로 교실 책상이나 서랍을 가리킬 때 매일 씁니다.',
                  "책상 위에 올려놔! (위치 지정 기본동사)", "Tear into puzzle.", "퍼즐 조각으로 찢으라는 오답이에요.", "Throw out window.", "창밖으로 던지라는 오답이에요."),
        make_turn(7, "Leo", "🦁", "We rushed through the last three division problems on page 42! Handing it to the teacher in thirty seconds!", "42쪽 마지막 세 문제 나눗셈 번개같이 풀었어! 30초 뒤에 선생님께 제출한다!",
                  '"맞았는지 꼭 확인해봐!"라고 구동사 make sure를 써서 점검해보세요!', "Make sure it's right!",
                  "Quick double check... Oops, 7 times 8 is 56, fixed it! Now it's 100% ready for an A-plus!", "초스피드 더블 체크... 앗 7 곱하기 8은 56이지, 고쳤다! 이제 A+ 받을 준비 100% 완료!",
                  '구동사 "make sure"는 "반드시 확인하다/확실하게 하다"라는 뜻으로 숙제나 준비물을 꼼꼼히 챙길 때 매일 쓰는 최고빈도 표현입니다.',
                  "맞았는지 꼭 확인해봐! (점검과 확인 필수 구동사)", "Erase all your hard work.", "공부한 거 싹 지우라는 오답이에요.", "Draw graffiti on the test.", "시험지에 낙서하라는 오답이에요.")
    ]),

    make_ep("t2_e8", "tier2", "아케이드 2인 협동", "📍 Episode 8/10: Arcade Co-op High Score", "arcade", [
        make_turn(1, "Sammy", "🦊", "Grab Player 2 joystick! The boss monster is charging up a plasma beam!", "2P 조이스틱 잡아! 보스 몬스터가 플라즈마 빔 충전 중이야!",
                  '"나 준비 완료야!"라고 당차게 출격 신호를 보내세요!', "Ready when you are!",
                  "Fire missiles on three! One, two, three, blast!", "셋 셀 때 미사일 발사! 하나, 둘, 셋, 쏴라!",
                  '협동 작업이나 게임을 시작할 때 상대방의 준비 상태에 맞춰 완벽히 대기 중임을 알리는 멋진 구어체입니다.',
                  "준비 완전 끝났어! (출격 대기)", "I don't have coins.", "동전 없다는 김빠지는 소리예요.", "The screen is black.", "화면 검다는 딴소리예요."),
        make_turn(2, "Sammy", "🦊", "Whoa, watch the fireballs dropping from the ceiling! Jump left!", "우와 천장에서 떨어지는 불덩이 조심해! 왼쪽으로 점프해!",
                  '"내가 막아줄게, 보호할게!"라고 든든하게 방패를 들어보세요!', "I got your back!",
                  "Shield deployed! Your barrier saved my remaining two lives!", "보호막 전개 완료! 네 방어막이 내 남은 목숨 두 개 살렸어!",
                  '팀원이나 친구를 뒤에서 든든하게 지켜주고 지원하겠다고 안심시키는 최고의 팀워크 표현입니다.',
                  "내가 엄호할게! (든든한 백업)", "I have back pain.", "허리 아프다는 엉뚱한 말이에요.", "Look behind you.", "뒤돌아보라는 혼란 유발이에요."),
        make_turn(3, "Sammy", "🦊", "Boom! The giant shadow dragon shattered into golden coins!", "펑! 거대 그림자 드래곤이 황금 코인으로 산산조각 났어!",
                  '"완벽한 승리다!"라고 환호하며 자축해보세요!', "Flawless victory!",
                  "Zero deaths on stage five! We just set the high score in town!", "5단계 노데스 클리어! 우리 동네 신기록 세웠다!",
                  '흠잡을 데 없이 완벽한 경기력으로 대승을 거두었을 때 자축하는 게이머들의 명대사입니다.',
                  "완벽한 승리야! (무결점 대승 자축)", "We lost completely.", "완패했다는 오답이에요.", "Game over forever.", "영원한 게임오버라는 엉뚱한 말이에요."),
        make_turn(4, "Sammy", "🦊", "The ticket dispenser is spitting out a mile-long ribbon of red prize tickets!", "티켓 배출기에서 빨간 경품 티켓이 리본처럼 1미터 넘게 쏟아져 나와!",
                  '"티켓 다 챙겨!"라고 구동사 pick up을 써서 말해보세요!', "Pick them up!",
                  "Rolling them into a giant ball! We have enough tickets for the giant plush bear!", "왕공처럼 돌돌 마는 중! 대형 곰 인형 바꿀 만큼 티켓 충분해!",
                  '구동사 "pick up"은 쏟아져 나온 티켓이나 물건을 바닥에서 "주워 담다/챙기다"라는 의미로 쓰입니다.',
                  "얼른 다 챙겨! (물건 수거 구동사)", "Burn the tickets.", "티켓 태우라는 이상한 말이에요.", "Leave them behind.", "버려두고 가자는 손해예요."),
        make_turn(5, "Sammy", "🦊", "We carried the giant tickets to the prize counter! The clerk is pulling down the giant plush bear!", "경품 카운터로 티켓 다 들고 왔어! 점원분이 대형 곰 인형 내려주시는 중이야!",
                  '"한번 꼭 안아봐!"라고 기본동사 hold를 써서 건네보세요!', "Hold it tight!",
                  "It's as big as my entire body and so fluffy! Arcade champions of the world!", "내 몸채만 하고 완전 폭신폭신해! 우리가 오락실 세계 챔피언이다!",
                  '기본동사 "hold"는 물건이나 손을 "꼭 잡다/안다"라는 뜻으로 "Hold it tight!(꼭 쥐어봐/안아봐!)"는 일상에서 매일 쓰입니다.',
                  "꼭 안아봐! 꽉 쥐어봐! (포옹과 그립의 기본동사)", "Rip the bear ears.", "귀 찢으라는 오답이에요.", "Throw in trash.", "버리라는 오답이에요."),
        make_turn(6, "Sammy", "🦊", "Look at the claw machine in the front row! The claw grabbed the giant Pikachu by the neck!", "앞줄 인형 뽑기 기계 좀 봐! 집게가 대형 피카츄 목덜미를 딱 잡았어!",
                  '"떨어뜨리지 마!"라고 기본동사 drop을 써서 간절하게 외쳐보세요!', "Don't drop it!",
                  "The claw moved all the way across and released into the chute! We won the arcade jackpot today!", "집게가 출구까지 쭉 이동해서 툭 떨어뜨렸다! 오늘 오락실 잭팟 터졌어!",
                  '기본동사 "drop"은 손이나 기계가 물건을 아래로 "떨어뜨리다"라는 뜻으로 "Don\\\'t drop it!"은 떨어뜨리지 말라는 필수 당부 표현입니다.',
                  "떨어뜨리지 마! (낙하 방지 기본동사)", "Smash the glass.", "유리창 깨라는 난폭한 오답이에요.", "Turn off electricity.", "전기 끄라는 엉뚱한 말이에요."),
        make_turn(7, "Sammy", "🦊", "We're hugging our giant plush bear in the arcade lobby! But the flashing coin token cup is still on top of the machine!", "오락실 로비에서 대형 곰 인형 안고 있어! 근데 반짝이는 동전 토큰 컵이 기계 위에 아직 있잖아!",
                  '"동전 컵 챙겨!"라고 기본동사 take를 써서 챙겨보세요!', "Take the cup!",
                  "Grabbed the red token cup! Five silver tokens left for the racing simulator next weekend!", "빨간 토큰 컵 낚아챘다! 다음 주말 레이싱 시뮬레이터 탈 은색 토큰 다섯 개 남았어!",
                  '기본동사 "take"는 손으로 물건을 "챙기다/가져가다"라는 뜻으로 잊고 갈 뻔한 물건을 챙길 때 매일 쓰는 대표적 표현입니다.',
                  "동전 컵 챙겨! (소지품 수거 필수 기본동사)", "Smash the token cup.", "컵 부수라는 오답이에요.", "Leave silver coins for strangers.", "남에게 코인 버리고 가라는 오답이에요.")
    ]),

    make_ep("t2_e9", "tier2", "생일 파티 초대", "📍 Episode 9/10: Laser Tag Birthday Invite", "tag", [
        make_turn(1, "Penny", "🐧", "My birthday is this Saturday! We booked the giant laser tag arena!", "이번 주 토요일 내 생일이야! 대형 레이저 태그 경기장 통째로 빌렸어!",
                  '"너 토요일에 시간 돼?"라고 일정을 물어보세요!', "Are you free?",
                  "Totally open! I already told my mom to clear the whole afternoon!", "완전 비었지! 나 이미 엄마한테 토요일 오후 비워달라고 말씀드렸어!",
                  '친구에게 약속이나 초대를 건넬 때 일정이 비어 있는지 가장 깔끔하게 묻는 표현입니다.',
                  "시간 돼? (자연스러운 일정 확인)", "Are you cheap?", "너 값싸냐는 심각한 무례예요.", "I am twelve years old.", "나이 뜬금포예요."),
        make_turn(2, "Penny", "🐧", "Awesome! The party starts at two, with neon pizza and double arcade passes!", "신난다! 파티는 2시 시작이고 네온 피자에 오락실 2회권도 줘!",
                  '"무조건 갈게!"라고 흔쾌히 참석을 확정 지어보세요!', "I'll be there!",
                  "Yay! Our neon laser squad is gonna dominate the battlefield!", "야호! 우리 네온 레이저 분대가 경기장 다 쓸어버리자!",
                  '친구의 초대에 확신과 기쁨을 담아 반드시 가겠다고 못 박는 명쾌한 답변입니다.',
                  "무조건 갈게! (확실한 참석 약속)", "I decline coming.", "냉정하게 거절하는 말이에요.", "Where is my shoe?", "신발 찾는 엉뚱한 소리예요."),
        make_turn(3, "Penny", "🐧", "I heard they even have a glowing two-story obstacle castle inside!", "듣자하니 안에 2층짜리 발광 장애물 성벽도 있대!",
                  '"진짜 기대된다! 못 참겠어!"라고 설렘을 표현해보세요!', "Can't wait!",
                  "Me neither! I've been counting down the days on my calendar!", "나도 그래! 나 달력에 매일 동그라미 치면서 세고 있거든!",
                  '다가올 파티나 이벤트를 너무 기대하며 설렐 때 미국인들이 입버릇처럼 쓰는 구어체입니다.',
                  "진짜 기대돼! 못 참겠다! (설렘 폭발)", "I hate waiting.", "기다리는 거 싫다는 불평이에요.", "Time is money.", "시간은 돈이라는 엉뚱한 속담이에요."),
        make_turn(4, "Penny", "🐧", "My mom is baking a giant chocolate volcano cake with sparkler candles!", "우리 엄마가 불꽃 나오는 촛불 꽂은 거대 초콜릿 화산 케이크 굽고 계셔!",
                  '"진짜 대박 재밌을 거야!"라고 축하를 건네보세요!', "It's gonna be a blast!",
                  "The best birthday party of the fourth grade! See you Saturday!", "4학년 최고의 생일 파티가 될 거야! 토요일에 만나!",
                  '파티나 여행이 엄청나게 신나고 재밌을 것이라 확신할 때 쓰는 대표적인 찬사 표현입니다.',
                  "진짜 대박 재밌을 거야! (최고의 파티 예고)", "It will explode dangerously.", "위험하게 폭발한다는 오역이에요.", "Happy New Year.", "새해 인사예요."),
        make_turn(5, "Penny", "🐧", "Our team needs to wear dark sneakers and sneakers with good grip for the ramps!", "우리 팀 경기장 경사로 뛰려면 접지력 좋은 어두운 운동화 신고 와야 해!",
                  '"편한 신발 신고 갈게!"라고 구동사 put on을 써서 답해보세요!', "I'll put them on!",
                  "Perfect! Dark clothes, fast sneakers, laser blasters ready to fire! See ya Saturday!", "완벽해! 어두운 옷에 빠른 신발, 레이저 총 발사 준비 완료! 토요일에 보자!",
                  '구동사 "put on"은 옷, 신발, 모자, 안경 등을 "착용하다/신다"라는 뜻으로 일상에서 가장 자주 쓰이는 핵심 구동사입니다.',
                  "꼭 챙겨 신을게! (의류 착용 필수 구동사)", "Take off shoes.", "신발 벗으라는 오답이에요.", "Throw sneakers.", "신발 던지라는 엉뚱한 말이에요."),
        make_turn(6, "Penny", "🐧", "My mom said she can pick you up from your driveway at 1:30 PM if you need a ride!", "우리 엄마가 너 차 필요하면 1시 30분에 집 앞마당으로 데리러 갈 수 있대!",
                  '"나 태우러 와줘!"라고 구동사 pick up을 써서 부탁해보세요!', "Please pick me up!",
                  "Locked in! We'll honk twice outside your house at one-thirty sharp! Laser tag time!", "일정 픽스! 1시 30분 정각에 집 앞에서 빵빵 두 번 울릴게! 레이저 태그 가보자!",
                  '구동사 "pick [someone] up"은 자동차로 사람을 "데리러 가다/태우다"라는 뜻의 초특급 생활 구동사입니다.',
                  "나 태우러 와줘! (차량 픽업 필수 구동사)", "Leave me alone.", "내버려 두라는 오답이에요.", "Forget my house.", "집 까먹으라는 오답이에요."),
        make_turn(7, "Penny", "🐧", "Everything is set for Saturday laser tag! My mom bought twenty neon glow sticks for our team to wear!", "토요일 레이저 태그 준비 끝! 우리 팀 착용하라고 엄마가 네온 야광봉 20개 사두셨어!",
                  '"야광 팔찌 꼭 차고 올게!"라고 구동사 put on을 써서 화답해보세요!', "I'll put it on!",
                  "Glowing neon green in the dark labyrinth! The birthday countdown is officially on! See you Saturday!", "어두운 미로 속에서 네온 초록빛 뿜어내자! 생일 카운트다운 공식 시작! 토요일에 만나!",
                  '구동사 "put on"은 팔찌, 목걸이, 옷, 모자 등을 "착용하다"라는 의미의 필수 표현입니다.',
                  "꼭 챙겨 차고 갈게! (착용 필수 구동사)", "Snap the glow sticks in half.", "야광봉 부러뜨리라는 오답이에요.", "Stay home in bed.", "집에 누워있겠다는 거절 오답이에요.")
    ]),

    make_ep("t2_e10", "tier2", "비밀 아지트 규칙", "📍 Episode 10/10: Secret Treehouse Vault", "treehouse", [
        make_turn(1, "Leo", "🦁", "Halt! Who goes there? No one enters the treehouse without clearance!", "멈춰라! 누구냐? 허가 없이는 아무도 이 오두막에 못 들어온다!",
                  '"암호가 뭐야?"라고 암구호를 물어보세요!', "What's the password?",
                  "Golden Acorn! Whisper it three times or the trapdoor stays locked!", "황금 도토리! 세 번 속삭여라, 안 그러면 문 안 열어준다!",
                  '비밀 모임이나 아지트에 들어갈 때 재미있게 암호를 묻고 답하는 아동 놀이 표현입니다.',
                  "암호가 뭐야? (비밀 아지트 암호 묻기)", "What is your name?", "이름 묻는 평범한 질문이에요.", "Open the bank.", "은행 열라는 엉뚱한 말이에요."),
        make_turn(2, "Leo", "🦁", "Golden Acorn, Golden Acorn, Golden Acorn! Identity confirmed!", "황금 도토리 세 번 확인! 신원 확인 완료!",
                  '"들어와도 좋아!"라고 문을 활짝 열어주세요!', "You may enter.",
                  "Welcome to Headquarters! Mind your head on the low wooden beam!", "비밀 본부에 온 걸 환영한다! 낮은 나무 기둥에 머리 부딪치지 마!",
                  '허가를 내주거나 문을 열어줄 때 의젓하고 폼나게 건네는 표현입니다.',
                  "들어와도 좋아! (품격 있는 입장 허가)", "Stay outside in rain.", "비 맞고 밖에 있으라는 매정한 말이에요.", "I am asleep.", "자고 있다는 말이에요."),
        make_turn(3, "Leo", "🦁", "Here is our secret map of the neighborhood! Swear to keep it safe?", "여기 우리 동네 비밀 지도야! 절대 아무한테도 안 보여준다고 맹세해?",
                  '"새끼손가락 걸고 약속할게!"라고 단단히 약속하세요!', "Pinky promise?",
                  "Locked with the pinky oath! Not even aliens could make me talk!", "새끼손가락 맹세 봉인 완료! 외계인이 와도 절대 입 안 연다!",
                  '어린이들이 가장 진지하고 엄숙하게 비밀을 지키기로 서약할 때 쓰는 관용 표현입니다.',
                  "새끼손가락 걸고 약속! (엄숙한 비밀 서약)", "Cut my little finger.", "손가락 자르라는 무서운 오역이에요.", "I have five fingers.", "손가락 다섯 개라는 딴소리예요."),
        make_turn(4, "Leo", "🦁", "If anyone asks what we're doing up in this oak tree...", "누가 우리가 이 참나무 위에서 뭐 하고 있는지 물어보면...",
                  '"일급비밀이라고 해!"라고 장난스럽게 윙크하세요!', "Top secret!",
                  "Code Red Classified! Welcome to the secret club, agent!", "코드 레드 1급 기밀! 비밀 클럽의 정식 요원이 된 걸 환영한다!",
                  '비밀 작전이나 모임의 기밀성을 강조하며 스파이 놀이를 할 때 외치는 단어입니다.',
                  "일급비밀이야! (비밀 클럽의 완성)", "Tell the whole world.", "온 세상에 알리라는 반대말이에요.", "I want ice cream.", "아이스크림 달라는 딴소리예요."),
        make_turn(5, "Leo", "🦁", "It's getting chilly and the orange sunset is hiding behind the hill!", "점점 쌀쌀해지고 주황색 노을이 언덕 뒤로 숨고 있어!",
                  '"이제 사다리 타고 내려가자!"라고 구동사 climb down을 써서 말해보세요!', "Let's climb down!",
                  "Ladder cleared! Trapdoor locked! Meeting back at Headquarters tomorrow at recess!", "사다리 통과! 뚜껑문 시건 완료! 내일 쉬는 시간에 비밀 본부에서 다시 집합!",
                  '구동사 "climb down"은 나무나 사다리 높은 곳에서 "조심조심 기어내려오다"라는 뜻의 동작 구동사입니다.',
                  "조심해서 내려가자! (하강 동작 구동사)", "Jump out window.", "창문으로 뛰어내리라는 위험한 말이에요.", "Sleep in tree.", "나무에서 자라는 엉뚱한 말이에요."),
        make_turn(6, "Leo", "🦁", "Both of our sneakers touched the grass! But look up, the wooden rope ladder is still hanging!", "우리 둘 다 잔디밭에 발 닿았어! 근데 위를 봐, 나무 밧줄 사다리가 아직 매달려 있어!",
                  '"사다리 끌어올려!"라고 구동사 pull up을 써서 아지트를 숨겨보세요!', "Pull it up!",
                  "Rope coiled inside the trapdoor! The treehouse is totally invisible to intruders!", "밧줄 뚜껑문 안으로 돌돌 말아 넣었어! 이제 침입자 눈엔 오두막 절대 안 보여!",
                  '구동사 "pull up"은 아래에 늘어진 줄이나 물건을 "끌어올리다/당겨 올리다"라는 뜻의 핵심 동작 구동사입니다.',
                  "사다리 끌어올려! (견인 및 인양 필수 구동사)", "Cut the rope.", "줄 자르라는 오답이에요.", "Burn the tree.", "나무 태우라는 위험한 오답이에요."),
        make_turn(7, "Leo", "🦁", "The trapdoor is locked and the rope ladder is pulled up! Our secret treehouse is 100% fortified!", "뚜껑문 닫혔고 밧줄 사다리 끌어올렸어! 우리 비밀 아지트 방어율 100%다!",
                  '"이제 집에 가자!"라고 구동사 head home을 써서 하산해보세요!', "Let's head home!",
                  "Riding our bikes before the streetlights turn bright! Mission Treehouse complete! Best secret agent squad ever!", "가로등 켜지기 전에 자전거 타고 슝 가자! 트리하우스 미션 완벽 종료! 최고 비밀 요원 팀 만세!",
                  '구동사 "head home" 또는 head out은 "집으로 향하다/귀가하다"라는 뜻으로 해 질 무렵 친구들과 헤어질 때 매일 쓰는 자연스러운 표현입니다.',
                  "이제 집에 가자! (귀가 필수 구동사)", "Sleep on the wet grass.", "축축한 잔디에서 자자는 오답이에요.", "Cut down the oak tree.", "참나무 베어버리자는 위험한 오답이에요.")
    ])
]
