"""Tier 2 Scenarios: Ages 9-10 (10 episodes x 5 turns = 50 turns)."""
from scenarios_common import make_ep, make_turn

t2 = [
    make_ep("t2_e1", "tier2", "그네 찜하기", "📍 Episode 1/10: Tire Swing Showdown", "swing", [
        make_turn(1, "Leo", "🦁", "Hey! The tire swing is finally open! Who's riding first?", "야! 타이어 그네 비었다! 누가 먼저 탈래?",
                  '"내가 찜했어!"라고 외치세요!', "I call dibs!",
                  "Aw man, you were fast! Okay, you ride first!", "아깝다, 너 진짜 빠르네! 좋아 네가 먼저 타!",
                  '미국 아이들이 무언가를 선점할 때 무조건 외치는 마법의 구어체 단어입니다.',
                  "내가 찜했어! (선점 구어체)", "I reserve the swing.", "너무 딱딱한 문장이에요.", "Good morning teacher.", "상황에 안 맞아요."),
        make_turn(2, "Leo", "🦁", "Can you give me a push? Let's take turns after twenty seconds!", "나 좀 밀어줄래? 20초 뒤에 바꿔 타자!",
                  '"좋아, 합의!"라고 쿨하게 답해보세요!', "Deal!",
                  "Sweet! Push me high into the clouds!", "나이스! 구름까지 닿게 높이 밀어줘!",
                  '협상이나 제안을 흔쾌히 수락할 때 외치는 짧고 강력한 단어입니다.',
                  "좋아, 그렇게 하자! (흔쾌한 합의)", "I reject this.", "거절하는 쌀쌀맞은 말이에요.", "My name is Leo.", "동문서답이에요."),
        make_turn(3, "Leo", "🦁", "Wait! Look, Sammy wants to ride too! Can he squeeze on with us?", "잠깐! 저기 새미도 타고 싶어 해! 우리랑 같이 낑겨 타도 돼?",
                  '"새미도 끼워주자!"라고 너그럽게 말해보세요!', "Count him in!",
                  "Awesome! Three kids on the tire swing! Hold on tight!", "신난다! 타이어 그네에 세 명 탑승 완료! 꽉 잡아!",
                  '놀이나 모임에 누군가를 참여시킬 때 "Count [someone] in"은 필수 표현입니다.',
                  "걔도 끼워주자! (포용과 참여)", "Kick him out.", "너무 심술궂은 말이에요.", "I want to sleep.", "졸리다는 엉뚱한 말이에요."),
        make_turn(4, "Leo", "🦁", "Whoa, we are spinning so fast! This is the most fun recess ever!", "우와, 우리 엄청 뱅글뱅글 돈다! 이번 쉬는 시간 역대급으로 재밌어!",
                  '"오늘 진짜 최고의 날이다!"라고 환호해보세요!', "Best day ever!",
                  "Totally! We rule the playground today!", "완전 인정! 오늘 놀이터는 우리가 접수했다!",
                  '신나게 놀며 행복이 폭발할 때 미국 아이들이 매일 쓰는 대표적 찬사입니다.',
                  "진짜 최고의 날이야! (행복의 찬사)", "Worst day ever.", "최악의 날이라는 반대말이에요.", "School starts now.", "쉬는 시간 끝났다는 찬물이에요."),
        make_turn(5, "Leo", "🦁", "I'm gonna push the tire swing in a giant spinning whirlpool! 3, 2, 1!", "내가 타이어 그네를 거대한 회오리처럼 뱅글뱅글 밀어줄게! 3, 2, 1!",
                  '"손잡이 꽉 잡아!"라고 구동사 hang on을 써서 외쳐보세요!', "Hang on tight!",
                  "Holding on with both hands! Wheeeeee, we're flying through the clouds!", "두 손으로 꽉 잡았어! 우와아아 우리 구름 속을 나는 것 같아!",
                  '구동사 "Hang on"은 손으로 무언가를 꽉 붙잡거나, 잠깐 멈춰 기다릴 때 "Hang on tight!(꽉 잡아!)"로 일상에서 쓰입니다.',
                  "손잡이 꽉 잡아! (안전 필수 구동사)", "Let go now.", "손 놓으라는 위험한 말이에요.", "Close your eyes.", "눈 감으라는 엉뚱한 말이에요.")
    ]),

    make_ep("t2_e2", "tier2", "급식실 자리 맡기", "📍 Episode 2/10: Cafeteria Seat Rescue", "cafeteria", [
        make_turn(1, "Penny", "🐧", "The cafeteria is packed! I'm heading over to get chocolate milk!", "급식실 꽉 찼어! 나 초코우유 가져오러 갈게!",
                  '"내 자리 좀 맡아줘!"라고 부탁해보세요!', "Save me a seat!",
                  "Got your back! I'll put my jacket right on this chair!", "맡겨둬! 이 의자에 내 겉옷 딱 올려놓을게!",
                  '급식실, 영화관, 버스에서 자리를 지켜달라고 부탁할 때 가장 빈번히 쓰이는 표현입니다.',
                  "자리 맡아줘! (자리 선점 요청)", "Sit down alone.", "혼자 앉으라는 차가운 말이에요.", "I dislike milk.", "우유 싫다는 딴소리예요."),
        make_turn(2, "Penny", "🐧", "Here comes someone eyeing this empty chair... But I told them it's taken!", "누가 이 빈자리 쳐다보면서 오길래... 이미 사람 있다고 말해줬지!",
                  '"너 진짜 짱이다!"라고 칭찬해보세요!', "You rock!",
                  "Haha, anytime! Best friends sit together, always!", "하하 언제든! 절친은 무조건 같이 앉아야지!",
                  '상대방이 고마운 행동을 했을 때 가볍고 기분 좋게 칭찬하는 표현입니다.',
                  "너 진짜 짱이야! (친근한 극찬)", "You are a stone.", "너는 돌이라는 직역 오역이에요.", "Excuse me.", "자리 비켜달라는 말이에요."),
        make_turn(3, "Penny", "🐧", "Guess what? Today is double pizza Friday! They gave us two huge slices!", "너 그거 알아? 오늘 피자 두 배 금요일이라 큰 조각 두 개씩 줬어!",
                  '"말도 안 돼, 실화야?"라고 깜짝 놀라보세요!', "No way!",
                  "Yes way! Look at all this melted gooey cheese!", "진짜라니까! 이 흘러내리는 끈적한 치즈 좀 봐!",
                  '믿기지 않는 좋은 소식을 들었을 때 턱 빠지게 놀라며 외치는 필수 리액션입니다.',
                  "말도 안 돼! 실화야? (깜짝 리액션)", "I knew that.", "재미없게 아는 척하는 말이에요.", "Pizza is round.", "피자는 둥글다는 뜬금없는 말이에요."),
        make_turn(4, "Penny", "🐧", "I got garlic breadsticks, but I really wanted chocolate pudding like yours!", "난 마늘빵 스틱 받았는데, 사실 너처럼 초코 푸딩 먹고 싶었거든!",
                  '"나랑 바꾸자!"라고 신나게 제안해보세요!', "Trade ya!",
                  "Deal! Warm breadsticks for cold pudding! Win-win!", "콜! 따끈한 마늘빵이랑 시원한 푸딩 맞교환! 윈윈이다!",
                  '급식실이나 놀이터에서 간식을 맞바꿀 때 아이들이 리드미컬하게 외치는 슬랭입니다.',
                  "나랑 바꾸자! (신나는 간식 교환)", "I keep everything.", "욕심부리는 쌀쌀맞은 말이에요.", "Throw it away.", "버리라는 나쁜 말이에요."),
        make_turn(5, "Penny", "🐧", "Our trays are settled and the pizza cheese is still warm and stretchy!", "우리 식판 자리 잡았고 피자 치즈 아직 따끈따끈 쭉 늘어나!",
                  '"얼른 맛있게 다 먹자!"라고 구동사 eat up을 써서 말해보세요!', "Eat up!",
                  "Mmm, this garlic crust is amazing! Best Friday lunch ever!", "음, 이 마늘 도우 진짜 환상적이다! 역대 최고의 금요일 점심이야!",
                  '구동사 "Eat up"은 남김없이 "맛있게 다 먹어!"라고 권할 때 미국인들이 가장 친근하게 쓰는 식사 구동사입니다.',
                  "맛있게 다 먹자! (식사 권유 필수 구동사)", "Spit it out.", "뱉으라는 무례한 말이에요.", "Hide the food.", "음식 숨기라는 이상한 말이에요.")
    ]),

    make_ep("t2_e3", "tier2", "피구 경기 작전", "📍 Episode 3/10: Dodgeball Showdown", "basketball", [
        make_turn(1, "Sammy", "🦊", "Red team needs one more player for recess dodgeball! Who's brave?", "빨간 팀 피구 선수 한 명 부족해! 용기 있는 사람 누구?",
                  '"나도 무조건 낄래!"라고 손을 번쩍 들어보세요!', "Count me in!",
                  "Yes! Grab a red jersey! We're gonna crush the Blue team!", "나이스! 빨간 조끼 입어! 우리 파란 팀 싹 다 이기자!",
                  '게임이나 모임에 적극적으로 동참하고 싶을 때 쓰는 자신만만한 구어체입니다.',
                  "나도 낄래! (당당한 참여 선언)", "Count sheep.", "양 세라는 엉뚱한 말이에요.", "I hate sports.", "스포츠 싫다는 초 치기예요."),
        make_turn(2, "Sammy", "🦊", "Watch out! Mike has the heavy red dodgeball aimed at you!", "조심해! 마이크가 너 조준하고 무거운 피구공 던지려고 해!",
                  '"머리 조심해!"라고 팀원들에게 다급히 외치세요!', "Heads up!",
                  "Whoosh! You ducked like a matrix ninja! He missed by an inch!", "슉! 너 닌자처럼 숙였다! 1센티 차이로 빗나갔어!",
                  '공이나 물체가 날아올 때 "조심해, 위험해!"라고 알리는 가장 직관적인 스포츠 경고입니다.',
                  "조심해! (날아오는 공 경고)", "Use your head.", "머리 쓰라는 다른 뜻이에요.", "Good afternoon.", "오후 인사예요."),
        make_turn(3, "Sammy", "🦊", "Now you caught the rebound! Throw it right at their back line!", "너 리바운드 공 잡았잖아! 쟤네 뒷줄 향해 바로 던져!",
                  '"나이스 샷!"라고 환호하며 날려보세요!', "Nice throw!",
                  "Smack! Double elimination! Their two strongest players are out!", "퍽! 더블 아웃! 상대 팀 에이스 두 명 한 방에 퇴장!",
                  '스포츠나 경기에서 훌륭한 플레이를 보았을 때 관중과 선수가 다 함께 외치는 찬사입니다.',
                  "멋진 투구야! (플레이 찬사)", "Awful ball.", "형편없다는 악담이에요.", "I want dinner.", "저녁밥 달라는 딴소리예요."),
        make_turn(4, "Sammy", "🦊", "Only their captain was left, and our ball tagged his ankle!", "주장 한 명 남았었는데, 우리 공이 걔 발목 맞혔어!",
                  '"우리가 이겼다!"라고 승리의 포효를 질러보세요!', "We won!",
                  "Recess Dodgeball Champions! High fives all around!", "쉬는 시간 피구 챔피언 등극! 다들 하이파이브!",
                  '경기에서 승리했을 때 온몸으로 기쁨을 터뜨리는 가장 순수하고 강력한 외침입니다.',
                  "우리가 이겼어! (승리의 환호)", "We surrendered.", "항복했다는 패배자 말이에요.", "Time to study.", "공부하자는 김빠지는 말이에요."),
        make_turn(5, "Sammy", "🦊", "Only two of us left against three on their team! Can we pull off a comeback?", "우리 팀 둘 남고 쟤네 셋 남았어! 역전승 가능할까?",
                  '"절대 포기하지 마!"라고 구동사 give up을 써서 용기를 북돋워주세요!', "Don't give up!",
                  "You're right! We've got this! Let's watch the red ball and dodge together!", "네 말이 맞아! 우리 할 수 있어! 빨간 공 잘 보면서 같이 피하자!",
                  '구동사 "give up"은 포기하다라는 뜻으로, "Don\'t give up!(절대 포기하지 마!)"은 스포츠와 일상에서 가장 힘이 되는 응원 구호입니다.',
                  "절대 포기하지 마! (용기 충전 대표 구동사)", "Give up now.", "지금 포기하라는 패배자 말이에요.", "Go home alone.", "혼자 집 가라는 딴소리예요.")
    ]),

    make_ep("t2_e4", "tier2", "만화책 스포일러 방어", "📍 Episode 4/10: Comic Spoiler Shield", "library", [
        make_turn(1, "Leo", "🦁", "Did you read Volume 4 of Dragon Knight? The villain is actually...", "너 드래곤 나이트 4권 읽었어? 악당의 진짜 정체가 사실...",
                  '"스포 절대 금지야!"라고 강력하게 막아서세요!', "No spoilers!",
                  "Oops, my bad! I won't ruin the plot twist for you!", "앗 내 실수! 반전 결말 절대 안 망칠게!",
                  '영화나 만화의 핵심 내용을 미리 말하려는 친구의 입을 막을 때 쓰는 표현입니다.',
                  "스포 금지! (결말 방어)", "Spoil everything.", "다 스포하라는 반대말이에요.", "Read louder.", "더 크게 읽으라는 말이에요."),
        make_turn(2, "Leo", "🦁", "Don't worry, I won't say a single peep until you finish page ninety!", "걱정 마, 네가 90페이지 다 읽을 때까지 진짜 찍소리도 안 낼게!",
                  '"입 꾹 닫고 비밀 지켜!"라고 다짐을 받아두세요!', "My lips are sealed.",
                  "Cross my heart! You're gonna gasp out loud on page fifty though!", "맹세코 입 닫을게! 그래도 50페이지에서 턱 빠질걸!",
                  '비밀을 절대 발설하지 않겠다고 단단히 약속할 때 쓰는 관용구입니다.',
                  "입 꾹 닫을게! (철통 보안 약속)", "My mouth is open.", "입 벌리고 있다는 직역 오역이에요.", "I like pizza.", "피자 좋아한다는 딴소리예요."),
        make_turn(3, "Leo", "🦁", "Can I at least tell you if someone gets cool golden wings?", "황금 날개 얻는 캐릭터가 누군지 딱 그거 하나만 힌트 주면 안 돼?",
                  '"아무 말도 하지 마, 듣기 싫어!"라고 단호히 거절하세요!', "Don't tell me!",
                  "Fine, fine! My zipper is fully locked! Go read it in peace!", "알았어, 알았어! 내 지퍼 완전 잠갔다! 방해 안 할 테니 읽어!",
                  '기대감을 지키기 위해 힌트조차 사양할 때 단호하고 유쾌하게 외치는 표현입니다.',
                  "말하지 마! (단호한 거절)", "Tell me everything.", "전부 말해달라는 반대말이에요.", "I am illiterate.", "글 못 읽는다는 오답이에요."),
        make_turn(4, "Leo", "🦁", "How about you read it right now during reading period and we talk at lunch?", "그럼 지금 독서 시간에 얼른 읽고 점심시간에 토론하는 거 어때?",
                  '"그 말도 일리 있네, 인정!"이라고 동의해보세요!', "Fair enough.",
                  "Deal! Meet by the library lockers right at noon!", "콜! 딱 정오에 도서관 락커 앞에서 만나서 폭풍 수다 떨자!",
                  '상대방의 합리적인 제안이나 타협안에 고개를 끄덕이며 "그럼 그렇게 하자"고 할 때 씁니다.',
                  "그 말도 일리 있네! (합리적 수용)", "Completely unfair.", "완전 불공평하다는 반발이에요.", "Library is noisy.", "도서관 시끄럽다는 불평이에요."),
        make_turn(5, "Leo", "🦁", "You are totally gonna love chapter seven! Here, take Volume 4 into your backpack!", "너 진짜 7장 완전 좋아할걸! 자, 4권 네 가방에 얼른 챙겨 넣어!",
                  '"고마워, 잘 챙겨둘게!"라고 구동사 put away를 써서 말해보세요!', "I'll put it away!",
                  "Take good care of it! We'll talk all about the epic battle at recess tomorrow!", "소중히 잘 읽어줘! 내일 쉬는 시간에 대결 장면 이야기 폭풍 수다 떨자!",
                  '구동사 "put away"는 책이나 물건을 제자리나 가방에 "정리하여 넣어두다/챙기다"라는 뜻의 핵심 구동사입니다.',
                  "가방에 잘 넣어둘게! (정리 및 보관 구동사)", "Tear the pages.", "책 찢으라는 나쁜 말이에요.", "Throw it away.", "버리라는 무례한 말이에요.")
    ]),

    make_ep("t2_e5", "tier2", "쉬는 시간 달리기 대결", "📍 Episode 5/10: Recess Sprint Showdown", "playground", [
        make_turn(1, "Sammy", "🦊", "I'm the fastest kid in grade four! Race you to the fence right now!", "나 4학년에서 제일 빠르거든! 지금 당장 저 울타리까지 달리기 뜰래?",
                  '"진정해, 서두르지 마!"라고 친구를 워워 진정시키세요!', "Hold your horses!",
                  "Haha, okay! Let me tie my laces properly first!", "하하 좋아! 일단 내 운동화 끈부터 제대로 묶고!",
                  '상대방이 너무 흥분하거나 앞서나갈 때 "워워 진정해, 서두르지 마"라는 위트 있는 표현입니다.',
                  "진정해! (흥분 진정)", "Ride a real horse.", "진짜 말 타라는 엉뚱한 말이에요.", "Good night sleep.", "자러 가자는 말이에요."),
        make_turn(2, "Sammy", "🦊", "I bet five strawberry gummy candies I cross the line before you!", "내가 너보다 먼저 결승선 통과한다에 딸기 젤리 다섯 개 건다!",
                  '"꿈 깨시지! 어림없어!"라고 당당하게 맞받아치세요!', "In your dreams!",
                  "Oh, you think so? Just wait till you eat my dust!", "오, 그렇게 나온다 이거지? 내 흙먼지나 마시지 마라!",
                  '상대의 허풍이나 자만에 "꿈 깨, 어림 반푼어치도 없어"라고 맞받아치는 자신감 넘치는 슬랭입니다.',
                  "꿈 깨시지! (자신만만한 맞받아침)", "I dream about bears.", "곰 꿈꾼다는 엉뚱한 직역이에요.", "Please do not run.", "달리지 말라는 부탁이에요."),
        make_turn(3, "Sammy", "🦊", "Three, two, one, go! Look at me pull ahead by three steps!", "셋, 둘, 하나, 출발! 나 세 걸음 앞서가는 것 좀 봐라!",
                  '"너무 느려, 따라와 봐!"라고 옆에서 도발해보세요!', "Too slow!",
                  "What? You just zoomed right past my elbow! Wait up!", "뭐야? 방금 내 팔꿈치 옆으로 슝 지나갔잖아! 같이 가!",
                  '달리기 대결이나 게임에서 상대를 유쾌하게 약 올리며 추월할 때 쓰는 한마디입니다.',
                  "너무 느려! (유쾌한 추월 도발)", "Walk slowly please.", "천천히 걸으라는 오답이에요.", "I broke my leg.", "다리 부러졌다는 거짓말이에요."),
        make_turn(4, "Sammy", "🦊", "Phew! We both crossed the fence at the exact same millisecond!", "휴! 우리 둘 다 0.001초 차이도 없이 동시에 울타리 터치했어!",
                  '"내일 재대결이야!"라고 다음 승부를 기약하세요!', "Rematch tomorrow!",
                  "You're on! Bring your lucky neon sneakers tomorrow!", "좋았어, 받아주지! 내일 형광 행운 운동화 신고 와라!",
                  '팽팽한 승부 끝에 다음 판을 약속하며 승부욕을 불태울 때 쓰는 멋진 스포츠 구어체입니다.',
                  "내일 재대결이야! (승부 기약)", "I quit running.", "달리기 그만둔다는 말이에요.", "Where is lunch?", "점심밥 찾는 말이에요."),
        make_turn(5, "Sammy", "🦊", "Phew! My heart is racing and I drank all my cold water!", "휴! 심장 엄청 쿵쾅거리고 시원한 물 다 마셨어!",
                  '"숨 좀 돌리자!"라고 기본동사 take를 써서 제안해보세요!', "Let's take a breath!",
                  "Phew, yes! Deep breaths in and out... My lungs are finally calming down!", "휴 맞아! 숨 깊이 들이쉬고 내쉬고... 숨 이제 좀 찬찬히 가라앉는다!",
                  '기본동사 "take"와 명사가 결합하여 "Take a breath(숨을 고르다/쉬다)"처럼 신체 회복을 표현할 때 자연스럽게 쓰입니다.',
                  "숨 좀 고르자! (호흡 회복 기본동사)", "Run another mile.", "1마일 더 뛰라는 끔찍한 말이에요.", "Stop breathing.", "숨 멈추라는 위험한 말이에요.")
    ]),

    make_ep("t2_e6", "tier2", "포켓몬 카드 교환", "📍 Episode 6/10: Trading Card Bargain", "teenLocker", [
        make_turn(1, "Penny", "🐧", "Look at this holographic shiny lightning dragon card I just pulled!", "내가 방금 팩에서 뽑은 번쩍이는 홀로그램 번개 용 카드 봐봐!",
                  '"대박 멋지다! 쩔어!"라고 감탄해보세요!', "That is fire!",
                  "Right? The rainbow foil sparkles in the classroom sunlight!", "그치? 교실 햇빛 받으니까 무지개 포일이 번쩍거려!",
                  'Z세대와 유초등생들이 진짜 멋지고 대박인 것을 볼 때 "불타오른다, 쩐다"는 의미로 쓰는 감탄사입니다.',
                  "대박 멋지다! (극찬 감탄)", "Put out the fire.", "불 끄라는 엉뚱한 말이에요.", "Cards are boring.", "카드 재미없다는 악담이에요."),
        make_turn(2, "Penny", "🐧", "I will trade you for your shadow panther card if you add two stickers!", "네 그림자 표범 카드에 스티커 두 개 얹어주면 이 용 카드랑 바꿀게!",
                  '"완전 공정한 거래네!"라고 동의해보세요!', "Fair trade!",
                  "Awesome! Slap the sleeves on and make the swap!", "신난다! 카드 슬리브 씌우고 공식 교환하자!",
                  '조건이 양쪽 모두에게 합리적이고 마음에 들 때 흔쾌히 승낙하는 교환 표현입니다.',
                  "공정한 거래야! (합리적 교환 동의)", "You are a thief.", "도둑이라는 비난이에요.", "I lost my backpack.", "가방 잃어버렸다는 딴소리예요."),
        make_turn(3, "Penny", "🐧", "Wait, are you sure you don't want to keep your rare holographic sticker?", "잠깐, 너 저 희귀 홀로그램 스티커 진짜 나한테 줘도 괜찮아?",
                  '"너 진심이야?"라고 쿨하게 확인해보세요!', "Are you serious?",
                  "Dead serious! I've been hunting for this panther card all semester!", "완전 진심이지! 나 이번 학기 내내 이 표범 카드 찾아다녔거든!",
                  '상대의 파격적인 제안이나 호의에 "너 진짜 진심이지?"라고 반문할 때 씁니다.',
                  "진심이야? (쿨한 확인)", "I am a clown.", "광대라는 엉뚱한 말이에요.", "Good luck to nobody.", "상황에 안 맞아요."),
        make_turn(4, "Penny", "🐧", "Here's the lightning dragon safely inside the protective hard case!", "여기 하드 케이스에 안전하게 넣은 번개 용 카드 건네줄게!",
                  '"거래해서 즐거웠어!"라고 악수를 청해보세요!', "Pleasure doing business!",
                  "Haha, you sound like a Wall Street broker! High five!", "하하 너 월스트리트 주식 브로커 같다! 하이파이브!",
                  '친구들끼리 카드나 장난감을 교환한 뒤 어른스럽고 유머러스하게 건네는 비즈니스 인사입니다.',
                  "거래해서 즐거웠어! (유머러스한 거래 인사)", "Give it back now.", "당장 돌려달라는 억지예요.", "I forgot my wallet.", "지갑 없다는 말이에요."),
        make_turn(5, "Penny", "🐧", "This shiny panther card is going straight into my top-secret binder!", "이 반짝이는 표범 카드 내 일급비밀 카드 앨범에 바로 넣을 거야!",
                  '"소중히 잘 간직해!"라고 기본동사 keep을 써서 격려해보세요!', "Keep it safe!",
                  "Locked with double sleeves! It's never getting scratched! Thanks for the trade!", "이중 슬리브 장착 완료! 흠집 절대 안 나게 할게! 교환해줘서 고마워!",
                  '기본동사 "keep"은 "상태를 유지하다, 간직하다"라는 뜻으로, "Keep it safe(안전하게 잘 간직해)"는 카드를 넘겨줄 때 멋진 당부 표현입니다.',
                  "소중히 잘 간직해! (보관 당부 기본동사)", "Drop on ground.", "바닥에 떨어뜨리라는 오답이에요.", "Fold in half.", "반으로 접으라는 악담이에요.")
    ]),

    make_ep("t2_e7", "tier2", "숙제 깜빡했을 때", "📍 Episode 7/10: Forgotten Homework Crisis", "classroom", [
        make_turn(1, "Leo", "🦁", "Mr. Davis is collecting the science worksheet in two minutes!", "데이비스 선생님이 2분 뒤에 과학 과제물 걷으신대!",
                  '"나 진짜 망했다!"라고 절망해보세요!', "I am totally screwed!",
                  "Wait, don't panic yet! Did you leave it at home or in your gym bag?", "잠깐, 아직 멘붕하지 마! 집에 두고 왔어, 아니면 체육 가방에 있어?",
                  '실수를 하거나 난처한 상황에 빠졌을 때 미국 학생들이 가장 자주 쓰는 구어체 비명입니다.',
                  "나 진짜 망했어! (절체절명의 비명)", "Everything is perfect.", "모든 게 완벽하다는 거짓말이에요.", "I love tests.", "시험 좋아한다는 헛소리예요."),
        make_turn(2, "Leo", "🦁", "Look! I have a blank backup copy Mr. Davis gave me yesterday!", "봐봐! 어제 선생님이 나한테 여분으로 주신 빈 프린트물 한 장 있어!",
                  '"백만 배로 고마워!"라고 깊은 감사를 표하세요!', "Thanks a million!",
                  "Quick, grab your pencil! I'll read the questions out loud to you!", "빨리 연필 잡아! 내가 질문 소리 내서 읽어줄 테니까 적어!",
                  '상대방이 엄청난 구원의 손길을 내밀었을 때 건네는 극상의 감사 표현입니다.',
                  "백만 배로 고마워! (극상의 감사)", "One thank you.", "너무 인색한 말이에요.", "Take all my money.", "돈 다 가져가라는 오답이에요."),
        make_turn(3, "Leo", "🦁", "Question three: What is the powerhouse of the cell? Mitochondria!", "3번 질문: 세포의 에너지 공장은? 미토콘드리아!",
                  '"너 진짜 내 생명의 은인이야!"라고 감격해보세요!', "You're a lifesaver!",
                  "Thirty seconds left! Scrawl your name on top fast!", "30초 남았다! 맨 위에 네 이름 휘갈겨 적어!",
                  '위기 상황에서 결정적인 도움을 준 친구에게 최고의 찬사로 건네는 관용구입니다.',
                  "넌 내 생명의 은인이야! (감격의 찬사)", "You are a killer.", "살인자라는 엉뚱한 말이에요.", "I am asleep.", "자고 있다는 딴소리예요."),
        make_turn(4, "Leo", "🦁", "Mr. Davis just walked past and picked up both our neat papers!", "선생님이 방금 지나가시면서 우리 둘 과제물 다 걷어가셨어!",
                  '"내가 신세 한 번 갚을게!"라고 의리를 보여주세요!', "I owe you one!",
                  "Haha remember that at lunchtime! Extra tater tots for me!", "하하 점심시간에 잊지 마라! 내 식판에 감자튀김 더 얹어주기다!",
                  '큰 도움을 받은 뒤 상대방에게 은혜를 반드시 갚겠다고 약속하는 신뢰의 표현입니다.',
                  "내가 신세 꼭 갚을게! (의리 넘치는 약속)", "You owe me money.", "네가 돈 내놓으라는 적반하장이에요.", "Class is dismissed.", "수업 끝났다는 거짓말이에요."),
        make_turn(5, "Leo", "🦁", "Pencils down! Mr. Davis took the stack of worksheets to his teacher desk!", "연필 끝! 선생님이 과제물 뭉치 교탁으로 다 들고 가셨어!",
                  '"위기 잘 넘겼다!"라고 구동사 get through를 써서 기뻐해보세요!', "We got through it!",
                  "High five! That was the closest homework close-call of the entire year!", "하이파이브! 올해 과제 제출 중에 진짜 역대급으로 심장 쫄깃했어!",
                  '구동사 "get through"는 힘든 고비나 위기 상황을 "무사히 통과하다/이겨내다"라는 뜻으로 널리 쓰입니다.',
                  "위기 잘 넘겼다! (난관 극복 구동사)", "We got arrested.", "체포되었다는 엉뚱한 오역이에요.", "Give me homework.", "숙제 더 달라는 망언이에요.")
    ]),

    make_ep("t2_e8", "tier2", "게임 오버 후 재도전", "📍 Episode 8/10: Arcade Boss Battle", "toybox", [
        make_turn(1, "Sammy", "🦊", "Aaargh! The shadow boss swung his tail with one HP left!", "으아악! 그림자 보스가 체력 1 남았는데 꼬리 휘둘렀어!",
                  '"아, 아까웠다! 거의 깰 뻔했는데!"라고 탄식해보세요!', "That was close!",
                  "So close! If we dodged left instead of jumping, we had him!", "진짜 아까웠어! 점프 대신 왼쪽으로 피했으면 우리가 잡았는데!",
                  '아슬아슬한 승부나 위기에서 한 끗 차이로 비켜갔을 때 쓰는 대표적인 탄식 표현입니다.',
                  "진짜 아까웠어! (아슬아슬한 탄식)", "That was very far.", "멀었다는 반대말이에요.", "I hate games.", "게임 싫다는 초 치기예요."),
        make_turn(2, "Sammy", "🦊", "We still have three glowing arcade tokens left in the slot!", "슬롯에 아직 번쩍이는 오락실 토큰 세 개나 남아있어!",
                  '"한 판 더 가자! 재도전!"라고 패기 있게 외치세요!', "Let's run it back!",
                  "Insert coin! This time I'll freeze him with the ice cannon!", "코인 투입! 이번엔 내가 얼음 대포로 녀석 꽁꽁 얼려버릴게!",
                  '게임이나 시합에서 패배 후 곧바로 다시 리턴 매치를 시작할 때 외치는 최신 게이머 슬랭입니다.',
                  "한 판 더 가자! (패기 넘치는 재도전)", "Run away home.", "집으로 도망치라는 뜻이에요.", "Turn off TV.", "TV 끄라는 김빠지는 소리예요."),
        make_turn(3, "Sammy", "🦊", "He's charging up the giant fireball! Quick, flank from the side!", "보스가 대왕 화염구 충전 중이야! 얼른 옆으로 돌아 들어가!",
                  '"내가 엄호할게! 뒤는 맡겨!"라고 든든하게 받쳐주세요!', "I got your back!",
                  "Cover fire active! I'm unleashing the laser storm right at his heart!", "엄호 사격 완료! 내가 심장에 레이저 폭풍 바로 꽂아 넣는다!",
                  '팀원이나 친구를 뒤에서 든든하게 지켜주고 지원하겠다고 안심시키는 최고의 팀워크 표현입니다.',
                  "내가 엄호할게! (든든한 백업)", "I have back pain.", "허리 아프다는 엉뚱한 말이에요.", "Look behind you.", "뒤돌아보라는 혼란 유발이에요."),
        make_turn(4, "Sammy", "🦊", "Boom! The giant shadow dragon shattered into golden coins!", "펑! 거대 그림자 드래곤이 황금 코인으로 산산조각 났어!",
                  '"완벽한 승리다!"라고 환호하며 자축해보세요!', "Flawless victory!",
                  "Zero deaths on stage five! We just set the high score in town!", "5단계 노데스 클리어! 우리 동네 신기록 세웠다!",
                  '흠잡을 데 없이 완벽한 경기력으로 대승을 거두었을 때 자축하는 게이머들의 명대사입니다.',
                  "완벽한 승리야! (무결점 대승 자축)", "We lost completely.", "완패했다는 오답이에요.", "Game over forever.", "영원한 게임오버라는 엉뚱한 말이에요."),
        make_turn(5, "Sammy", "🦊", "The ticket dispenser is spitting out a mile-long ribbon of red prize tickets!", "티켓 배출기에서 빨간 경품 티켓이 리본처럼 1미터 넘게 쏟아져 나와!",
                  '"티켓 다 챙겨!"라고 구동사 pick up을 써서 말해보세요!', "Pick them up!",
                  "Rolling them into a giant ball! We have enough tickets for the giant plush bear!", "왕공처럼 돌돌 마는 중! 대형 곰 인형 바꿀 만큼 티켓 충분해!",
                  '구동사 "pick up"은 쏟아져 나온 티켓이나 물건을 바닥에서 "주워 담다/챙기다"라는 의미로 쓰입니다.',
                  "얼른 다 챙겨! (물건 수거 구동사)", "Burn the tickets.", "티켓 태우라는 이상한 말이에요.", "Leave them behind.", "버려두고 가자는 손해예요.")
    ]),

    make_ep("t2_e9", "tier2", "생일 파티 초대", "📍 Episode 9/10: Laser Tag Birthday Invite", "tag", [
        make_turn(1, "Penny", "🐧", "My birthday is this Saturday! We booked the giant laser tag arena!", "이번 주 토요일 내 생일이야! 대형 레이저 태그 경기장 통째로 빌렸어!",
                  '"너 토요일에 시간 돼?"라고 일정을 물어보세요!', "Are you free?",
                  "Totally open! I already told my mom to clear the whole afternoon!", "완전 비었지! 나 이미 엄마한테 토요일 오후 비워달라고 말씀드렸어!",
                  '친구에게 약속이나 초대를 건넬 때 일정이 비어 있는지 가장 깔끔하게 묻는 표현입니다.',
                  "시간 돼? (자연스러운 일정 확인)", "Are you cheap?", "너 값싸냐는 심각한 무례예요.", "I am twelve years old.", "나이 뜬금포예요."),
        make_turn(2, "Penny", "🐧", "Awesome! The party starts at two, with neon pizza and double arcade passes!", "신난다! 파티는 2시 시작이고 네온 피자에 오락실 2회권도 줘!",
                  '"무조건 갈게!"라고 흔쾌히 참석을 확정 지어보세요!', "I'll be there!",
                  "Yay! Our neon laser squad is gonna dominate the battlefield!", "야호! 우리 네온 레이저 분대가 경기장 다 쓸어버리자!",
                  '친구의 초대에 확신과 기쁨을 담아 반드시 가겠다고 못 박는 명쾌한 답변입니다.',
                  "무조건 갈게! (확실한 참석 약속)", "I decline coming.", "냉정하게 거절하는 말이에요.", "Where is my shoe?", "신발 찾는 엉뚱한 소리예요."),
        make_turn(3, "Penny", "🐧", "I heard they even have a glowing two-story obstacle castle inside!", "듣자하니 안에 2층짜리 발광 장애물 성벽도 있대!",
                  '"진짜 기대된다! 못 참겠어!"라고 설렘을 표현해보세요!', "Can't wait!",
                  "Me neither! I've been counting down the days on my calendar!", "나도 그래! 나 달력에 매일 동그라미 치면서 세고 있거든!",
                  '다가올 파티나 이벤트를 너무 기대하며 설렐 때 미국인들이 입버릇처럼 쓰는 구어체입니다.',
                  "진짜 기대돼! 못 참겠다! (설렘 폭발)", "I hate waiting.", "기다리는 거 싫다는 불평이에요.", "Time is money.", "시간은 돈이라는 엉뚱한 속담이에요."),
        make_turn(4, "Penny", "🐧", "My mom is baking a giant chocolate volcano cake with sparkler candles!", "우리 엄마가 불꽃 나오는 촛불 꽂은 거대 초콜릿 화산 케이크 굽고 계셔!",
                  '"진짜 대박 재밌을 거야!"라고 축하를 건네보세요!', "It's gonna be a blast!",
                  "The best birthday party of the fourth grade! See you Saturday!", "4학년 최고의 생일 파티가 될 거야! 토요일에 만나!",
                  '파티나 여행이 엄청나게 신나고 재밌을 것이라 확신할 때 쓰는 대표적인 찬사 표현입니다.',
                  "진짜 대박 재밌을 거야! (최고의 파티 예고)", "It will explode dangerously.", "위험하게 폭발한다는 오역이에요.", "Happy New Year.", "새해 인사예요."),
        make_turn(5, "Penny", "🐧", "Our team needs to wear dark sneakers and sneakers with good grip for the ramps!", "우리 팀 경기장 경사로 뛰려면 접지력 좋은 어두운 운동화 신고 와야 해!",
                  '"편한 신발 신고 갈게!"라고 구동사 put on을 써서 답해보세요!', "I'll put them on!",
                  "Perfect! Dark clothes, fast sneakers, laser blasters ready to fire! See ya Saturday!", "완벽해! 어두운 옷에 빠른 신발, 레이저 총 발사 준비 완료! 토요일에 보자!",
                  '구동사 "put on"은 옷, 신발, 모자, 안경 등을 "착용하다/신다"라는 뜻으로 일상에서 가장 자주 쓰이는 핵심 구동사입니다.',
                  "꼭 챙겨 신을게! (의류 착용 필수 구동사)", "Take off shoes.", "신발 벗으라는 오답이에요.", "Throw sneakers.", "신발 던지라는 엉뚱한 말이에요.")
    ]),

    make_ep("t2_e10", "tier2", "비밀 아지트 규칙", "📍 Episode 10/10: Secret Treehouse Vault", "treehouse", [
        make_turn(1, "Leo", "🦁", "Halt! Who goes there? No one enters the treehouse without clearance!", "멈춰라! 누구냐? 허가 없이는 아무도 이 오두막에 못 들어온다!",
                  '"암호가 뭐야?"라고 암구호를 물어보세요!', "What's the password?",
                  "Golden Acorn! Whisper it three times or the trapdoor stays locked!", "황금 도토리! 세 번 속삭여라, 안 그러면 문 안 열어준다!",
                  '비밀 모임이나 아지트에 들어갈 때 재미있게 암호를 묻고 답하는 아동 놀이 표현입니다.',
                  "암호가 뭐야? (비밀 아지트 암호 묻기)", "What is your name?", "이름 묻는 평범한 질문이에요.", "Open the bank.", "은행 열라는 엉뚱한 말이에요."),
        make_turn(2, "Leo", "🦁", "Golden Acorn, Golden Acorn, Golden Acorn! Identity confirmed!", "황금 도토리 세 번 확인! 신원 확인 완료!",
                  '"들어와도 좋아!"라고 문을 활짝 열어주세요!', "You may enter.",
                  "Welcome to Headquarters! Mind your head on the low wooden beam!", "비밀 본부에 온 걸 환영한다! 낮은 나무 기둥에 머리 부딪치지 마!",
                  '허가를 내주거나 문을 열어줄 때 의젓하고 폼나게 건네는 표현입니다.',
                  "들어와도 좋아! (품격 있는 입장 허가)", "Stay outside in rain.", "비 맞고 밖에 있으라는 매정한 말이에요.", "I am asleep.", "자고 있다는 말이에요."),
        make_turn(3, "Leo", "🦁", "Here is our secret map of the neighborhood! Swear to keep it safe?", "여기 우리 동네 비밀 지도야! 절대 아무한테도 안 보여준다고 맹세해?",
                  '"새끼손가락 걸고 약속할게!"라고 단단히 약속하세요!', "Pinky promise?",
                  "Locked with the pinky oath! Not even aliens could make me talk!", "새끼손가락 맹세 봉인 완료! 외계인이 와도 절대 입 안 연다!",
                  '어린이들이 가장 진지하고 엄숙하게 비밀을 지키기로 서약할 때 쓰는 관용 표현입니다.',
                  "새끼손가락 걸고 약속! (엄숙한 비밀 서약)", "Cut my little finger.", "손가락 자르라는 무서운 오역이에요.", "I have five fingers.", "손가락 다섯 개라는 딴소리예요."),
        make_turn(4, "Leo", "🦁", "If anyone asks what we're doing up in this oak tree...", "누가 우리가 이 참나무 위에서 뭐 하고 있는지 물어보면...",
                  '"일급비밀이라고 해!"라고 장난스럽게 윙크하세요!', "Top secret!",
                  "Code Red Classified! Welcome to the secret club, agent!", "코드 레드 1급 기밀! 비밀 클럽의 정식 요원이 된 걸 환영한다!",
                  '비밀 작전이나 모임의 기밀성을 강조하며 스파이 놀이를 할 때 외치는 단어입니다.',
                  "일급비밀이야! (비밀 클럽의 완성)", "Tell the whole world.", "온 세상에 알리라는 반대말이에요.", "I want ice cream.", "아이스크림 달라는 딴소리예요."),
        make_turn(5, "Leo", "🦁", "It's getting chilly and the orange sunset is hiding behind the hill!", "점점 쌀쌀해지고 주황색 노을이 언덕 뒤로 숨고 있어!",
                  '"이제 사다리 타고 내려가자!"라고 구동사 climb down을 써서 말해보세요!', "Let's climb down!",
                  "Ladder cleared! Trapdoor locked! Meeting back at Headquarters tomorrow at recess!", "사다리 통과! 뚜껑문 시건 완료! 내일 쉬는 시간에 비밀 본부에서 다시 집합!",
                  '구동사 "climb down"은 나무나 사다리 높은 곳에서 "조심조심 기어내려오다"라는 뜻의 동작 구동사입니다.',
                  "조심해서 내려가자! (하강 동작 구동사)", "Jump out window.", "창문으로 뛰어내리라는 위험한 말이에요.", "Sleep in tree.", "나무에서 자라는 엉뚱한 말이에요.")
    ])
]
